Repository kyma-project/test-infra, pull requests merged in 2019-04, with the labels that each got.

#825 Temporary job to run Octopus on Kyma
  prow/jobs/incubator/octopus/octopus-kyma-int.yaml
Labels: quality/productivity

#835 Add release 0.9 job for watch-pods
  prow/jobs/test-infra/watch-pods.yaml
Labels: area/ci, enhancement

#837 Temporary add more resources to Asset Store jobs
  prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml
Labels: area/ci, test-failing

#838 Fix release for watch-pods
  prow/scripts/build.sh
Labels: area/ci, bug

#840 Fix path alias for Octopus integration test
  prow/jobs/incubator/octopus/octopus-kyma-int.yaml
Labels: bug, quality/productivity

#844 Enable TLS in end2end tests
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/ci, bug, enhancement

#809 Cluster cleanup
  development/tools/cmd/clusterscollector/README.md
  development/tools/cmd/clusterscollector/main.go
  development/tools/pkg/clusterscollector/collector.go
  development/tools/pkg/clusterscollector/collector_test.go
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
Labels: area/ci, area/documentation

#856 Fix pointing Github release tag for 0.9
  prow/jobs/kyma/kyma-github-release.yaml
Labels: area/ci, bug

#821 Update commit SHA of prow
  docs/prow/production-cluster-configuration.md
Labels: area/ci

#861 Update release version to 1.0.0-rc1
  prow/RELEASE_VERSION
Labels: area/ci, enhancement

#863 Update CODEOWNERS
  CODEOWNERS
Labels: area/community, enhancement

#769 Firewall rule removal
  development/README.md
  development/firewall-cleanup.sh
  development/tools/cmd/firewallcleaner/main.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/pkg/firewallcleaner/automock/compute_api.go
  development/tools/pkg/firewallcleaner/cleaner.go
  development/tools/pkg/firewallcleaner/cleaner_test.go
  development/tools/pkg/firewallcleaner/options.go
  development/tools/pkg/firewallcleaner/wrappers.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, area/documentation

#866 Fix GKE upgrade plans: get helm certs before creating test resources
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: test-failing

#858 Cluster cleanup enable
  development/tools/cmd/clusterscollector/main.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/pkg/clusterscollector/automock/cluster_api.go
  development/tools/pkg/clusterscollector/collector.go
  development/tools/pkg/clusterscollector/collector_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#876 Update triggered jobs when there are changes in console/components/react
  development/tools/jobs/console/brokers_test.go
  development/tools/jobs/console/catalog_test.go
  development/tools/jobs/console/content_test.go
  development/tools/jobs/console/instances_test.go
  prow/jobs/console/brokers/brokers.yaml
  prow/jobs/console/catalog/catalog.yaml
  prow/jobs/console/content/content.yaml
  prow/jobs/console/instances/instances.yaml
Labels: area/ci, area/console, enhancement

#880 Change base image for application broker job
  development/tools/jobs/kyma/apiserver_proxy_test_test.go
  development/tools/jobs/kyma/application_broker_test.go
  development/tools/jobs/kyma/application_gateway_test.go
  development/tools/jobs/kyma/application_gateway_tests_test.go
  development/tools/jobs/kyma/application_proxy_test.go
  development/tools/jobs/kyma/asset_metadata_service_test.go
  development/tools/jobs/kyma/asset_store_controller_manager_test.go
  development/tools/jobs/kyma/asset_store_test_test.go
  development/tools/jobs/kyma/asset_upload_service_test.go
  development/tools/jobs/kyma/cluster_users_test.go
  development/tools/jobs/kyma/cms_controller_manager_test.go
  development/tools/jobs/kyma/connection_token_handler_test_test.go
  development/tools/jobs/kyma/connectivity_certs_controller_test.go
  development/tools/jobs/kyma/console_backend_service_test.go
  development/tools/jobs/kyma/console_backend_service_test_test.go
  development/tools/jobs/kyma/end_to_end_backup_restore_test_test.go
  development/tools/jobs/kyma/end_to_end_kubeless_integration_tests_test.go
  development/tools/jobs/kyma/end_to_end_upgrade_test.go
  development/tools/jobs/kyma/knative_serving_acceptance_test.go
  development/tools/jobs/kyma/monitoring_test.go
  development/tools/jobs/kyma/stability_checker_test.go
  development/tools/jobs/kyma/tools/gcp_broker_provider_test.go
  development/tools/jobs/kyma/watch_pods_test.go
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/branchprotector_test.go
  development/tools/jobs/testinfra/stability_checker_test.go
  development/tools/jobs/testinfra/watch_pods_test.go
  prow/jobs/kyma/components/application-broker/application-broker.yaml
  prow/jobs/kyma/tests/knative-serving/knative-serving.yaml
  prow/jobs/test-infra/stability-checker.yaml
Labels: enhancement

#888 Fix kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/service-mesh, bug

#881 Add ghproxy
  prow/cluster/04-branchprotector_cronjob.yaml
  prow/cluster/09-gce-ssd-retain_storageclass.yaml
  prow/cluster/10-ghproxy.yaml
  prow/cluster/README.md
  prow/cluster/starter.yaml
  prow/install-prow.sh
Labels: area/ci

#886 Add missing tls flag
  prow/scripts/cluster-integration/kyma-gke-load-test.sh
Labels: area/ci

#900 Change buildpack for release 1.0 in app broker
  development/tools/jobs/kyma/application_broker_test.go
  prow/jobs/kyma/components/application-broker/application-broker.yaml
Labels: area/application-connector, area/service-catalog

#898 Verify and improve documentation
  docs/prow/production-cluster-configuration.md
  docs/prow/prow-architecture.md
  docs/prow/prow-installation-on-forks.md
  prow/README.md
  prow/workload-cluster/README.md
Labels: area/documentation

#889 Introduce new xip pipeline
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
Labels: area/ci, area/cluster, enhancement

#869 Adjust stability checker to use Octopus CRDs instead of helm test
  prow/jobs/incubator/octopus/octopus-kyma-int.yaml
  prow/scripts/cluster-integration/helpers/install-stability-checker.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: quality/productivity

#914 pipeline fix
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
Labels: area/ci

#913 Stability-checker reads non json log entries
  stability-checker/internal/printer/export_test.go
  stability-checker/internal/printer/printer.go
  stability-checker/internal/printer/printer_test.go
Labels: area/cluster, bug

#916 Fix GCP auth
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
Labels: area/ci

#920 Add job and test for add-ons-ui
  development/tools/jobs/console/add-ons_test.go
  prow/jobs/console/add-ons/add-ons.yaml
Labels: area/console, area/core-and-supporting, enhancement

#921 XIP pipeline fix
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
Labels: area/ci

#927 xip upgrade configuration
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
Labels: area/ci

#924 Create periodic job for minikube verification
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/minikube-test.sh
Labels: area/ci, area/service-mesh, bug

#928 Feature/xip gke upgrade
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#932 Introduce temporary job to test jobguard
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, quality/productivity

#937 Add execute permission to let's encrypt script
  prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
Labels: area/ci, bug

#940 Fix logic responsible for generating certificates
  prow/config.yaml
  prow/scripts/cluster-integration/helpers/decrypt.sh
  prow/scripts/cluster-integration/helpers/encrypt.sh
  prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci, bug

#944 Add test version of e2e test for service catalog
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-long-lasting-aw-test.sh
Labels: WIP, area/service-catalog

#945 Add test version of e2e test for service catalog - fix
  prow/jobs/kyma/kyma-integration.yaml
Labels: WIP, area/service-catalog

#946 Enable cluster notification for slack channel
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, area/cluster

#948 Add presets for kyma-website-bot
  development/tools/jobs/tester/tester.go
  development/tools/jobs/website/website_test.go
  prow/config.yaml
  prow/jobs/website/website.yaml
Labels: area/ci, enhancement

#949 Update docs for presets
  docs/prow/presets.md
Labels: area/documentation, enhancement

#951 Disable cluster notification for slack channel
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/cli, area/cluster

#952 Add preset for ZenHub API token
  development/tools/jobs/tester/tester.go
  development/tools/jobs/website/website_test.go
  docs/prow/presets.md
  prow/config.yaml
  prow/jobs/website/website.yaml
Labels: area/ci, area/core-and-supporting, enhancement

#953 Create kyma-website job
  development/tools/jobs/kyma/docs_website_test.go
  prow/jobs/kyma/docs/docs-website.yaml
Labels: area/ci, enhancement

#955 Change repo refs in minikube verification
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, area/cluster, area/service-mesh

#943 All stability checker container logs as JSON
  stability-checker/deploy/chart/stability-checker/templates/deploy.yaml
  stability-checker/deploy/stability-checker/Dockerfile
  stability-checker/internal/printer/export_test.go
  stability-checker/internal/printer/printer.go
  stability-checker/internal/printer/printer_test.go
Labels: bug

#957 Fix readme
  README.md
Labels: area/documentation

#902 Add support for minio gateway in tests
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/delete-buckets.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
Labels: area/core-and-supporting, enhancement

#960 Service Catalog nightly job - fix
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-long-lasting-aw-test.sh
Labels: area/service-catalog

#904 Add Job Guard utility
  development/tools/cmd/jobguard/README.md
  development/tools/cmd/jobguard/main.go
  development/tools/cmd/jobguard/run.sh
  development/tools/pkg/jobguard/filter.go
  development/tools/pkg/jobguard/httpclient.go
  development/tools/pkg/jobguard/status.go
  development/tools/pkg/jobguard/waiter.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: WIP, area/ci, enhancement

#962 Service Catalog nightly job - update
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/service-catalog
