Repository kyma-project/test-infra, pull requests merged in 2019-08, with the labels that each got.

#1325 Mark jobs as required
  development/tools/jobs/kyma/asset_metadata_service_test.go
  development/tools/jobs/kyma/cms_services_test.go
  prow/jobs/kyma/components/asset-metadata-service/asset-metadata-service.yaml
  prow/jobs/kyma/components/cms-services/cms-services.yaml
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, enhancement

#1329 Fix link
  .github/pull-request-template.md
Labels: area/documentation

#1324 Prepare RELEASE_VERSION for next kyma version 1.5
  prow/RELEASE_VERSION
Labels: WIP

#1338 Add jobs for kyma-incubator/hack-showcase
  development/tools/jobs/incubator/hack-showcase/hack_showcase_test.go
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  prow/jobs/incubator/hack-showcase/hack-showcase.yaml
Labels: area/ci

#1336 Add kyma-gke-integration-with-compass jobs
  development/tools/jobs/kyma/kyma_integration_with_compass_test.go
  prow/jobs/kyma/kyma-integration-with-compass.yaml
Labels: area/application-connector, area/ci, enhancement

#1345 Add helm-broker to prow pipelines
  development/tools/jobs/helm-broker/helm_broker_test.go
  development/tools/jobs/kyma/helm_broker_test.go
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  prow/jobs/helm-broker/helm-broker.yaml
  prow/jobs/kyma/components/helm-broker/helm-broker.yaml
Labels: area/service-catalog

#1348 Delete not used compass jobs
  development/tools/jobs/kyma/kyma_integration_with_compass_test.go
  prow/jobs/kyma/kyma-integration-with-compass.yaml
Labels: area/application-connector, area/ci, bug

#1349 Prow ctrl image update for deployment
  prow/cluster/08-prow-addons-ctrl-manager.yaml
Labels: area/ci

#1350 Remove preset-docker-push-repository-incubator grom helm-broker job
  development/tools/jobs/helm-broker/helm_broker_test.go
  prow/jobs/helm-broker/helm-broker.yaml
Labels: area/service-catalog

#1351 Add preset-docker-push-repository to helm-broker job
  development/tools/jobs/helm-broker/helm_broker_test.go
  prow/jobs/helm-broker/helm-broker.yaml
Labels: area/service-catalog

#1354 Restore kyma component helm-broker job
  development/tools/jobs/kyma/helm_broker_test.go
  prow/jobs/kyma/components/helm-broker/helm-broker-deprecated.yaml
Labels: area/service-catalog

#1352 Adjust kyma-compass-integration job
  development/tools/jobs/kyma/kyma_compass_integration_test.go
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
Labels: area/application-connector, area/ci, enhancement

#1322 Remove odata job
  development/tools/jobs/console/react-odata_test.go
  prow/jobs/console/components/react-odata/react-odata.yaml
Labels: area/ci

#1361 Fix bugged kyma-gke-compass-integration pipeline
  development/tools/jobs/kyma/kyma_compass_integration_test.go
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
Labels: area/application-connector, area/ci, bug

#1366 Fix compass integration script
  prow/scripts/provision-vm-compass.sh
Labels: area/ci, bug

#1364 Copy compass artifacts
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build-kyma-development-artifacts.sh
  prow/scripts/provision-vm-compass.sh
Labels: area/installation, enhancement

#1367 Disable the tests manipulating the Application resource in kyma-gke-compass-integration
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
Labels: area/application-connector, area/ci, enhancement

#1369 Fix overrides in kyma-gke-compass-integration pipeline
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
Labels: area/application-connector, area/ci, bug

#1375 Add permissions to start-wssagent.sh and fix vendoring golint
  development/tools/Gopkg.lock
  development/tools/Gopkg.toml
  development/tools/before-commit.sh
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
Labels: area/ci, bug

#1381 Fix golint in watch-pods, stability-checker and in development/tools
  development/tools/Gopkg.lock
  development/tools/Gopkg.toml
  development/tools/before-commit.sh
  stability-checker/Gopkg.lock
  stability-checker/Gopkg.toml
  stability-checker/before-commit.sh
  watch-pods/Gopkg.lock
  watch-pods/Gopkg.toml
  watch-pods/before-commit.sh
Labels: area/ci, bug

#1379 Fix golint in every package in stability-checker and watch-pods
  stability-checker/Gopkg.lock
  stability-checker/Gopkg.toml
  stability-checker/before-commit.sh
  watch-pods/Gopkg.lock
  watch-pods/Gopkg.toml
  watch-pods/before-commit.sh
Labels: area/ci, bug

#1357 Adjust kyma-gke-compass-integration jobs after stabilization
  prow/jobs/kyma/kyma-compass-integration.yaml
Labels: area/application-connector, area/ci, enhancement

#1395 Update Kubebuilder version
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
  prow/images/buildpack-golang-kubebuilder2/README.md
Labels: area/ci, enhancement

#1394 Added mandatory arguments for delete-dns-record.sh script execution.
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/ci, bug

#1399 Connector tests job
  development/tools/jobs/incubator/compass/connector_tests_test.go
  prow/jobs/incubator/compass/tests/connector/connector-tests.yaml
Labels: area/application-connector, enhancement

#1406 Migrate pipelines to Kubernetes 1.13
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Labels: area/ci, area/cluster, enhancement

#1396 Change kubebuilder version
  development/tools/jobs/kyma/asset_store_controller_manager_test.go
  development/tools/jobs/kyma/cms_controller_manager_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/incubator/api-gateway/api-gateway.yaml
  prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml
  prow/jobs/kyma/components/cms-controller-manager/cms-controller-manager.yaml
Labels: area/ci, enhancement

#1410 Add jobs for the terraform provider gardener
  development/tools/jobs/incubator/terraform-provider-gardener/terraform_provider_gardener_test.go
  prow/jobs/incubator/terraform-provider-gardener/terraform-provider-gardener.yaml
Labels: area/cli
