Repository kyma-project/test-infra, pull requests merged in 2019-11, with the labels that each got.

#1676 Add pre-submit Kyma Lite on kind job
  .gitignore
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/scripts/kind-install-kyma.sh
  prow/scripts/kind/cluster.yaml
  prow/scripts/kind/resources/01-metrics-server.yaml
  prow/scripts/kind/resources/02-local-path-provisioner.yaml
  prow/scripts/lib/docker.sh
  prow/scripts/lib/junit.sh
  prow/scripts/lib/kind.sh
  prow/scripts/lib/kubernetes.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/log.sh
  prow/scripts/library.sh
Labels: area/ci, enhancement

#1700 Enable SSDs for GKE clusters
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#1702 Add stubDomains to the workload cluster
  prow/set-up-workload-cluster.sh
  prow/workload-cluster/03-kube-dns-stub-domains-patch.yaml
Labels: area/ci, area/cluster

#1698 add release-to-release upgrade pipeline
  development/tools/jobs/kyma/kyma_release_upgrade_test.go
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
Labels: area/ci, enhancement

#1703 Bump backup plugin image
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
Labels: area/eventing

#1704 Add a job for dex fork
  development/tools/jobs/incubator/dex/dex_test.go
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/incubator/dex/dex.yaml
  prow/jobs/kyma/tests/integration/dex/dex-tests.yaml
  templates/config.yaml
Labels: area/ci, area/security, enhancement

#1712 Increase memory limits #1623
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/resources/limitrange-patch.yaml
  prow/scripts/resources/prometheus-operator-stackdriver-patch.yaml
Labels: area/ci, enhancement

#1713 Add missing autogenerated files to tracking for validation prow job.
  prow/jobs/test-infra/validation.yaml
Labels: bug

#1723 Kyma gke nightly failing because of ip in status in use #1718
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
Labels: area/ci, bug, neighbours/interruption

#1725 Provision regional cluster for weekly and nightly #1717
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/deprovision-gke-cluster.sh
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, enhancement

#1736 Increase number of cpu cores for nightly and weekly clusters. #1735
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci, area/performance, area/quality, enhancement, neighbours/interruption

#1732 Migrate Kyma GKE pipeline to kind
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/scripts/README.md
  prow/scripts/kind-install-kyma.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/docker.sh
  prow/scripts/lib/host.sh
  prow/scripts/lib/junit.sh
  prow/scripts/lib/kind.sh
  prow/scripts/lib/kubernetes.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/log.sh
  prow/scripts/lib/testing-helpers.sh
Labels: area/ci, area/cluster, enhancement

#1739 Fix JUnit report generation
  prow/scripts/lib/junit.sh
Labels: area/ci, bug

#1747 Add preset-kind-volume-mounts for Rafter
  prow/jobs/rafter/rafter.yaml
Labels: area/ci, area/core-and-supporting, enhancement

#1746 Add JUnit reports to GKE jobs
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci, area/quality, enhancement

#1749 Add integration test target
  prow/jobs/rafter/rafter.yaml
Labels: area/ci, area/core-and-supporting, enhancement

#1752 Fix Rafter job config
  prow/jobs/rafter/rafter.yaml
Labels: area/ci, area/core-and-supporting, bug

#1753 Fix test suite name
  prow/scripts/kyma-testing.sh
Labels: area/ci, bug

#1754 Fix JUnit integration tests naming
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/junit.sh
Labels: area/ci

#1759 Move comment to fix line skipping
  prow/scripts/kyma-testing.sh
Labels: bug

#1763 Add kyma CLI stable binary job
  development/tools/jobs/cli/cli_test.go
  prow/config.yaml
  prow/jobs/cli/cli.yaml
  templates/templates/prow-config.yaml
Labels: area/cli

#1768 Replace Kyma CLI download URL
  prow/scripts/kyma-testing.sh
Labels: area/cli

#1781 Change Kyma on kind resources
  prow/jobs/kyma/kyma-kind-integration.yaml
Labels: area/ci, area/cluster, enhancement

#1751 increase ProwJob limit
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: WIP, area/ci

#1774 Prow upgrade #1556
  development/checker/Gopkg.toml
  development/create-service-accounts-for-fork.sh
  development/helper.sh
  development/prow-addons-ctrl-manager/config/kustomization.yaml
  development/prow-installer/.gitignore
  development/prow-installer/Makefile
  development/prow-installer/cmd/installer/main.go
  development/prow-installer/cmd/secrets/main.go
  development/prow-installer/config/prow-installer-config.yaml
  development/prow-installer/go.mod
  development/prow-installer/go.sum
  development/prow-installer/pkg/accessmanager/accessmanager.go
  development/prow-installer/pkg/installer/installer.go
  development/prow-installer/pkg/secrets/secrets.go
  development/prow-installer/pkg/secrets/secrets_test.go
  development/tools/Gopkg.toml
  prow/workload-cluster/required-secrets.yaml
Labels: area/ci, enhancement

#1755 Update job definitions for rafter
  development/tools/jobs/rafter/rafter_test.go
  development/tools/jobs/tester/preset/preset.go
  development/tools/jobs/tester/tester.go
  prow/jobs/rafter/rafter.yaml
Labels: area/core-and-supporting, enhancement

#1784 Update rafter jobs: add missing base_ref to test-infra with sha
  development/tools/jobs/rafter/rafter_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/rafter/rafter.yaml
Labels: area/core-and-supporting, bug

#1785 Add missing preset to rafter jobs for minio gcs gateway mode
  development/tools/jobs/rafter/rafter_test.go
  prow/jobs/rafter/rafter.yaml
Labels: area/core-and-supporting, bug

#1775 Parametrize kind::export_logs function
  prow/scripts/kind-install-kyma.sh
  prow/scripts/lib/kind.sh
Labels: area/core-and-supporting, enhancement

#1786 [Rafter] update base_sha and make gateway and migration jobs optional
  development/tools/jobs/rafter/rafter_test.go
  prow/jobs/rafter/rafter.yaml
Labels: area/core-and-supporting, enhancement
