Repository kyma-project/test-infra, pull requests merged in 2019-02, with the labels that each got.

#562 Define job for Asset Store
  development/tools/jobs/common/common_test.go
  development/tools/jobs/kyma/acceptance_tests_test.go
  development/tools/jobs/kyma/api_controller_acceptance_tests_test.go
  development/tools/jobs/kyma/api_controller_test.go
  development/tools/jobs/kyma/apiserver_proxy_test.go
  development/tools/jobs/kyma/application_broker_test.go
  development/tools/jobs/kyma/application_operator_test.go
  development/tools/jobs/kyma/application_operator_tests_test.go
  development/tools/jobs/kyma/application_proxy_test.go
  development/tools/jobs/kyma/application_registry_test.go
  development/tools/jobs/kyma/application_registry_tests_test.go
  development/tools/jobs/kyma/assetstore_controller_manager_test.go
  development/tools/jobs/kyma/binding_usage_controller_test.go
  development/tools/jobs/kyma/bucket_controller_test.go
  development/tools/jobs/kyma/configurations_generator_test.go
  development/tools/jobs/kyma/connection_token_handler_test.go
  development/tools/jobs/kyma/connector_service_test.go
  development/tools/jobs/kyma/connector_service_tests_test.go
  development/tools/jobs/kyma/docs_test.go
  development/tools/jobs/kyma/event_bus_test.go
  development/tools/jobs/kyma/event_service_test.go
  development/tools/jobs/kyma/gateway_tests_test.go
  development/tools/jobs/kyma/helm_broker_test.go
  development/tools/jobs/kyma/installer_test.go
  development/tools/jobs/kyma/k8s_dashboard_proxy_test.go
  development/tools/jobs/kyma/knative_serving_acceptance_test.go
  development/tools/jobs/kyma/kubeless_integration_tests_test.go
  development/tools/jobs/kyma/kubeless_tests_test.go
  development/tools/jobs/kyma/logging_tests_test.go
  development/tools/jobs/kyma/namespace_controller_test.go
  development/tools/jobs/kyma/stability_checker_test.go
  development/tools/jobs/kyma/test_event_bus_test.go
  development/tools/jobs/kyma/test_logging_monitoring_test.go
  development/tools/jobs/kyma/test_namespace_controller_test.go
  development/tools/jobs/kyma/tools/alpine_net_test.go
  development/tools/jobs/kyma/tools/ark_plugins_test.go
  development/tools/jobs/kyma/tools/etcd_backup_test.go
  development/tools/jobs/kyma/tools/etcd_tls_setup_test.go
  development/tools/jobs/kyma/ui_api_layer_acceptance_tests_test.go
  development/tools/jobs/kyma/ui_api_layer_test.go
  development/tools/jobs/kyma/watch_pods_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/components/asset-controller/asset-controller.yaml
  prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml
Labels: area/ci, enhancement

#567 Add buildpack-golang-kubebuilder
  prow/images/buildpack-golang-kubebuilder/Dockerfile
  prow/images/buildpack-golang-kubebuilder/Makefile
  prow/images/buildpack-golang-kubebuilder/README.md
Labels: area/ci, enhancement

#569 Fix docker push directory for Kubebuilder buildpack
  prow/images/buildpack-golang-kubebuilder/Makefile
Labels: area/ci, bug

#568 Change buildpack for Asset Store
  development/tools/jobs/kyma/assetstore_controller_manager_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml
Labels: area/ci, enhancement

#540 Update release process
  development/tools/cmd/githubrelease/README.md
  development/tools/cmd/githubrelease/main.go
  development/tools/pkg/release/release.go
  docs/prow/assets/kyma-rel-jobs.svg
  docs/prow/release-process.md
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/ci, area/documentation, enhancement

#573 Change golang buildpacks in ui-api-layer and acceptance tests
  development/tools/jobs/kyma/ui_api_layer_acceptance_tests_test.go
  development/tools/jobs/kyma/ui_api_layer_test.go
  prow/jobs/kyma/components/ui-api-layer/ui-api-layer.yaml
  prow/jobs/kyma/tests/ui-api-layer-acceptance-tests/ui-api-layer-acceptance-tests.yaml
Labels: area/console, bug

#574 Fix clusters removal process
  development/tools/cmd/clusterscollector/README.md
  development/tools/cmd/clusterscollector/main.go
  development/tools/pkg/clusterscollector/collector.go
  development/tools/pkg/clusterscollector/collector_test.go
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
Labels: area/ci

#571 Final configuration for nightly and weekly cluster
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/tester/tester.go
  docs/prow/presets.md
  prow/cluster/required-secrets.yaml
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/generate-self-signed-cert.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#578 Add job with flunetd testing cluster
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-fluentd.sh
Labels: area/cluster

#580 Add missing tests, add validation for unique jobs name
  development/README.md
  development/checker/unique-jobs-name/main.go
  development/tools/jobs/common/common_test.go
  development/tools/jobs/kyma/acceptance_tests_test.go
  development/tools/jobs/kyma/api_controller_acceptance_tests_test.go
  development/tools/jobs/kyma/api_controller_test.go
  development/tools/jobs/kyma/apiserver_proxy_test.go
  development/tools/jobs/kyma/application_broker_test.go
  development/tools/jobs/kyma/application_operator_test.go
  development/tools/jobs/kyma/application_operator_tests_test.go
  development/tools/jobs/kyma/application_proxy_test.go
  development/tools/jobs/kyma/application_registry_test.go
  development/tools/jobs/kyma/application_registry_tests_test.go
  development/tools/jobs/kyma/binding_usage_controller_test.go
  development/tools/jobs/kyma/configurations_generator_test.go
  development/tools/jobs/kyma/connection_token_handler_test.go
  development/tools/jobs/kyma/connector_service_test.go
  development/tools/jobs/kyma/connector_service_tests_test.go
  development/tools/jobs/kyma/docs_test.go
  development/tools/jobs/kyma/event_bus_test.go
  development/tools/jobs/kyma/event_service_test.go
  development/tools/jobs/kyma/gateway_tests_test.go
  development/tools/jobs/kyma/helm_broker_test.go
  development/tools/jobs/kyma/installer_test.go
  development/tools/jobs/kyma/istio_kyma_patch_test.go
  development/tools/jobs/kyma/k8s_dashboard_proxy_test.go
  development/tools/jobs/kyma/knative_serving_acceptance_test.go
  development/tools/jobs/kyma/kubeless_integration_tests_test.go
  development/tools/jobs/kyma/kubeless_tests_test.go
  development/tools/jobs/kyma/kyma_artifacts_test.go
  development/tools/jobs/kyma/kyma_installer_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/logging_tests_test.go
  development/tools/jobs/kyma/namespace_controller_test.go
  development/tools/jobs/kyma/stability_checker_test.go
  development/tools/jobs/kyma/test_event_bus_test.go
  development/tools/jobs/kyma/test_logging_monitoring_test.go
  development/tools/jobs/kyma/test_namespace_controller_test.go
  development/tools/jobs/kyma/tools/alpine_net_test.go
  development/tools/jobs/kyma/tools/ark_plugins_test.go
  development/tools/jobs/kyma/tools/etcd_backup_test.go
  development/tools/jobs/kyma/tools/etcd_tls_setup_test.go
  development/tools/jobs/kyma/tools/static_users_generator_test.go
  development/tools/jobs/kyma/ui_api_layer_acceptance_tests_test.go
  development/tools/jobs/kyma/ui_api_layer_test.go
  development/tools/jobs/kyma/watch_pods_test.go
  development/tools/jobs/kyma/xip_patch_test.go
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/buildpack_test.go
  development/validate-config.sh
  docs/prow/release-jobs.md
Labels: area/ci, enhancement

#579 Grant the cluster-access team access to the clusters
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, enhancement, sig/core

#585 Remove developers teams from accessing clusters
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#572 Ip dns removal tool
  development/tools/Gopkg.lock
  development/tools/cmd/dnscollector/README.md
  development/tools/cmd/dnscollector/main.go
  development/tools/pkg/dnscollector/automock/compute_api.go
  development/tools/pkg/dnscollector/automock/dnsapi.go
  development/tools/pkg/dnscollector/collector.go
  development/tools/pkg/dnscollector/collector_test.go
  development/tools/pkg/dnscollector/wrappers.go
Labels: area/ci

#586 Create prowjob for dnscollector
  development/dns-cleanup.sh
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, wg/prow

#593 Add missing presets
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, wg/prow

#594 Disable dry-run for dnscollector
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, wg/prow

#595 Add prow-addons-ctrl job and slack token secret information and checks
  development/tools/jobs/testinfra/prow_addons_ctrl_manager_test.go
  docs/prow/presets.md
  docs/prow/prow-installation-on-forks.md
  prow/cluster/required-secrets.yaml
  prow/config.yaml
  prow/jobs/test-infra/prow-addons-ctrl-manager.yaml
Labels: area/ci

#564 Adding a new flag --image to provision-vm-and-start-kyma script
  prow/scripts/provision-vm-and-start-kyma.sh
Labels: area/ci

#599 Fix kyma-integration job
  prow/scripts/provision-vm-and-start-kyma.sh
Labels: area/ci, bug

#563 Adding the option to label the custom image as default
  development/custom-image/README.md
  development/custom-image/create-custom-image.sh
Labels: area/ci

#596 Bump image of milv
  prow/scripts/governance.sh
Labels: enhancement

#601 Revert custom image patch
  prow/scripts/provision-vm-and-start-kyma.sh
Labels: area/ci, bug

#610 Release tool: fix RELEASE_VERSION regexp
  development/tools/pkg/release/version.go
  development/tools/pkg/release/version_test.go
Labels: bug, priority/critical

#616 On demand clusters
  development/tools/jobs/kyma/ondemand_test.go
  docs/prow/presets.md
  prow/config.yaml
  prow/jobs/kyma/kyma-ondemand.yaml
  prow/scripts/build-ondemand-kyma-artifacts.sh
Labels: area/ci

#592 So awesome add-ons controller
  development/prow-addons-ctrl-manager/.gitignore
  development/prow-addons-ctrl-manager/Dockerfile
  development/prow-addons-ctrl-manager/Gopkg.lock
  development/prow-addons-ctrl-manager/Gopkg.toml
  development/prow-addons-ctrl-manager/Makefile
  development/prow-addons-ctrl-manager/PROJECT
  development/prow-addons-ctrl-manager/README.md
  development/prow-addons-ctrl-manager/cmd/manager/main.go
  development/prow-addons-ctrl-manager/config/crds/prowjob.yaml
  development/prow-addons-ctrl-manager/config/default/manager_auth_proxy_patch.yaml
  development/prow-addons-ctrl-manager/config/default/manager_env_patch.yaml
  development/prow-addons-ctrl-manager/config/default/manager_prometheus_metrics_patch.yaml
  development/prow-addons-ctrl-manager/config/default/manager_promethues_service.yaml
  development/prow-addons-ctrl-manager/config/default/rbac_role_binding_patch.yaml
  development/prow-addons-ctrl-manager/config/deploy/deploy.yaml
  development/prow-addons-ctrl-manager/config/kustomization.yaml
  development/prow-addons-ctrl-manager/config/manager/manager.yaml
  development/prow-addons-ctrl-manager/config/rbac/auth_proxy_role.yaml
  development/prow-addons-ctrl-manager/config/rbac/auth_proxy_role_binding.yaml
  development/prow-addons-ctrl-manager/config/rbac/auth_proxy_service.yaml
  development/prow-addons-ctrl-manager/config/rbac/rbac_role.yaml
  development/prow-addons-ctrl-manager/config/rbac/rbac_role_binding.yaml
  development/prow-addons-ctrl-manager/docs/assets/slack_alert.png
  development/prow-addons-ctrl-manager/hack/boilerplate.go.txt
  development/prow-addons-ctrl-manager/pkg/apis/addtoscheme_prowjobs_v1.go
  development/prow-addons-ctrl-manager/pkg/apis/apis.go
  development/prow-addons-ctrl-manager/pkg/controller/add_notifier.go
  development/prow-addons-ctrl-manager/pkg/controller/controller.go
  development/prow-addons-ctrl-manager/pkg/controller/notifier/automock/report_client.go
  development/prow-addons-ctrl-manager/pkg/controller/notifier/notifier_controller.go
  development/prow-addons-ctrl-manager/pkg/controller/notifier/notifier_controller_test.go
  development/prow-addons-ctrl-manager/pkg/controller/notifier/prowjob_controller_suite_test.go
  development/prow-addons-ctrl-manager/pkg/slack/reporter.go
  milv.config.yaml
Labels: area/monitoring, enhancement

#617 Log ui build pack update
  development/tools/jobs/console/log-ui_test.go
  prow/jobs/console/log-ui/log-ui.yaml
Labels: area/ci, area/console, area/logging

#602 Add slack notifier to starter.yaml, skip notify for upgrade job, remo…
  docs/prow/assets/prow-architecture.svg
  docs/prow/production-cluster-configuration.md
  docs/prow/prow-architecture.md
  prow/cluster/08-prow-addons-ctrl-manager.yaml
  prow/cluster/README.md
  prow/cluster/resources/monitoring/templates/prometheus-rule.yaml
  prow/cluster/resources/monitoring/values.yaml
  prow/install-prow.sh
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/monitoring, enhancement

#614 Create authorization doc
  docs/prow/README.md
  docs/prow/authorization.md
Labels: area/ci, area/documentation, area/security

#628 Define Asset Upload Service job
  development/tools/jobs/kyma/asset_upload_service_test.go
  prow/jobs/kyma/components/asset-upload-service/asset-upload-service.yaml
Labels: area/documentation, enhancement

#629 Make Asset Upload Service job optional
  development/tools/jobs/kyma/asset_upload_service_test.go
  prow/jobs/kyma/components/asset-upload-service/asset-upload-service.yaml
Labels: area/ci, enhancement

#632 Add job for website tool - content-loader
  development/tools/jobs/website/website_tools_content_loader_test.go
  prow/jobs/website/tools/website-tools-content-loader.yaml
Labels: area/community, area/documentation, enhancement

#636 Build development artifacts for PR and master branch
  development/tools/jobs/kyma/development_artifacts_test.go
  development/tools/jobs/kyma/ondemand_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-development-artifacts.yaml
  prow/jobs/kyma/kyma-ondemand.yaml
  prow/scripts/build-kyma-development-artifacts.sh
  prow/scripts/build-ondemand-kyma-artifacts.sh
Labels: WIP, area/ci

#637 Add job for Connectivity Certs Controller
  development/tools/jobs/kyma/connectivity_certs_controller_test.go
  prow/jobs/kyma/components/connectivity-certs-controller/connectivity-certs-controller.yaml
Labels: area/application-connector, enhancement

#635 Move the release process to the community repository
  docs/prow/README.md
  docs/prow/assets/kyma-rel-jobs.svg
  docs/prow/assets/release-PR.png
  docs/prow/release-jobs.md
  docs/prow/release-process.md
Labels: area/documentation

#634 Add documentation on prow jobs
  docs/prow/README.md
  docs/prow/component-jobs.md
  docs/prow/prow-jobs.md
  prow/README.md
Labels: area/documentation

#640 Document generation of development artifacts
  development/tools/jobs/kyma/development_artifacts_test.go
  docs/prow/prow-architecture.md
  prow/jobs/kyma/kyma-development-artifacts.yaml
Labels: area/ci

#649 Rename console/log-ui to console/logging
  development/tools/jobs/console/logging_test.go
  prow/jobs/console/logging/logging-ui.yaml
Labels: area/ci, enhancement

#651 Add more resources to Asset Store job
  prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml
Labels: area/ci, bug

#647 Create prowjob for building cluster-users-test image
  development/tools/jobs/kyma/cluster_users_test.go
  prow/jobs/kyma/tests/cluster-users-test/cluster-users-test.yaml
Labels: area/ci, area/service-mesh

#656 fix creation of end to end cluster
  prow/config.yaml
  prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh
Labels: area/ci

#654 Add vulnerability scanner image
  prow/images/README.md
  prow/images/vulnerability-scanner/Dockerfile
  prow/images/vulnerability-scanner/Makefile
  prow/images/vulnerability-scanner/README.md
Labels: area/ci

#650 Add open source vulnerabilities scanner job
  development/tools/jobs/kyma/vulnerability_scanner_test.go
  development/vulnerabilites-scanner.sh
  prow/cluster/required-secrets.yaml
  prow/config.yaml
  prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Labels: area/ci

#661 Vulnerabilities scanner fix
  development/tools/jobs/kyma/vulnerability_scanner_test.go
  development/vulnerabilities-scanner.sh
  prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Labels: area/ci

#663 Vulnerabilities scanner fix
  development/tools/jobs/kyma/vulnerability_scanner_test.go
  development/vulnerabilities-scanner.sh
  prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Labels: area/ci

#660 Vulnerabilities scanner job updated schedule
  development/tools/jobs/kyma/vulnerability_scanner_test.go
  prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Labels: area/ci

#655 Add prow job for kyma-incubator/octopus
  development/tools/jobs/incubator/octopus/octopus_test.go
  prow/jobs/incubator/octopus/octopus.yaml
Labels: area/ci

#664 Add az to kyma-cluster-infra image
  prow/images/kyma-cluster-infra/Dockerfile
Labels: area/ci, area/installation, enhancement

#668 Integration for kyma with central connector
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/application-connector, area/ci, enhancement

#669 path_alias typo fix in central job
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/application-connector, area/ci

#657 Rename tests for monitoring
  development/tools/jobs/kyma/monitoring_test.go
  development/tools/jobs/kyma/test_logging_monitoring_test.go
  prow/jobs/kyma/tests/monitoring/monitoring.yaml
Labels: area/monitoring

#666 Add kyma-gke-central script
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-central.sh
Labels: area/application-connector, area/ci, enhancement

#674 Add prowjob for apiserver-proxy-test
  development/tools/jobs/kyma/apiserver_proxy_test_test.go
  prow/jobs/kyma/tests/apiserver-proxy-tests/apiserver-proxy-test.yaml
Labels: area/ci

#642 Add provisioning job to nightly kyma on aks
  development/tools/jobs/kyma/kyma_integration_test.go
  docs/prow/presets.md
  prow/cluster/required-secrets.yaml
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Labels: area/ci, area/installation, enhancement
