Repository kyma-project/test-infra, pull requests merged in 2019-07, with the labels that each got.

#1189 Adding vars to periodic job
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1193 Fix typo
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1190 Introduce License Puller
  prow/scripts/library.sh
  prow/scripts/license-puller.sh
Labels: area/ci, area/community, enhancement

#1197 Kyma-operator development artifatcs update
  prow/scripts/build-kyma-development-artifacts.sh
Labels: area/security, enhancement

#1201 Periodic xip
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1203 add missing variable
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1200 Add job for Application Connectivity Cert Setup Job
  development/tools/jobs/kyma/application_connectivity_certs_setup_job_test.go
  prow/jobs/kyma/components/application-connectivity-certs-setup-job/application-connectivity-certs-setup-job.yaml
Labels: area/application-connector, enhancement

#1208 Remove Compass Registry job
  development/tools/jobs/incubator/compass/registry_test.go
  prow/jobs/incubator/compass/components/registry/registry.yaml
Labels: area/ci, enhancement

#1195 remove installer jobs
  development/tools/jobs/kyma/installer_test.go
  development/tools/jobs/kyma/kyma_operator_test.go
  prow/jobs/kyma/components/installer/installer.yaml
  prow/jobs/kyma/components/kyma-operator/kyma-operator.yaml
Labels: area/security, enhancement

#1209 remove installer from development artifatcs job
  development/tools/jobs/kyma/development_artifacts_test.go
  prow/jobs/kyma/kyma-development-artifacts.yaml
  prow/scripts/build-kyma-development-artifacts.sh
Labels: area/security, enhancement

#1207 Revert XIP implementation
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci

#1214 Copy api-controller integration tests job
  development/tools/jobs/kyma/api_controller_tests_test.go
  development/tools/jobs/kyma/apiserver_proxy_tests_test.go
  prow/jobs/kyma/tests/integration/api-controller/api-controller-integration.yaml
Labels: area/service-mesh

#1215 Test 1.3-RC0
  prow/RELEASE_VERSION
Labels: WIP

#1216 Remove branches, add base_ref
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1221 Add periodic job for Compass integration
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/incubator/compass/resources/installer-cr-cluster-with-compass.yaml.tpl
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci

#1223 Fix kyma-compass-integration-periodic job
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1217 Switch the Job for the API-controller tests
  development/tools/jobs/kyma/api_controller_acceptance_tests_test.go
  development/tools/jobs/kyma/api_controller_tests_test.go
  prow/jobs/kyma/tests/api-controller-acceptance-tests/api-controller-acceptance-tests.yaml
  prow/jobs/kyma/tests/integration/api-controller/api-controller-integration.yaml
Labels: area/service-mesh

#1225 Add extra ref to compass integration job
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/scripts/provision-vm-compass.sh
Labels: WIP

#1222 remove redundant overrides
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/ci, area/installation

#1232 Mark minio migration job as required
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci, enhancement

#1231 Remove Compass periodic job
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: bug

#1235 Fix compass release
  prow/RELEASE_VERSION
  prow/scripts/build.sh
Labels: area/ci

#1237 Remove readonly from variable
  prow/scripts/library.sh
Labels: area/ci, bug

#1236 Add compass integration jobs
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/scripts/provision-vm-compass.sh
Labels: WIP

#1229 Debug xip DNS resolution issues #1206
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1239 disable notifications
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1242 Overwrite kube-dns-autoscaler config map
  prow/set-up-workload-cluster.sh
Labels: area/ci

#1241 Add compass integration jobs
  development/tools/jobs/incubator/compass/compass_end_to_end_test.go
  development/tools/jobs/incubator/compass/compass_integration_test.go
  development/tools/jobs/incubator/compass/connector_test.go
  development/tools/jobs/incubator/compass/director_test.go
  development/tools/jobs/incubator/compass/gateway_test.go
  development/tools/jobs/incubator/compass/healthchecker_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/incubator/compass/components/connector/connector.yaml
  prow/jobs/incubator/compass/components/director/director.yaml
  prow/jobs/incubator/compass/components/gateway/gateway.yaml
  prow/jobs/incubator/compass/components/healthchecker/healthchecker.yaml
  prow/jobs/incubator/compass/tests/end-to-end/end-to-end.yaml
Labels: area/ci, enhancement

#1240 Job for runtime-agent added
  development/tools/jobs/incubator/compass/runtime-agent_test.go
  prow/jobs/incubator/compass/components/runtime-agent/runtime-agent.yaml
Labels: area/application-connector

#1230 CI build pipeline for Compass UI
  development/tools/jobs/console/compass_test.go
  prow/jobs/console/compass/compass.yaml
Labels: enhancement

#1228 Enable periodic job for Kyma with Compass
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci, enhancement

#1248 Add additional labels to compass job
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1249 Add additional labels for the Compass periodic job
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1252 Cleanup the Compass tests
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/incubator/compass/compass-integration.yaml
Labels: area/ci

#1255 sa necessary for knative testing
  prow/config.yaml
Labels: area/ci

#1259 Move Runtime Agent jobs to Kyma
  development/tools/jobs/incubator/compass/runtime-agent_test.go
  development/tools/jobs/kyma/compass_runtime_agent_test.go
  prow/jobs/incubator/compass/components/runtime-agent/runtime-agent.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent.yaml
Labels: area/application-connector

#1258 Test solution for xip.io issues #1206
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
Labels: area/ci

#1260 Add compass schema-migrator component build job
  development/tools/jobs/incubator/compass/schema-migrator_test.go
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator.yaml
Labels: area/ci

#1264 Make Compass Runtime Job required
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent.yaml
Labels: area/application-connector

#1243 Remove gcp-broker-provider
  development/tools/jobs/kyma/tools/gcp_broker_provider_test.go
  prow/jobs/kyma/tools/gcp-broker-provider/gcp-broker-provider.yaml
Labels: area/service-catalog

#1265 Add prow job for Compass Runtime Agent tests
  development/tools/jobs/kyma/compass_runtime_agent_test_test.go
  prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-test.yaml
Labels: area/application-connector, area/ci, enhancement

#1270 Add compass job for testing purposes
  prow/jobs/incubator/compass/compass-integration.yaml
Labels: area/ci

#1279 Modify gke compass integration periodic job
  development/tools/jobs/kyma/kyma_compass_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/incubator/compass/resources/installer-cr-cluster-with-compass.yaml.tpl
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
Labels: area/ci, bug

#1280 Add Kyma CLI integration job
  development/tools/jobs/cli/cli_integration_test.go
  prow/jobs/cli/cli-integration.yaml
  prow/scripts/provision-vm-cli.sh
Labels: area/cli

#1286 Fix compass periodic job refs
  prow/jobs/kyma/kyma-compass-integration.yaml
Labels: area/ci

#1289 Add kyma test command to the CLI integration test
  prow/scripts/provision-vm-cli.sh
Labels: area/cli

#1251 Add periodic whitesource scan
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/images/README.md
  prow/images/buildpack-java/Dockerfile
  prow/images/buildpack-java/Makefile
  prow/images/buildpack-java/README.md
  prow/images/whitesource-scanner/Dockerfile
  prow/images/whitesource-scanner/Makefile
  prow/images/whitesource-scanner/README.md
  prow/images/whitesource-scanner/wss-unified-agent.config
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
Labels: area/ci, area/security

#1296 Update stale bot settings to exclude epics
  .github/stale.yml
Labels: area/community

#1272 Make Compass Runtime Agent Tests job required
  prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-test.yaml
Labels: area/application-connector, area/ci, enhancement

#1250 Container vulnerability collector for gcr.io registry
  development/container-vulnerabilities.sh
  development/tools/Gopkg.lock
  development/tools/Gopkg.toml
  development/tools/cmd/vulnerabilitycollector/README.md
  development/tools/cmd/vulnerabilitycollector/main.go
  development/tools/jobs/kyma/vulnerability_scanner_test.go
  development/tools/pkg/vulnerabilitycollector/vulnerabilitycollector.go
  development/tools/pkg/vulnerabilitycollector/vulnerabilitycollector_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-governance.yaml
  prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Labels: area/ci, area/security

#1262 Add jobs for kyma-incubator/documentation-component
  development/tools/jobs/incubator/documentation-component/documentation-component_test.go
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  prow/jobs/incubator/documentation-component/documentation-component.yaml
Labels: area/core-and-supporting, enhancement

#1302 Add job fo CMS Services
  development/tools/jobs/kyma/cms_services_test.go
  prow/jobs/kyma/components/cms-services/cms-services.yaml
Labels: area/ci, area/core-and-supporting, enhancement

#1307 Bump Golang and Dep in golang buildpack
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-golang/README.md
Labels: area/ci, area/documentation, enhancement

#1308 Change go version in cms-services
  development/tools/jobs/kyma/cms_services_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/components/cms-services/cms-services.yaml
Labels: area/ci, enhancement

#1310 Implement workaround
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1311 Compass Integration adjust VM settings
  prow/scripts/provision-vm-compass.sh
Labels: area/ci

#1314 Adjust compass integration vm settings
  prow/scripts/provision-vm-compass.sh
Labels: area/ci
