Repository kyma-project/test-infra, pull requests merged in 2019-09, with the labels that each got.

#1407 Improve nightly cleaners
  development/resources-cleanup.sh
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#1422 DNS cleanup fix
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#1424 fix dns name
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
Labels: area/ci

#1426 Fetch proper IP
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
Labels: area/ci

#1427 IP-cleanup fixes
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#1428 Gateway IP
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
Labels: area/application-connector

#1429 reverting changes
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#1431 Provisioner pipeline
  development/tools/jobs/incubator/compass/provisioner_test.go
  development/tools/jobs/incubator/compass/provisioner_tests_test.go
  prow/jobs/incubator/compass/components/provisioner/provisioner.yaml
  prow/jobs/incubator/compass/tests/provisioner/provisioner-tests.yaml
Labels: area/application-connector, enhancement

#1433 changing europe-west4-c to europe-west4-a zone
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/kyma_release_candidate_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: area/ci

#1439 Adding nightly test job
  templates/templates/kyma-integration.yaml
Labels: area/ci

#1442 New test job
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#1443 Changing from post to presubmit job
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1447 add retries
  prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
Labels: area/ci

#1462 Make generic CBS job optional
  prow/jobs/kyma/components/console-backend-service/console-backend-service-generic.yaml
  templates/templates/generic-component.yaml
Labels: area/ci, bug

#1397 Prow endpoints monitoring(1123)
  development/create-service-accounts-for-fork.sh
  development/helper.sh
  development/install-prow.sh
  development/provision-cluster.sh
  docs/prow/prow-monitoring.md
  prow/cluster/resources/monitoring/alertmanager-config.yaml
  prow/cluster/resources/monitoring/dashboards/grafana-prow.json
  prow/cluster/resources/monitoring/grafana-config.yaml
  prow/cluster/resources/monitoring/prometheus-config.yaml
  prow/cluster/resources/monitoring/templates/prow_prometheusrules.yaml
  prow/cluster/resources/monitoring/values.yaml
Labels: area/ci, enhancement

#1478 Kyma aks nightly fail #1446
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Labels: area/ci, bug

#1484 Old jobs
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
Labels: area/ci

#1487 Bump Kubernetes version to 1.14
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Labels: area/ci, area/cluster, area/installation, enhancement

#1493 Corrected dashboard section title.
  prow/cluster/resources/monitoring/dashboards/grafana-prow.json
Labels: area/ci, bug

#1496 Added required arguments for release-ip-address.sh script execution.
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
Labels: area/ci, bug

#1497 Enable Slack notifications for Whitesource scans
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#1517 Add MinIO Azure Gateway pipelines
  CODEOWNERS
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
  prow/scripts/cluster-integration/minio/azure-cleaner.sh
  prow/scripts/cluster-integration/minio/azure-gateway.sh
  prow/scripts/cluster-integration/minio/gcs-gateway.sh
  templates/config.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci, area/core-and-supporting, enhancement

#1520 remove kyma-gke-service-catalog-crd-periodic job
  development/tools/cmd/dnscollector/main.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/workload-cluster/required-secrets.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/service-catalog

#1402 Add pr images guard job on release branches
  development/tools/jobs/kyma/kyma_release_pr_image_guard_test.go
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
  prow/scripts/pr-image-guard.sh
Labels: area/ci, enhancement

#1521 Execute only Asset Store tests for MinIO Gateway modes
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
Labels: area/ci, area/core-and-supporting, enhancement

#1490 Bump integration jobs to Kubernetes 1.14
  development/tools/jobs/kyma/kyma_compass_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/kyma_release_pr_image_guard_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  templates/templates/compass-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci, area/cluster, enhancement
