Repository kyma-project/test-infra, pull requests merged in 2019-10, with the labels that each got.

#1536 Fix a non-existent anchor in a link
  development/custom-image/README.md
Labels: area/documentation, bug

#1534 Add kind to toolbox image and high load node pool to workload cluster
  development/provision-cluster.sh
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang-toolbox/README.md
Labels: area/ci, area/cluster, area/documentation, enhancement

#1547 Make core UI job non-optional
  development/tools/jobs/console/core_ui_test.go
  prow/jobs/console/core-ui/core-ui.yaml
  templates/config.yaml
Labels: area/ci

#1566 Make pre-master-kyma-minio-* jobs optional
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#1600 Adapt cli changes in the compass integration
  development/tools/jobs/incubator/compass/compass_integration_test.go
  prow/jobs/incubator/compass/compass-integration.yaml
  templates/templates/compass-integration.yaml
Labels: enhancement

#1582 Add rsync and procps to Golang Toolbox image
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang-toolbox/README.md
Labels: area/ci, area/documentation, enhancement

#1539 Update documentation to explain the job templates approach
  development/prow-addons-ctrl-manager/README.md
  development/tools/cmd/configuploader/README.md
  development/tools/cmd/rendertemplates/README.md
  development/tools/cmd/secretspopulator/README.md
  docs/prow/README.md
  docs/prow/assets/prow-architecture.svg
  docs/prow/component-jobs.md
  docs/prow/manage-component-jobs-with-templates.md
  docs/prow/presets.md
  docs/prow/production-cluster-configuration.md
  docs/prow/prow-architecture.md
  docs/prow/prow-installation-on-forks.md
  docs/prow/prow-jobs.md
  docs/prow/prow-secrets-management.md
  docs/prow/release-jobs.md
  docs/prow/templates.md
  prow/README.md
  prow/cluster/README.md
  prow/images/README.md
  prow/scripts/cluster-integration/README.md
  templates/README.md
Labels: area/documentation

#1608 Switch to generic prow job for api-controller tests
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/integration/api-controller/api-controller-tests-generic.yaml
  prow/jobs/kyma/tests/integration/api-controller/api-controller-tests.yaml
  templates/config.yaml
Labels: area/ci, enhancement

#1609 Add jobs for Kind environment
  CODEOWNERS
  prow/jobs/test-infra/test-infra-kind.yaml
Labels: area/ci, area/cluster, enhancement

#1538 Add Kind cluster setup
  kind/KIND_KUBERNETES_VERSION
  kind/README.md
  kind/cluster/cluster.yaml
  kind/cluster/resources/01-metrics-server.yaml
  kind/cluster/resources/02-local-path-provisioner.yaml
  kind/config/overrides.yaml
  kind/scripts/build-kubernetes-image.sh
  kind/scripts/common.sh
  kind/scripts/install-kyma.sh
Labels: area/ci, area/documentation, enhancement

#1611 Fix kind periodic job
  prow/jobs/test-infra/test-infra-kind.yaml
Labels: area/ci, bug

#1567 Generic prow jobs for Framefrogs' component pool
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/components/application-connectivity-certs-setup-job/application-connectivity-certs-setup-job-generic.yaml
  prow/jobs/kyma/components/application-connectivity-validator/application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/application-gateway/application-gateway-generic.yaml
  prow/jobs/kyma/components/application-operator/application-operator-generic.yaml
  prow/jobs/kyma/components/application-registry/application-registry-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent.yaml
  prow/jobs/kyma/components/connection-token-handler/connection-token-handler-generic.yaml
  prow/jobs/kyma/components/connectivity-certs-controller/connectivity-certs-controller-generic.yaml
  prow/jobs/kyma/components/connector-service/connector-service-generic.yaml
  prow/jobs/kyma/tests/application-connector-tests/application-connector-tests-generic.yaml
  prow/jobs/kyma/tests/application-gateway-tests/application-gateway-tests-generic.yaml
  prow/jobs/kyma/tests/application-operator-tests/application-operator-tests-generic.yaml
  prow/jobs/kyma/tests/application-registry-tests/application-registry-tests-generic.yaml
  prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-tests-generic.yaml
  prow/jobs/kyma/tests/connection-token-handler-tests/connection-token-handler-tests-generic.yaml
  prow/jobs/kyma/tests/connector-service-tests/connector-service-tests-generic.yaml
  templates/config.yaml
Labels: area/application-connector, area/ci, enhancement

#1645 Fix GREEN: unbound variable error
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
Labels: area/ci, bug

#1656 fix-backup-restore-event-bus
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
Labels: area/ci

#1631 Change section `if-change` to new makefile location
  prow/jobs/kyma/components/api-controller/api-controller-generic.yaml
  prow/jobs/kyma/components/apiserver-proxy/apiserver-proxy-generic.yaml
  prow/jobs/kyma/components/application-broker/application-broker-generic.yaml
  prow/jobs/kyma/components/application-connectivity-certs-setup-job/application-connectivity-certs-setup-job-generic.yaml
  prow/jobs/kyma/components/application-connectivity-validator/application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/application-gateway/application-gateway-generic.yaml
  prow/jobs/kyma/components/application-operator/application-operator-generic.yaml
  prow/jobs/kyma/components/application-registry/application-registry-generic.yaml
  prow/jobs/kyma/components/backup-plugins/backup-plugins-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/connection-token-handler/connection-token-handler-generic.yaml
  prow/jobs/kyma/components/connectivity-certs-controller/connectivity-certs-controller-generic.yaml
  prow/jobs/kyma/components/connector-service/connector-service-generic.yaml
  prow/jobs/kyma/components/console-backend-service/console-backend-service-generic.yaml
  prow/jobs/kyma/components/dex-static-user-configurer/dex-static-user-configurer-generic.yaml
  prow/jobs/kyma/components/iam-kubeconfig-service/iam-kubeconfig-service-generic.yaml
  prow/jobs/kyma/components/istio-kyma-patch/istio-kyma-patch-generic.yaml
  prow/jobs/kyma/components/kyma-operator/kyma-operator-generic.yaml
  prow/jobs/kyma/components/service-binding-usage-controller/service-binding-usage-controller-generic.yaml
  prow/jobs/kyma/components/xip-patch/xip-patch-generic.yaml
  prow/jobs/kyma/tests/application-connector-tests/application-connector-tests-generic.yaml
  prow/jobs/kyma/tests/application-gateway-tests/application-gateway-tests-generic.yaml
  prow/jobs/kyma/tests/application-operator-tests/application-operator-tests-generic.yaml
  prow/jobs/kyma/tests/application-registry-tests/application-registry-tests-generic.yaml
  prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-tests-generic.yaml
  prow/jobs/kyma/tests/connection-token-handler-tests/connection-token-handler-tests-generic.yaml
  prow/jobs/kyma/tests/connector-service-tests/connector-service-tests-generic.yaml
  prow/jobs/kyma/tests/console-backend-service/console-backend-service-tests-generic.yaml
  prow/jobs/kyma/tests/end-to-end/upgrade/upgrade-tests-generic.yaml
  prow/jobs/kyma/tests/integration/api-controller/api-controller-tests-generic.yaml
  prow/jobs/kyma/tests/integration/api-gateway/api-gateway-test-generic.yaml
  prow/jobs/kyma/tests/integration/apiserver-proxy/apiserver-proxy-tests-generic.yaml
  prow/jobs/kyma/tests/integration/cluster-users/cluster-users-tests-generic.yaml
  prow/jobs/kyma/tests/integration/dex/dex-tests-generic.yaml
  prow/jobs/kyma/tests/integration/logging/logging-generic.yaml
  prow/jobs/kyma/tests/integration/monitoring/monitoring-generic.yaml
  prow/jobs/kyma/tests/service-catalog/service-catalog-tests-generic.yaml
  prow/jobs/kyma/tools/alpine-net/alpine-net-generic.yaml
  templates/config.yaml
Labels: enhancement

#1655 Enable kind environment in marketplaces jobs
  prow/jobs/incubator/marketplaces/marketplaces.yaml
Labels: area/core-and-supporting, enhancement

#1666 Clean up disks used by compass clusters
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/cluster

#1672 Migrate to generic jobs for Framefrog's components
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/components/application-connectivity-certs-setup-job/application-connectivity-certs-setup-job-generic.yaml
  prow/jobs/kyma/components/application-connectivity-certs-setup-job/application-connectivity-certs-setup-job.yaml
  prow/jobs/kyma/components/application-connectivity-validator/application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/application-connectivity-validator/application-connectivity-validator.yaml
  prow/jobs/kyma/components/application-gateway/application-gateway-generic.yaml
  prow/jobs/kyma/components/application-gateway/application-gateway.yaml
  prow/jobs/kyma/components/application-operator/application-operator-generic.yaml
  prow/jobs/kyma/components/application-operator/application-operator.yaml
  prow/jobs/kyma/components/application-registry/application-registry-generic.yaml
  prow/jobs/kyma/components/application-registry/application-registry.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent.yaml
  prow/jobs/kyma/components/connection-token-handler/connection-token-handler-generic.yaml
  prow/jobs/kyma/components/connection-token-handler/connection-token-handler.yaml
  prow/jobs/kyma/components/connectivity-certs-controller/connectivity-certs-controller-generic.yaml
  prow/jobs/kyma/components/connectivity-certs-controller/connectivity-certs-controller.yaml
  prow/jobs/kyma/components/connector-service/connector-service-generic.yaml
  prow/jobs/kyma/components/connector-service/connector-service.yaml
  prow/jobs/kyma/tests/application-connector-tests/application-connector-tests-generic.yaml
  prow/jobs/kyma/tests/application-connector-tests/application-connector-tests.yaml
  prow/jobs/kyma/tests/application-gateway-tests/application-gateway-tests-generic.yaml
  prow/jobs/kyma/tests/application-gateway-tests/application-gateway-tests.yaml
  prow/jobs/kyma/tests/application-operator-tests/application-operator-tests-generic.yaml
  prow/jobs/kyma/tests/application-operator-tests/application-operator-tests.yaml
  prow/jobs/kyma/tests/application-registry-tests/application-registry-tests-generic.yaml
  prow/jobs/kyma/tests/application-registry-tests/application-registry-tests.yaml
  prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-tests-generic.yaml
  prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-tests.yaml
  prow/jobs/kyma/tests/connection-token-handler-tests/connection-token-handler-tests-generic.yaml
  prow/jobs/kyma/tests/connection-token-handler-tests/connection-token-handler-tests.yaml
  prow/jobs/kyma/tests/connector-service-tests/connector-service-tests-generic.yaml
  prow/jobs/kyma/tests/connector-service-tests/connector-service-tests.yaml
  templates/config.yaml
Labels: area/application-connector, area/ci

#1680 Add 'restore' cluster to disk cleaner
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#1687 Update mkpj documentation
  docs/prow/prow-jobs.md
Labels: area/ci, area/documentation
