Repository kyma-project/test-infra, pull requests merged in 2020-04, with the labels that each got.

#2190 Kubernetes 1.16
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
Labels: area/ci

#2193 Disable release jobs for changes in documentation
  prow/jobs/kyma/kyma-github-release.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  templates/templates/kyma-github-release.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: enhancement

#2189 Build image with precompiled tools
  development/tools/Dockerfile
  development/tools/Makefile
  development/tools/build-cleaners.sh
  prow/jobs/test-infra/buildpack.yaml
Labels: area/ci

#2206 Rename /tools to /prow-tools in development/tools/Dockerfile
  development/tools/Dockerfile
Labels: area/ci

#2207 Copy tools from prow-tools image to kyma-integration image
  prow/images/kyma-integration/Dockerfile
Labels: area/ci

#2198 Change the output of the azure-event-hubs overrides file to adapt to the new Chart structure
  prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
Labels: area/eventing

#2210 Define build argument for kyma integration image
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
Labels: area/ci

#2214 Add Application Registry detailed error override
  prow/scripts/cluster-integration/helpers/install-kyma.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/application-connector, test-failing

#2203 Usage of prebuilt tools binaries instead of building them at runtime in prow jobs
  development/resources-cleanup.sh
  development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-integration-gardener-azure.yaml
  prow/jobs/kyma/kyma-integration-gardener-gcp.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/jobs/rafter/rafter.yaml
  prow/jobs/test-infra/buildpack.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: area/ci

#2225 Usage of prebuilt tools binaries instead of building them at runtime in prow jobs
  development/resources-cleanup.sh
  development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-integration-gardener-azure.yaml
  prow/jobs/kyma/kyma-integration-gardener-gcp.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/jobs/rafter/rafter.yaml
  prow/jobs/test-infra/buildpack.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: area/ci

#2228 Assetstore cleaner job binary execution
  development/assetstore-gcp-bucket-cleaner.sh
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2231 GitHub-stats job update
  development/github-stats.sh
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2234 Fix prow-tools build job regexp
  prow/jobs/test-infra/buildpack.yaml
Labels: area/ci

#2233 GitHub-release job optimisation
  development/github-release.sh
  development/tools/jobs/kyma/kyma_github-release_test.go
  prow/jobs/kyma/kyma-github-release.yaml
  templates/templates/kyma-github-release.yaml
Labels: area/ci

#2220 Use string values for stringData in knative-eventing-kafka overrides
  prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
Labels: area/eventing

#2236 Resources requests edit in cleaner jobs.
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2250 Build fix of build-cleaners.sh in test-infra-prow-tools job
  development/tools/build-cleaners.sh
Labels: area/ci

#2257 validate-configs job bump image to go1.13
  development/tools/jobs/testinfra/validate_test.go
  prow/jobs/test-infra/validation.yaml
Labels: area/ci

#2247 change image of github-release job to kyma-integration:k1.15
  development/tools/jobs/kyma/kyma_github-release_test.go
  prow/jobs/kyma/kyma-github-release.yaml
  templates/templates/kyma-github-release.yaml
Labels: area/ci

#2181 Clean up old lambda UI view - test-infra part
  development/tools/jobs/console/lambda_test.go
  prow/jobs/console/lambda/lambda.yaml
Labels: area/console, area/serverless

#2263 Whitelist the hook link
  milv.config.yaml
Labels: area/documentation, bug

#2264 Move prow-tools Dockerfile to prow/images
  development/tools/Makefile
  prow/images/prow-tools/Dockerfile
  prow/images/prow-tools/Makefile
  prow/images/prow-tools/README.md
  prow/jobs/test-infra/buildpack.yaml
Labels: area/ci

#2251 Fixed jobguard import path.
  development/jobguard/cmd/jobguard/main.go
  development/jobguard/pkg/jobguard/filter.go
  development/jobguard/pkg/jobguard/httpclient.go
  development/jobguard/pkg/jobguard/status.go
  development/jobguard/pkg/jobguard/waiter.go
  development/jobguard/scripts/run.sh
Labels: area/ci

#2276 Delete kyma-kind-k8s-1-16 job
  prow/jobs/kyma/kyma-kind-integration.yaml
Labels: area/ci

#2274 Add prowjob for compass audit log mock service
  development/tools/jobs/incubator/components_test.go
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  templates/config.yaml
Labels: area/ci

#2284 add jobguard build to prow-tools Dockerfile
  prow/images/prow-tools/Dockerfile
  prow/jobs/test-infra/buildpack.yaml
Labels: area/ci

#2290 Bump images and edit run.sh script of jobguard
  development/jobguard/scripts/run.sh
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-github-release.yaml
  prow/jobs/kyma/kyma-integration-gardener-azure.yaml
  prow/jobs/kyma/kyma-integration-gardener-gcp.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/jobs/rafter/rafter.yaml
  templates/templates/kyma-github-release.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: area/ci

#2259 Secrets cleanup
  development/prow-installer/config/prow-installer-config.yaml
  development/tools/cmd/secretspopulator/README.md
  docs/prow/README.md
  docs/prow/obligatory-security-measures.md
  docs/prow/presets.md
  docs/prow/prow-secrets.md
  prow/cluster/required-secrets.yaml
  prow/config.yaml
  prow/workload-cluster/required-secrets.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#2296 Switch stability-checker to go modules.
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/stability_checker_test.go
  prow/jobs/test-infra/stability-checker.yaml
  stability-checker/Gopkg.lock
  stability-checker/Gopkg.toml
  stability-checker/README.md
  stability-checker/before-commit.sh
  stability-checker/go.mod
  stability-checker/go.sum
  stability-checker/internal/log/logfetcher.go
  stability-checker/internal/notifier/dep.go
  stability-checker/internal/notifier/notifier.go
  stability-checker/internal/runner/dep.go
  stability-checker/internal/runner/runner.go
  stability-checker/internal/summary/automock/log_fetcher.go
  stability-checker/internal/summary/automock/log_processor.go
  stability-checker/local_minikube_build.sh
Labels: area/ci

#2302 Switch watch-pods to go.mod
  development/tools/jobs/testinfra/watch_pods_test.go
  prow/jobs/test-infra/watch-pods/watch-pods.yaml
  templates/config.yaml
  watch-pods/Gopkg.lock
  watch-pods/Gopkg.toml
  watch-pods/README.md
  watch-pods/before-commit.sh
  watch-pods/go.mod
  watch-pods/go.sum
Labels: area/ci
