Repository kyma-project/test-infra, pull requests merged in 2020-01, with the labels that each got.

#1864 Upgrade Velero to 1.2.0
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
Labels: area/quality

#1881 Release pipeline
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
Labels: area/ci

#1887 Revert "Add monitoring links to the white list"
  milv.config.yaml
Labels: area/ci, area/documentation

#1897 CODEOWNERS update
  CODEOWNERS
Labels: area/ci

#1888 Update the project name for the Release Candidate clusters
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/kyma_release_candidate_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
  templates/templates/prow-config.yaml
Labels: area/cluster, area/core-and-supporting, bug, enhancement

#1899 Add Rafter's resources to the 1st restoring phase
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
Labels: area/ci, area/cluster, enhancement

#1886 Cert manager upgrade #1869
  prow/cluster/01-cert-manager.yaml
Labels: area/application-connector, area/ci, area/cli, area/cluster, area/community

#1765 Add nslookup test to clonerefs
  prow/images/clonerefs/Dockerfile
  prow/images/clonerefs/Makefile
  prow/images/clonerefs/README.md
  prow/images/clonerefs/clonerefs
Labels: area/ci

#1867 Sc apiserver metrics
  docs/prow/prow-monitoring.md
  prow/scripts/README.md
  prow/scripts/cluster-integration/README.md
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/resources/README.md
  prow/scripts/resources/prometheus-operator-additional-scrape-config.yaml
  prow/scripts/resources/prometheus-operator-stackdriver-patch.yaml
Labels: area/ci, area/monitoring

#1901 Vulnerability scanner fix
  development/vulnerabilities-scanner.sh
Labels: area/ci

#1903 Bump clonerefs image
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#1910 kyma-vulnerabilities-scanner: Send Slack notification if any vulnerabilities found.
  development/vulnerabilities-scanner.sh
Labels: area/ci

#1856 Cluster permissions
  docs/prow/README.md
  docs/prow/assets/GGroups.png
  docs/prow/test-clusters.md
Labels: area/documentation

#1927 Change base image for hb job
  development/tools/jobs/helm-broker/helm_broker_test.go
  prow/jobs/helm-broker/helm-broker.yaml
Labels: area/ci

#1942 Test minikube
  development/custom-image/install-deps-debian.sh
Labels: area/ci

#1944 Remove obsolete value for AKS nightly
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Labels: area/ci, area/cluster, bug, test-failing

#1943 Kubectl version
  prow/images/bootstrap/Dockerfile
Labels: area/ci

#1948 Enable stale bot for epics
  .github/stale.yml
Labels: area/community

#1946 cron reschedule
  development/tools/jobs/kyma/vulnerability_scanner_test.go
  prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Labels: area/ci

#1949 Bump buildpack-golang image
  prow/images/buildpack-golang/Dockerfile
Labels: area/ci

#1951 Bump cluster-infra image
  prow/images/kyma-cluster-infra/Dockerfile
Labels: area/ci

#1952 Update SDK and cluster version
  prow/images/bootstrap/Dockerfile
Labels: area/ci

#1953 buildpack-golang 1.16
  prow/images/buildpack-golang/Dockerfile
Labels: area/ci

#1956 Preset for k8s 1.14
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/kyma-compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/jobs/rafter/rafter.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: area/ci

#1917 Switch to k8s 1.16 in kind integration jobs
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/scripts/kind-install-kyma.sh
  prow/scripts/kind-upgrade-kyma.sh
Labels: area/ci, area/core-and-supporting, enhancement

#1960 Do not stale issues with "ci/future" label
  .github/stale.yml
Labels: area/ci

#1962 Add prow job for the Knative Kafka channel contract tests
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/contract/knative-channel-kafka/knative-channel-kafka-tests-generic.yaml
  templates/config.yaml
Labels: area/ci, area/eventing, area/serverless

#1967 Fix logs display for prepare data upgrade test pod
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: test-failing

#1972 Increase kyma timeout for gardener to 60m
  prow/jobs/kyma/kyma-integration-gardener-azure.yaml
  prow/scripts/cluster-integration/kyma-gardener-integration.sh
Labels: area/ci

#1959 Dns cleaner
  development/tools/cmd/dnscollector/main.go
Labels: WIP, area/ci

#1973 Correct order in which resources are restored in backup test
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
Labels: area/cluster, area/core-and-supporting, enhancement

#1975 Make knative-channel-kafka prow job non optional
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/contract/knative-channel-kafka/knative-channel-kafka-tests-generic.yaml
  templates/config.yaml
Labels: area/ci, area/eventing

#1979 Revert changes to backup tests
  prow/scripts/cluster-integration/kyma-gke-backup-test.sh
Labels: area/cluster
