Repository kyma-project/test-infra, pull requests merged in 2020-11, with the labels that each got.

#2906 Enabled login to docker hub.
  prow/scripts/lib/docker.sh
  prow/scripts/library.sh
Labels: area/ci

#2908 Added debugging commands.
  prow/scripts/cluster-integration/helpers/create-dns-record.sh
Labels: area/ci, test-failing

#2911 Redirect dns debug data to separate file.
  prow/scripts/cluster-integration/helpers/create-dns-record.sh
Labels: area/ci

#2679 Introduce test-log-collector for gardener periodics
  development/test-log-collector/chart/test-log-collector/values.yaml
  development/test-log-collector/cmd/app/mainerr.go
  development/test-log-collector/cmd/app/mainerr_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  templates/templates/kyma-integration-gardener.yaml
Labels: area/ci

#2916 Update config in test-log-collector
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/test-log-collector/chart/test-log-collector/values.yaml
  development/test-log-collector/cmd/app/mainerr.go
  development/test-log-collector/go.mod
  development/test-log-collector/go.sum
  development/test-log-collector/pkg/slack/slack.go
Labels: area/ci

#2914 Add flags to prtagbuilder
  development/tools/cmd/prtagbuilder/main.go
  development/tools/pkg/prtagbuilder/prtagbuilder.go
Labels: area/ci

#2920 Update test-log-collector config
  development/test-log-collector/chart/test-log-collector/files/config.yaml
Labels: area/ci

#2924 Add new commands to Kyma CLI integration tests
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/provision-vm-cli.sh
Labels: area/cli

#2904 Fix pjtester generated prowjob name and env vars
  development/tools/cmd/prtagbuilder/main.go
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_test.go
  development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/test-job.yaml
  development/tools/pkg/prtagbuilder/mocks/fakeghclient.go
  development/tools/pkg/prtagbuilder/prtagbuilder.go
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci

#2937 Fix the TW alias in the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, bug

#2942 Removed unsuported pjtester arguments.
  prow/jobs/test-infra/pjtester.yaml
Labels: area/ci

#2947 Pjtester docs update
  development/tools/cmd/pjtester/README.md
  development/tools/pkg/pjtester/pjtester.go
Labels: area/ci, area/documentation

#2948 Added description accepted flags. Removed deprecated data.
  development/tools/cmd/prtagbuilder/main.go
  development/tools/pkg/prtagbuilder/README.md
Labels: area/ci, area/documentation

#2951 Update prow-tools version.
  prow/images/alpine-kubectl/Dockerfile
  prow/images/bootstrap-helm/Dockerfile
  prow/images/bootstrap/Dockerfile
  prow/images/buildpack-golang-kubebuilder/Dockerfile
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-java-node/Dockerfile
  prow/images/buildpack-java/Dockerfile
  prow/images/buildpack-node/Dockerfile
  prow/images/cleaner/Dockerfile
  prow/images/kyma-cluster-infra/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
Labels: area/ci

#2953 Bump gke version to 1.18.10-gke.2101
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
Labels: area/ci

#2966 Consistent flag naming
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci, area/cli

#2965 Add azure.sh library script for Azure-related jobs.
  prow/scripts/lib/azure.sh
Labels: area/ci

#2967 Add patched kaniko image to external-images.yaml
  development/image-syncer/external-images.yaml
Labels: area/ci, area/serverless

#2968 Edit create-azure-event-hubs-secret.sh to use azure.sh lib
  prow/config.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/lib/azure.sh
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#2970 Change file to edit in istio-ingressgateway patch
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#2971 Edit azure scripts to use lib script
  development/tools/jobs/kyma/kyma_azure_event_hubs_namespaces_cleanup_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/rafter/rafter_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-azure-event-hubs-namespaces-cleanup.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/jobs/rafter/rafter.yaml
  prow/scripts/cluster-integration/helpers/cleanup-azure-event-hubs-namespaces.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/cluster-integration/minio/azure-cleaner.sh
  prow/scripts/cluster-integration/minio/azure-gateway.sh
  prow/scripts/lib/aks-library.sh
  templates/templates/kyma-azure-event-hubs-namespaces-cleanup.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#2950 Use kyma-gateway instead of compass-gateway during kyma installation
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: area/management-plane

#2979 Fix kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Labels: area/ci

#2982 Add unstale-gardener-project prowjob
  prow/jobs/test-infra/unstale-gardener-project.yaml
  prow/scripts/lib/kyma-cli.sh
  prow/scripts/unstale-gardener-project.sh
Labels: area/ci

#2985 Bump kube-state-metrics image
  development/image-syncer/external-images.yaml
Labels: area/monitoring

#2984 Replace latest-published source flag with master source flag
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
Labels: area/ci, area/cli

#2990 Bump grafana image
  development/image-syncer/external-images.yaml
Labels: area/monitoring

#2989 Configure log collector for Console and Console Backend Service
  development/test-log-collector/chart/test-log-collector/files/config.yaml
Labels: area/console, enhancement
