Repository kyma-project/test-infra, pull requests merged in 2020-09, with the labels that each got.

#2739 Add the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, enhancement

#2729 Using Kyma CLI in gke upgrade prow job
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/ci, area/cli, enhancement

#2746 Use CLI in upgrade job only when build type is master
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/ci, area/cli

#2745 Add Application Gateway Legacy Tests job
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/application-gateway-legacy-tests/application-gateway-legacy-tests-generic.yaml
  templates/config.yaml
Labels: area/application-connector, enhancement

#2747 Enable test-log-collector for integration and upgrade jobs
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: area/ci

#2736 Added cluster definition to all templates.
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/incubator/knative-kafka/knative-kafka.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/kyma-github-release.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-installer.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  templates/config.yaml
  templates/templates/compass-gke-integration.yaml
  templates/templates/compass-integration.yaml
  templates/templates/component.yaml
  templates/templates/generic-component.yaml
  templates/templates/knative-kafka-component.yaml
  templates/templates/kyma-artifacts.yaml
  templates/templates/kyma-github-release.yaml
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-installer.yaml
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
  templates/templates/whitesource-periodics.yaml
Labels: area/ci

#2763 Use Kyma CLI in kyma-integration minikube jobs
  prow/scripts/cluster-integration/kyma-integration-minikube.sh
  prow/scripts/provision-vm-and-start-kyma.sh
Labels: area/ci

#2755 Run gke-external-registry with changes on resources/serverless
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  templates/templates/kyma-gke-external-registry.yaml
Labels: area/serverless, enhancement

#2767 Use Kyma-cli in the kyma-integration job.
  prow/scripts/cluster-integration/kyma-integration-minikube.sh
  prow/scripts/provision-vm-and-start-kyma.sh
Labels: area/ci

#2751 Make application-gateway-legacy-tests job required
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/application-gateway-legacy-tests/application-gateway-legacy-tests-generic.yaml
  templates/config.yaml
Labels: area/application-connector, enhancement

#2775 Add go and dep to the whitesource scanner image.
  prow/images/whitesource-scanner/Dockerfile
Labels: area/ci, area/security

#2778 Bump wss agent image to the one with go and dep binaries.
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-whitesource.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/templates/whitesource-periodics.yaml
Labels: area/ci, area/security

#2784 Add GO111MODULE=on for go mod scans.
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
Labels: area/ci

#2786 Fix CLI-GKE integration job
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
Labels: area/ci, area/cli

#2787 Add Application Connector alpine images
  development/image-syncer/external-images.yaml
Labels: area/application-connector

#2795 Copy config file for local installation to buckets
  prow/scripts/build-kyma-development-artifacts.sh
Labels: area/ci

#2796 Make fucntion-serverless test build job as required
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  templates/config.yaml
Labels: enhancement
