Repository kyma-project/test-infra, pull requests merged in 2020-06, with the labels that each got.

#2424 Add jobs for testing compass-integration script
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  templates/templates/kyma-gke-compass-integration.yaml
Labels: area/quality

#2423 Increased number of attempts for DNS resolving from 3 to 10
  prow/scripts/cluster-integration/helpers/create-dns-record.sh
  prow/scripts/cluster-integration/helpers/delete-dns-record.sh
Labels: area/ci

#2425 Missing docs
  docs/prow/assets/rerun.png
  docs/prow/prow-jobs.md
  docs/prow/prow-secrets.md
Labels: area/ci, area/documentation

#2430 Move certificates to kyma-prowjobs-secrets
  development/assetstore-gcp-bucket-cleaner.sh
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, enhancement

#2427 Prepare job for building Compass artifacts
  development/tools/jobs/incubator/compass/development_artifacts_test.go
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/scripts/build-compass-development-artifacts.sh
Labels: area/ci, area/management-plane, enhancement

#2429 Add Kyma dependencies artifact
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build-kyma-development-artifacts.sh
Labels: area/ci, area/management-plane, enhancement

#2433 Add E2E upgrade job
  development/tools/go.mod
  development/tools/go.sum
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2431 Crier documentation
  docs/prow/authorization.md
  docs/prow/crier.md
Labels: area/ci

#2435 Remove timestamp from Compass PR artifacts docker tags
  prow/scripts/build-compass-development-artifacts.sh
Labels: area/ci, area/management-plane, enhancement

#2432 add checkconfig and unique-jobs-name compiling to prow-tools image
  prow/images/prow-tools/Dockerfile
Labels: area/ci

#2434 Switch assetstore bucket cleaner to sa-prow-job-resource-cleaner
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/tester/preset/preset.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, enhancement

#2437 Presets docs update
  docs/prow/presets.md
Labels: area/ci, enhancement

#2440 Provide the domain value for the E2E upgrade test
  prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
Labels: area/eventing

#2442 Use a shorter name for the upgrade test namespace
  prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
Labels: area/eventing

#2428 GitHub token monitoring dashboard changes
  prow/cluster/resources/monitoring/dashboards/grafana-prow.json
Labels: area/ci, area/monitoring

#2385 Development dir scripts cleanup
  development/README.md
  development/resources-cleanup.sh
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/vulnerability_scanner_test.go
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/validate_test.go
  development/validate-scripts.sh
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-vulnerability-scanner.yaml
  prow/jobs/test-infra/validation.yaml
  prow/scripts/README.md
  prow/scripts/assetstore-gcp-bucket-cleaner.sh
  prow/scripts/cluster-integration/helpers/delete-dns-record.sh
  prow/scripts/cluster-integration/helpers/release-ip-address.sh
  prow/scripts/github-stats.sh
  prow/scripts/validate-config.sh
  prow/scripts/validate-scripts.sh
  prow/scripts/vulnerabilities-scanner.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2444 Make pre-test-infra-validate-configs required again
  prow/jobs/test-infra/validation.yaml
Labels: area/ci

#2448 Enable start-wssagent.sh to use mounted keys.
  prow/config.yaml
  prow/jobs/incubator/compass/tests/provisioner-tests/provisioner-whitesource.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
  templates/templates/prow-config.yaml
  templates/templates/whitesource-periodics.yaml
Labels: area/ci, enhancement

#2450 Fix links
  docs/prow/production-cluster-configuration.md
  docs/prow/prow-installation-on-forks.md
Labels: area/documentation

#2451 Fix typo in file name.
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
Labels: area/ci, bug

#2452 Skip the new E2E upgrade job by default
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2447 Move to workloads kms.
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, enhancement

#2449 Switch jobs to use sa-gcr-push for image push.
  prow/config.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/jobs/test-infra/performance-test.yaml
  prow/scripts/cluster-integration/helpers/create-image.sh
  prow/scripts/cluster-integration/helpers/install-kyma.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, enhancement

#2458 Added missing dolar sign.
  prow/scripts/cluster-integration/helpers/create-image.sh
Labels: area/ci, bug, test-failing

#2459 export credentials variable
  prow/scripts/cluster-integration/helpers/create-image.sh
Labels: area/ci, test-failing

#2457 Introduce GKE Integration job installing Compass on top of Kyma
  development/tools/jobs/incubator/compass/development_artifacts_test.go
  development/tools/jobs/kyma/development_artifacts_test.go
  development/tools/jobs/kyma/kyma_gke_separate_compass_integration.go
  development/tools/jobs/tester/preset/preset.go
  docs/prow/presets.md
  prow/config.yaml
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/kyma/kyma-development-artifacts.yaml
  prow/jobs/kyma/kyma-gke-separate-compass-integration.yaml
  prow/scripts/cluster-integration/helpers/create-config-map.sh
  prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
  templates/config.yaml
  templates/templates/kyma-gke-separate-compass-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, area/management-plane, enhancement

#2469 Change project name for KMS preset
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, test-failing

#2470 Add missing preset to Kyma GKE Separate Compass integration
  development/tools/jobs/kyma/kyma_gke_separate_compass_integration.go
  prow/jobs/kyma/kyma-gke-separate-compass-integration.yaml
  templates/templates/kyma-gke-separate-compass-integration.yaml
Labels: area/ci, area/management-plane, bug

#2473 Make is-installed.sh script executable for Separate Compass pipeline
  prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
Labels: area/ci, area/management-plane, bug

#2465 ProwJobs validation job rewrite
  development/tools/Makefile
  development/tools/before-commit.sh
  development/tools/cmd/certbotauthenticator/main.go
  development/tools/jobs/kyma/development_artifacts_test.go
  development/tools/jobs/releases/releases.go
  development/tools/jobs/testinfra/validate_test.go
  prow/jobs/test-infra/validation.yaml
  templates/templates/releases.go.tmpl
Labels: area/ci

#2477 Add missing override for separate Compass pipeline
  prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
Labels: area/ci, area/management-plane, bug

#2480 Separate Ingress overrides to additional ConfigMap in Compass GKE Job
  prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
Labels: area/ci, area/management-plane, enhancement

#2463 Add Compass GKE integration job
  development/tools/jobs/incubator/compass/compass_gke_integration_test.go
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/helpers/create-compass-image.sh
  templates/config.yaml
  templates/templates/compass-gke-integration.yaml
Labels: area/ci, area/management-plane, enhancement

#2464 Storage permissions cleanup 2399
  prow/config.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/jobs/test-infra/performance-test.yaml
  prow/scripts/cluster-integration/helpers/create-image.sh
  prow/scripts/cluster-integration/helpers/install-kyma.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/library.sh
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#2493 Added case with no docker authentication.
  prow/scripts/library.sh
Labels: area/ci, test-failing

#2495 Add preset-sa-test-gcr-push
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-gke-separate-compass-integration.yaml
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-gke-separate-compass-integration.yaml
Labels: area/ci, test-failing

#2494 Fix delete image access denied
  prow/scripts/cluster-integration/helpers/delete-image.sh
  prow/scripts/library.sh
Labels: area/ci, test-failing

#2490 Make validate-prow-jobs and prow-tools required
  prow/jobs/test-infra/validation.yaml
Labels: area/ci

#2479 Release improvements
  prow/config.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build.sh
  prow/scripts/cluster-integration/README.md
  prow/scripts/cluster-integration/helpers/install-stability-checker.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/provision-vm-and-start-kyma.sh
  prow/scripts/provision-vm-compass.sh
  templates/templates/kyma-artifacts.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#2509 Assetstore cleaner job fixup
  prow/scripts/assetstore-gcp-bucket-cleaner.sh
Labels: area/ci

#2511 Governance nightly
  development/tools/jobs/addons/governance_test.go
  development/tools/jobs/community/governance_test.go
  development/tools/jobs/console/governance_test.go
  development/tools/jobs/incubator/documentation-component/documentation-component_test.go
  development/tools/jobs/incubator/marketplaces/marketplaces_test.go
  development/tools/jobs/kyma/governance_test.go
  development/tools/jobs/testinfra/governance_test.go
  development/tools/jobs/website/governance_test.go
  prow/jobs/addons/addons-governance.yaml
  prow/jobs/community/community-governance.yaml
  prow/jobs/console/console-governance.yaml
  prow/jobs/incubator/documentation-component/documentation-component.yaml
  prow/jobs/incubator/marketplaces/marketplaces.yaml
  prow/jobs/kyma/kyma-governance.yaml
  prow/jobs/test-infra/test-infra-governance.yaml
  prow/jobs/website/website-governance.yaml
Labels: area/ci

#2513 Add kyma-prow-access-storage-logs to the excluded bucket list
  prow/scripts/assetstore-gcp-bucket-cleaner.sh
Labels: area/ci

#2514 Change the way of passing overrides
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/library.sh
Labels: area/cli

#2515 [Control Plane separation] Add control-plane component jobs
  development/tools/jobs/control-plane/components_test.go
  development/tools/jobs/control-plane/tests_test.go
  development/tools/jobs/tester/jobsuite/options.go
  development/tools/jobs/tester/preset/preset.go
  docs/prow/presets.md
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-kcp-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-kcp-generic.yaml
  prow/jobs/control-plane/components/metris/metris-kcp-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-kcp-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-kcp-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-kcp-generic.yaml
  templates/config.yaml
Labels: area/management-plane

#2520 Add KCP artifacts jobs
  development/tools/jobs/control-plane/development_artifacts_test.go
  prow/jobs/control-plane/kcp-development-artifacts.yaml
  prow/scripts/build-kcp-development-artifacts.sh
Labels: area/management-plane, enhancement

#2518 Add kyma-prow-workloads-logs to the excluded bucket list
  prow/scripts/assetstore-gcp-bucket-cleaner.sh
Labels: area/ci

#2528 Connect new workload clusters 2482
  prow/cluster/components/11-plank_deployment.yaml
  prow/cluster/components/13-sinker_deployment.yaml
  prow/cluster/components/15-deck_deployment.yaml
  prow/cluster/components/30-crier_deployment.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/workload-cluster/00-clusterrolebinding.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci, enhancement

#2531 Trigger all console jobs on main package.json change
  prow/jobs/console/add-ons/add-ons.yaml
  prow/jobs/console/compass/compass.yaml
  prow/jobs/console/content/content.yaml
  prow/jobs/console/core-ui/core-ui.yaml
  prow/jobs/console/core/core.yaml
  prow/jobs/console/logging/console-logging.yaml
  prow/jobs/console/service-catalog-ui/service-catalog-ui.yaml
  prow/jobs/console/tests/tests.yaml
  templates/config.yaml
Labels: area/console, enhancement

#2419 Kyma gardener azure upgrade job
  development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
Labels: area/quality

#2526 Introduce Control Plane integration jobs
  development/tools/jobs/control-plane/components_test.go
  development/tools/jobs/control-plane/control_plane_gke_integration_test.go
  development/tools/jobs/control-plane/control_plane_integration_test.go
  development/tools/jobs/control-plane/tests_test.go
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-integration.yaml
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/helpers/create-control-plane-image.sh
  prow/scripts/provision-vm-control-plane.sh
Labels: area/ci, area/management-plane, enhancement

#2536 Fix TMP_DIR redefinition for GKE KCP job
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
Labels: bug
