Repository kyma-project/test-infra, pull requests merged in 2020-12, with the labels that each got.

#2991 More dns debug
  development/dns-debug-role.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/scripts/cluster-integration/helpers/create-dns-record.sh
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2939 Introduce k3s pipeline for serverless integration jobs
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci, area/serverless

#2995 Add kyma-incubator/pamela to branchprotector-config.yaml
  prow/branchprotector-config.yaml
  templates/templates/branchprotector-config.yaml
Labels: area/ci

#2987 Configure prow alerts for Framefrog
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/library.sh
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/application-connector, area/quality, enhancement

#3002 Bump gke version to latest default from channels
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
Labels: area/ci

#3005 Add more logs to test-log-collector
  development/test-log-collector/Dockerfile
  development/test-log-collector/chart/test-log-collector/values.yaml
  development/test-log-collector/cmd/app/mainerr.go
  development/test-log-collector/go.mod
  development/test-log-collector/pkg/config/config.go
  development/test-log-collector/pkg/slack/slack.go
Labels: area/ci

#3007 Reduce sample limits to prevent restarts on prometheus istio server
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci, area/monitoring

#3012 Kyma fast integration pipeline
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-azure-event-hubs-namespaces-cleanup.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-github-release.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/jobs/rafter/rafter.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-azure-event-hubs-namespaces-cleanup.yaml
  templates/templates/kyma-github-release.yaml
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: area/ci

#3025 Fix typo in several scripts
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/lib/docker.sh
Labels: area/ci

#3026 Bump GKE rapid version to 1.18.12-gke.300
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
Labels: area/ci

#3022 Add more functionality to gcloud.sh lib
  prow/scripts/lib/gcloud.sh
Labels: area/ci

#3034 Fix core console build
  prow/jobs/console/core/core.yaml
  templates/config.yaml
Labels: area/console, bug

#3036 Add missing log.sh source to kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
Labels: area/ci

#3028 Do not fail if no log collector in the master job
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/library.sh
Labels: test-failing

#3046 Fix bug in installing helm binary in install-deps-debian.sh
  development/custom-image/install-deps-debian.sh
Labels: area/ci, bug

#3047 Bump gke rapid version to 1.18.12-gke.1201
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
Labels: area/ci

#3050 Set static version of yq to version 3.4.1
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#3053 Add several new functions to azure.sh, remove aks-library.sh
  prow/scripts/lib/aks-library.sh
  prow/scripts/lib/azure.sh
Labels: area/ci

#3059 Remove kind integration
  docs/prow/README.md
  docs/prow/kind-jobs.md
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/scripts/README.md
  prow/scripts/kind-install-kyma.sh
  prow/scripts/kind-upgrade-kyma.sh
  prow/scripts/lib/helm.sh
  prow/scripts/lib/host.sh
  prow/scripts/lib/kind.sh
  prow/scripts/lib/kubernetes.sh
Labels: area/ci

#3063 scripts: remove init
  prow/scripts/build-addons.sh
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/build-generic.sh
  prow/scripts/build-kcp-cli.sh
  prow/scripts/build-kcp-development-artifacts.sh
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/governance.sh
  prow/scripts/metadata-governance.sh
  prow/scripts/publish-buildpack.sh
Labels: area/ci

#3067 scripts: fix gardener azure integration
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
Labels: area/ci

#3071 pjtesting dns-debug.sh
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/create-dns-record.sh
  prow/scripts/dns-debug.sh
  prow/scripts/lib/gcloud.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci
