Repository kyma-project/test-infra, pull requests merged in 2020-10, with the labels that each got.

#2804 Add governance image to image-syncer
  development/image-syncer/external-images.yaml
Labels: enhancement

#2806 Switch governance image to gcp-internal
  prow/scripts/governance.sh
Labels: enhancement

#2783 Add pre-master-kyma-gke* jobs which use new GKE K8s version.
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  templates/config.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2807 Fix istio installation error
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
Labels: test-failing

#2816 Remove RELEASE_CHANNEL from `preset-gke-ver-stable`
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#2741 Enable prtagbuilder
  development/tools/cmd/rendertemplates/main.go
  development/tools/go.mod
  development/tools/go.sum
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/buildpack_test.go
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/jobs/test-infra/buildpack.yaml
  templates/config.yaml
  templates/templates/buildpack.yaml
Labels: area/ci

#2817 Added cluster filter to prowjobparser.
  development/prowjobparser/main.go
Labels: area/ci, enhancement

#2827 Fix a dead link
  development/tools/cmd/enablegithubauth/README.md
Labels: area/documentation

#2831 Move prowjobs to new cluster 4
  prow/jobs/addons/addons-governance.yaml
  prow/jobs/addons/addons.yaml
  prow/jobs/cli/cli-compatibility.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/cli/cli.yaml
  prow/jobs/community/community-governance.yaml
  prow/jobs/console/components/react/react-components.yaml
  prow/jobs/console/console-governance.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/control-plane/control-plane-integration.yaml
  prow/jobs/control-plane/kcp-development-artifacts.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-whitesource.yaml
  prow/jobs/examples/event-email-service/event-email-service.yaml
  prow/jobs/examples/examples-governance.yaml
  prow/jobs/examples/http-db-service/http-db-service.yaml
  prow/jobs/examples/monitoring-custom-metrics/monitoring-custom-metrics.yaml
  prow/jobs/examples/orders-service/orders-service.yaml
  prow/jobs/examples/tests/http-db-service-acceptance-tests/http-db-service-acceptance-tests.yaml
  prow/jobs/examples/tracing/tracing.yaml
  prow/jobs/helm-broker/helm-broker.yaml
  prow/jobs/incubator/api-gateway/api-gateway.yaml
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/incubator/dex/dex.yaml
  prow/jobs/incubator/documentation-component/documentation-component.yaml
  prow/jobs/incubator/gcp-service-broker/gcp-service-broker.yaml
  prow/jobs/incubator/github-slack-connectors/github-connector/github-connector.yaml
  prow/jobs/incubator/github-slack-connectors/slack-connector/slack-connector.yaml
  prow/jobs/incubator/hydroform/hydroform.yaml
  prow/jobs/incubator/marketplaces/marketplaces.yaml
  prow/jobs/incubator/octopus/octopus.yaml
  prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
  prow/jobs/incubator/service-catalog-tester/service-catalog-tester.yaml
  prow/jobs/incubator/terraform-provider-gardener/terraform-provider-gardener.yaml
  prow/jobs/incubator/third-party-images/docker-registry/registry.yaml
  prow/jobs/incubator/third-party-images/fluent-bit/fluent-bit.yaml
  prow/jobs/incubator/third-party-images/jaeger-operator/jaeger-operator.yaml
  prow/jobs/incubator/third-party-images/kiali-operator/kiali-operator.yaml
  prow/jobs/incubator/third-party-images/kiali/kiali.yaml
  prow/jobs/incubator/third-party-images/kiwigrid-sidecar/kiwigrid-sidecar.yaml
  prow/jobs/incubator/third-party-images/minio-mc/minio-mc.yaml
  prow/jobs/incubator/third-party-images/minio/minio.yaml
  prow/jobs/incubator/third-party-images/prometheus-node-exporter/prometheus-node-exporter.yaml
  prow/jobs/incubator/varkes/varkes.yaml
  prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-development-artifacts.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-governance.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/jobs/kyma/kyma-metadata-governance.yaml
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/jobs/kyma/tools/failery/failery.yaml
  prow/jobs/rafter/rafter.yaml
  prow/jobs/test-infra/stability-checker.yaml
  templates/config.yaml
Labels: area/ci

#2833 Added tagging with post PR tag.
  prow/images/alpine-kubectl/Makefile
  prow/images/bootstrap-helm/Makefile
  prow/images/bootstrap/Makefile
  prow/images/buildpack-golang-kubebuilder/Makefile
  prow/images/buildpack-golang-kubebuilder2/Makefile
  prow/images/buildpack-golang-toolbox/Makefile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-java-node/Makefile
  prow/images/buildpack-java/Makefile
  prow/images/buildpack-node/Makefile
  prow/images/cleaner/Makefile
  prow/images/clonerefs/Makefile
  prow/images/kyma-cluster-infra/Makefile
  prow/images/kyma-integration/Makefile
  prow/images/probot-stale/Makefile
  prow/images/prow-tools/Makefile
  prow/images/whitesource-scanner/Makefile
  prow/scripts/publish-buildpack.sh
Labels: area/ci, enhancement

#2832 Removed duplicated text.
  development/tools/cmd/pjtester/README.md
Labels: area/ci, area/documentation

#2837 Added tagging with post PR tag.
  development/tools/cmd/prtagbuilder/main.go
Labels: area/ci, bug, priority/critical, test-failing

#2838 Disabled pr tag for prow-tools image.
  prow/images/prow-tools/Makefile
Labels: area/ci, bug

#2839 Rebuild without prtag bug.
  prow/images/bootstrap/Dockerfile
  prow/images/bootstrap/Makefile
Labels: area/ci, bug

#2841 Update bootstrap image tag in test-infra buildpack.yaml
  development/tools/jobs/tester/tester.go
  prow/jobs/test-infra/buildpack.yaml
  templates/config.yaml
Labels: area/ci

#2840 Testing with first image.
  prow/images/alpine-kubectl/Dockerfile
  prow/images/alpine-kubectl/Makefile
  prow/images/bootstrap-helm/Dockerfile
  prow/images/bootstrap-helm/Makefile
  prow/images/bootstrap/Makefile
  prow/images/buildpack-golang-kubebuilder/Dockerfile
  prow/images/buildpack-golang-kubebuilder/Makefile
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
  prow/images/buildpack-golang-kubebuilder2/Makefile
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang-toolbox/Makefile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-java-node/Dockerfile
  prow/images/buildpack-java-node/Makefile
  prow/images/buildpack-java/Dockerfile
  prow/images/buildpack-java/Makefile
  prow/images/buildpack-node/Dockerfile
  prow/images/buildpack-node/Makefile
  prow/images/cleaner/Dockerfile
  prow/images/cleaner/Makefile
  prow/images/clonerefs/Makefile
  prow/images/kyma-cluster-infra/Dockerfile
  prow/images/kyma-cluster-infra/Makefile
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
  prow/images/probot-stale/Makefile
  prow/images/prow-tools/Makefile
  prow/images/whitesource-scanner/Dockerfile
  prow/images/whitesource-scanner/Makefile
Labels: area/ci

#2843 Disabled prtagbuilder.
  prow/images/alpine-kubectl/Makefile
  prow/images/bootstrap-helm/Makefile
  prow/images/bootstrap/Makefile
  prow/images/buildpack-golang-kubebuilder/Makefile
  prow/images/buildpack-golang-kubebuilder2/Makefile
  prow/images/buildpack-golang-toolbox/Makefile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-java-node/Makefile
  prow/images/buildpack-java/Makefile
  prow/images/buildpack-node/Makefile
  prow/images/cleaner/Makefile
  prow/images/clonerefs/Makefile
  prow/images/kyma-cluster-infra/Makefile
  prow/images/kyma-integration/Makefile
  prow/images/probot-stale/Makefile
  prow/images/prow-tools/Makefile
  prow/images/whitesource-scanner/Makefile
  prow/scripts/publish-buildpack.sh
Labels: area/ci

#2844 Fixed matching regex
  development/tools/pkg/prtagbuilder/prtagbuilder.go
Labels: area/ci, bug

#2845 Updated prow-tools image tag.
  prow/images/alpine-kubectl/Dockerfile
  prow/images/bootstrap-helm/Dockerfile
  prow/images/bootstrap/Dockerfile
  prow/images/buildpack-golang-kubebuilder/Dockerfile
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-java-node/Dockerfile
  prow/images/buildpack-java/Dockerfile
  prow/images/buildpack-node/Dockerfile
  prow/images/cleaner/Dockerfile
  prow/images/kyma-cluster-infra/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
Labels: area/ci

#2846 Updated bootstrap image.
  development/tools/jobs/tester/tester.go
  prow/jobs/test-infra/buildpack.yaml
  templates/config.yaml
Labels: area/ci

#2771 Monitoring of docker images - admission controller
  development/image-guard/Dockerfile
  development/image-guard/README.md
  development/image-guard/go.mod
  development/image-guard/go.sum
  development/image-guard/image-guard/.helmignore
  development/image-guard/image-guard/Chart.yaml
  development/image-guard/image-guard/templates/admissionwebhook.yaml
  development/image-guard/image-guard/templates/deployment.yaml
  development/image-guard/image-guard/templates/service.yaml
  development/image-guard/image-guard/values.yaml
  development/image-guard/main.go
Labels: area/ci

#2849 Use one Azure Eventhubs ResourceGroup for Gardner jobs
  development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
Labels: area/eventing

#2835 Add a cleanup job for Azure Eventhubs Namespaces
  development/tools/jobs/kyma/kyma_azure_event_hubs_namespaces_cleanup_test.go
  prow/jobs/kyma/kyma-azure-event-hubs-namespaces-cleanup.yaml
  prow/scripts/cluster-integration/helpers/cleanup-azure-event-hubs-namespaces.sh
  templates/config.yaml
  templates/templates/kyma-azure-event-hubs-namespaces-cleanup.yaml
Labels: area/eventing

#2861 Removed cluster secret from plank.
  prow/cluster/components/11-plank_deployment.yaml
Labels: area/ci

#2862 Update kyma-development-artifacts job and script with new changes
  development/tools/jobs/kyma/development_artifacts_test.go
  prow/jobs/kyma/kyma-development-artifacts.yaml
  prow/scripts/build-kyma-development-artifacts.sh
Labels: area/ci, area/installation

#2853 Rewrite kyma-gke-integration.sh to use kyma-cli
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/kyma-cli.sh
Labels: area/ci

#2860 Docs for prtagbuilder.
  development/tools/pkg/prtagbuilder/README.md
Labels: area/ci, area/documentation

#2866 Remove `allow-http` annotation from stalebot chart
  prow/cluster/resources/probot-stale/values.yaml
Labels: area/ci

#2870 Add pre/post GKE integration job for multiple GKE versions.
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2871 Bumg gcloud version to 314.0.0 in kyma-integration image
  prow/images/kyma-integration/Dockerfile
Labels: area/ci

#2877 Re-add --release-channel variable to provision-gke-cluster.sh
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
Labels: area/ci

#2881 Rewrite kyma-gke-central.sh to use pre-built artifacts and Kyma CLI.
  prow/scripts/cluster-integration/kyma-gke-central.sh
Labels: area/ci

#2883 Rewrite provision-vm-and-start-kyma.sh to fix fetching JUnit report
  prow/scripts/provision-vm-and-start-kyma.sh
Labels: area/ci

#2873 Update chromium version in console dockerfile
  prow/images/buildpack-node-chromium/Dockerfile
Labels: enhancement

#2884 Buildpack for image-guard
  development/image-guard/Dockerfile
  development/image-guard/Makefile
  prow/jobs/test-infra/buildpack.yaml
  templates/config.yaml
Labels: area/ci

#2872 Divide the upgrade test for pre and post functionality
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  templates/templates/kyma-integration.yaml
Labels: hacktoberfest-accepted

#2885 Add installing image-guard to nightly and weekly cluster
  development/image-guard/image-guard/values.yaml
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: area/ci

#2891 Removed code for rendering prowjobs for not supported releases.
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2890 Update 1.18 gke version.
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
Labels: area/ci, test-failing
