Repository kyma-project/test-infra, pull requests merged in 2020-08, with the labels that each got.

#2659 Pjtester test few prowjobs
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_test.go
  development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/test-job.yaml
Labels: area/ci, enhancement

#2665 Update kyma-integration image to newest in all related jobs.
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-github-release.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-kind-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/jobs/rafter/rafter.yaml
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-for-debug.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-github-release.yaml
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
Labels: enhancement

#2666 Make function-runtimes pre-master and post-master jobs required
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/config.yaml
Labels: area/ci, area/serverless, enhancement

#2541 Introduce test-log-collector
  development/test-log-collector/.dockerignore
  development/test-log-collector/.gitignore
  development/test-log-collector/Dockerfile
  development/test-log-collector/Makefile
  development/test-log-collector/README.md
  development/test-log-collector/chart/test-log-collector/.helmignore
  development/test-log-collector/chart/test-log-collector/Chart.yaml
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/test-log-collector/chart/test-log-collector/templates/_helpers.tpl
  development/test-log-collector/chart/test-log-collector/templates/clusterrole.yaml
  development/test-log-collector/chart/test-log-collector/templates/clusterrolebinding.yaml
  development/test-log-collector/chart/test-log-collector/templates/cm.yaml
  development/test-log-collector/chart/test-log-collector/templates/job.yaml
  development/test-log-collector/chart/test-log-collector/templates/serviceaccount.yaml
  development/test-log-collector/chart/test-log-collector/values.yaml
  development/test-log-collector/cmd/app/mainerr.go
  development/test-log-collector/cmd/app/mainerr_test.go
  development/test-log-collector/cmd/main.go
  development/test-log-collector/go.mod
  development/test-log-collector/go.sum
  development/test-log-collector/pkg/config/config.go
  development/test-log-collector/pkg/config/config_test.go
  development/test-log-collector/pkg/hyperscaler/hyperscaler.go
  development/test-log-collector/pkg/hyperscaler/hyperscaler_test.go
  development/test-log-collector/pkg/resources/clustertestsuite/clustertestsuite.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/README.md
  development/test-log-collector/pkg/resources/clustertestsuite/types/labels.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/register.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/types.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/zz_generated.deepcopy.go
  development/test-log-collector/pkg/resources/resource.go
  development/test-log-collector/pkg/slack/slack.go
  development/test-log-collector/pkg/slack/slack_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/test-infra/test-log-collector.yaml
  prow/scripts/cluster-integration/helpers/install-test-log-collector.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, area/cluster

#2660 Stackdriver logging installation overrides for azure-gardener based jobs
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/scripts/cluster-integration/helpers/fluent-bit-stackdriver-logging.sh
  prow/scripts/cluster-integration/helpers/kyma-cli.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  templates/templates/kyma-integration-gardener.yaml
Labels: WIP

#2668 Update test-log-collector image
  development/test-log-collector/chart/test-log-collector/values.yaml
Labels: area/ci

#2670 Update test-log-collector configuration
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/install-test-log-collector.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci

#2675 Run prowjob test on PR on other repository.
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_test.go
  development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/test-job.yaml
Labels: area/ci, enhancement

#2676 Added github endpoint flags.
  prow/jobs/test-infra/pjtester.yaml
Labels: area/ci, enhancement

#2682 Add job for orders-service example
  development/tools/jobs/examples/orders_service_test.go
  prow/jobs/examples/orders-service/orders-service.yaml
Labels: enhancement

#2684 Pjtester fix flags
  development/tools/cmd/pjtester/main.go
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_test.go
Labels: area/ci, bug

#2686 Fixed pjtester args.
  prow/jobs/test-infra/pjtester.yaml
Labels: area/ci, bug

#2685 Update buildpack image in orders-service job
  development/tools/jobs/examples/orders_service_test.go
  prow/jobs/examples/orders-service/orders-service.yaml
Labels: bug

#2677 Fix prepare data stage for eventmesh upgrade in kyma-upgrade-gardener-azure job
  development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
Labels: area/eventing

#2697 Fix filename with a double dot
  prow/cluster/resources/probot-stale/templates/service.yaml
Labels: bug

#2525 Remove Tiller
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build-kyma-development-artifacts.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
  prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-for-debug.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/kind-install-kyma.sh
  prow/scripts/kind-upgrade-kyma.sh
  prow/scripts/lib/kyma.sh
Labels: area/ci

#2704 Fix pr-image-guard script
  prow/scripts/pr-image-guard.sh
Labels: bug

#2683 Add running test-log-collector to bash trap
  development/test-log-collector/Dockerfile
  development/test-log-collector/README.md
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/test-log-collector/chart/test-log-collector/templates/job.yaml
  development/test-log-collector/chart/test-log-collector/values.yaml
  development/test-log-collector/cmd/app/mainerr.go
  development/test-log-collector/pkg/hyperscaler/hyperscaler.go
  development/test-log-collector/pkg/hyperscaler/hyperscaler_test.go
  development/test-log-collector/pkg/slack/slack.go
  prow/scripts/cluster-integration/helpers/install-test-log-collector.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci

#2705 Move jobs to new clusters
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/image-syncer.yaml
  prow/jobs/test-infra/stability-checker.yaml
  prow/jobs/test-infra/test-infra-governance.yaml
  prow/jobs/test-infra/test-log-collector.yaml
  prow/jobs/test-infra/testgrid-automation.yaml
  prow/jobs/test-infra/validation.yaml
  prow/jobs/test-infra/watch-pods/watch-pods.yaml
  prow/jobs/website/website-governance.yaml
  templates/config.yaml
  templates/templates/component.yaml
Labels: area/ci, enhancement

#2702 add generation of image list in json
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
Labels: area/ci

#2696 Add gitserver tool building job
  development/tools/jobs/kyma/tools_test.go
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  templates/config.yaml
Labels: area/ci, area/serverless, enhancement

#2721 Add prtagbuilder.
  development/tools/cmd/prtagbuilder/main.go
  development/tools/go.mod
  development/tools/go.sum
  development/tools/pkg/prtagbuilder/prtagbuilder.go
  prow/scripts/lib/docker.sh
Labels: area/ci, enhancement

#2644 Pjtester docs
  development/tools/cmd/pjtester/README.md
  docs/prow/README.md
Labels: area/ci, area/documentation

#2727 Add prow-tools to test-infra images.
  prow/images/alpine-kubectl/Dockerfile
  prow/images/alpine-kubectl/Makefile
  prow/images/bootstrap-helm/Dockerfile
  prow/images/bootstrap-helm/Makefile
  prow/images/bootstrap/Dockerfile
  prow/images/bootstrap/Makefile
  prow/images/buildpack-golang-kubebuilder/Dockerfile
  prow/images/buildpack-golang-kubebuilder/Makefile
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
  prow/images/buildpack-golang-kubebuilder2/Makefile
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang-toolbox/Makefile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-java-node/Dockerfile
  prow/images/buildpack-java-node/Makefile
  prow/images/buildpack-java/Dockerfile
  prow/images/buildpack-java/Makefile
  prow/images/buildpack-node/Dockerfile
  prow/images/buildpack-node/Makefile
  prow/images/cleaner/Dockerfile
  prow/images/cleaner/Makefile
  prow/images/clonerefs/Dockerfile
  prow/images/clonerefs/Makefile
  prow/images/kyma-cluster-infra/Dockerfile
  prow/images/kyma-cluster-infra/Makefile
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
  prow/images/probot-stale/Dockerfile
  prow/images/probot-stale/Makefile
  prow/images/prow-tools/Dockerfile
  prow/images/prow-tools/Makefile
  prow/images/vulnerability-scanner/Dockerfile
  prow/images/vulnerability-scanner/Makefile
  prow/images/whitesource-scanner/Dockerfile
  prow/images/whitesource-scanner/Makefile
Labels: area/ci, enhancement
