Repository kyma-project/test-infra, pull requests merged in 2021-01, with the labels that each got.

#3070 scripts: consolidate kyma-integration-gardener
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/fluent-bit-stackdriver-logging.sh
  prow/scripts/cluster-integration/helpers/kyma-cli.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/kyma-cli.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/testing-helpers.sh
  prow/scripts/unstale-gardener-project.sh
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3084 Remove non-existent secret from prow deployments
  prow/cluster/components/13-sinker_deployment.yaml
  prow/cluster/components/15-deck_deployment.yaml
  prow/cluster/components/30-crier_deployment.yaml
Labels: area/ci

#3075 Run only weekdays
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#3080 scripts: partially deprecate library.sh
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/build-generic.sh
  prow/scripts/build-kcp-cli.sh
  prow/scripts/build-kcp-development-artifacts.sh
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build-kyma-development-artifacts.sh
  prow/scripts/build.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/dns-debug.sh
  prow/scripts/lib/docker.sh
  prow/scripts/lib/gcloud.sh
  prow/scripts/library.sh
  prow/scripts/minikube-test.sh
  prow/scripts/provision-vm-and-start-kyma-k3s.sh
  prow/scripts/provision-vm-and-start-kyma-minikube.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/provision-vm-control-plane.sh
  prow/scripts/publish-buildpack.sh
Labels: area/ci

#3085 Remove dns debug
  development/dns-debug-role.yaml
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/helpers/create-dns-record.sh
  prow/scripts/dns-debug.sh
  prow/scripts/lib/gcloud.sh
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#3091 scripts: remove doubled log::info
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
Labels: area/ci

#3086 scripts: deprecate library.sh
  development/custom-image/create-custom-image.sh
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/build-kcp-cli.sh
  prow/scripts/build-kcp-development-artifacts.sh
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build.sh
  prow/scripts/cli-tests/test-function.sh
  prow/scripts/cli-tests/test-runtest.sh
  prow/scripts/cli-tests/test-version.sh
  prow/scripts/cli-tests/testsuite-alpha.sh
  prow/scripts/cli-tests/testsuite-default.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
  prow/scripts/cluster-integration/helpers/create-cluster.sh
  prow/scripts/cluster-integration/helpers/decrypt.sh
  prow/scripts/cluster-integration/helpers/encrypt.sh
  prow/scripts/cluster-integration/helpers/generate-and-export-letsencrypt-TLS-cert.sh
  prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
  prow/scripts/cluster-integration/helpers/install-kyma.sh
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/cluster-integration/minio/azure-gateway.sh
  prow/scripts/cluster-integration/minio/gcs-gateway.sh
  prow/scripts/compatibility-cli.sh
  prow/scripts/governance.sh
  prow/scripts/lib/clitests.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gcloud.sh
  prow/scripts/metadata-governance.sh
  prow/scripts/minikube-test.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/provision-vm-control-plane.sh
  prow/scripts/validate-generated.sh
Labels: area/ci

#3100 Fix serverless k3s pipeline
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
Labels: area/ci, area/serverless

#3103 Template pjtester
  development/tools/cmd/rendertemplates/main.go
  prow/jobs/pamela/pamela.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/buildpack-node-data.yaml
  templates/data/pjtester-data.yaml
  templates/templates/buildpack.yaml
  templates/templates/generic.tmpl
Labels: area/ci

#3056 Gcloud lib integration
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/create-cluster.sh
  prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/lib/gcloud.sh
  prow/scripts/lib/utils.sh
Labels: area/ci

#3121 Rename readonly parameters to local in gcloud.sh encrypt/decrypt functions
  prow/scripts/lib/gcloud.sh
Labels: area/ci

#3122 Bump GKE regular version to 1.17.14-gke.1200
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
Labels: area/ci

#3128 Make pre-release-pr-image-guard required again.
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
Labels: area/ci

#3127 Scripts:refactor helpers
  prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/lib/kyma.sh
Labels: area/ci

#3126 scripts: additional labels as optional argument for gcloud::provide_gke_cluster
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/helpers/create-cluster.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/lib/gcloud.sh
Labels: area/ci

#3132 scripts: remove unused helpers
  prow/scripts/README.md
  prow/scripts/cluster-integration/README.md
  prow/scripts/cluster-integration/helpers/create-cluster.sh
  prow/scripts/cluster-integration/helpers/create-dns-record.sh
  prow/scripts/cluster-integration/helpers/create-network-with-subnet.sh
  prow/scripts/cluster-integration/helpers/decrypt.sh
  prow/scripts/cluster-integration/helpers/delete-dns-record-gcloud.sh
  prow/scripts/cluster-integration/helpers/delete-dns-record.sh
  prow/scripts/cluster-integration/helpers/delete-image.sh
  prow/scripts/cluster-integration/helpers/delete-network-with-subnet.sh
  prow/scripts/cluster-integration/helpers/deprovision-gke-cluster.sh
  prow/scripts/cluster-integration/helpers/encrypt.sh
  prow/scripts/cluster-integration/helpers/generate-self-signed-cert.sh
  prow/scripts/cluster-integration/helpers/get-helm-certs.sh
  prow/scripts/cluster-integration/helpers/install-test-log-collector.sh
  prow/scripts/cluster-integration/helpers/network-exists.sh
  prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
  prow/scripts/cluster-integration/helpers/release-ip-address.sh
  prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
  prow/scripts/library.sh
Labels: area/ci, area/documentation

#3136 Templates buildpack node
  development/tools/cmd/rendertemplates/main.go
  prow/config.yaml
  prow/jobs/pamela/pamela.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/unstale-gardener-project.yaml
  templates/config.yaml
  templates/data/buildpack-node-data.yaml
  templates/data/unstale-gardener-project-data.yaml
  templates/templates/generic.tmpl
  templates/templates/prow-config.yaml
Labels: area/ci

#3152 scripts: fix garderner gcp parallel
  prow/scripts/lib/gardener/gcp.sh
Labels: area/ci

#3147 scripts: add readme for lib
  prow/scripts/lib/README.md
  prow/scripts/lib/github.sh
Labels: area/ci

#3161 Templating testgird-automation and validation yamls
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/validate_test.go
  prow/jobs/test-infra/testgrid-automation.yaml
  prow/jobs/test-infra/validation.yaml
  templates/data/testgrid-automation-data.yaml
  templates/data/validation-data.yaml
Labels: area/ci

#3160 Templates other
  development/tools/jobs/testinfra/governance_test.go
  development/tools/jobs/testinfra/stability_checker_test.go
  prow/jobs/test-infra/stability-checker.yaml
  prow/jobs/test-infra/test-infra-governance.yaml
  prow/jobs/test-infra/test-log-collector.yaml
  templates/data/stability-checker-data.yaml
  templates/data/test-infra-governance-data.yaml
  templates/data/test-log-collector-data.yaml
Labels: area/ci

#3181 Templating for watch-pods
  development/tools/jobs/tester/componentsuite.go
  prow/jobs/test-infra/watch-pods/watch-pods.yaml
  templates/config.yaml
  templates/data/watch-pods-data.yaml
Labels: area/ci

#3133 scripts: integrate helpers
  prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
  prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
  prow/scripts/cluster-integration/helpers/install-kyma.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/minio/azure-cleaner.sh
  prow/scripts/lib/utils.sh
Labels: area/ci

#3144 scripts: refactor deprovision-gardener-cluster
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/utils.sh
  prow/scripts/unstale-gardener-project.sh
Labels: area/ci

#3194 Fix protecode guard - add missing variable
  prow/jobs/scans/protecode-guard.yaml
  templates/data/protecode-guard-data.yaml
Labels: area/ci

#3201 Use helm that is already in the vm in serverless-integration-k3s.sh
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
Labels: area/ci

#3203 bump RELEASE_VERSION to 1.19.0-rc3
  prow/RELEASE_VERSION
Labels: area/ci

#3207 Switch stability-checker notification to new workspace
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3205 Restore missing variables in Pamela prowjobs
  prow/jobs/pamela/pamela.yaml
  prow/jobs/scans/protecode-guard.yaml
  templates/data/buildpack-node-data.yaml
  templates/data/protecode-guard-data.yaml
Labels: area/ci

#3218 Remove duplicated and unnecessary function from kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
Labels: area/ci

#3225 fixing constantly red kyma alpha deploy pipeline
  prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
Labels: area/installation

#3226 Alpha deploy fix
  prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
Labels: area/installation
