Repository kyma-project/test-infra, pull requests merged in 2021-06, with the labels that each got.

#3716 Delete Azure EventHubs related jobs
  development/tools/jobs/kyma/kyma_azure_event_hubs_namespaces_cleanup_test.go
  prow/jobs/kyma/kyma-azure-event-hubs-namespaces-cleanup.yaml
  prow/scripts/cluster-integration/helpers/cleanup-azure-event-hubs-namespaces.sh
  prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  templates/data/kyma-azure-event-hubs-namespaces-cleanup-data.yaml
Labels: area/eventing, lgtm, size/L

#3717 Bump Go version to latest 1.16.4
  prow/images/buildpack-golang/Makefile
Labels: lgtm, size/XS

#3578 Bump k8s version on gardener to 1.20
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/XS

#3718 Bump Go version to latest 1.16.4
  development/tools/jobs/incubator/milv/milv_test.go
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang/README.md
  prow/images/debug-commando/Dockerfile
  prow/jobs/incubator/milv/milv.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: lgtm, size/S

#3712 Use static ssh key for gcloud ssh
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/S

#3719 Bump buildpack kubebuillder2 image
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
Labels: lgtm, size/XS

#3726 Enable ext svc mock auditlog for tests
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: lgtm, size/XS

#3523 Enable highcpu config for generic template
  development/tools/jobs/rafter/rafter_test.go
  prow/jobs/addons/addons.yaml
  prow/jobs/busola/ui-test.yaml
  prow/jobs/cli/cli-compatibility.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/cli/cli.yaml
  prow/jobs/console/components/react/react-components.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/control-plane/control-plane-integration.yaml
  prow/jobs/control-plane/kcp-cli.yaml
  prow/jobs/control-plane/kcp-development-artifacts.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-whitesource.yaml
  prow/jobs/examples/examples-buildpack.yaml
  prow/jobs/governance.yaml
  prow/jobs/helm-broker/helm-broker.yaml
  prow/jobs/incubator/api-gateway/api-gateway.yaml
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/incubator/dex/dex.yaml
  prow/jobs/incubator/documentation-component/documentation-component.yaml
  prow/jobs/incubator/gcp-service-broker/gcp-service-broker.yaml
  prow/jobs/incubator/github-slack-connectors/github-slack-connectors.yaml
  prow/jobs/incubator/hydroform/hydroform.yaml
  prow/jobs/incubator/knative-kafka/knative-kafka.yaml
  prow/jobs/incubator/milv/milv.yaml
  prow/jobs/incubator/octopus/octopus.yaml
  prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
  prow/jobs/incubator/service-catalog-tester/service-catalog-tester.yaml
  prow/jobs/incubator/terraform-provider-gardener/terraform-provider-gardener.yaml
  prow/jobs/incubator/varkes/varkes.yaml
  prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
  prow/jobs/kyma/common/common.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/jobs/kyma/releases/kyma-release-124.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/jobs/kyma/tools/failery.yaml
  prow/jobs/rafter/rafter.yaml
  prow/jobs/scans/protecode-guard.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/image-syncer.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/stability-checker.yaml
  prow/jobs/test-infra/test-log-collector.yaml
  prow/jobs/test-infra/testgrid-automation.yaml
  prow/jobs/test-infra/validation.yaml
  prow/jobs/test-infra/watch-pods/watch-pods.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/config.yaml
  templates/data/rafter-data.yaml
  templates/templates/generic.tmpl
Labels: lgtm, size/XXL

#3729 Remove knative related config from gardener-azure-integration job
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, lgtm, size/XS

#3732 Removed old monitoring Tests
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/integration/monitoring/monitoring-generic.yaml
  templates/config.yaml
Labels: lgtm, size/L

#3738 Consolidate current buildpack-golang images into one.
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-golang/license-puller.sh
Labels: lgtm, size/L

#3737 Fix permission problem for Cypress downloads folder
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: lgtm, size/XS

#3693 Busola kyma fix test
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/M

#3739 Add Istio 1.10 images
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3743 Add copy of Cypress screenshots folder
  prow/scripts/cluster-integration/busola-ui-tests-k3s.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: lgtm, size/XS

#3734 Provider Config Migration Job added
  development/tools/jobs/control-plane/components_test.go
  prow/jobs/control-plane/components/provider-config-migration-job/provider-config-migration-job-generic.yaml
  templates/config.yaml
Labels: lgtm, size/L

#3699 Configure SKR pipeline for AWS to support audit logs
  prow/config.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/S

#3749 Upgrade Cypress to 7.5.0 version
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3747 Busola improve screenshot handling
  prow/scripts/cluster-integration/busola-ui-tests-k3s.sh
Labels: lgtm, size/XS

#3750 Upgrade Cypress to 7.5.0 version
  prow/scripts/cluster-integration/busola-ui-tests-k3s.sh
Labels: lgtm, size/XS

#3751 Remove readiness probe disablement from stability-checker helm chart
  stability-checker/deploy/chart/stability-checker/templates/deploy.yaml
Labels: lgtm, size/XS

#3753 Grafana: change quality dashbaord timeframes
  prow/cluster/components/monitoring/dashboards/quality/quality.json
Labels: lgtm, size/XS

#3754 switching to kymatest ias tennant for nightly cluster
  prow/scripts/resources/busola/cluster-kyma.yaml
Labels: lgtm, size/XS

#3756 remove deprecated buildpack-golang-* prowjobs
  development/tools/jobs/testinfra/buildpack_test.go
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: lgtm, size/L

#3757 Remove deprecated buildpack-golang-* image Dockerfiles
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
  prow/images/buildpack-golang-kubebuilder2/Makefile
  prow/images/buildpack-golang-kubebuilder2/README.md
  prow/images/buildpack-golang-toolbox/Dockerfile
  prow/images/buildpack-golang-toolbox/Makefile
  prow/images/buildpack-golang-toolbox/README.md
  prow/images/buildpack-golang-toolbox/license-puller.sh
Labels: lgtm, size/L

#3748 Delete kyma before cluster deletion in busola pipeline
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
Labels: lgtm, size/XS

#3760 Temporary disable Compass DB dump
  prow/scripts/provision-vm-compass.sh
Labels: lgtm, size/XS

#3755 Make Busola UI tests required
  prow/jobs/busola/ui-test.yaml
  templates/data/busola-ui-test-data.yaml
Labels: lgtm, size/XS

#3761 Update gardener cleaner
  development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
  templates/data/kyma-gardener-cleanup-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/L

#3713 API Gateway integration tests refactoring
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/L

#3764 Disable kyma 2.0 nightly and update periodic cron expression
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/L

#3720 Workaround waiting for shoot condition to finish
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gardener.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/gcloud.sh
  prow/scripts/lib/utils.sh
  prow/scripts/resources/debug-container.yaml
  prow/scripts/unstale-gardener-project.sh
  templates/data/kyma-integration-data.yaml
Labels: area/ci, lgtm, size/L

#3768 Bump oathkepper image version
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3769 Disable firewall cleaner
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/L

#3767 added new jobs for oauth2-proxy image
  development/tools/jobs/third-party-images/oauth2_proxy_test.go
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: lgtm, size/L

#3770 Fix azure gardener jobs
  prow/scripts/lib/gardener/azure.sh
Labels: lgtm, size/XS

#3771 Gardener: fix azure script
  prow/scripts/lib/gardener/azure.sh
Labels: lgtm, size/XS

#3775 Initial Prow autobump configuration
  prow/autobump-config/prow-cluster-autobump-config.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: lgtm, size/M

#3773 fix cleanup second failed cluster.
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
Labels: area/ci, bug, lgtm, size/S

#3778 Fix run_if_changed regex for API gateway tests
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/XS

#3766 Templates: update documentation
  development/tools/cmd/rendertemplates/README.md
  templates/README.md
Labels: lgtm, size/L

#3776 Add new optional governance job for kyma-2.0-docu
  development/tools/jobs/governance/common_governance_test.go
  development/tools/jobs/governance/kyma_governance_test.go
  go.sum
  prow/jobs/governance.yaml
  templates/config.yaml
  templates/data/governance-data.yaml
Labels: lgtm, size/L

#3781 Enable auditlog secret for benchmark tests
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: lgtm, size/XS

#3782 Auto deploy prow prowjob
  prow/cluster/deploy.sh
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: lgtm, size/L

#3783 Add jobs for reconciler
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/config.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/L

#3785 Fix typo in post-test-infra-deploy-prow command
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: lgtm, size/XS

#3787 Change deck service type from not working ClusterIP to NodePort
  prow/cluster/components/deck_service.yaml
Labels: lgtm, size/XS

#3790 Fix branch name in branch-protector (reconciler)
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/XS

#3772 Fix tests for kyma alpha uninstall
  prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh
Labels: lgtm, size/XS

#3789 Templates: don't use susbstitution in data files
  development/tools/jobs/incubator/milv/milv_test.go
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/milv/milv.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/config.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: lgtm, size/L

#3791 Fetch correct current version for kyma-cli-compatibility-2 job
  prow/scripts/compatibility-cli.sh
Labels: lgtm, size/XS

#3792 GZIP job-config
  prow/plugins.yaml
Labels: lgtm, size/XS

#3794 Change repo as per generic-autobumper docs
  prow/autobump-config/prow-cluster-autobump-config.yaml
Labels: lgtm, size/XS

#3581 Add fast integration job for central Application Gateway
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3s.sh
  prow/scripts/provision-vm-and-start-kyma-k3s.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
Labels: area/application-connector, enhancement, lgtm, size/L

#3774 Skip Compass tests in Control Plane integration tests jobs
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
Labels: lgtm, size/XS

#3780 Increase number of vCPUs for Cypress tests
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: lgtm, size/XS

#3802 Change schedule for weekly and nightly clusters
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/S

#3803 Update postgres version
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3808 CLI compatibility script: check 2 latest kyma versions and set node runtime
  prow/scripts/cli-tests/test-function.sh
  prow/scripts/compatibility-cli.sh
Labels: lgtm, size/M

#3798 Add optional job for busola
  development/tools/jobs/busola/busola_test.go
  prow/jobs/busola/busola-web/busola-web.yaml
  templates/data/generic_component_busola_data.yaml
Labels: lgtm, size/L

#3811 skip_report for busola-web
  prow/jobs/busola/busola-web/busola-web.yaml
  templates/config.yaml
  templates/data/generic_component_busola_data.yaml
Labels: lgtm, size/XS

#3815 Add `show-output-dir` flag to rendertemplates
  development/tools/cmd/rendertemplates/main.go
Labels: lgtm, size/XS

#3821 Pre-fetch docker images in VM image
  development/custom-image/install-deps-debian.sh
Labels: lgtm, size/XS

#3822 Bump Istio to 1.10.2
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3786 trying to fix the upgrade-test
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/M

#3810 Remove old busola jobs
  development/tools/jobs/busola/busola_test.go
  prow/jobs/busola/busola-web/busola-web.yaml
  templates/data/generic_component_busola_data.yaml
Labels: lgtm, size/M

#3824 Remove console nginx jobs
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: lgtm, size/L

#3814 Run Busola UI test on post-main and rename to Integration test
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/busola/integration-test.yaml
  prow/jobs/busola/ui-test.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  templates/data/busola-integration-test-k3s-data.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/L

#3825 Remove old busola jobs
  prow/jobs/busola/busola-core-ui/busola-core-ui.yaml
  prow/jobs/busola/busola-core/busola-core.yaml
  prow/jobs/busola/busola-service-catalog-ui/busola-service-catalog-ui.yaml
Labels: lgtm, size/XXL

#3827 Fix typo in Busola integration test script name
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: lgtm, size/XS

#3828 Rename Busola UI to Integration test script
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
Labels: lgtm, size/XS

#3823 Upgrade Cypress to 7.6.0 version
  development/custom-image/install-deps-debian.sh
  development/image-syncer/external-images.yaml
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
Labels: lgtm, size/XS

#3830 Upgrade Cypress to 7.6.0 version
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
Labels: lgtm, size/XS

#3831 Bump service manager proxy external image
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3826 Local git hooks
  .githooks/README.md
  .githooks/post-commit
  .githooks/post-commit.d/.init
  .githooks/pre-commit
  .githooks/pre-commit.d/01-rendertemplates.sh
Labels: lgtm, size/M

#3833 Clean-up images and remove dynamic image tags from definitions
  development/image-guard/image-guard/values.yaml
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/validate_test.go
  prow/jobs/console/components/react/react-components.yaml
  prow/jobs/examples/examples-buildpack.yaml
  prow/jobs/governance.yaml
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/incubator/dex/dex.yaml
  prow/jobs/incubator/documentation-component/documentation-component.yaml
  prow/jobs/incubator/varkes/varkes.yaml
  prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/validation.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  prow/scripts/resources/debug-container.yaml
  templates/config.yaml
Labels: lgtm, size/L

#3837 Add reconciler whitesource job
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: lgtm, size/M

#3839 upgrade to loki 2.2.1
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3838 Add job definitions for Kyma 2.0
  development/tools/jobs/releases/releases.go
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/testgrid-default.yaml
  templates/config.yaml
  templates/templates/releases.go.tmpl
Labels: lgtm, size/M

#3836 Re-enable DB dump on Compass tests
  prow/scripts/provision-vm-compass.sh
Labels: lgtm, size/XS

#3710 Enable tests on GKE with containerd images
  prow/config.yaml
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/resources/containerd-gke-patch.tpl.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/L

#3840 Add override for system-fetcher tests
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: lgtm, size/S

#3845 Revert "Add override for system-fetcher tests (#3840)"
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: lgtm, size/S

#3846 Revert "Enable tests on GKE with containerd images (#3710)"
  prow/config.yaml
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/resources/containerd-gke-patch.tpl.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/L

#3841 CLI alpha: change command name
  prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh
Labels: lgtm, size/XS

#3832 Remove false-positives for Busola UI Integration tests
  prow/jobs/busola/integration-test.yaml
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  templates/data/busola-integration-test-k3s-data.yaml
  templates/data/generic_component_busola_data.yaml
Labels: lgtm, size/S

#3799 Autobump config for test-infra images
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: lgtm, size/M

#3759 Use common lib scripts and functions in gke integration prowjobs
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/helpers/start-wssagent.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/lib/gardener/gardener.sh
  prow/scripts/lib/gcloud.sh
  prow/scripts/lib/gcp.sh
  prow/scripts/lib/utils.sh
Labels: area/ci, lgtm, size/XXL

#3848 Scritps: fix gcp lib
  prow/scripts/lib/gcp.sh
Labels: lgtm, size/XS

#3849 Scripts: fix gardener lib
  prow/scripts/lib/gardener/gardener.sh
Labels: lgtm, size/XS

#3850 Scripts: fix gcp lib
  prow/scripts/lib/gcp.sh
Labels: lgtm, size/XS

#3852 Scripts: fix gcloud ip function
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: lgtm, size/S

#3854 Scripts: fix variable name
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/lib/gcloud.sh
Labels: lgtm, size/S
