Repository kyma-project/test-infra, pull requests merged in 2021-12, with the labels that each got.

#4513 Added yq and gh tools to kyma-integration image
  prow/images/kyma-integration/Dockerfile
Labels: size/S, lgtm

#4515 Fix nightly-main-reconciler-publish-unstable-cli job
  prow/scripts/reconciler-publish-unstable-cli.sh
Labels: size/XS, lgtm

#4516 Added copy nbusola
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: size/XS, lgtm

#4517 Fix nightly-main-reconciler-publish-unstable-cli job
  prow/scripts/reconciler-publish-unstable-cli.sh
Labels: area/eventing, size/XS, lgtm

#4504 Image-URL-helper: add option to exclude images from being promoted
  development/image-url-helper/cmd/promote.go
  development/image-url-helper/excludes_promote.yaml
  development/image-url-helper/pkg/list/imagelister.go
  development/image-url-helper/pkg/promote/promote.go
Labels: size/M, lgtm

#4519 Removed copying nbusola
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: size/XS, lgtm

#4522 Upgrade Node.js to Active LTS in custom image
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#4523 Set preview 2.0.0rc8
  prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
  templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
Labels: size/XS, lgtm

#4525 Revert node upgrade until kyma deps are updated
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#4527 Use different names for nightly clusters
  prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
Labels: size/S, lgtm

#4509 Enable privileged debug container for AWS and Azure
  prow/scripts/resources/debug-container.yaml
Labels: size/S, lgtm

#4533 Add release k3d jobs for kyma 2.0
  prow/jobs/kyma/releases/kyma-release-20.yaml
  templates/data/kyma-release-data.yaml
Labels: size/L, lgtm

#4535 Add a branch section to the cli-integration-kyma-2 job
  prow/jobs/cli/cli-integration.yaml
  templates/data/cli-data.yaml
Labels: size/XS, lgtm

#4537 Enable post job and make gke-external-registry required.
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  templates/data/kyma-gke-external-registry-data.yaml
Labels: size/M, lgtm

#4541 Run pre-kyma-cli on release branches
  development/tools/jobs/cli/cli_test.go
  prow/jobs/cli/cli.yaml
  templates/data/cli-data.yaml
Labels: size/S, lgtm

#4543 Set upgrade preview2.0.0
  prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
  templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
Labels: size/XS, lgtm

#4532 Remove watch-pods template
  CODEOWNERS
  prow/jobs/test-infra/watch-pods/watch-pods.yaml
  templates/data/watch-pods-data.yaml
Labels: size/L, lgtm

#4485 Remove not needed cmp overrides
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/M, lgtm

#4291 Analyze multiple benchmark tests in Cоmpass
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/S, lgtm

#4464 Image-url-helper: add documentation for promote command
  development/image-url-helper/README.md
Labels: size/S, lgtm

#4545 Scripts: make Kyma version retrieval more universal
  prow/scripts/lib/kyma.sh
Labels: size/S, lgtm

#4547 Use regional clusters for Compass GKE integration tests
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#4544 extract LAST_RELEASE_VERSION as env value, provide latest 1.x version
  prow/scripts/cluster-integration/reconciler-e2e-upgrade-gardener.sh
Labels: size/XS, lgtm

#4536 Fix RC cluster
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-release-data.yaml
Labels: size/L, lgtm

#4549 Use regional clusters for Compass GKE benchmark tests
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  templates/data/compass-gke-benchmark-data.yaml
Labels: size/S, lgtm

#4554 add kyma_version to upgrade test
  prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
  templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
Labels: size/XS, lgtm

#4553 Fix reconciler ci job
  prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
Labels: size/M, lgtm

#4557 Do not make the PV zone node unschedulable
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/XS, lgtm

#4555 refactor reconciler jobs
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
  prow/scripts/cluster-integration/reconciler-e2e-upgrade-gardener.sh
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
Labels: size/L, lgtm

#4530 added auto image bump job for reconciler in control-plane
  prow/autobump-config/control-plane-autobump-reconciler-config.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4559 Revert compass jobs to use zonal clusters
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#4558 Bump Golang to 1.17.5
  development/image-syncer/external-images.yaml
  development/kyma-ci-force-bot/ciforcebot/Dockerfile
  development/kyma-github-connector/githubWebhookGateway/Dockerfile
  development/kyma-pubsub-connector/pubSubGateway/Dockerfile
  development/test-log-collector/Dockerfile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-golang/README.md
  prow/images/kyma-integration/Dockerfile
  prow/images/prow-tools/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
  prow/scripts/cluster-integration/reconciler-integration-k3d.sh
Labels: size/S, lgtm

#4564 Dependabot/go modules/GitHub.com/tidwall/gjson 1.9.3
  go.mod
  go.sum
Labels: area/ci, size/XL, lgtm

#4567 Update go.mod and go.sum entries
  development/checker/unique-jobs-name/main.go
  development/gcp/cloud-functions/getGithubIssue/getgithubissue.go
  development/gcp/cloud-functions/getfailureinstancedetails/getfailureinstancedetails.go
  development/gcp/pkg/pubsub/client.go
  development/github/pkg/client/client.go
  development/jobguard/cmd/jobguard/main.go
  development/prow/prowjobs.go
  development/tools/cmd/githubissues/main.go
  development/tools/cmd/oomfinder/main.go
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_test.go
  development/tools/pkg/prtagbuilder/mocks/fakeghclient.go
  development/tools/pkg/prtagbuilder/prtagbuilder.go
  development/tools/pkg/release/github.go
  development/tools/pkg/release/mock.go
  go.mod
  go.sum
Labels: size/L, lgtm

#4571 Image-syncer: fix dependencies
  go.mod
  go.sum
Labels: size/XL, lgtm

#4569 update jaeger image to latest 1.29.0
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4572 Debug commando: bump base image to Go 1.17.5
  prow/images/debug-commando/Dockerfile
Labels: size/XS, lgtm

#4565 Add initial OWNERS and OWNERS_ALIASES for demo purposes
  OWNERS
  OWNERS_ALIASES
Labels: size/S, lgtm

#4575 fix dead link for commitish value
  development/tools/cmd/githubrelease/README.md
Labels: size/XS, lgtm

#4579 Bump Grafana to 7.5.12
  prow/cluster/components/monitoring/grafana_deployment.yaml
Labels: size/XS, lgtm

#4580 Add gke nightly job for Kyma 2.0
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-125.yaml
  prow/jobs/kyma/releases/kyma-release-20.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-release-data.yaml
Labels: size/L, lgtm

#4584 Remove Piotr from codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#4552 Add test upgrade paths
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma-to-kyma2.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
  prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma-to-kyma2.sh
  prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma2-to-main.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/provision-vm-and-start-kyma-upgrade-k3d.sh
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/XL, lgtm

#4589 Add prowjobparser job
  development/prowjobparser/main.go
  prow/jobs/test-infra/validation.yaml
  templates/data/validation-data.yaml
Labels: size/M, lgtm

#4528 Update tooling kyma workloads.
  development/kyma-ci-force-bot/kyma-ci-force-bot/prod-values.yaml
  development/kyma-github-connector/githubConnectorChart/global-prod-values.yaml
  development/kyma-github-connector/githubConnectorChart/templates/webhookGatewayConfigMap.yaml
  development/kyma-github-connector/githubConnectorChart/values/sap.tools.github/backlog/prod-values.yaml
  development/kyma-pubsub-connector/pubsubConnectorChart/global-prod-values.yaml
  development/kyma-pubsub-connector/pubsubConnectorChart/templates/googleServiceAccountSecret.yaml
  development/kyma-pubsub-connector/pubsubConnectorChart/values/oomevent.found/prod-values.yaml
  development/kyma-slack-connector/issueLabeledFunction/handler.py
  development/kyma-slack-connector/slackConnectorChart/global-prod-values.yaml
  development/kyma-slack-connector/slackConnectorChart/templates/functionSubscription.yaml
  development/kyma-slack-connector/slackConnectorChart/values/issuesevent.labeled/prod-values.yaml
  development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/prod-values.yaml
  development/kyma-slack-connector/slackConnectorChart/values/prowjob.failed/prod-values.yaml
Labels: area/ci, size/M, lgtm

#4593 Run Reconciler integration jobs form Monday till Friday
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/S, lgtm

#4600 Add kyma-upgrade regexp for upgrade k3d jobs in VMs cleaner
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4599 Update smctl version to v1.11.12
  prow/images/kyma-integration/Dockerfile
Labels: size/XS, lgtm

#4460 Add mTLS Prometheus patching
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/L, lgtm

#4606 Fix kyma1-kyma2-upgrade plan
  prow/scripts/cluster-integration/reconciler-e2e-upgrade-gardener.sh
  prow/scripts/lib/gardener/gcp.sh
Labels: size/S, lgtm

#4605 Notify Jellyfish slack channel in case of failures
  prow/jobs/cli/cli.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
  templates/data/cli-data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/M, lgtm

#4582 Enable dependabot for test-infra repo.
  .github/dependabot.yml
  templates/data/dependabot-config-data.yaml
  templates/templates/dependabot.tmpl
Labels: enhancement, area/ci, size/L, lgtm, dependencies

#4611 Dependabot: fix prefixes length
  .github/dependabot.yml
  templates/data/dependabot-config-data.yaml
Labels: size/M, lgtm

#4623 Disable branch protection for private repo.
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#4602 Remove kyma-upgrade-k3d-kyma-to-kyma2 job
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4583 Pin sigstore version
  go.mod
  go.sum
Labels: size/L, lgtm

#4576 Go.mod: add testing
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/image-syncer.yaml
  prow/jobs/test-infra/test-log-collector.yaml
  prow/jobs/test-infra/validation.yaml
  templates/data/buildpack-data.yaml
  templates/data/image-syncer-data.yaml
  templates/data/test-log-collector-data.yaml
  templates/data/validation-data.yaml
Labels: size/S, lgtm

#4546 Add serverless git auth integration tests
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/lib/serverless-shared-k3s.sh
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4597 Update external-secrets docs
  prow/cluster/resources/external-secrets/README.md
Labels: size/XS, lgtm

#4635 Update prometheus images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4633 adjust cron schedule
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#4518 Image-url-helper refactor
  development/image-url-helper/cmd/check.go
  development/image-url-helper/cmd/list.go
  development/image-url-helper/cmd/promote.go
  development/image-url-helper/pkg/common/component.go
  development/image-url-helper/pkg/common/images.go
  development/image-url-helper/pkg/common/valuefile.go
  development/image-url-helper/pkg/list/imagelister.go
  development/image-url-helper/pkg/list/outputjson.go
  development/image-url-helper/pkg/promote/externalsyncer.go
  development/image-url-helper/pkg/promote/promote.go
Labels: size/L, lgtm

#4629 Remove unused images.
  .github/dependabot.yml
  development/tools/jobs/testinfra/buildpack_test.go
  prow/images/whitesource-scanner/Dockerfile
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
  templates/data/dependabot-config-data.yaml
Labels: area/ci, size/L, lgtm

#4652 temporarily make protecode jobs optional
  prow/jobs/scans/protecode-guard.yaml
  templates/data/protecode-guard-data.yaml
Labels: size/XS, lgtm

#4641 Add environmental variables for kcp client in fast integration tests
  prow/jobs/kyma/skr-svcat-migration.yaml
  templates/data/skr-svcat-migration-data.yaml
Labels: size/S, lgtm
