Repository kyma-project/test-infra, pull requests merged in 2021-08, with the labels that each got.

#3948 Compass down migrations
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: lgtm, size/XS

#3977 Add telemetry operator tests and build
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/telemetry-operator/telemetry-operator-generic.yaml
  templates/data/generic_component_data.yaml
Labels: lgtm, size/L

#3930 External secrets: add synchronization
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
  prow/cluster/resources/external-secrets/values_prow.yaml
  prow/cluster/resources/external-secrets/values_trusted.yaml
  prow/cluster/resources/external-secrets/values_untrusted.yaml
Labels: lgtm, size/XXL

#3989 GKE upgrade: add missing flag
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: lgtm, size/XS

#3931 External secrets: add readme
  milv.config.yaml
  prow/cluster/resources/external-secrets/README.md
Labels: lgtm, size/M

#3992 Fast integration long lasting
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/fast-integration-test.sh
  prow/scripts/lib/gcp.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: lgtm, size/L

#3996 Github release: use token authorization
  development/tools/pkg/release/github.go
Labels: lgtm, size/XS

#3997 init LogEntry.Labels map if nil
  development/gcp/pkg/cloudfunctions/logging.go
Labels: area/ci, lgtm, size/XS

#3998 Fast integration: fix weekly schedule
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/XS

#3988 Migrate alpha commands to stable
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/provision-vm-cli.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/L

#4001 Rename k3s->k3d
  prow/jobs/cli/cli-integration.yaml
  prow/scripts/provision-vm-cli.sh
  templates/data/cli-data.yaml
Labels: lgtm, size/S

#4000 Bump golang version in prow-tools
  prow/images/prow-tools/Dockerfile
Labels: lgtm, size/XS

#4004 Bump buildpacks for golang
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
Labels: lgtm, size/XS

#4005 Bump version due to CVE issue
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/README.md
Labels: lgtm, size/XS

#4006 add preset-kyma-kms-sign-key for image-syncer
  prow/jobs/test-infra/image-syncer.yaml
  templates/data/image-syncer-data.yaml
Labels: lgtm, size/XS

#3999 Orphaned disk cleaner: change regexp
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/XS

#4008 Fix formatting
  prow/cluster/resources/external-secrets/README.md
Labels: lgtm, size/M

#4013 IP cleaner: make it more universal
  development/tools/cmd/ipcleaner/main.go
  development/tools/pkg/ipcleaner/automock/address_api.go
  development/tools/pkg/ipcleaner/automock/compute_api.go
  development/tools/pkg/ipcleaner/automock/region_api.go
  development/tools/pkg/ipcleaner/compute_wrapper.go
  development/tools/pkg/ipcleaner/remover.go
  development/tools/pkg/ipcleaner/remover_test.go
  development/tools/pkg/ipcleaner/wrappers.go
Labels: lgtm, size/XL

#4003 Image syncer sign
  development/image-syncer/Makefile
  development/image-syncer/README.md
  development/image-syncer/external-images.yaml
  development/image-syncer/main.go
  development/image-syncer/sign.go
  development/image-syncer/util.go
  go.mod
  go.sum
Labels: lgtm, size/XXL

#4016 IP cleaner: more meaningful regex name
  development/tools/cmd/ipcleaner/main.go
Labels: lgtm, size/XS

#3905 Extend Central Application Gateway fast integration tests to Central Application Connectivity
  development/tools/jobs/kyma/kyma_integration_test.go
  go.sum
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3s.sh
  prow/scripts/provision-vm-and-start-kyma-k3s.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: area/application-connector, area/quality, size/L, lgtm

#4018 Remove extra intendation near run_if_changed field
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/S, lgtm

#4015 IP cleaner: update documentation
  development/tools/cmd/ipcleaner/README.md
Labels: size/S, lgtm

#4019 skr-azure-svcat-migration-dev: run every 4 hours
  prow/jobs/kyma/skr-svcat-migration.yaml
  templates/data/skr-svcat-migration-data.yaml
Labels: size/XS, lgtm

#4020 AKS nightly: disable stability checker
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Labels: size/S, lgtm

#4021 gcp logging client externalSecret and prow preset.
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/M, lgtm

#4029 Add dependency k3d for fast-integration tests to VM image
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#4023 Kyma cli install for fast-integration
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/README.md
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/cluster-integration/kyma-integration-k3s.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4031 Rename busola job name
  prow/jobs/busola/busola.yaml
  templates/data/generic_component_busola_data.yaml
Labels: size/S, lgtm

#4010 test-infra dependency update
  development/gcp/cloud-functions/getGithubIssue/go.mod
Labels: area/ci, size/XS, lgtm

#4032 Replace occurences of ci-no-install make target with ci
  prow/scripts/cluster-integration/fast-integration-test.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
Labels: size/XS, lgtm

#4038 Provide components for compass tests via file
  prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
Labels: size/M, lgtm

#4024 GCR: change bucket
  prow/config.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/jobs/test-infra/oom-tester.yaml
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  templates/data/compass-gke-benchmark-data.yaml
  templates/data/compass-gke-integration-data.yaml
  templates/data/control-plane-integration-data.yaml
  templates/data/kyma-gke-external-registry-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-release-data.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#4043 Gardener unstale: fix script
  prow/scripts/unstale-gardener-project.sh
Labels: size/XS, lgtm

#4044 Add new template mappings for compass tests
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#4046 Remove link from log message.
  development/tools/cmd/usersmapchecker/main.go
Labels: area/ci, size/XS, lgtm

#4036 Rendertemplates: better component job generation
  development/tools/pkg/rendertemplates/rendertemplates.go
  templates/data/generic_component_busola_data.yaml
  templates/data/generic_component_compass_data.yaml
  templates/data/generic_component_console_data.yaml
  templates/data/generic_component_control_plane_data.yaml
  templates/data/generic_component_data.yaml
Labels: size/XL, lgtm

#4030 Fix integration jobs for cli
  prow/jobs/cli/cli-integration.yaml
  templates/data/cli-data.yaml
Labels: size/L, lgtm

#4048 fixed setting exitcode on success
  development/tools/cmd/usersmapchecker/main.go
Labels: bug, test-failing, size/S, lgtm

#4040 Use postsubmit image.
  prow/jobs/test-infra/kyma-bot.yaml
  templates/data/kyma-bot-data.yaml
Labels: area/ci, size/XS, lgtm

#3961 Close failing instance
  development/kyma-ci-force-bot/ciforcebot/Dockerfile
  development/kyma-ci-force-bot/ciforcebot/Makefile
  development/kyma-ci-force-bot/ciforcebot/before-commit.sh
  development/kyma-ci-force-bot/ciforcebot/cmd/main.go
  development/kyma-ci-force-bot/ciforcebot/go.mod
  development/kyma-ci-force-bot/ciforcebot/go.sum
  development/kyma-ci-force-bot/kyma-ci-force-bot/Chart.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/prod_values.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/ciForceBotConfigMap.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/ciForceBotDeployment.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/ciForceBotIssueClosedSubscription.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/ciForceBotService.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/ciForceBotServiceAccountSecret.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/values.yaml
  development/kyma-github-connector/githubConnector/prod_values.yaml
  development/kyma-github-connector/githubConnector/templates/03-ghConnectorGatewayApiRule.yaml
  development/kyma-github-connector/githubConnector/templates/06-ghConnectorGatewayConfigMap.yaml
  development/kyma-github-connector/githubConnector/templates/07-ghConnectorGatewayDeployment.yaml
  development/kyma-github-connector/githubConnector/templates/13-ghConnectorSlackClientFnSubscription.yaml
  development/kyma-github-connector/githubConnector/templates/backlogRepoWebhookGatewayApiRule.yaml
  development/kyma-github-connector/githubConnector/templates/kymaRepoWebhookGatewayApiRule.yaml
  development/kyma-github-connector/githubConnector/templates/webhookGatewayConfigMap.yaml
  development/kyma-github-connector/githubConnector/templates/webhookGatewayDeployment.yaml
  development/kyma-github-connector/githubConnector/templates/webhookGatewaySecret.yaml
  development/kyma-github-connector/githubConnector/templates/webhookGatewayService.yaml
  development/kyma-github-connector/githubConnector/values.yaml
  development/kyma-github-connector/githubWebhookGateway/cmd/main.go
  development/kyma-github-connector/githubWebhookGateway/go.mod
  development/kyma-github-connector/githubWebhookGateway/go.sum
  development/kyma-github-connector/githubWebhookGateway/pkg/events/sender.go
  development/kyma-github-connector/githubWebhookGateway/pkg/gateway/types.go
  development/kyma-slack-connector/issueLabeledFunction/README.md
  development/kyma-slack-connector/issueLabeledFunction/handler.py
  development/kyma-slack-connector/issueLabeledFunction/requirements.txt
  development/kyma-slack-connector/slackConnector/.helmignore
  development/kyma-slack-connector/slackConnector/Chart.yaml
  development/kyma-slack-connector/slackConnector/README.md
  development/kyma-slack-connector/slackConnector/ghConnectorEvent.json
  development/kyma-slack-connector/slackConnector/prod_values.yaml
  development/kyma-slack-connector/slackConnector/templates/01-ghConnectorSlackBotTokenSecret.yaml
  development/kyma-slack-connector/slackConnector/templates/02-ghConnectorSlackApplicationMapping.yaml
  development/kyma-slack-connector/slackConnector/templates/06-ghConnectorGatewayConfigMap.yaml
  development/kyma-slack-connector/slackConnector/templates/08-ghConnectorSlackClientFunctionGitRepo.yaml
  development/kyma-slack-connector/slackConnector/templates/10-ghConnectorSlackServiceInstance.yaml
  development/kyma-slack-connector/slackConnector/templates/11-ghConnectorServiceBinding.yaml
  development/kyma-slack-connector/slackConnector/templates/12-ghConnectorSlackClientBindingUsage.yaml
  development/kyma-slack-connector/slackConnector/templates/13-ghConnectorSlackClientFnSubscription.yaml
  development/kyma-slack-connector/slackConnector/templates/14-ghConnectorSlackClientFunction.yaml
  development/kyma-slack-connector/slackConnector/values.yaml
Labels: enhancement, area/ci, size/XXL, lgtm

#4050 CLI k3d: fix k3d provisioning
  prow/scripts/provision-vm-cli.sh
Labels: size/XS, lgtm

#4052 Revert "Add new template mappings for compass tests"
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#4037 Rendertemplates: update documentation
  development/tools/cmd/rendertemplates/README.md
  templates/README.md
Labels: size/M, lgtm

#4054 Upgrade Cypress to 8.3.0 version
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4051 Remove kazydek from CODEOWNERS
  CODEOWNERS
Labels: area/community, area/documentation, size/XS, lgtm

#4055 Upgrade Cypress to 8.3.0 version
  development/custom-image/install-deps-debian.sh
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
Labels: size/XS, lgtm

#4045 Prow: update secrets population
  development/prow-installer/config/prow-installer-config.yaml
  development/tools/cmd/secretspopulator/README.md
  development/tools/cmd/secretspopulator/automock/decryptor.go
  development/tools/cmd/secretspopulator/automock/storage_reader.go
  development/tools/cmd/secretspopulator/main.go
  development/tools/cmd/secretspopulator/main_test.go
  docs/prow/obligatory-security-measures.md
  docs/prow/production-cluster-configuration.md
  docs/prow/prow-installation-on-forks.md
  prow/cluster/README.md
  prow/cluster/required-secrets.yaml
  prow/scripts/assetstore-gcp-bucket-cleaner.sh
  prow/scripts/install-prow.sh
  prow/set-up-workload-cluster.sh
  prow/workload-cluster/README.md
  prow/workload-cluster/required-secrets.yaml
Labels: size/XL, lgtm

#4022 Configure subaccountid for svcat migration test
  prow/config.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/jobs/kyma/skr-svcat-migration.yaml
  templates/data/skr-integration-data.yaml
  templates/data/skr-svcat-migration-data.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#4056 Add hydra-login-consent squash method to tide
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#4057 Add fluent-bit image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4059 Disable AWS gardener job
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/skr-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4062 reenable AWS jobs
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/skr-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4058 adding job for kyma-incubator/hydra-login-consent
  prow/jobs/incubator/hydra-login-consent/hydra-login-consent.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4068 Fix sequential compass installations in benchmark tests
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/XS, lgtm

#4064 Disable rapid jobs
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4066 Add GCR cleaner docs
  development/tools/cmd/gcrcleaner/README.md
Labels: size/M, lgtm

#4061 Add GCR cleaner
  development/tools/cmd/gcrcleaner/main.go
  development/tools/pkg/gcrcleaner/automock/image_api.go
  development/tools/pkg/gcrcleaner/automock/repo_api.go
  development/tools/pkg/gcrcleaner/cleaner.go
  development/tools/pkg/gcrcleaner/cleaner_test.go
  development/tools/pkg/gcrcleaner/wrappers.go
  prow/scripts/assetstore-gcp-bucket-cleaner.sh
Labels: size/XL, lgtm

#4069 Fn controller buildpack change
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  templates/config.yaml
  templates/data/generic_component_data.yaml
Labels: size/S, lgtm

#4028 Remove Dex from API-Gateway tests
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/L, lgtm

#4072 Replace dot to dash provision-vm-cli.sh labels
  prow/scripts/provision-vm-cli.sh
Labels: size/XS, lgtm

#4074 Revert "Revert "Add new template mappings for compass tests""
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#4065 Fast integration remove flag for app connectivity
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4067 Enable internal authentication between compass components
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/provision-vm-compass.sh
Labels: size/M, lgtm

#4086 Bump Go version to 1.17.0
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-golang/README.md
  prow/images/debug-commando/Dockerfile
  prow/images/prow-tools/Dockerfile
Labels: size/S, lgtm

#4089 add missing kyma major version
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#4090 Enable tenant-fetcher test authenticator
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/XS, lgtm
