Repository kyma-project/test-infra, pull requests merged in 2021-03, with the labels that each got.

#3344 Switch used MILV image to in-house version
  development/image-syncer/external-images.yaml
  prow/scripts/governance.sh
Labels: area/documentation, enhancement

#3358 Remove deprecated fields from MILV config
  milv.config.yaml
Labels: area/documentation, enhancement

#3362 remove marketplaces jobs and tests
  development/tools/jobs/incubator/marketplaces/marketplaces_test.go
  prow/jobs/incubator/marketplaces/marketplaces-governance.yaml
  prow/jobs/incubator/marketplaces/marketplaces.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: area/ci

#3363 Add conditional loading for gcloud and docker init in build-generic.sh
  prow/scripts/build-generic.sh
Labels: area/ci

#3365 Remove build.sh and related stuff
  development/tools/jobs/tester/tester.go
  prow/scripts/README.md
  prow/scripts/build.sh
Labels: area/ci

#3369 Gardener: add test jobs
  development/tools/jobs/cli/cli_integration_test.go
  prow/config.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/lib/gardener/azure.sh
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3375 Fall back to older version of transfigure image
  prow/jobs/test-infra/testgrid-automation.yaml
  templates/data/testgrid-automation-data.yaml
Labels: area/ci

#3378 Bump Alpine image to 3.13.2
  development/image-syncer/external-images.yaml
Labels: area/ci

#3379 Enable podinfo reporter
  prow/cluster/components/11-plank_deployment.yaml
  prow/cluster/components/30-crier_deployment.yaml
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3367 Enable serverless tests
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/lib/gcloud.sh
Labels: area/serverless, test-failing

#3387 Improve cli tests
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
Labels: area/serverless, test-failing

#3389 Improve cli tests of kyma functions
  prow/scripts/cli-tests/test-function.sh
Labels: area/serverless, test-failing

#3390 Gardener: remove temporary test jobs
  development/tools/jobs/cli/cli_integration_test.go
  prow/config.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/lib/gardener/azure.sh
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3391 Fix oom debug
  prow/scripts/resources/debug-container.yaml
Labels: area/ci

#3400 Set up prow jobs busola
  development/tools/jobs/busola/busola_test.go
  development/tools/jobs/busola/governance_test.go
  development/tools/jobs/tester/jobsuite/options.go
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-core-ui/busola-core-ui.yaml
  prow/jobs/busola/busola-core/busola-core.yaml
  prow/jobs/busola/busola-governance.yaml
  prow/jobs/busola/busola-service-catalog-ui/busola-service-catalog-ui.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
  templates/data/react-components-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/generic-component-busola.yaml
Labels: area/console

#3411 Governance: work with main branch
  prow/scripts/governance.sh
Labels: area/ci

#3401 Test verbose ssh output
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-start-kyma-minikube.sh
Labels: area/ci

#3416 ssh: fix verbose flag
  prow/scripts/lib/utils.sh
Labels: area/ci

#3393 Gh connector documentation
  development/github-slack-connector/README.md
  development/github-slack-connector/githubConnector/README.md
  development/github-slack-connector/githubConnector/values.yaml
  development/github-slack-connector/githubWebhookGateway/README.md
  development/github-slack-connector/issueLabeledFunction/README.md
Labels: area/ci, area/documentation

#3427 ssh: better debug
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-start-kyma-minikube.sh
Labels: area/ci

#3422 Debug container image
  prow/images/debug-commando/Dockerfile
  prow/images/debug-commando/Makefile
  prow/images/debug-commando/license-puller.sh
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci

#3431 Add nats-operator build job
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/nats-operator/nats-operator-generic.yaml
  templates/config.yaml
Labels: area/eventing

#3432 SKR: disable reporting
  prow/jobs/kyma/skr-integration.yaml
  templates/templates/skr-integration.yaml
Labels: area/ci

#3435 fix path in run_if_changed
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci

#3434 SSH: remove debug flags
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-start-kyma-minikube.sh
Labels: area/ci

#3433 Building image.
  prow/images/debug-commando/Dockerfile
Labels: area/ci

#3430 enable pubsub reporter
  prow/cluster/components/30-crier_deployment.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/templates/kyma-integration-gardener.yaml
Labels: area/ci, enhancement

#3439 SKR: enable reporting
  prow/jobs/kyma/skr-integration.yaml
  templates/templates/skr-integration.yaml
Labels: area/ci

#3438 Cleanup external-solution test related code
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-122.yaml
  prow/jobs/kyma/tests/end-to-end/external-solution-integration/external-solution-integration-tests-generic.yaml
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  templates/config.yaml
  templates/data/kyma-release-data.yaml
  templates/templates/kyma-integration.yaml
Labels: enhancement

#3448 slack reporting to dev null
  development/tools/pkg/pjtester/pjtester.go
Labels: area/ci, enhancement

#3442 Prowjobs: use templates
  development/tools/jobs/governance/addons_governance_test.go
  development/tools/jobs/governance/busola_governance_test.go
  development/tools/jobs/governance/common_governance_test.go
  development/tools/jobs/governance/community_governance_test.go
  development/tools/jobs/governance/console_governance_test.go
  development/tools/jobs/governance/examples_governance_test.go
  development/tools/jobs/governance/incubator_documentation-component_governance_test.go
  development/tools/jobs/governance/kyma_governance_test.go
  development/tools/jobs/governance/kyma_metadata_governance_test.go
  development/tools/jobs/governance/test-infra_governance_test.go
  development/tools/jobs/governance/website_governance_test.go
  development/tools/jobs/incubator/documentation-component/documentation-component_test.go
  prow/jobs/addons/addons-governance.yaml
  prow/jobs/busola/busola-governance.yaml
  prow/jobs/community/community-governance.yaml
  prow/jobs/console/console-governance.yaml
  prow/jobs/examples/examples-governance.yaml
  prow/jobs/governance.yaml
  prow/jobs/incubator/documentation-component/documentation-component-governance.yaml
  prow/jobs/kyma/kyma-governance.yaml
  prow/jobs/kyma/kyma-metadata-governance.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/test-infra-governance.yaml
  prow/jobs/website/website-governance.yaml
  templates/config.yaml
  templates/data/governance-data.yaml
  templates/data/kyma-release-data.yaml
  templates/data/test-infra-governance-data.yaml
  templates/templates/generic.tmpl
  templates/templates/whitesource-periodics.tmpl
Labels: area/ci

#3455 Governance: fix text-infra job
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: area/ci

#3477 Add protecode to third-party-images
  prow/jobs/scans/protecode-guard.yaml
  templates/data/protecode-guard-data.yaml
Labels: area/ci

#3474 Fix Prow monitoring links
  milv.config.yaml
Labels: area/documentation

#3476 Fix pjtester
  development/tools/pkg/pjtester/pjtester.go
Labels: area/ci, bug

#3480 Protecode: fix thirt-party-images job
  prow/jobs/scans/protecode-guard.yaml
  templates/data/protecode-guard-data.yaml
Labels: area/ci

#3481 better log message
  development/tools/pkg/pjtester/pjtester.go
Labels: area/ci, bug

#3459 Prowjobs: use templates
  development/tools/jobs/addons/addons_test.go
  development/tools/jobs/incubator/dex/dex_test.go
  development/tools/jobs/kyma/kyma_release_pr_image_guard_test.go
  prow/jobs/addons/addons.yaml
  prow/jobs/cli/cli-compatibility.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/incubator/dex/dex.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
  prow/jobs/kyma/releases/kyma-release-122.yaml
  prow/jobs/scans/protecode-guard.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/unstale-gardener-project.yaml
  prow/scripts/build-addons.sh
  templates/config.yaml
  templates/data/addons-data.yaml
  templates/data/cli-data.yaml
  templates/data/incubator-dex-data.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
  templates/data/kyma-release-image-guard-data.yaml
  templates/templates/generic.tmpl
Labels: area/ci

#3483 search for oom events by default
  prow/scripts/lib/utils.sh
Labels: area/ci, bug

#3479 Main branch: rename for website, community and examples repos
  development/tools/jobs/governance/community_governance_test.go
  development/tools/jobs/governance/examples_governance_test.go
  development/tools/jobs/governance/website_governance_test.go
  prow/jobs/governance.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/governance-data.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci

#3461 Prowjobs: use templates for control-plane, compass and rafter
  development/tools/jobs/control-plane/control_plane_gke_integration_test.go
  development/tools/jobs/control-plane/control_plane_gke_provisioner_integration_test.go
  development/tools/jobs/incubator/compass/development_artifacts_test.go
  development/tools/jobs/rafter/rafter_test.go
  prow/config.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/control-plane/control-plane-integration.yaml
  prow/jobs/control-plane/kcp-cli.yaml
  prow/jobs/control-plane/kcp-development-artifacts.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-whitesource.yaml
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/rafter/rafter.yaml
  prow/jobs/scans/protecode-guard.yaml
  templates/data/compass-development-artifacts-data.yaml
  templates/data/control-plane-integration-data.yaml
  templates/data/control-plane-kcp-data.yaml
  templates/data/control-plane-whitesource.yaml
  templates/data/rafter-data.yaml
  templates/templates/generic.tmpl
  templates/templates/prow-config.yaml
Labels: area/ci

#3490 branchprotector: check if template was rendered
  prow/jobs/test-infra/validation.yaml
  templates/data/validation-data.yaml
Labels: area/ci

#3491 Language: remove whitelist from the code
  development/image-guard/README.md
  development/test-log-collector/Dockerfile
  development/tools/cmd/clusterscollector/README.md
  development/tools/cmd/clusterscollector/main.go
  development/tools/pkg/clusterscollector/collector.go
  prow/images/prow-tools/Dockerfile
Labels: area/ci, area/documentation

#3494 Add jobguard to prow-tools run_if_changed
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci
