Repository kyma-project/test-infra, pull requests merged in 2021-05, with the labels that each got.

#3594 Change master to main (leftovers)
  development/tools/cmd/rendertemplates/README.md
  docs/prow/manage-component-jobs-with-templates.md
  docs/prow/presets.md
  docs/prow/prow-jobs.md
Labels: lgtm, size/S

#3609 Enable pubsub reporter
  prow/cluster/components/crier_deployment.yaml
Labels: area/ci, lgtm, size/XS

#3610 Missing service account and rbac for pjtester on new prow
  prow/cluster/components/pjtester_prowjob-scheduler_rbac.yaml
Labels: area/ci, lgtm, size/M

#3613 Presets: change master to main
  development/tools/jobs/rafter/rafter_test.go
  development/tools/jobs/tester/preset/preset.go
  prow/config.yaml
  prow/jobs/addons/addons.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/control-plane/control-plane-integration.yaml
  prow/jobs/control-plane/kcp-cli.yaml
  prow/jobs/control-plane/kcp-development-artifacts.yaml
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/incubator/dex/dex.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-120.yaml
  prow/jobs/kyma/releases/kyma-release-121.yaml
  prow/jobs/kyma/releases/kyma-release-122.yaml
  prow/jobs/kyma/releases/kyma-release-123.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/jobs/rafter/rafter.yaml
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/build-kcp-development-artifacts.sh
  templates/data/addons-data.yaml
  templates/data/cli-data.yaml
  templates/data/compass-development-artifacts-data.yaml
  templates/data/compass-gke-integration-data.yaml
  templates/data/compass-integration-data.yaml
  templates/data/control-plane-integration-data.yaml
  templates/data/control-plane-kcp-data.yaml
  templates/data/incubator-dex-data.yaml
  templates/data/kyma-gke-external-registry-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/kyma-release-data.yaml
  templates/data/rafter-data.yaml
  templates/data/skr-integration-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/L

#3611 Disable debug-commando builds.
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci, lgtm, size/M

#3608 Central Application Connectivity Validator job added
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  templates/config.yaml
Labels: lgtm, size/M

#3614 Bump sb-proxy-k8s image
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3616 Remove link to non-existing resource
  docs/prow/crier.md
Labels: area/documentation, lgtm, size/XS

#3597 Run pre and post Kyma upgrade tests in Gardener upgrade script
  prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
Labels: lgtm, size/M

#3619 Bump alpine image to 3.13.5
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3620 Busola Kyma: fix jobs
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm, size/L

#3598 Pubsub to slack
  development/github-slack-connector/githubConnector/ghConnectorSlackAPI.json
  development/pubsub-connector/oomFoundFunction/handler.py
  development/pubsub-connector/oomFoundFunction/requirements.txt
  development/pubsub-connector/pubSubGateway/Dockerfile
  development/pubsub-connector/pubSubGateway/Makefile
  development/pubsub-connector/pubSubGateway/before-commit.sh
  development/pubsub-connector/pubSubGateway/cmd/main.go
  development/pubsub-connector/pubSubGateway/go.mod
  development/pubsub-connector/pubsubConnector/.helmignore
  development/pubsub-connector/pubsubConnector/Chart.yaml
  development/pubsub-connector/pubsubConnector/pubsubConnectorEvent.json
  development/pubsub-connector/pubsubConnector/pubsubConnectorEventAsyncSpec.json
  development/pubsub-connector/pubsubConnector/templates/01-pubsubConnectorSlackBotTokenSecret.yaml
  development/pubsub-connector/pubsubConnector/templates/02-pubsubConnectorSlackApplicationMapping.yaml
  development/pubsub-connector/pubsubConnector/templates/06-pubsubConnectorGatewayConfigMap.yaml
  development/pubsub-connector/pubsubConnector/templates/07-pubsubConnectorGatewayDeployment.yaml
  development/pubsub-connector/pubsubConnector/templates/08-pubsubConnectorSlackClientFunctionGitRepo.yaml
  development/pubsub-connector/pubsubConnector/templates/10-pubsubConnectorSlackServiceInstance.yaml
  development/pubsub-connector/pubsubConnector/templates/11-pubsubConnectorServiceBinding.yaml
  development/pubsub-connector/pubsubConnector/templates/12-pubsubConnectorSlackClientSvcBindingUsage.yaml
  development/pubsub-connector/pubsubConnector/templates/13-pubsubConnectorSlackClientFnSubscription.yaml
  development/pubsub-connector/pubsubConnector/templates/14-pubsubConnectorSlackClientFunction.yaml
  development/pubsub-connector/pubsubConnector/values.yaml
  prow/jobs/test-infra/oom-tester.yaml
  prow/scripts/resources/debug-container.yaml
Labels: area/ci, lgtm, size/XL

#3623 build_pubsub_gateway
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci, enhancement, lgtm, size/M

#3625 Define free aws skr fast int test
  prow/config.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/M

#3630 Images for istio 1.9.5
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3631 Add "Cypress" to image-syncer for Busola
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3633 Remove branchprotector-config.yaml
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/branchprotector-config.yaml
  prow/config.yaml
  templates/config.yaml
  templates/templates/branchprotector-config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/L

#3636 Bump ory components version in external-images.yaml
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3628 Bump sb-proxy image to latest version
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3637 Scripts: fix gcloud
  prow/scripts/lib/gcloud.sh
Labels: lgtm, size/XS

#3642 Scripts: fiz Azure lib
  prow/scripts/lib/azure.sh
  prow/scripts/lib/testing-helpers.sh
Labels: lgtm, size/XS

#3617 Busola UI tests
  prow/jobs/busola/ui-test.yaml
  prow/scripts/cluster-integration/busola-ui-tests-k3s.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  templates/data/busola-ui-test-data.yaml
Labels: lgtm, size/L

#3632 Remove minio pre/post/release tests
  development/tools/go.mod
  development/tools/go.sum
  development/tools/jobs/rafter/rafter_test.go
  prow/config.yaml
  prow/jobs/rafter/rafter.yaml
  templates/data/rafter-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/XXL

#3644 Oom fund env fix
  development/pubsub-connector/oomFoundFunction/handler.py
  development/pubsub-connector/pubsubConnector/templates/06-pubsubConnectorGatewayConfigMap.yaml
  development/pubsub-connector/pubsubConnector/templates/14-pubsubConnectorSlackClientFunction.yaml
  development/pubsub-connector/pubsubConnector/values.yaml
Labels: area/ci, lgtm, size/S

#3638 Update probot-stale chart for new deployment on new cluster
  prow/cluster/resources/probot-stale/templates/_helpers.tpl
  prow/cluster/resources/probot-stale/templates/deployment.yaml
  prow/cluster/resources/probot-stale/templates/frontendconfig.yaml
  prow/cluster/resources/probot-stale/templates/ingress.yaml
  prow/cluster/resources/probot-stale/templates/managedcert.yaml
  prow/cluster/resources/probot-stale/templates/service.yaml
  prow/cluster/resources/probot-stale/values.yaml
Labels: lgtm, size/M

#3641 Update old kyma components that should be removed
  prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
Labels: lgtm, size/XS

#3648 Values for open source Kyma stalebot.
  prow/cluster/resources/probot-stale/templates/deployment.yaml
  prow/cluster/resources/probot-stale/values-oss.yaml
Labels: lgtm, size/M

#3649 fix variable name
  development/pubsub-connector/oomFoundFunction/handler.py
Labels: area/ci, lgtm, size/XS

#3652 Update codeowners
  CODEOWNERS
Labels: area/community, lgtm, size/XS

#3653 Adapt CLI integration test to k3s
  prow/jobs/cli/cli-integration.yaml
  prow/scripts/provision-vm-cli.sh
  templates/data/cli-data.yaml
Labels: lgtm, size/M

#3650 Ack when no oom
  development/gcp/cloud-functions/checkoomevent/checkoomevent.go
  development/gcp/cloud-functions/checkoomevent/go.mod
  development/pubsub-connector/pubsubConnector/templates/13-pubsubConnectorSlackClientFnSubscription.yaml
Labels: area/ci, lgtm, size/L

#3655 Add etcd external image pipeline
  development/tools/jobs/third-party-images/etcd_test.go
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: lgtm, size/L

#3657 Fix batch
  development/gcp/cloud-functions/checkoomevent/checkoomevent.go
  development/pubsub-connector/oomFoundFunction/handler.py
Labels: area/ci, lgtm, size/L

#3661 Update vm-cleaner regexp
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/XS

#3659 Log message ID in kyma function
  development/pubsub-connector/oomFoundFunction/handler.py
  development/pubsub-connector/pubsubConnector/values.yaml
Labels: area/ci, lgtm, size/S

#3669 Add benchmark utilities to kyma-integration docker image
  prow/images/kyma-integration/Dockerfile
Labels: lgtm, size/XS

#3670 add nats server and exporter images
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3663 Move more projects into one go module
  development/prowjobparser/go.mod
  development/prowjobparser/go.sum
  development/prowjobparser/main.go
  go.mod
  stability-checker/go.mod
  stability-checker/go.sum
  stability-checker/internal/log/logfetcher.go
  stability-checker/internal/notifier/dep.go
  stability-checker/internal/notifier/notifier.go
  stability-checker/internal/runner/dep.go
  stability-checker/internal/runner/runner.go
Labels: lgtm, size/XXL

#3643 Add Github issues to BigQuery application
  development/tools/cmd/githubissues/README.md
  development/tools/cmd/githubissues/main.go
  development/tools/cmd/githubissues/table_org_schema.json
  development/tools/cmd/githubissues/table_repo_schema.json
  go.mod
  go.sum
  prow/config.yaml
  prow/scripts/github-issues.sh
  templates/templates/prow-config.yaml
Labels: lgtm, size/XXL

#3672 Make pre compass integration pipeline optional
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/XS

#3671 GitHub issues to bigquery: add prowjob
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/github-issues.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/M

#3673 add nats 2.1.9 and 2.2.4 for testing purpose
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3677 Github issues: fix script permissions
  prow/scripts/github-issues.sh
Labels: lgtm, size/XS

#3678 FIx jobguard contexts error in release-1.21
  development/jobguard/scripts/run.sh
Labels: lgtm, size/XS

#3675 remove knative-kafka-whitesource scan
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: lgtm, size/M

#3674 New prow docs after upgrade
  docs/prow/crier.md
  docs/prow/prow-architecture.md
  docs/prow/prow-monitoring.md
Labels: area/documentation, lgtm, size/L

#3684 Dissable benchmark job on hotfix
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  templates/data/compass-gke-benchmark-data.yaml
Labels: lgtm, size/XS

#3685 Remove alpine-kubectl image and tests
  development/tools/jobs/testinfra/buildpack_test.go
  prow/images/alpine-kubectl/Makefile
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: lgtm, size/L

#3681 Busola tests artifacts
  development/image-syncer/external-images.yaml
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: lgtm, size/XS

#3687 Remove alpine-kubectl image
  prow/images/alpine-kubectl/Dockerfile
  prow/images/alpine-kubectl/Makefile
  prow/images/alpine-kubectl/README.md
Labels: lgtm, size/M

#3686 Busola tests artifacts fix
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: lgtm, size/XS

#3689 bump golang alpine
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3692 Make k3s-compass job mandatory
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/XS

#3696 Increase timeout for protecode guard
  prow/scripts/cluster-integration/protecode-guard.sh
Labels: lgtm, size/XS

#3694 KEB Resolve user (email) of the runtime creator
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/XS

#3698 Fix compass performance tests script
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: lgtm, size/XS

#3656 Add Serverless integration tests for kyma 2.0 on k3s
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/L

#3690 Ensure Compass VM job uses data dump
  prow/scripts/provision-vm-compass.sh
Labels: lgtm, size/XS

#3700 Make compass performance tests optional
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  templates/data/compass-gke-benchmark-data.yaml
Labels: lgtm, size/XS

#3702 update pubsub-connector and github-connector paths
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci, lgtm, size/M

#3704 remove not needed case condition
  development/kyma-github-connector/githubWebhookGateway/pkg/httperrors/httperrors.go
Labels: area/ci, lgtm, size/XS

#3706 Execute benchmarks on a specific node
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: lgtm, size/XS

#3708 Run serverless integration tests only when serverless is changed
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  templates/data/kyma-integration-data.yaml
Labels: lgtm, size/S

#3709 Omit benchmarks on integration tests
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: lgtm, size/XS

#3705 switch to main branch
  development/kyma-github-connector/githubConnector/values.yaml
  development/kyma-pubsub-connector/pubsubConnector/values.yaml
Labels: area/ci, lgtm, size/S

#3664 oom notification system docs
  development/gcp/cloud-functions/checkoomevent/checkoomevent.go
  development/kyma-pubsub-connector/README.md
  development/kyma-pubsub-connector/oomFoundFunction/README.md
  development/kyma-pubsub-connector/pubSubGateway/README.md
  development/kyma-pubsub-connector/pubsubConnector/README.md
  development/tools/cmd/oomfinder/README.md
  development/tools/cmd/oomfinder/main.go
  docs/prow/README.md
  prow/scripts/resources/README.md
Labels: area/ci, area/documentation, lgtm, size/L

#3711 Execute benchmark tests on a dedicated node
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: lgtm, size/S

#3612 Grafana: add quality dashboard
  prow/cluster/components/monitoring/dashboards/Makefile
  prow/cluster/components/monitoring/dashboards/quality/quality.json
  prow/cluster/components/monitoring/dashboards/quality/test_coverage.json
  prow/cluster/components/monitoring/grafana_configmaps.yaml
  prow/cluster/components/monitoring/grafana_deployment.yaml
Labels: lgtm, size/XXL
