Repository kyma-project/test-infra, pull requests merged in 2021-09, with the labels that each got.

#4091 GKE long lasting: disable stability checker
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/S, lgtm

#4084 Bump kubectl to v1.18 and helm to v3.6.2 in kyma-integration
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
Labels: size/S, lgtm

#4088 edit svcat prow job to be run on aws instead of azure
  prow/jobs/kyma/skr-svcat-migration.yaml
  templates/data/skr-svcat-migration-data.yaml
Labels: size/S, lgtm

#4093 Fast integration: update notifications
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/S, lgtm

#4097 Add kyma major version for Busola pipelines
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#4098 Remove k8s version from tag in kyma-integration
  prow/images/kyma-integration/Makefile
Labels: size/XS, lgtm

#4100 Bump kyma-integration image
  development/tools/jobs/tester/tester.go
  prow/jobs/busola/busola-backend/backend-deployment-check.yaml
  prow/jobs/busola/busola-web/web-deployment-check.yaml
  prow/jobs/busola/integration-test.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/jobs/kyma/skr-svcat-migration.yaml
  prow/jobs/scans/protecode-guard.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  prow/jobs/test-infra/unstale-gardener-project.yaml
  templates/config.yaml
Labels: size/L, lgtm

#4101 Make pre-main-kyma-integration-k3d-compass-dev optional
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4099 Add GCR cleaner job
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/M, lgtm

#4102 Update Prometheus Alertmanager to Version 0.23.0
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4103 GCR cleaner: allow for empty exclude expression
  development/tools/pkg/gcrcleaner/cleaner.go
  development/tools/pkg/gcrcleaner/cleaner_test.go
Labels: size/S, lgtm

#4105 GCR cleaner: remove excludes
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4106 Go: update go get to install
  development/image-syncer/before-commit.sh
  development/kyma-ci-force-bot/ciforcebot/before-commit.sh
  development/kyma-github-connector/githubWebhookGateway/before-commit.sh
  development/kyma-pubsub-connector/pubSubGateway/before-commit.sh
  development/prowjobparser/before-commit.sh
  development/tools/before-commit.sh
  prow/images/buildpack-golang/Dockerfile
  prow/images/debug-commando/Dockerfile
  prow/images/kyma-integration/Dockerfile
  stability-checker/before-commit.sh
  watch-pods/before-commit.sh
Labels: size/M, lgtm

#4108 Fix Kyma installation for Compass resources
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#3667 Busola: remove Kyma nightly
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/S, lgtm

#4111 Workaround for new kubectl version
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: size/XS, lgtm

#4113 Add KMS key to jobs
  prow/jobs/helm-broker/helm-broker.yaml
  prow/jobs/incubator/dex/dex.yaml
  templates/data/helm-broker-data.yaml
  templates/data/incubator-dex-data.yaml
Labels: size/XS, lgtm

#4112 Make Busola test run on makefile change
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  templates/data/generic_component_busola_data.yaml
Labels: size/S, lgtm

#4114 Removal of Unused Pipeline
  development/tools/jobs/control-plane/components_test.go
  prow/jobs/control-plane/components/provider-config-migration-job/provider-config-migration-job-generic.yaml
  templates/data/generic_component_control_plane_data.yaml
Labels: size/L, lgtm

#4110 add basic prow job for kyma-preview
  prow/jobs/kyma/kyma-preview.yaml
  templates/data/kyma-preview-data.yaml
Labels: size/L, lgtm

#4118 1686 change preview plan to test skr
  prow/jobs/kyma/kyma-preview.yaml
  templates/data/kyma-preview-data.yaml
Labels: size/XS, lgtm

#4120 Workaround for new kubectl version
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
Labels: size/S, lgtm

#4078 Rename master branch to main for compass jobs
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#4124 Fix podpreset jobs
  prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#4071 Reconciler test job
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4121 Add KMS key to jobs
  prow/jobs/rafter/rafter.yaml
  templates/data/rafter-data.yaml
Labels: size/XS, lgtm

#4131 Make e2e job for reconciler optional
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#4011 modify cluster-user test jobs to run on kyma2
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/cluster-users-integration-k3d.sh
  prow/scripts/provision-vm-and-start-cluster-users-k3d.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4132 Fix kyma-showcase spelling
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#4130 Add jobs for Kyma-Showcase
  prow/jobs/incubator/kyma-showcase/kyma-showcase.yaml
  templates/data/kyma-showcase-data.yaml
Labels: size/L, lgtm

#4109 Reconciler periodic upgrade test job
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-upgrade-gardener.sh
  templates/config.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4136 adjust varkes release process
  development/tools/jobs/incubator/varkes/varkes_test.go
  prow/jobs/incubator/varkes/varkes.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/S, lgtm

#4139 Better quality dashboard results representation
  prow/cluster/components/monitoring/dashboards/quality/quality.json
Labels: size/XS, lgtm

#4140 Silence reconciler periodic e2e job until it is stable
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#4123 move 1.24-only jobs to kyma-release124.yaml
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-124.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/XXL, lgtm

#4141 move gke-upgrade jobs from main to rel124
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-124.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4143 Fix nigthly jobs
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-124.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/S, lgtm

#4146 Update cleaner regex
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/S, lgtm

#4149 Fix long-lasting jobs
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/XS, lgtm

#4150 Fix long-lasting jobs
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/XS, lgtm

#4142 Add build jobs and test for third-party-images/kaniko_executer
  development/tools/jobs/third-party-images/kaniko_executer_test.go
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: size/L, lgtm

#4151 Bump istio 1.11.1 -> 1.11.2
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4153 Disable fast integration tests on long lasting clusters
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4144 Fix fast integration tests with central app gateway failing
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: bug, area/application-connector, size/L, lgtm

#4155 change kyma-preview prow job to execute every four hours
  prow/jobs/kyma/kyma-preview.yaml
  templates/data/kyma-preview-data.yaml
Labels: size/XS, lgtm

#4159 Disable kyma-whitesource-scan
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/M, lgtm

#4162 add spectral tool
  prow/images/bootstrap/Dockerfile
Labels: size/XS, lgtm

#4161 bump alpine to 3.14.2
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4158 Call eventing fast-integration on release
  prow/jobs/kyma/releases/kyma-release-124.yaml
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
Labels: size/S, lgtm

#4164 Re-enable nightly to fix sec scans
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4137 Add hotfix branch for Compass components
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/L, lgtm

#4169 Fix docker MTU
  prow/scripts/lib/docker.sh
Labels: size/XS, lgtm

#4167 remove pre-main-kyma-gke-external-registry
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  templates/data/kyma-gke-external-registry-data.yaml
Labels: size/M, lgtm

#4157 Fix whitesource scan for podpreset project
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/XS, lgtm

#4170 bumping postgres to 11.13-alpine
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4173 changing postgres tag to sha256
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4175 Update Kyma installation method
  prow/scripts/cluster-integration/helpers/integration-tests.sh
Labels: size/XS, lgtm

#4171 Pass domain to components in e2e-test
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm

#4174 Add benchstat to buildpack-golang
  prow/images/buildpack-golang/Dockerfile
Labels: size/XS, lgtm

#4177 Add kcp-tech-user secret
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#4160 Add reconciler nightly job for cluster
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
  prow/scripts/lib/gardener/gardener.sh
  prow/scripts/resources/reconciler/shoot-template.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4178 Fixed bug for reconciler periodic job
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm

#4181 Fix docker mtu
  prow/scripts/lib/docker.sh
Labels: size/XS, lgtm

#4180 Reenable fast-integration tests on nightly
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4182 add kcp-cli to kyma integration image
  prow/images/kyma-integration/Dockerfile
Labels: size/S, lgtm

#4183 add commit id to kcpcli version
  prow/images/kyma-integration/Dockerfile
Labels: size/XS, lgtm

#4186 Temporarily make compass jobs optional
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4189 fix compass-gke-benchmark jobs
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  templates/data/compass-gke-benchmark-data.yaml
Labels: size/S, lgtm

#4166 added back pre-main-kyma-gardener-gcp-eventing with kyma deploy
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4172 Run eventing fast-integration on release
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  templates/data/kyma-release-data.yaml
Labels: size/M, lgtm

#4191 Fast-integration: use Kyma 2 tests
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4194 Made pre-main-kyma-gardener-gcp-eventing job optional
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#4198 Exclude rec-nightly cluster from deletion
  development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
Labels: size/XS, lgtm

#4196 Bump sb-proxy-k8s to v0.9.1
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4199 Fine tune cluster size for reconciler nightly job
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#4207 Upgrade Cypress to 8.5.0 version
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4206 Disable istio sidecar injection for reconciler ns
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
Labels: size/XS, lgtm

#4208 Upgrade Cypress to 8.5.0 version
  development/custom-image/install-deps-debian.sh
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
Labels: size/XS, lgtm

#4209 Rename cli integration pipelines
  development/tools/jobs/cli/cli_integration_test.go
  prow/jobs/cli/cli-integration.yaml
  prow/scripts/provision-vm-cli.sh
  templates/data/cli-data.yaml
Labels: size/M, lgtm

#4200 Create reconciler integration job
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/reconciler-integration-k3d.sh
  prow/scripts/provision-vm-and-start-reconciler-k3d.sh
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm
