Repository kyma-project/test-infra, pull requests merged in 2021-04, with the labels that each got.

#3488 Enable for kyma-cli-alpha-uninstall-gke
  prow/jobs/cli/cli-integration.yaml
  templates/data/cli-data.yaml
Labels: area/ci

#3493 Main branch: rename control-plane main branch
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci

#3500 Gardener cleanup: add option to exclude clusters
  development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
  templates/data/kyma-gardener-cleanup-data.yaml
Labels: area/ci

#3501 Inclusive lg changes
  .github/pull-request-template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  development/tools/cmd/pjtester/README.md
  development/tools/cmd/rendertemplates/README.md
  docs/prow/crier.md
  docs/prow/prow-architecture.md
  docs/prow/prow-installation-on-forks.md
  docs/prow/prow-jobs.md
  docs/prow/prow-k8s-testgrid.md
  docs/prow/prow-secrets.md
  docs/prow/quality-metrics.md
  docs/prow/workload-clusters.md
  prow/README.md
  prow/scripts/README.md
  prow/scripts/cluster-integration/README.md
  stability-checker/README.md
  templates/README.md
  watch-pods/README.md
Labels: area/documentation

#3482 New JobGuard application code
  development/jobguard/README.md
  development/jobguard/cmd/jobguard/main.go
  development/jobguard/go.mod
  development/jobguard/go.sum
  development/jobguard/pkg/jobguard/v2/jobguard.go
  development/jobguard/pkg/jobguard/v2/status.go
  development/jobguard/scripts/run.sh
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3495 Third-party-images: move to kyma-project
  development/tools/jobs/tester/preset/preset.go
  development/tools/jobs/third-party-images/cloudsql_proxy_test.go
  development/tools/jobs/third-party-images/docker_registry_test.go
  development/tools/jobs/third-party-images/fluent_bit_test.go
  development/tools/jobs/third-party-images/grafana_test.go
  development/tools/jobs/third-party-images/jaeger_operator_test.go
  development/tools/jobs/third-party-images/kiali_test.go
  development/tools/jobs/third-party-images/kiwigrid_sidecar_test.go
  development/tools/jobs/third-party-images/minio_mc_test.go
  development/tools/jobs/third-party-images/minio_test.go
  development/tools/jobs/third-party-images/prometheus_node_exporter_test.go
  prow/config.yaml
  prow/jobs/scans/protecode-guard.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/incubator-third-party-images-data.yaml
  templates/data/protecode-guard-data.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3504 TPI: rename main branch
  development/tools/jobs/third-party-images/cloudsql_proxy_test.go
  development/tools/jobs/third-party-images/docker_registry_test.go
  development/tools/jobs/third-party-images/fluent_bit_test.go
  development/tools/jobs/third-party-images/grafana_test.go
  development/tools/jobs/third-party-images/jaeger_operator_test.go
  development/tools/jobs/third-party-images/kiali_test.go
  development/tools/jobs/third-party-images/kiwigrid_sidecar_test.go
  development/tools/jobs/third-party-images/minio_mc_test.go
  development/tools/jobs/third-party-images/minio_test.go
  development/tools/jobs/third-party-images/prometheus_node_exporter_test.go
  templates/data/third-party-images-data.yaml
Labels: area/ci

#3507 Correct headings
  docs/prow/workload-clusters.md
Labels: area/documentation

#3510 third-party-images: rename ci-master to ci-main
  development/tools/jobs/third-party-images/cloudsql_proxy_test.go
  development/tools/jobs/third-party-images/docker_registry_test.go
  development/tools/jobs/third-party-images/fluent_bit_test.go
  development/tools/jobs/third-party-images/grafana_test.go
  development/tools/jobs/third-party-images/jaeger_operator_test.go
  development/tools/jobs/third-party-images/kiali_test.go
  development/tools/jobs/third-party-images/kiwigrid_sidecar_test.go
  development/tools/jobs/third-party-images/minio_mc_test.go
  development/tools/jobs/third-party-images/minio_test.go
  development/tools/jobs/third-party-images/prometheus_node_exporter_test.go
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: area/ci

#3514 Templates: fix cli-integration pre jobs
  prow/jobs/cli/cli-integration.yaml
  templates/data/cli-data.yaml
Labels: area/ci

#3515 set skr pipelines to run once a day
  prow/jobs/kyma/skr-integration.yaml
  templates/templates/skr-integration.yaml
Labels: test-failing

#3502 Add busola-migrator build jobs
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/busola-migrator/busola-migrator-generic.yaml
  templates/config.yaml
Labels: area/console, area/security, enhancement

#3517 Make busola-migrator job optional
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/busola-migrator/busola-migrator-generic.yaml
  templates/config.yaml
Labels: area/console, area/security, enhancement

#3519 Remove Python third party image jobs
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: area/serverless, enhancement

#3525 suppress k3s integration with compass
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci, test-failing

#3524 Monitoring yamls
  prow/staging/cluster/crier_deployment.yaml
  prow/staging/cluster/deck_deployment.yaml
  prow/staging/cluster/ghproxy.yaml
  prow/staging/cluster/hook_deployment.yaml
  prow/staging/cluster/horologium_deployment.yaml
  prow/staging/cluster/monitoring/dashboards/Makefile
  prow/staging/cluster/monitoring/dashboards/jsonnet/deck.jsonnet
  prow/staging/cluster/monitoring/dashboards/jsonnet/ghproxy.jsonnet
  prow/staging/cluster/monitoring/dashboards/jsonnet/hook.jsonnet
  prow/staging/cluster/monitoring/dashboards/jsonnet/plank.jsonnet
  prow/staging/cluster/monitoring/dashboards/jsonnet/prow.jsonnet
  prow/staging/cluster/monitoring/dashboards/jsonnet/sinker.jsonnet
  prow/staging/cluster/monitoring/dashboards/jsonnet/tide.jsonnet
  prow/staging/cluster/monitoring/dashboards/jsonnetfile.json
  prow/staging/cluster/monitoring/dashboards/jsonnetfile.lock.json
  prow/staging/cluster/monitoring/dashboards/lib/config.libsonnet
  prow/staging/cluster/monitoring/dashboards/lib/config_util.libsonnet
  prow/staging/cluster/monitoring/grafana_configmaps.yaml
  prow/staging/cluster/monitoring/grafana_deployment.yaml
  prow/staging/cluster/monitoring/grafana_expose.yaml
  prow/staging/cluster/monitoring/grafana_rbac.yaml
  prow/staging/cluster/monitoring/grafana_secret.yaml
  prow/staging/cluster/monitoring/monitoring-kyma-prow_managedcertificate.yaml
  prow/staging/cluster/monitoring/prometheus_expose.yaml
  prow/staging/cluster/monitoring/prometheus_operator_deployment.yaml
  prow/staging/cluster/monitoring/prometheus_operator_rbac.yaml
  prow/staging/cluster/monitoring/prometheus_rbac.yaml
  prow/staging/cluster/monitoring/prow_alertmanager.yaml
  prow/staging/cluster/monitoring/prow_monitoring_namespace.yaml
  prow/staging/cluster/monitoring/prow_prometheus.yaml
  prow/staging/cluster/monitoring/prow_servicemonitors.yaml
  prow/staging/cluster/prow_controller_manager_deployment.yaml
  prow/staging/cluster/pushgateway_deployment.yaml
  prow/staging/cluster/sinker_deployment.yaml
  prow/staging/cluster/statusreconciler_deployment.yaml
  prow/staging/cluster/tide_deployment.yaml
  prow/staging/cluster/tls-ing_ingress.yaml
  prow/staging/config.yaml
  prow/staging/jobs/test-infra-jobs.yaml
Labels: area/ci

#3505 Kyma: main branch rename
  development/tools/jobs/cli/cli_integration_test.go
  development/tools/jobs/governance/kyma_governance_test.go
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/governance.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/config.yaml
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/skr-integration.yaml
Labels: area/ci

#3527 Kyma: change artifacts bucket path to main
  prow/scripts/build-kyma-artifacts.sh
Labels: area/ci

#3450 listen for oom events from container runtime
  development/gcp/cloud-functions/checkoomevent/checkoomevent.go
  development/gcp/cloud-functions/checkoomevent/go.mod
  development/gcp/go.mod
  development/gcp/go.sum
  development/tools/cmd/oomfinder/go.mod
  development/tools/cmd/oomfinder/go.sum
  development/tools/cmd/oomfinder/main.go
  development/tools/go.sum
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/utils.sh
  prow/scripts/resources/debug-container.yaml
  templates/templates/kyma-integration-gardener.yaml
Labels: area/ci

#3534 Add alpine:3.13.4 to image-syncer
  development/image-syncer/external-images.yaml
Labels: area/security

#3530 Replace ci-master with ci-main
  development/image-syncer/Makefile
  development/prow-installer/Makefile
  development/test-log-collector/Makefile
  prow/jobs/test-infra/watch-pods/watch-pods.yaml
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/build-kcp-development-artifacts.sh
  prow/scripts/build-kyma-development-artifacts.sh
  stability-checker/Makefile
  templates/data/watch-pods-data.yaml
  watch-pods/Makefile
Labels: area/ci

#3543 Busola: fix long lasting
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
Labels: area/ci, bug

#3512 Rewrite templates to new solution
  development/tools/jobs/kyma/kyma_azure_event_hubs_namespaces_cleanup_test.go
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/kyma/kyma-azure-event-hubs-namespaces-cleanup.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/config.yaml
  templates/data/compass-integration-data.yaml
  templates/data/kyma-azure-event-hubs-namespaces-cleanup-data.yaml
  templates/data/skr-integration-data.yaml
  templates/templates/compass-integration.yaml
  templates/templates/kyma-azure-event-hubs-namespaces-cleanup.yaml
  templates/templates/skr-integration.yaml
Labels: area/ci

#3545 postsubmit kyma alpha job
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/templates/kyma-integration-gardener.yaml
Labels: area/ci, area/installation

#3549 Initial label-sync Prowjob
  prow/jobs/test-infra/prow-periodics.yaml
  prow/labels.yaml
  prow/plugins.yaml
  templates/data/prow-periodics.yaml
  templates/templates/generic.tmpl
Labels: area/ci

#3551 Certbot: remove deprecated flag
  prow/scripts/cluster-integration/helpers/generate-and-export-letsencrypt-TLS-cert.sh
  prow/scripts/lib/utils.sh
Labels: area/ci

#3552 Kyma-upgrade-gardener: use templates
  development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  templates/data/kyma-upgrade-gardener-data.yaml
Labels: area/ci

#3546 Busola: split into two jobs
  prow/config.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3556 Whitesource: fix api-gateway job
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci, bug

#3559 Busola: change cluster name
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
Labels: area/ci

#3563 Add golang 1 16 3 alpine to image syncer
  development/image-syncer/external-images.yaml
Labels: area/security

#3569 disabled hibernation
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
Labels: area/ci

#3568 We push the cronjobs some hours earlier
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/templates/kyma-integration-gardener.yaml
Labels: area/ci

#3555 Gardener-integration: use new templates
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/config.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/templates/kyma-integration-gardener.yaml
Labels: area/ci

#3554 Remove Console Backend Service tests
  prow/jobs/kyma/tests/console-backend-service/console-backend-service-tests-generic.yaml
  prow/scripts/cluster-integration/compass-gke-integration.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  templates/config.yaml
Labels: area/console

#3580 Revert "Adjust kyma-incubator/compass branch protection rules"
  prow/branchprotector-config.yaml
  templates/templates/branchprotector-config.yaml
Labels: area/ci

#3571 GKE-integration: check if cluster is compliant
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/lib/utils.sh
Labels: area/ci

#3585 Remove dead link to Event Service
  development/github-slack-connector/githubWebhookGateway/README.md
Labels: area/documentation

#3589 Tune branchprotector config
  prow/jobs/test-infra/branchprotector.yaml
  prow/plugins.yaml
  prow/workload-cluster/gce-ssd-retain_storageclass.yaml
  prow/workload-cluster/ghproxy.yaml
Labels: lgtm, size/L

#3590 Split queries to two orgs
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/S

#3586 Fix bug
  prow/scripts/lib/kyma.sh
Labels: lgtm, size/XS

#3591 Add allow_disabled_policies to compass repo
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/XS

#3540 Create pipeline testing upgrade from Kyma 1.x to Kyma 2.0
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: lgtm

#3592 Disable `--fail-on-no-contexts` flag in jobguard
  development/jobguard/scripts/run.sh
Labels: lgtm, size/XS

#3570 Add periodic for busola
  prow/config.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/kyma.sh
  templates/data/kyma-integration-gardener-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/L

#3574 templates: cleanup
  development/tools/cmd/rendertemplates/README.md
  prow/config.yaml
  templates/data/addons-data.yaml
  templates/data/buildpack-data.yaml
  templates/data/cli-data.yaml
  templates/data/compass-development-artifacts-data.yaml
  templates/data/compass-integration-data.yaml
  templates/data/control-plane-integration-data.yaml
  templates/data/control-plane-kcp-data.yaml
  templates/data/control-plane-whitesource.yaml
  templates/data/governance-data.yaml
  templates/data/incubator-dex-data.yaml
  templates/data/kyma-azure-event-hubs-namespaces-cleanup-data.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/kyma-release-image-guard-data.yaml
  templates/data/kyma-upgrade-gardener-data.yaml
  templates/data/rafter-data.yaml
  templates/data/skr-integration-data.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, lgtm, size/XXL

#3548 Templates: rewrite
  development/tools/jobs/kyma/kyma_artifacts_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
  templates/data/compass-gke-integration-data.yaml
  templates/data/kyma-artifacts-data.yaml
  templates/data/kyma-gke-external-registry-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-artifacts.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, lgtm, size/XXL

#3593 Add allow_disabled_policies to root level of branch protection
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/XS

#3595 Use `gcr.io/k8s-prow/checkconfig:v20210407-51f95c2d52` for checking Prow config files.
  development/tools/jobs/testinfra/validate_test.go
  prow/jobs/test-infra/validation.yaml
  templates/data/validation-data.yaml
Labels: lgtm, size/S

#3599 FIx jobguard contexts error in release-1.22
  development/jobguard/scripts/run.sh
Labels: lgtm, size/XS

#3600 Fix pre-main-kyma-integration-k3s job
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: area/ci, bug, lgtm, size/XS

#3601 Remove remove release branch protection config from kyma
  prow/config.yaml
  prow/jobs/test-infra/branchprotector.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/M

#3602 Bump SC image
  development/image-syncer/external-images.yaml
Labels: lgtm, size/XS

#3596 Remove job for metris
  development/tools/jobs/control-plane/components_test.go
  templates/config.yaml
Labels: lgtm, size/XS

#3603 Ensure jobguard works on PR commit
  development/jobguard/scripts/run.sh
Labels: lgtm, size/XS

#3605 Disable batch merging for kyma repository
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/XS

#3606 Prow configuration updates and fixes
  prow/cluster/components/crier_deployment.yaml
  prow/cluster/components/deck_deployment.yaml
  prow/config.yaml
  prow/jobs/test-infra/testgrid-automation.yaml
  prow/labels.yaml
  prow/plugins.yaml
  templates/data/testgrid-automation-data.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/S

#3607 Fix typo in labels.yaml
  prow/labels.yaml
Labels: lgtm, size/XS

#3604 Remove metris completely
  development/tools/jobs/control-plane/components_test.go
  prow/config.yaml
  prow/jobs/control-plane/components/metris/metris-generic.yaml
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  templates/config.yaml
  templates/templates/prow-config.yaml
Labels: lgtm, size/L
