Repository kyma-project/test-infra, pull requests merged in 2021-10, with the labels that each got.

#4193 Introduce nightly e2e test job for reconciler
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4211 Remove old release integration jobs
  prow/jobs/kyma/releases/kyma-release-124.yaml
Labels: size/L, lgtm

#4217 Adapt kyma delete to undeploy
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/lib/kyma.sh
Labels: size/S, lgtm

#4221 remove concurrency flag
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
Labels: size/XS, lgtm

#4220 Fixed dead links
  .github/pull-request-template.md
  docs/prow/prow-installation-on-forks.md
Labels: area/documentation, size/XS, lgtm

#4224 Remove reuse-values flag
  prow/scripts/lib/kyma.sh
Labels: size/XS, lgtm

#4222 Disable reporting for kyma-integration-k3d-compass-dev job
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4225 Remove cluster-users test
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/cluster-users-integration-k3d.sh
  prow/scripts/cluster-integration/kyma-integration-minikube.sh
  prow/scripts/provision-vm-and-start-cluster-users-k3d.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4226 Remove timeout flag from CLI
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/XS, lgtm

#4228 Remove atomic flag from serverless script
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
Labels: size/XS, lgtm

#4082 cleaner composition and methods calls
  development/github/pkg/client/client.go
Labels: area/ci, size/XS, lgtm

#4234 Add tunas secret for event mesh
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Labels: size/S, lgtm

#4216 ci-force notification automation fixes
  development/gcp/cloud-functions/getGithubIssue/getgithubissue.go
  development/gcp/cloud-functions/getGithubIssue/go.mod
  development/gcp/cloud-functions/getGithubIssue/go.sum
  development/gcp/cloud-functions/getfailureinstancedetails/getfailureinstancedetails.go
  development/gcp/cloud-functions/getgithubcommiter/getgithubcommiter.go
  development/gcp/cloud-functions/getgithubcommiter/go.mod
  development/gcp/cloud-functions/getgithubcommiter/go.sum
  development/gcp/cloud-functions/getslackuserforgithubuser/getslackuserforgithubuser.go
  development/gcp/cloud-functions/getslackuserforgithubuser/go.mod
  development/gcp/cloud-functions/getslackuserforgithubuser/go.sum
  development/gcp/pkg/pubsub/client.go
  development/kyma-ci-force-bot/ciforcebot/cmd/main.go
  development/kyma-ci-force-bot/kyma-ci-force-bot/prod-values.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/stage-values.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/configMap.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/deployment.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/googleServiceAccountKeySecret.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/issueClosedSubscription.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/service.yaml
  development/kyma-pubsub-connector/pubsubConnectorChart/values/prowjob.failed/prod-values.yaml
  development/kyma-slack-connector/notifyCommiterFunction/handler.py
  development/kyma-slack-connector/slackConnectorChart/values/prowjob.failed/prod-values.yaml
Labels: enhancement, area/ci, size/XXL, lgtm

#4238 Add logs when timeout while reconciliation
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/S, lgtm

#4239 Fix kyma2 cli integration job
  prow/scripts/provision-vm-cli.sh
Labels: size/XS, lgtm

#4231 Remove init params from Busola
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
Labels: size/XS, lgtm

#4237 use release testing EMS account
  prow/jobs/kyma/releases/kyma-release-20.yaml
  templates/data/kyma-release-data.yaml
Labels: size/S, lgtm

#4243 Remove k3d install from pre-main-serverless-integration-alpha-k3s
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
Labels: size/S, lgtm

#4242 Disable nightly-main-reconciler-e2e job
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4241 Clean up build kyma artifacts
  prow/scripts/build-kyma-artifacts.sh
Labels: size/S, lgtm

#4250 Update kyma integration image
  development/image-guard/Makefile
  development/kyma-ci-force-bot/ciforcebot/Makefile
  development/kyma-github-connector/githubWebhookGateway/Makefile
  development/kyma-pubsub-connector/pubSubGateway/Makefile
  prow/images/bootstrap/Makefile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-java/Makefile
  prow/images/buildpack-node/Makefile
  prow/images/cleaner/Makefile
  prow/images/clonerefs/Makefile
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
  prow/images/probot-stale/Makefile
  prow/images/prow-tools/Makefile
  prow/images/whitesource-scanner/Makefile
Labels: size/M, lgtm

#4254 Added get commit for branch
  development/github/pkg/client/client.go
Labels: enhancement, area/ci, size/S, lgtm

#4262 Fix component list (istio-configuration)
  prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
Labels: size/XS, lgtm

#4283 Skip ssl for compass connector gke integration tests
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#4286 Add ord aggregator skip ssl validation for tests
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/XS, lgtm

#4230 Clean up nightly script
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/M, lgtm

#4297 Remove old serverless job
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#4294 Fix dockerfiles linting
  changelog-generator/Dockerfile
  development/test-log-collector/Dockerfile
  prow/images/bootstrap/Dockerfile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-java-node/Dockerfile
  prow/images/buildpack-java/Dockerfile
  prow/images/buildpack-node-chromium/Dockerfile
  prow/images/buildpack-node/Dockerfile
  prow/images/cleaner/Dockerfile
  prow/images/debug-commando/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/probot-stale/Dockerfile
  prow/images/prow-tools/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
  stability-checker/deploy/stability-checker/Dockerfile
Labels: size/L, lgtm

#4304 Fix pjtester tests
  development/tools/pkg/pjtester/pjtester_test.go
  development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
Labels: size/S, lgtm

#4308 Update githubissues documentation
  development/tools/cmd/githubissues/README.md
Labels: size/S, lgtm

#4323 Update release-1.24 jobs to use container os with Docker
  prow/jobs/kyma/releases/kyma-release-124.yaml
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Labels: size/S, lgtm

#4325 Fix hadolint wildcard arg
  prow/jobs/test-infra/validation.yaml
  templates/data/validation-data.yaml
Labels: size/S, lgtm

#4329 Add website-vuepress repo to tide
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#4320 Change system-fetcher config
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/compass-gke-integration.sh
Labels: size/S, lgtm

#4311 Re-enable reconciler nightly and make e2e job non-optional
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/resources/reconciler/shoot-template.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
Labels: size/L, lgtm

#4338 added nats:2.6.1-alpine to image-syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm
