Repository kyma-project/test-infra, pull requests merged in 2021-02, with the labels that each got.

#3231 Fix protecode guard script
  prow/scripts/cluster-integration/protecode-guard.sh
Labels: area/ci

#3232 Bump RELEASE_VERSION to 1.18.2
  prow/RELEASE_VERSION
Labels: area/ci

#3184 k8s: bump Gardener version to 1.19
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
Labels: area/ci

#3237 removing test for non existing component kyma alpha uninstall pipeline
  prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh
Labels: area/installation

#3148 Test fast-integration with nodejs installer - infra part
  prow/scripts/cluster-integration/kyma-integration-k3s.sh
Labels: area/ci

#3187 bump gcloud sdk version to 324
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
  prow/jobs/kyma/kyma-integration.yaml
  templates/templates/kyma-integration.yaml
Labels: area/ci

#3246 k8s: move CLUSTER_VERSION to yaml files
  development/tools/jobs/cli/cli_integration_test.go
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
  development/tools/jobs/tester/preset/preset.go
  prow/config.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-upgrade-gardener.yaml
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/lib/azure.sh
  templates/templates/kyma-integration-gardener.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, area/cluster

#3248 Fix volumes section in generic.tmpl
  prow/jobs/test-infra/testgrid-automation.yaml
  templates/data/testgrid-automation-data.yaml
  templates/templates/generic.tmpl
Labels: area/ci, bug

#3259 k8s: use new version in Compass and control plane jobs
  development/tools/jobs/control-plane/control_plane_gke_integration_test.go
  development/tools/jobs/control-plane/control_plane_gke_provisioner_integration_test.go
  development/tools/jobs/incubator/compass/compass_gke_integration_test.go
  development/tools/jobs/kyma/kyma_compass_provisioner_tests_test.go
  development/tools/jobs/kyma/kyma_gke_compass_integration_test.go
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-gke-compass-integration.yaml
Labels: area/ci

#3263 tools: update readme
  development/tools/README.md
Labels: area/documentation

#3264 gcloud: remove quotes from k8s channel version
  prow/scripts/lib/gcloud.sh
Labels: area/ci, bug

#3265 GitHub: use HTTP headers authorisation
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
  prow/scripts/lib/kyma.sh
Labels: area/ci

#3217 Remove RELEASE_VERSION file from test-infra
  development/github-release.sh
  development/tools/jobs/kyma/kyma_github-release_test.go
  prow/RELEASE_VERSION
  prow/jobs/kyma/kyma-github-release.yaml
  prow/scripts/build-kyma-artifacts.sh
  prow/scripts/build.sh
  prow/scripts/changelog-generator.sh
  prow/scripts/cluster-integration/kyma-gke-central.sh
  prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  templates/templates/kyma-github-release.yaml
Labels: area/ci

#3270 Enable PSP for GKE jobs
  prow/config.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
  prow/jobs/kyma/kyma-gke-compass-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  prow/scripts/lib/gcloud.sh
  templates/templates/compass-gke-integration.yaml
  templates/templates/kyma-gke-compass-integration.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
  templates/templates/kyma-release-upgrade.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3258 Gh slack connector
  development/github-slack-connector/githubConnector/.helmignore
  development/github-slack-connector/githubConnector/Chart.yaml
  development/github-slack-connector/githubConnector/ghConnectorEvent.json
  development/github-slack-connector/githubConnector/ghConnectorSlackAPI.json
  development/github-slack-connector/githubConnector/templates/01-ghConnectorApplicationMapping.yaml
  development/github-slack-connector/githubConnector/templates/02-ghConnectorSlackApplicationMapping.yaml
  development/github-slack-connector/githubConnector/templates/03-ghConnectorGatewayApiRule.yaml
  development/github-slack-connector/githubConnector/templates/04-ghConnectorGatewayService.yaml
  development/github-slack-connector/githubConnector/templates/05-ghConnectorWebhookSecret.yaml
  development/github-slack-connector/githubConnector/templates/06-ghConnectorGatewayConfigMap.yaml
  development/github-slack-connector/githubConnector/templates/07-ghConnectorGatewayDeployment.yaml
  development/github-slack-connector/githubConnector/templates/08-ghConnectorSlackClientFunctionGitRepo.yaml
  development/github-slack-connector/githubConnector/templates/09-ghConnectorWebhookGatewayServiceInstance.yaml
  development/github-slack-connector/githubConnector/templates/10-ghConnectorSlackServiceInstance.yaml
  development/github-slack-connector/githubConnector/templates/11-ghConnectorServiceBinding.yaml
  development/github-slack-connector/githubConnector/templates/12-ghConnectorSlackClientBindingUsage.yaml
  development/github-slack-connector/githubConnector/templates/13-ghConnectorSlackClientTrigger.yaml
  development/github-slack-connector/githubConnector/templates/14-ghConnectorSlackClientFunction.yaml
  development/github-slack-connector/githubConnector/values.yaml
  development/github-slack-connector/githubWebhookGateway/Dockerfile
  development/github-slack-connector/githubWebhookGateway/Makefile
  development/github-slack-connector/githubWebhookGateway/before-commit.sh
  development/github-slack-connector/githubWebhookGateway/cmd/main.go
  development/github-slack-connector/githubWebhookGateway/go.mod
  development/github-slack-connector/githubWebhookGateway/go.sum
  development/github-slack-connector/githubWebhookGateway/pkg/apperrors/apperrors.go
  development/github-slack-connector/githubWebhookGateway/pkg/apperrors/apperrors_test.go
  development/github-slack-connector/githubWebhookGateway/pkg/events/mocks/Validator.go
  development/github-slack-connector/githubWebhookGateway/pkg/events/sender.go
  development/github-slack-connector/githubWebhookGateway/pkg/events/sender_test.go
  development/github-slack-connector/githubWebhookGateway/pkg/events/validator.go
  development/github-slack-connector/githubWebhookGateway/pkg/events/validator_test.go
  development/github-slack-connector/githubWebhookGateway/pkg/github/mocks/Validator.go
  development/github-slack-connector/githubWebhookGateway/pkg/github/wrappers.go
  development/github-slack-connector/githubWebhookGateway/pkg/handlers/mocks/Sender.go
  development/github-slack-connector/githubWebhookGateway/pkg/handlers/webhookhandler.go
  development/github-slack-connector/githubWebhookGateway/pkg/handlers/webhookhandler_test.go
  development/github-slack-connector/githubWebhookGateway/pkg/hook/hook.go
  development/github-slack-connector/githubWebhookGateway/pkg/hook/hook_test.go
  development/github-slack-connector/githubWebhookGateway/pkg/hook/model.go
  development/github-slack-connector/githubWebhookGateway/pkg/httperrors/httperrors.go
  development/github-slack-connector/issueLabeledFunction/handler.py
  development/github-slack-connector/issueLabeledFunction/requirements.txt
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci

#3277 Add channel notification
  development/github-slack-connector/githubConnector/templates/05-ghConnectorWebhookSecret.yaml
  development/github-slack-connector/githubConnector/templates/14-ghConnectorSlackClientFunction.yaml
  development/github-slack-connector/githubConnector/values.yaml
  development/github-slack-connector/issueLabeledFunction/handler.py
Labels: area/ci

#3272 Rewrite the examples repo prowjobs for new templating
  development/tools/jobs/console/react_components_test.go
  development/tools/jobs/examples/event_email_service_test.go
  development/tools/jobs/examples/http_db_service_test.go
  development/tools/jobs/examples/monitoring_custom_metrics_test.go
  development/tools/jobs/examples/orders_service_test.go
  development/tools/jobs/examples/tests/http_db_service_acceptance_tests_test.go
  development/tools/jobs/examples/tracing_test.go
  development/tools/jobs/tester/tester.go
  prow/jobs/console/components/react/react-components.yaml
  prow/jobs/examples/event-email-service/event-email-service.yaml
  prow/jobs/examples/examples-buildpack.yaml
  prow/jobs/examples/http-db-service/http-db-service.yaml
  prow/jobs/examples/monitoring-custom-metrics/monitoring-custom-metrics.yaml
  prow/jobs/examples/orders-service/orders-service.yaml
  prow/jobs/examples/tests/http-db-service-acceptance-tests/http-db-service-acceptance-tests.yaml
  prow/jobs/examples/tracing/tracing.yaml
  templates/data/examples-data.yaml
  templates/data/react-components-data.yaml
Labels: area/ci

#3279 PSP: disable for control plane jobs
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
Labels: area/ci

#3280 Add missing presets to image-syncer-data.yaml
  prow/jobs/test-infra/image-syncer.yaml
  templates/data/image-syncer-data.yaml
Labels: area/ci, bug

#3281 test if report: false works
  prow/jobs/cli/cli-integration.yaml
Labels: area/ci

#3282 GKE rapid: disable failing tests
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci

#3283 sending notification to dev-null channel
  prow/jobs/cli/cli-integration.yaml
Labels: area/ci

#3284 GKE rapid: disable failing core-test-external-solution test
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci

#3295 gke-integration: fix typo
  prow/scripts/cluster-integration/kyma-gke-integration.sh
Labels: area/ci

#3239 Templating docs
  development/tools/cmd/rendertemplates/README.md
  development/tools/cmd/rendertemplates/main.go
  templates/templates/protecode-guard_disabled.yaml
  templates/templates/whitesource-periodics_disabled.yaml
Labels: area/ci, area/documentation

#3268 Junit reports for fast-integration tests - test-infra part
  prow/scripts/provision-vm-and-start-kyma-k3s.sh
Labels: area/ci

#3302 build-generic: add time to output
  prow/scripts/build-generic.sh
Labels: area/ci

#3304 Treat data files as templates in rendertemplates
  development/tools/cmd/rendertemplates/main.go
Labels: area/ci

#3307 Update test-log-collector config for serverless tests
  development/test-log-collector/chart/test-log-collector/files/config.yaml
Labels: area/serverless

#3312 Separate testgrid annotations from jobConfig_default
  templates/config.yaml
  templates/data/examples-data.yaml
  templates/data/image-syncer-data.yaml
  templates/data/incubator-third-party-images-data.yaml
  templates/data/react-components-data.yaml
  templates/data/stability-checker-data.yaml
  templates/data/test-log-collector-data.yaml
  templates/data/testgrid-automation-data.yaml
  templates/data/watch-pods-data.yaml
Labels: area/ci

#3310 PSP: save logs to artifacts
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/lib/utils.sh
  templates/templates/kyma-integration.yaml
Labels: area/ci

#3317 PSP: remove from non-integration jobs
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-release-candidate.yaml
  prow/jobs/kyma/kyma-release-upgrade.yaml
  templates/templates/kyma-gke-external-registry.yaml
  templates/templates/kyma-release-candidate.yaml
  templates/templates/kyma-release-upgrade.yaml
Labels: area/ci

#3318 Gardener: test PSP
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
Labels: area/ci

#3322 Add python third party image
  prow/jobs/incubator/third-party-images/third-party-images.yaml
  templates/data/incubator-third-party-images-data.yaml
Labels: area/security, area/serverless

#3323 kyma alpha deploy improvements
  development/tools/jobs/cli/cli_integration_test.go
  prow/jobs/cli/cli-integration.yaml
  prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
  prow/scripts/lib/cli-alpha.sh
Labels: area/installation

#3306 Add new release templating solution for release jobs
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/kyma_release_candidate_test.go
  development/tools/jobs/kyma/kyma_release_upgrade_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-118.yaml
  prow/jobs/kyma/releases/kyma-release-119.yaml
  prow/jobs/kyma/releases/kyma-release-120.yaml
  prow/jobs/kyma/releases/kyma-release-121.yaml
  prow/jobs/kyma/releases/kyma-release-candidate.yaml
  prow/jobs/kyma/releases/kyma-release-upgrade.yaml
  prow/testgrid-default.yaml
  templates/config.yaml
  templates/data/kyma-release-data.yaml
  templates/templates/kyma-integration.yaml
  templates/templates/kyma-release-candidate.yaml
  templates/templates/kyma-release-upgrade.yaml
  templates/templates/testgrid-default.yaml
Labels: area/ci

#3339 Fix typo in compass preset
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, bug

#3333 scripts: remove install-kyma.sh
  prow/scripts/cluster-integration/helpers/install-kyma.sh
Labels: area/ci

#3341 images: bump kubebuilder2 base
  prow/images/buildpack-golang-kubebuilder2/Dockerfile
Labels: area/ci

#3340 Add renamed fields to MILV config
  milv.config.yaml
Labels: area/documentation, enhancement

#3348 fix SLACK_CLIENT_WEBHOOK_URL to new Slack URL
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci

#3349 Add always_run to milv pre job
  development/tools/jobs/incubator/milv/milv_test.go
  prow/jobs/incubator/milv/milv.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: area/documentation, bug

#3345 remove unused images
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/buildpack_test.go
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci

#3347 Remove unused buildpack-golang-kubebuilder image
  development/tools/jobs/tester/tester.go
  development/tools/jobs/testinfra/buildpack_test.go
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci

#3350 remove unsued images
  prow/images/bootstrap-helm/Dockerfile
  prow/images/bootstrap-helm/Makefile
  prow/images/bootstrap-helm/README.md
  prow/images/buildpack-golang-kubebuilder/Dockerfile
  prow/images/buildpack-golang-kubebuilder/Makefile
  prow/images/buildpack-golang-kubebuilder/README.md
  prow/images/kyma-cluster-infra/Dockerfile
  prow/images/kyma-cluster-infra/Makefile
  prow/images/kyma-cluster-infra/README.md
Labels: area/ci

#3352 gardener: remove unused GCP parallel install conditionals
  prow/scripts/lib/gardener/gcp.sh
Labels: area/ci

#3351 Remove ci args from milv jobs
  development/tools/jobs/incubator/milv/milv_test.go
  prow/jobs/incubator/milv/milv.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: area/documentation, bug

#3353 gardener: fix gcp library
  prow/scripts/lib/gardener/gcp.sh
Labels: area/ci

#3336 VM: remove warning for ssh keys
  prow/scripts/lib/utils.sh
Labels: area/ci

#3346 Add kyma_experimental dashboard for experimental jobs
  prow/jobs/test-infra/image-syncer.yaml
  prow/jobs/test-infra/testgrid-automation.yaml
  prow/testgrid-default.yaml
  templates/data/image-syncer-data.yaml
  templates/data/testgrid-automation-data.yaml
  templates/templates/generic.tmpl
  templates/templates/testgrid-default.yaml
Labels: area/ci
