Repository kyma-project/test-infra, pull requests merged in 2022-01, with the labels that each got.

#4659 make protecode jobs mandatory
  prow/jobs/scans/protecode-guard.yaml
  templates/data/protecode-guard-data.yaml
Labels: size/XS, lgtm

#4653 install istioctl in custom image and export ISTIOCTL_PATH
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
Labels: size/XS, lgtm

#4660 Add missing label to kyma-preview prowjob
  prow/jobs/kyma/kyma-preview.yaml
  templates/data/kyma-preview-data.yaml
Labels: size/XS, lgtm

#4639 Update kyma-artifacts
  development/github-release.sh
  prow/scripts/build-kyma-artifacts.sh
Labels: size/XS, lgtm

#4655 Cleanup permission controller
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/permission-controller/permission-controller-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#4610 New dev pipelines
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/L, lgtm

#4608 Image-url-checker: add component descriptor generator
  development/image-url-helper/cmd/components.go
  development/image-url-helper/cmd/image_url_helper.go
  development/image-url-helper/pkg/component/component.go
  go.mod
  go.sum
  prow/jobs/kyma/kyma-validation.yaml
  prow/scripts/generate-component-descriptors.sh
  templates/data/kyma-validation-data.yaml
Labels: size/L, lgtm

#4664 Update component descriptor jobs
  prow/jobs/kyma/kyma-validation.yaml
  prow/scripts/generate-component-descriptors.sh
  templates/data/kyma-validation-data.yaml
Labels: size/M, lgtm

#4666 Bump prow-tools image in kyma-integration Dockerfile
  prow/images/kyma-integration/Dockerfile
Labels: size/XS, lgtm

#4668 Component descriptor: use integration image
  prow/jobs/kyma/kyma-validation.yaml
  templates/data/kyma-validation-data.yaml
Labels: size/XS, lgtm

#4680 Branchprotector: fix reconciler protection rules
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#4681 Fix testgrid groups
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-validation.yaml
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/jobs/kyma/releases/kyma-release-21.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-release-data.yaml
  templates/data/kyma-validation-data.yaml
Labels: size/S, lgtm

#4679 Increase periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade timeout
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
  prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
  prow/scripts/cluster-integration/reconciler-periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade.sh
  templates/data/incubator-buildpack-data.yaml
Labels: size/M, lgtm

#4684 solo fips distroless istio images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4685 Bump gardenlinux version
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#4686 Bump k8s version for Busola & Reconciler gardener
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#4694 Bump Prometheus pushgateway
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4695 call cleanup on EXIT, HUP and INT
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: area/ci, size/XS, lgtm

#4697 Fix failing jobs on release branch
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/minikube-test.sh
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  prow/scripts/provision-vm-and-start-reconciler-k3d.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/provision-vm-control-plane.sh
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-release-data.yaml
Labels: size/L, lgtm

#4698 update kube-state-metrics image to v2.3.0
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4701 remove `iam-kubeconfig` for in Kyma 2
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/iam-kubeconfig-service/iam-kubeconfig-service-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#4702 remove `apiserver-proxy` for in Kyma 2
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/components/apiserver-proxy/apiserver-proxy-generic.yaml
  prow/jobs/kyma/tests/integration/apiserver-proxy/apiserver-proxy-tests-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#4703 Fix vm cleaner regexp
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4704 Fix vm cleaner regexp
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4705 Fix vm cleaner regexp for Busola
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#4458 remove pre/post-{rel}-gke-upgrade jobs
  development/tools/before-commit.sh
  prow/jobs/kyma/releases/kyma-release-20.yaml
  prow/scripts/cluster-integration/README.md
  prow/scripts/cluster-integration/kyma-gke-upgrade.sh
  templates/data/kyma-integration-data.yaml
Labels: area/ci, area/quality, size/L, lgtm

#4708 Upgrade Kyma-Upgrade-Version to 2.0.2 in skr-kyma-to-kyma2-upgrade-aws-dev
  prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
  templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
Labels: size/XS, lgtm

#4706 add kyma telemetry integration tests
  development/tools/jobs/kyma/telemetry_test.go
  prow/jobs/kyma/components/telemetry-operator/telemetry-test.yaml
  prow/scripts/kyma-telemetry-test.sh
  templates/data/kyma-telemetry-data.yaml
Labels: size/L, lgtm

#4716 Revert "add kyma telemetry integration tests (#4706)"
  development/tools/jobs/kyma/telemetry_test.go
  prow/jobs/kyma/components/telemetry-operator/telemetry-test.yaml
  prow/scripts/kyma-telemetry-test.sh
  templates/data/kyma-telemetry-data.yaml
Labels: size/L, lgtm

#4721 Add initial area labels to `label_sync`.
  OWNERS
  prow/labels.yaml
Labels: size/M, lgtm

#4723 Revert "clonerefs(deps): bump k8s-prow/clonerefs from v20220107-c0207137f8 to v20220110-28076d3f8c in /prow/images/clonerefs"
  prow/images/clonerefs/Dockerfile
Labels: area/ci, size/XS, lgtm

#4711 remove `xip-patch` for in Kyma 2
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/xip-patch/xip-patch-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#4728 Add golang:1.17.6-alpine3.15 to external images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4729 Pin golang image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#4718 VMcollector: change regexp to exclude
  development/tools/cmd/vmscollector/main.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/pkg/vmscollector/collector.go
  development/tools/pkg/vmscollector/collector_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/L, lgtm

#4731 Revert "clonerefs(deps): bump k8s-prow/clonerefs from v20220110-28076d3f8c to v20220112-0a53e24183 in /prow/images/clonerefs"
  prow/images/clonerefs/Dockerfile
Labels: size/XS, lgtm

#4732 Make testgrid job optional
  prow/jobs/test-infra/testgrid-automation.yaml
  templates/data/testgrid-automation-data.yaml
Labels: size/XS, lgtm

#4726 remove old upgrade jobs
  development/tools/cmd/yamlmerge/main.go
  prow/jobs/kyma/releases/kyma-release-21.yaml
  prow/jobs/kyma/tests/end-to-end/upgrade/upgrade-tests-generic.yaml
  prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
  templates/data/generic_component_data.yaml
  templates/data/kyma-release-data.yaml
Labels: size/XL, lgtm

#4699 Remove not used images.
  prow/images/buildpack-java-node/Dockerfile
  prow/images/buildpack-java-node/Makefile
  prow/images/buildpack-java-node/README.md
  prow/images/buildpack-java/Dockerfile
  prow/images/buildpack-java/Makefile
  prow/images/buildpack-java/README.md
  prow/images/buildpack-node-chromium/Dockerfile
  prow/images/buildpack-node-chromium/Makefile
  prow/images/buildpack-node-chromium/README.md
Labels: area/ci, size/L, lgtm

#4719 VMcollector: update documentation
  development/tools/cmd/vmscollector/README.md
Labels: size/S, lgtm

#4734 Make testgrid job mandatory
  prow/jobs/test-infra/testgrid-automation.yaml
  templates/data/testgrid-automation-data.yaml
Labels: size/XS, lgtm

#4720 Add `approve` related plugin configuration for kyma-project/test-infra repo
  prow/config.yaml
  prow/plugins.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#4739 Bump Kyma version to 2.0.3 in upgrade tests
  prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
  templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
Labels: size/XS, approved, lgtm

#4742 Update OWNERS configuation
  OWNERS
  OWNERS_ALIASES
  prow/plugins.yaml
Labels: approved, size/S, lgtm

#4740 Remove CODEOWNERS from test-infra
  CODEOWNERS
Labels: approved, size/M, lgtm

#4744 Remove labels filters and use simple OWNERS file
  development/OWNERS
  prow/OWNERS
  prow/cluster/OWNERS
  prow/images/OWNERS
  prow/jobs/OWNERS
  prow/scripts/OWNERS
  templates/templates/OWNERS
Labels: approved, size/M, lgtm

#4745 Add grego952 in OWNERS_ALIASES as a documentation OWNER in `test-infra`
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#4665 Add serverless metrics job
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/cluster/components/monitoring/dashboards/Makefile
  prow/cluster/components/monitoring/dashboards/serverless/serverless-controller-dashboard.json
  prow/cluster/components/monitoring/grafana_deployment.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-serverless-metrics-nightly.sh
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/cluster-integration/serverless-metrics-collector.yaml
  prow/scripts/lib/serverless-shared-k3s.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/XL, approved, lgtm, area/prow, area/tooling

#4749 Enable additional useful plug-ins for test-infra
  prow/plugins.yaml
Labels: size/XS, approved, lgtm, area/prow

#4696 Autotest for dependabot plugin
  .github/dependabot.yml
  development/external-plugins/test-untrusted/cmd/main.go
  development/prow/externalplugin/externalplugin.go
  go.mod
  prow/cluster/components/test-untrusted-external-plugin_deployment.yaml
  prow/cluster/components/test-untrusted-external-plugin_service.yaml
  prow/images/test-untrusted-plugin/Dockerfile
  prow/images/test-untrusted-plugin/Makefile
  prow/images/test-untrusted-plugin/README.md
  prow/jobs/test-infra/prow-plugins.yaml
  prow/labels.yaml
  prow/plugins.yaml
  templates/data/dependabot-config-data.yaml
  templates/data/prow-plugins-data.yaml
  templates/templates/dependabot.tmpl
Labels: area/ci, size/XL, approved, lgtm, area/prow, area/tooling, area/templates

#4753 Fix nightly cluster
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/XS, approved, lgtm

#4754 Update kyma nightly to use local sources
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/XS, approved, lgtm, area/prow

#4757 Fix test untrusted path
  prow/jobs/test-infra/prow-plugins.yaml
  templates/data/prow-plugins-data.yaml
Labels: size/XS, approved, do-not-merge/hold, lgtm, area/prow

#4759 Add npm to Whitesource image
  prow/images/whitesource-scanner/Dockerfile
  prow/images/whitesource-scanner/go-wss-unified-agent.config
  prow/images/whitesource-scanner/javascript-wss-unified-agent.config
Labels: approved, size/S, lgtm, area/prow

#4713 Update Dependencies
  development/gcp/cloud-functions/getfailureinstancedetails/go.mod
  development/test-log-collector/go.mod
  development/test-log-collector/go.sum
  go.mod
  go.sum
Labels: approved, size/L, lgtm, area/tooling

#4763 Fix whitesource image
  prow/images/whitesource-scanner/Dockerfile
Labels: size/XS, approved, lgtm, area/prow

#4762 Build test untrusted
  development/external-plugins/test-untrusted/cmd/main.go
Labels: size/XS, approved, lgtm, area/tooling

#4586 Added job to run SKR fast-integration tests as pre-submit for eventing
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/cluster-integration/kyma-integration-skr-eventing.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: approved, size/L, lgtm, area/prow

#4707 Fix promotion for custom container registry
  development/image-url-helper/excludes_promote.yaml
  development/image-url-helper/pkg/promote/promote.go
Labels: approved, size/M, lgtm, area/tooling

#4746 kyma telemetry integration tests
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: approved, size/L, lgtm, area/prow, area/tooling, area/templates

#4778 Remove failery jobs
  development/tools/jobs/kyma/failery_test.go
  prow/jobs/kyma/tools/failery.yaml
  templates/data/kyma-tools-data.yaml
Labels: approved, size/L, lgtm, area/prow, area/tooling

#4776 new component istio-resources
  prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
Labels: area/service-mesh, area/ci, size/XS, approved, lgtm, area/prow

#4788 Add documentation for `image-url-helper` components subcommand
  development/image-url-helper/README.md
Labels: approved, size/M, lgtm, area/tooling

#4789 Use Kyma 1.x CLI for Octopus tests
  development/tools/jobs/cli/cli_integration_test.go
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/incubator/compass/compass-gke-integration.yaml
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-minikube.sh
  prow/scripts/lib/kyma.sh
  templates/data/cli-data.yaml
  templates/data/compass-development-artifacts-data.yaml
  templates/data/compass-gke-benchmark-data.yaml
  templates/data/compass-gke-integration-data.yaml
  templates/data/compass-integration-data.yaml
  templates/data/compass-integration-no-dump.yaml
Labels: approved, size/M, lgtm, area/prow, area/tooling

#4561 Add needs-tws plugin code.
  development/external-plugins/needs-tws/main.go
  development/external-plugins/needs-tws/plugin.go
  development/external-plugins/needs-tws/plugin_test.go
  prow/cluster/components/needs-tws_external-plugin.yaml
  prow/config.yaml
  prow/images/needs-tws-external-plugin/Dockerfile
  prow/labels.yaml
  prow/plugins.yaml
  templates/templates/prow-config.yaml
Labels: size/XL, approved, lgtm, area/prow, area/tooling, area/templates

#4796 Fix cleaner regex
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, approved, lgtm, area/prow, area/tooling

#4791 Restore testing `kyma install` on main branch
  prow/jobs/cli/cli-integration.yaml
  prow/scripts/cli-tests/test-all.sh
  prow/scripts/cli-tests/test-runtest.sh
  templates/data/cli-data.yaml
Labels: approved, size/S, lgtm, area/prow

#4790 Add tpi serverless-bench build job
  development/tools/jobs/third-party-images/serverless_bench_test.go
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: approved, size/L, lgtm, area/prow, area/tooling

#4800 Update owners_aliases file
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#4803 Disable testgrid for some jobs
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, approved, lgtm, area/prow

#4804 Use fixed kyma version for control plane
  prow/scripts/provision-vm-control-plane.sh
Labels: size/XS, approved, lgtm, area/prow

#4807 Use kyma cli1 for control plane
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
Labels: size/XS, approved, lgtm, area/prow

#4722 Ory component integration test on eval profile
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/reconciler-component-integration.sh
  prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh
  templates/data/incubator-buildpack-data.yaml
Labels: approved, size/L, lgtm, area/prow

#4809 Make the `pre-main-control-plane-reconciler-e2e` pipeline optional
  development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  templates/data/control-plane-integration-data.yaml
Labels: size/XS, approved, lgtm, area/prow, area/tooling

#4581 Eventing upgrade prowjob
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/kyma.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: approved, size/L, lgtm, area/prow, area/tooling, area/templates

#4815 Revert: Make the `pre-main-control-plane-reconciler-e2e` pipeline optional
  development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  templates/data/control-plane-integration-data.yaml
Labels: size/XS, approved, lgtm, area/prow, area/tooling

#4816 Remove requiring GitHub review from test-infra context
  prow/config.yaml
  prow/plugins.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, approved, lgtm, area/prow, area/templates, kind/feature

#4810 Test pipeline for ORY on prod profile
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/reconciler-component-integration.sh
  prow/scripts/cluster-integration/reconciler-component-provision-gardener.sh
  prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh
  templates/data/incubator-buildpack-data.yaml
Labels: approved, size/L, lgtm, area/prow

#4824 Use trusted_apps and ignore_drafts
  prow/plugins.yaml
Labels: size/XS, approved, lgtm, area/prow

#4814 Bump k8s to 1.20
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, approved, lgtm, area/prow, area/templates

#4821 Bump long-lasting Kyma 1.24 version to 1.24.9
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Labels: size/XS, approved, lgtm, area/prow

#4826 Remove test-untested-external-plugin from plugins.yaml
  prow/plugins.yaml
Labels: size/XS, approved, lgtm, area/prow, kind/cleanup

#4829 Disable required_pull_request_reviews for test-infra
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: approved, size/S, lgtm, area/prow, area/tooling, area/templates, kind/cleanup

#4839 Fix Kyma CLI usage for 1.24 releases
  prow/jobs/kyma/releases/kyma-release-124.yaml
Labels: approved, size/S, lgtm, area/prow

#4838 Bump Grafana to 7.5.13
  prow/cluster/components/monitoring/grafana_deployment.yaml
Labels: size/XS, approved, lgtm, area/prow

#4840 Fix broken serverless grafana board
  prow/cluster/components/monitoring/dashboards/serverless/serverless-controller-dashboard.json
Labels: approved, size/L, lgtm, area/prow

#4844 bump istio to 1.12.2
  development/image-syncer/external-images.yaml
Labels: size/XS, approved, lgtm, area/tooling

#4828 Fix two pipelines: Use latest released Kyma version
  OWNERS_ALIASES
  prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
  prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma-to-kyma2.sh
  prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma2-to-main.sh
  prow/scripts/cluster-integration/kyma-upgrade-skr-aws-kyma-to-kyma2.sh
  prow/scripts/cluster-integration/reconciler-periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade.sh
  templates/config.yaml
  templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
Labels: approved, size/L, lgtm, area/prow

#4836 Use proper CLI version for Kyma 1.24
  prow/scripts/cluster-integration/kyma-integration-minikube.sh
Labels: size/XS, approved, lgtm, area/prow

#4847 make governance job optional
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: size/XS, approved, lgtm, area/prow

#4849 fix previous bump istio to 1.12.2 distroless version
  development/image-syncer/external-images.yaml
Labels: size/XS, approved, lgtm, area/tooling
