Repository kyma-project/test-infra, pull requests merged in 2022-06, with the labels that each got.

#5500 remove github-stats job
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/github-stats.sh
  templates/data/kyma-integration-data.yaml
Labels: size/M, lgtm

#5504 Update quality dashboard
  prow/cluster/components/monitoring/dashboards/quality/quality.json
Labels: size/S, lgtm

#5501 Remove not used AC jobs
  CODEOWNERS
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/application-operator-tests/application-operator-tests-generic.yaml
  prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-tests-generic.yaml
  templates/data/generic_component_data.yaml
Labels: area/application-connector, size/XL, lgtm

#5511 Linked templates documentation with Render Templates documentation.
  development/tools/cmd/rendertemplates/README.md
  templates/README.md
Labels: area/documentation, size/S, lgtm

#5482 Istio eval/prod pipeline
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-istio-components.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#5532 Remove api-gateway test building pipeline
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/integration/api-gateway/api-gateway-tests-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#5502 Refactor skr-aws-upgrade-integration-dev test
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
Labels: size/XS, lgtm

#5535 add istio images to image syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5453 Cleanup of Service Catalog code
  CODEOWNERS
  development/image-syncer/external-images.yaml
  development/tools/cmd/dnscollector/main.go
  development/tools/jobs/console/console_test.go
  development/tools/jobs/helm-broker/helm_broker_test.go
  development/tools/jobs/incubator/service-catalog-tester/service_catalog_tester_test.go
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/tests_test.go
  development/tools/jobs/testinfra/branchprotector_test.go
  development/tools/pkg/clusterscollector/collector_test.go
  prow/config.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola-web/web-deployment-check.yaml
  prow/jobs/busola/busola.yaml
  prow/jobs/console/service-catalog-ui/service-catalog-ui.yaml
  prow/jobs/helm-broker/helm-broker.yaml
  prow/jobs/incubator/service-catalog-tester/service-catalog-tester.yaml
  prow/jobs/kyma/components/service-binding-usage-controller/service-binding-usage-controller-generic.yaml
  prow/jobs/kyma/tests/service-catalog/service-catalog-tests-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
  templates/data/busola-web-deployment-check-data.yaml
  templates/data/generic_component_busola_data.yaml
  templates/data/generic_component_console_data.yaml
  templates/data/generic_component_data.yaml
  templates/data/helm-broker-data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/XXL, lgtm

#5542 Enable Prow secret censoring
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/security, size/XS, lgtm, area/prow, kind/feature

#5521 Make the Eventing upgrade job required
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/M, lgtm

#5499 Remove jetstream test
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#5549 Make istio test optional
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#5551 bump golang version golang1.18.3:alpine3.16
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5510 Reduce execution frequency: kyma-upgrade-gardener-kyma2-minor-versions
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/lib/kyma.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/S, lgtm

#5479 Update Prow Jobs documentation
  development/tools/cmd/pjtester/README.md
  development/tools/cmd/rendertemplates/README.md
  docs/prow/README.md
  docs/prow/manage-component-jobs-with-templates.md
  docs/prow/prow-jobs-quick-start.md
  docs/prow/prow-jobs.md
Labels: area/documentation, size/XL, lgtm

#5552 More resources to tests
  prow/scripts/provision-vm-compass.sh
Labels: size/XS, lgtm

#5509 Add missing image check
  development/image-url-helper/cmd/image_url_helper.go
  development/image-url-helper/cmd/missing.go
  development/image-url-helper/pkg/common/common.go
  development/image-url-helper/pkg/common/component.go
  development/image-url-helper/pkg/common/images.go
  development/image-url-helper/pkg/common/outputlist.go
  development/image-url-helper/pkg/list/outputjson.go
  development/image-url-helper/pkg/missing/missing.go
  development/image-url-helper/pkg/missing/missing_test.go
Labels: area/ci, size/L, lgtm

#5562 Remove unused Prowjobs
  development/tools/jobs/incubator/compass/compass_integration_test.go
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/compass-integration-data.yaml
  templates/data/compass-integration-no-dump.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: area/ci, size/XL, lgtm

#5564 Add component test dir to istio pipeline
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#5117 Enabled inrepo config.
  prow/config.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/validation.yaml
  templates/config.yaml
  templates/data/checkconfig.yaml
  templates/data/validation-data.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, approved, size/XXL, lgtm, area/prow, area/templates

#5533 Restore api-gateway pipeline
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#5571 Make Kyma istio-evaluation pipeline optional
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#5464 Adjust compass to use kyma 2.0.4
  development/tools/jobs/incubator/compass/development_artifacts_test.go
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  prow/scripts/build-compass-development-artifacts.sh
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/resources/compass-gke-kyma-overrides.tpl.yaml
  templates/data/compass-development-artifacts-data.yaml
  templates/data/compass-gke-benchmark-data.yaml
  templates/data/compass-integration-data.yaml
  templates/data/compass-integration-no-dump.yaml
Labels: size/XL, lgtm

#5572 Add missing image check job
  development/image-url-helper/README.md
  prow/jobs/kyma/kyma-validation.yaml
  templates/data/kyma-validation-data.yaml
Labels: size/M, lgtm

#5573 Bump Golang version to 1.18.3
  development/custom-image/install-deps-debian.sh
  development/kyma-ci-force-bot/ciforcebot/Dockerfile
  development/kyma-github-connector/githubWebhookGateway/Dockerfile
  development/kyma-pubsub-connector/pubSubGateway/Dockerfile
  development/test-log-collector/Dockerfile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-golang/README.md
  prow/images/kyma-integration/Dockerfile
  prow/images/prow-tools/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
Labels: size/S, lgtm

#5578 Delete testing jobs from familly kyma-integration-k3d-compass-dev
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#5580 Remove SVCAT migration test
  prow/jobs/kyma/skr-svcat-migration.yaml
  templates/data/skr-svcat-migration-data.yaml
Labels: size/L, lgtm

#5576 Rework Istio component tests pipelines
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/M, lgtm

#5584 Track Github configuration changes
  .github/ISSUE_TEMPLATE/github-config-change.md
Labels: size/S, lgtm

#5590 Install yq in compass-benchmark script
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/lib/utils.sh
Labels: size/M, lgtm

#5591 Fix typo in compass-benchmark script
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/XS, lgtm

#5594 Rename yq exec used in compass-benchmark script
  prow/scripts/lib/utils.sh
Labels: size/XS, lgtm

#5595 Install helm in compass-benchmark script
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/lib/utils.sh
Labels: size/M, lgtm

#5596 update ShootMachineImage to latest 576.9.0
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#5600 make pre-main-control-plane-reconciler-e2e optional
  development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  templates/data/control-plane-integration-data.yaml
Labels: size/XS, lgtm

#5602 Remove Obsolete Application Connector tests
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/components/application-connectivity-validator/application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/application-gateway/application-gateway-generic.yaml
  prow/jobs/kyma/components/application-operator/application-operator-generic.yaml
  prow/jobs/kyma/tests/application-gateway-legacy-tests/application-gateway-legacy-tests-generic.yaml
  prow/jobs/kyma/tests/application-gateway-tests/application-gateway-tests-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/XXL, lgtm

#5386 Drop Rafter related configuration
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  CODEOWNERS
  development/test-log-collector/README.md
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/test-log-collector/pkg/config/config_test.go
  development/tools/cmd/dnscollector/main.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/tests_test.go
  development/tools/jobs/rafter/rafter_test.go
  development/tools/jobs/third-party-images/minio_test.go
  prow/cluster/components/monitoring/dashboards/quality/test_coverage.json
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/rafter/rafter.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
  prow/scripts/cluster-integration/minio/azure-cleaner.sh
  prow/scripts/cluster-integration/minio/azure-gateway.sh
  prow/scripts/cluster-integration/minio/gcs-gateway.sh
  templates/config.yaml
  templates/data/generic_component_data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/rafter-data.yaml
  templates/data/third-party-images-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/prow/jobs/kyma/components/busola-migrator/busola-migrator-generic.yaml
  templates/templates/prow-config.yaml
Labels: size/XXL, lgtm

#5615 bump istio images to 1.14.1
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5614 Fix generated jobs
  templates/data/generic_component_data.yaml
  templates/prow/jobs/kyma/components/busola-migrator/busola-migrator-generic.yaml
Labels: size/L, lgtm

#5617 Enable skip plugin on all repos
  prow/plugins.yaml
Labels: size/XS, lgtm

#5621 Remove uaa-activator
  CODEOWNERS
  development/tools/jobs/kyma/components_test.go
  prow/jobs/kyma/components/uaa-activator/uaa-activator-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#5623 Make the eventing upgrade test optional
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#5624 Add Istio 1.13.5 to image syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5631 Change grep regex in order to adapt new values.yaml file
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm

#5633 Change kcp value reference
  development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
  development/tools/jobs/control-plane/control_plane_reconciler_upgrade_test.go
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/reconciler-image-autobump.sh
  prow/scripts/resources/control-plane-autobump-reconciler-config.yaml
  templates/data/control-plane-integration-data.yaml
Labels: size/S, lgtm

#5639 revert back detect change from default values file
  development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
  development/tools/jobs/control-plane/control_plane_reconciler_upgrade_test.go
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/reconciler-image-autobump.sh
  prow/scripts/resources/control-plane-autobump-reconciler-config.yaml
  templates/data/control-plane-integration-data.yaml
Labels: size/S, lgtm

#5628 Add golangci-lint image for Kyma
  prow/images/README.md
  prow/images/golangci-lint/Dockerfile
  prow/images/golangci-lint/Makefile
  prow/images/golangci-lint/README.md
  prow/images/golangci-lint/golangci-lint.sh
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: size/L, lgtm

#5645 Update nextRelease version
  development/tools/jobs/releases/releases.go
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/console/add-ons/add-ons.yaml
  prow/jobs/console/core-ui/core-ui.yaml
  prow/jobs/console/core/core.yaml
  prow/jobs/console/logging/console-logging.yaml
  prow/jobs/console/tests/tests.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma/components/busola-migrator/busola-migrator-generic.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/components/telemetry-operator/telemetry-operator-generic.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-25.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/XXL, lgtm

#5644 Add golangci-lint job with default config
  .golangci.yaml
  prow/jobs/test-infra/go-linting.yaml
Labels: size/M, lgtm

#5649 Revert Temporarily make app-connectivity compass job optional (#5304)
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#5650 Update log highlight regexes
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#5646 Generate Istio component tests report
  prow/config.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  prow/staging/config.yaml
  templates/templates/prow-config.yaml
Labels: area/service-mesh, size/S, lgtm, area/tests

#5655 Change run_if_changed for Ory reconciler tests
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#5651 Update log highlight regexes
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm
