Repository kyma-project/test-infra, pull requests merged in 2022-05, with the labels that each got.

#5293 Rename pipeline skr-kyma-to-kyma2-upgrade-aws-dev
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/scripts/cluster-integration/skr-aws-upgrade-integration-dev.sh
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
Labels: size/L, lgtm, area/prow

#5360 Delete skr-kyma-to-kyma2-upgrade-aws files
  prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
  prow/scripts/cluster-integration/kyma-upgrade-skr-aws-kyma-to-kyma2.sh
  prow/scripts/cluster-integration/skr-aws-upgrade-integration-dev.sh
  templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
Labels: size/L, lgtm

#5335 Refactor pipeline to extract ssh connection code as shared function
  development/custom-image/create-custom-image.sh
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  prow/scripts/provision-vm-and-start-busola-lighthouse.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-minikube.sh
  prow/scripts/provision-vm-and-start-kyma-upgrade-k3d.sh
  prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh
  prow/scripts/provision-vm-and-start-reconciler-k3d.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/provision-vm-control-plane.sh
  prow/scripts/reconciler-publish-unstable-cli.sh
Labels: size/L, lgtm

#5369 upgrade kcp-cli version to master-1208b417
  prow/images/kyma-integration/Dockerfile
Labels: size/XS, lgtm

#5371 Adjust cleaners exclude list
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/S, lgtm

#5362 Bump Grafana image
  prow/cluster/components/monitoring/grafana_configmaps.yaml
  prow/cluster/components/monitoring/grafana_deployment.yaml
Labels: size/XS, lgtm

#5359 making operator env credentials available
  prow/jobs/kyma/kyma-preview.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/data/kyma-preview-data.yaml
  templates/data/skr-integration-data.yaml
Labels: size/XS, lgtm

#5380 Fix serverless job
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#5373 Updated nats image in image-syncer tool
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5382 make pre-main-control-plane-reconciler-e2e-latest-release optional
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  templates/data/control-plane-integration-data.yaml
Labels: size/XS, lgtm

#5385 Change kyma input version to 2.1.3
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
Labels: size/XS, lgtm

#5384 Add btp-admin-credentials secret
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Labels: size/M, lgtm

#5383 BTP_SM_ADMIN_CREDS env to reuse SM instance in skr test
  prow/config.yaml
  prow/jobs/kyma/skr-svcat-migration.yaml
  templates/data/skr-svcat-migration-data.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#5387 Run kyma-integration-k3d-telemetry jobs if chart or crds changed
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/S, lgtm

#5391 fix kyma version condition
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/lib/log.sh
Labels: size/S, lgtm

#5390 Fix case in cr
  development/kyma-slack-connector/slackConnectorChart/templates/function.yaml
Labels: size/XS, lgtm

#5393 Bump hydra and postgres to latest images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5379 Remove old 1.24 jobs
  prow/jobs/kyma/releases/kyma-release-124.yaml
Labels: area/ci, size/XL, lgtm, kind/cleanup

#4957 Revert "Remove everything related to Application Operator (#4912)"
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/components/application-connectivity-validator/application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/application-gateway/application-gateway-generic.yaml
  prow/jobs/kyma/components/application-operator/application-operator-generic.yaml
  prow/jobs/kyma/tests/application-gateway-legacy-tests/application-gateway-legacy-tests-generic.yaml
  prow/jobs/kyma/tests/application-gateway-tests/application-gateway-tests-generic.yaml
  prow/jobs/kyma/tests/application-operator-tests/application-operator-tests-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/XXL, lgtm, area/prow, area/tooling, lifecycle/rotten

#5400 Update nats-exporter image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5403 Normalize GitHub names and safe expand OWNERS_ALIASES
  development/external-plugins/needs-tws/plugin.go
  development/external-plugins/needs-tws/plugin_test.go
Labels: size/S, lgtm, area/tooling, kind/bug

#5405 Remove skr-without-sc-integration-dev prow job
  prow/jobs/kyma/skr-without-sc-intgration.yaml
  prow/scripts/skr-without-sc-intgration.sh
  templates/data/skr-without-sc-integration-dev.yaml
Labels: size/L, lgtm

#5409 One verbose attempt for gardener provisioning
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
Labels: size/S, lgtm

#5374 CI/CD 1005 add traceability to prow
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
  prow/scripts/cluster-integration/reconciler-integration-k3d.sh
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/generate-component-descriptors.sh
  prow/scripts/github-stats.sh
  prow/scripts/install-prow.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/azure.sh
  prow/scripts/lib/docker.sh
  prow/scripts/lib/gcp.sh
  prow/scripts/lib/github.sh
  prow/scripts/lib/junit.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/log.sh
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/provision-vm-control-plane.sh
  prow/scripts/publish-buildpack.sh
  prow/scripts/reconciler-publish-pr-cli.sh
  prow/scripts/reconciler-publish-unstable-cli.sh
  prow/scripts/validate-config.sh
  prow/scripts/validate-scripts.sh
  prow/scripts/vpathguard.sh
Labels: size/L, lgtm

#5414 Fix busola k3s
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
Labels: size/XS, lgtm

#5415 bump golang image to 1.18.2-alpine3.15
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5424 Revert "CI/CD 1005 add traceability to prow (#5374)"
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
  prow/scripts/cluster-integration/reconciler-integration-k3d.sh
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/generate-component-descriptors.sh
  prow/scripts/github-stats.sh
  prow/scripts/install-prow.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/azure.sh
  prow/scripts/lib/docker.sh
  prow/scripts/lib/gcp.sh
  prow/scripts/lib/github.sh
  prow/scripts/lib/junit.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/log.sh
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/provision-vm-control-plane.sh
  prow/scripts/publish-buildpack.sh
  prow/scripts/reconciler-publish-pr-cli.sh
  prow/scripts/reconciler-publish-unstable-cli.sh
  prow/scripts/validate-config.sh
  prow/scripts/validate-scripts.sh
  prow/scripts/vpathguard.sh
Labels: size/L, lgtm

#5316 Remove unused plugins
  prow/plugins.yaml
Labels: area/ci, approved, size/M, lgtm, area/prow, area/tooling

#5429 Bump Prometheus images
  development/image-syncer/external-images.yaml
Labels: area/monitoring, lgtm, area/charts

#5430 Do not require up-to-date branch for compass repo
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#5341 Introduce a smoke test for Compass director and ORD service
  prow/jobs/incubator/compass/compass-smoke-test.yaml
  prow/scripts/provision-vm-compass-smoke-test.sh
  templates/data/compass-smoke-test-data.yaml
Labels: size/L, lgtm

#5439 Fix typo in CPU request limits
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration.yaml
  templates/data/compass-integration-data.yaml
  templates/data/compass-integration-no-dump.yaml
Labels: size/S, lgtm

#5413 Restore api-gateway Whitesource scan
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/security, area/ci, size/M, lgtm

#5440 Add new job regex for release candidate
  prow/jobs/incubator/compass/compass-development-artifacts.yaml
  templates/data/compass-development-artifacts-data.yaml
Labels: size/XS, lgtm

#5433 Ci/CD Improve pipeline traceability (bash logging)
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
  prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
  prow/scripts/cluster-integration/reconciler-integration-k3d.sh
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
  prow/scripts/generate-component-descriptors.sh
  prow/scripts/github-stats.sh
  prow/scripts/install-prow.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/azure.sh
  prow/scripts/lib/docker.sh
  prow/scripts/lib/gcp.sh
  prow/scripts/lib/github.sh
  prow/scripts/lib/junit.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/log.sh
  prow/scripts/lib/utils.sh
  prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/provision-vm-control-plane.sh
  prow/scripts/publish-buildpack.sh
  prow/scripts/reconciler-publish-pr-cli.sh
  prow/scripts/reconciler-publish-unstable-cli.sh
  prow/scripts/validate-config.sh
  prow/scripts/validate-scripts.sh
  prow/scripts/vpathguard.sh
Labels: size/L, lgtm

#5232 Removal of the Application Registry, Connector Service and Connection Token Handler pipelines
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/components/application-connectivity-certs-setup-job/application-connectivity-certs-setup-job-generic.yaml
  prow/jobs/kyma/components/application-registry/application-registry-generic.yaml
  prow/jobs/kyma/components/connection-token-handler/connection-token-handler-generic.yaml
  prow/jobs/kyma/components/connector-service/connector-service-generic.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/tests/application-registry-tests/application-registry-tests-generic.yaml
  prow/jobs/kyma/tests/connection-token-handler-tests/connection-token-handler-tests-generic.yaml
  prow/jobs/kyma/tests/connector-service-tests/connector-service-tests-generic.yaml
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  prow/scripts/resources/kyma-installer-overrides.tpl.yaml
  prow/scripts/resources/kyma-serverless-external-registry-integration-overrides.tpl.yaml
  templates/data/generic_component_data.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/XXL, lgtm, area/prow, area/tooling

#5458 Bump gardener cluster image version from 576.1.0 to 576.2.0
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#5306 Support this new configuration approach for Reconciler image bump in control-plane job
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/reconciler-image-autobump.sh
  prow/scripts/resources/autobumper/bumper/bumper.go
  prow/scripts/resources/autobumper/bumper/bumper_test.go
  prow/scripts/resources/autobumper/go.mod
  prow/scripts/resources/autobumper/go.sum
  prow/scripts/resources/autobumper/helper.go
  prow/scripts/resources/autobumper/helper_test.go
  prow/scripts/resources/autobumper/main.go
  prow/scripts/resources/autobumper/main_test.go
  prow/scripts/resources/control-plane-autobump-reconciler-config.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XXL, lgtm, area/prow

#5460 Update cluster-kyma.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
Labels: size/XS, lgtm

#5461 Update cluster-busola.yaml
  prow/scripts/resources/busola/cluster-busola.yaml
Labels: size/XS, lgtm

#5467 Bump Golang to 1.18.2
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-golang/README.md
  prow/images/kyma-integration/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
Labels: size/S, lgtm

#5470 Bumped NATS config reloader image tag to 0.7.0 in image-syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5444 add prow job for building the fi-test-image
  development/tools/jobs/kyma/tests_test.go
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  templates/data/kyma-fast-integration-data.yaml
Labels: approved, size/L, lgtm

#5478 moved `fast-integration-image` up to release 2.3
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  templates/data/kyma-fast-integration-data.yaml
Labels: size/M, lgtm

#5484 Add golang to k3d vm install
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#5488 Mkdir for go install
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#5490 bump golang image to alpine-3.16
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5491 update prometheus-operator
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm
