Repository kyma-project/test-infra, pull requests merged in 2022-08, with the labels that each got.

#5804 Update nats image in image-syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5813 Make two blocking reconciler jobs optional
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#5819 Revert "Make two blocking reconciler jobs optional"
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#5836 bump golang image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5805 Setup "Kyma Test" product for whitesource operator scans
  prow/config.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/S, lgtm

#5840 fix DNS link
  docs/prow/production-cluster-configuration.md
Labels: size/XS, lgtm

#5830 Add k3s kubeconfig for Busola e2e tests
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
Labels: size/M, lgtm

#5837 Reconfig Operator related jobs
  prow/jobs/kyma-operator/kyma-operator.yaml
  prow/jobs/kyma-watcher/kyma-watcher.yaml
  prow/jobs/manifest-operator/manifest-operator.yaml
  templates/data/kyma-operator-data.yaml
  templates/data/kyma-watcher-data.yaml
  templates/data/manifest-operator-data.yaml
Labels: size/L, lgtm

#5845 Use gke-gcloud-auth-plugin
  prow/images/bootstrap/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
Labels: size/S, lgtm

#5847 Bump images for Kyma 2.5 jobs
  prow/jobs/kyma/releases/kyma-release-25.yaml
Labels: size/XS, lgtm

#5854 Pass examples folder to busola tests
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
  prow/scripts/cluster-integration/busola-lighthouse.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: size/S, lgtm

#5812 add GCP SA key rotation cloud function
  .gitignore
  development/gcp/cloud-functions/rotateserviceaccount/.gcloudignore
  development/gcp/cloud-functions/rotateserviceaccount/go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.sum
  development/gcp/cloud-functions/rotateserviceaccount/rotateserviceaccount.go
  development/gcp/pkg/cloudfunctions/logging.go
  development/gcp/pkg/pubsub/types.go
  development/gcp/pkg/secretmanager/service.go
Labels: size/XXL, lgtm

#5857 Update alpine image version in the image syncer
  development/image-syncer/external-images.yaml
Labels: area/security, size/XS, lgtm

#5862 Move pjtester github token to trusted cluster.
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Labels: size/S, lgtm, area/prow, kind/cleanup

#5866 Kyma operator IMG build
  prow/jobs/kyma-operator/kyma-operator.yaml
  templates/data/kyma-operator-data.yaml
Labels: size/M, lgtm

#5869 Manifest operator IMG Build
  prow/jobs/manifest-operator/manifest-operator.yaml
  templates/data/manifest-operator-data.yaml
Labels: size/M, lgtm

#5876 Update SA rotation cloudfunc go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.sum
Labels: size/XS, lgtm

#5872 Kyma watcher IMG build
  prow/jobs/kyma-watcher/kyma-watcher.yaml
  templates/data/kyma-watcher-data.yaml
Labels: size/L, lgtm

#5879 Update SA rotation cloudfunc go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.sum
Labels: size/XS, lgtm

#5880 Update SA rotation cloudfunc go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.sum
Labels: size/XS, lgtm

#5865 New prow job for directory-size-exporter component
  CODEOWNERS
  development/tools/jobs/kyma/components_test.go
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/components/directory-size-exporter/directory-size-exporter-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#5881 Make pre-main-kyma-integration-k3d-central-app-connectivity-compass job optional
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#5882 Disabling set-e option for reconciler e2e pipeline
  prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
Labels: size/XS, lgtm

#5885 Add Timeout to Compass component jobs
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/L, lgtm

#5875 Add service account rotation function documentation
  development/gcp/cloud-functions/rotateserviceaccount/README.md
Labels: size/M, lgtm

#5886 Increase Compass component job timeout
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/M, lgtm

#5725 Add Gardener token rotation tool
  development/gardener-rotate/README.md
  development/gardener-rotate/gardener-neighbors-config.yaml
  development/gardener-rotate/main.go
  prow/images/gardener-rotate/Dockerfile
  prow/images/gardener-rotate/Makefile
  prow/images/gardener-rotate/README.md
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: size/L, lgtm

#5887 Add [ERROR] to log highlights list
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#5889 Fix [ERROR] on log highlights list
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#5892 Bump `nats-config-reloader` and `nats-prometheus-exporter` images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5893 Bump Compass E2E tests component job timeout
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/XS, lgtm

#5894 Add Istio 1.14.3 to image syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5726 create gcbuild tool
  development/gcbuild/Dockerfile
  development/gcbuild/README.md
  development/gcbuild/cloudbuild.yaml
  development/gcbuild/config/checks.go
  development/gcbuild/config/checks_test.go
  development/gcbuild/config/config.go
  development/gcbuild/config/config_test.go
  development/gcbuild/main.go
  development/gcbuild/main_test.go
  development/gcbuild/run.sh
  development/gcbuild/tags/options.go
  development/gcbuild/tags/options_test.go
  development/gcbuild/tags/tags.go
  development/gcbuild/tags/tags_test.go
  development/gcbuild/tools/gcbuild-lint/main.go
  development/gcbuild/tools/gcbuild-lint/main_test.go
Labels: size/XXL, lgtm

#5899 Setup operator image build post-submits
  prow/jobs/kyma-operator/kyma-operator.yaml
  prow/jobs/kyma-watcher/kyma-watcher.yaml
  prow/jobs/manifest-operator/manifest-operator.yaml
  templates/data/kyma-operator-data.yaml
  templates/data/kyma-watcher-data.yaml
  templates/data/manifest-operator-data.yaml
Labels: size/L, lgtm

#5908 Remove test jobs for serverless v1alpha2 feature branch
  prow/jobs/kyma/kyma-integration.yaml
  templates/config.yaml
  templates/data/generic_component_data.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#5638 Adjust overrides in compass-benchmark job
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/resources/compass-gke-kyma-overrides.tpl.yaml
  prow/scripts/resources/compass-gke-overrides.tpl.yaml
  templates/data/compass-gke-benchmark-data.yaml
Labels: size/L, lgtm

#5907 Set api-gateway pipeline to mandatory
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#5911 Prepare 2.6
  development/tools/jobs/releases/releases.go
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/console/add-ons/add-ons.yaml
  prow/jobs/console/core-ui/core-ui.yaml
  prow/jobs/console/core/core.yaml
  prow/jobs/console/logging/console-logging.yaml
  prow/jobs/console/tests/tests.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma/components/busola-migrator/busola-migrator-generic.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/components/telemetry-operator/telemetry-operator-generic.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-27.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/XXL, lgtm

#5913 Add debug message for reconciler-status check
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm

#5909 Add gcbuild-config.yaml ConfigMap to workload clusters with autobumps
  configs/gcbuild-config.yaml
  prow/plugins.yaml
Labels: size/XS, lgtm

#5916 Adjust commit hash
  prow/scripts/provision-vm-compass-smoke-test.sh
Labels: size/XS, lgtm

#5888 Synchronize production and stage kyma secrets with GCP secrets manager
  configs/tooling-kyma/SecretStores_tooling_kyma_prod.yaml
  configs/tooling-kyma/external_secrets_tooling_kyma_prod.yaml
  configs/tooling-kyma/stage/SecretStores_tooling_kyma_dev.yaml
Labels: size/M, lgtm

#5918 Extract ORD commit hash based on PR state
  prow/scripts/provision-vm-compass-smoke-test.sh
Labels: size/XS, lgtm

#5910 Manifest post submit fix
  prow/jobs/manifest-operator/manifest-operator.yaml
  templates/data/manifest-operator-data.yaml
Labels: size/M, lgtm

#5919 Debug reconciler status check
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm

#5917 Move api-gateway repo pipeline
  development/tools/jobs/api-gateway/api_gateway_test.go
  development/tools/jobs/testinfra/branchprotector_test.go
  prow/config.yaml
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/checkconfig.yaml
  templates/config.yaml
  templates/data/generic_component_api_gateway_data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#5927 rename kyma-watcher => runtime-watcher
  prow/config.yaml
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/runtime-watcher-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#5925 rename kyma-operator => lifecycle-manager
  prow/config.yaml
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/checkconfig.yaml
  templates/config.yaml
  templates/data/lifecycle-manager-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#5930 rename manifest-operator => module-manager
  prow/config.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/checkconfig.yaml
  templates/config.yaml
  templates/data/manifest-operator-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#5931 Adjust reconciler template resolution
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm

#5932 Use main-template as default when calling reconciler
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/S, lgtm

#5934 Update kyma-gardener-cleanup-data.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
Labels: size/XS, lgtm

#5929 Remove dex
  CODEOWNERS
  development/tools/cmd/enablegithubauth/README.md
  development/tools/cmd/enablegithubauth/main.go
  development/tools/jobs/incubator/dex/dex_test.go
  docs/prow/presets.md
  prow/README.md
  prow/config.yaml
  prow/jobs/incubator/dex/dex.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/resources/overrides-dex-and-monitoring.tpl.yaml
  templates/config.yaml
  templates/data/incubator-dex-data.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#5941 Provide images for prometheus stack upgrade
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#5945 Create job that run unit tests across entire test-infra
  development/gcbuild/tools/gcbuild-lint/main_test.go
  prow/jobs/test-infra/go-validation.yaml
Labels: size/S, lgtm, area/prow

#5947 Provide images for pushgateway and kube-state-metrics
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm
