Repository kyma-project/test-infra, pull requests merged in 2022-11, with the labels that each got.

#6294 chore: bump image-builder image
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/btp-manager/btp-manager-build.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-build.yaml
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/components/telemetry-operator/telemetry-operator-generic.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  prow/jobs/test-infra/buildpack.yaml
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/generic_external_module_data.yaml
  templates/data/lifecycle-manager-data.yaml
  templates/data/module-manager-data.yaml
  templates/data/runtime-watcher-data.yaml
Labels: area/ci, size/L, lgtm

#6301 Bump Busola clusters version
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
Labels: size/XS, lgtm

#6302 bump golang image to go1.19.3-alpine3.16
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6300 change path to dockerfile
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/XS, lgtm

#6304 Update shoot version
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#6308 Provide latest images for prometheus and operator
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6319 Exclude onis gomega 1.23.0 from dependabot updates.
  .github/dependabot.yml
Labels: size/XS, lgtm

#6320 bump image of prometheus-nats-exporter to v0.10.1
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6323 Update keda-manager jobs with flattened layout
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  templates/data/generic_external_module_data.yaml
Labels: size/M, lgtm

#6324 bump nats server to v2.9.5-alpine3.16
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6281 Bump all jobs to k8s 1.24 except past releases
  prow/config.yaml
  prow/jobs/kyma/releases/kyma-release-26.yaml
  prow/jobs/kyma/releases/kyma-release-27.yaml
  prow/jobs/kyma/releases/kyma-release-28.yaml
  prow/jobs/kyma/releases/kyma-release-29.yaml
  templates/data/kyma-release-data.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#6246 Add test and lint job for compass console repo
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  templates/data/generic_component_compass_console_data.yaml
Labels: size/M, lgtm

#6330 Bump Google function dependency and fix linting issues
  development/gcp/cloud-run/kms-rotate/kms-rotate.go
  development/gcp/cloud-run/kms-rotate/kms-rotate_test.go
  go.mod
  go.sum
Labels: size/L, lgtm

#6329 Exclude automatically generated files from review.
  CODEOWNERS
Labels: area/documentation, size/XS, lgtm

#5544 Pjtester support inrepo
  development/external-plugins/automerge-notification/main.go
  development/github/pkg/client/v2/client.go
  development/github/pkg/git/client.go
  development/github/pkg/repoowners/client.go
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_suite_test.go
  development/tools/pkg/pjtester/pjtester_test.go
  development/tools/pkg/pjtester/test_artifacts/full-pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/invalid-pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/minimal-pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/no_prconfigs-no_prowjob_prconfig-pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
  development/tools/pkg/pjtester/test_artifacts/test-job.yaml
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  go.mod
  go.sum
  prow/images/prow-tools/Dockerfile
  test-inventory-integration.md
Labels: size/XXL, lgtm

#6102 Update docs to cover inrepo config support in pjtester.
  development/tools/cmd/pjtester/README.md
Labels: area/documentation, size/M, lgtm, area/prow

#6332 Adjust Operation Controller test job
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/XS, lgtm

#6298 Generate pjtester prowjobs for all repositories from templates config.
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/config.yaml
  templates/data/pjtester-data.yaml
Labels: area/ci, size/XXL, lgtm, area/prow

#6343 Use new version of prow-tools.
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjtester.yaml
Labels: size/L, lgtm, kind/bug

#6347 Bump NATS image to 2.9.6 in external images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6350 Wrap error returned by function and pass it up. It was not clear from…
  development/tools/pkg/pjtester/pjtester.go
Labels: size/S, lgtm, kind/bug, area/tools

#6351 Bump changelog generator
  development/tools/cmd/githubrelease/Dockerfile
Labels: size/XS, lgtm

#6354 Bump Prometheus operator
  prow/cluster/components/monitoring/prometheus_operator_deployment.yaml
Labels: size/XS, lgtm

#6353 Add Dockerfile to keda-manager jobs
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  templates/data/generic_external_module_data.yaml
Labels: size/XS, lgtm

#6325 new documentation guidelines
  docs/documentation_guidelines.md
Labels: area/documentation, size/S, lgtm

#6363 Update dependabot link to a working one
  .github/dependabot.yml
  templates/templates/dependabot.tmpl
Labels: size/XS, lgtm

#6371 bug: fix logic of getting env files
  development/image-builder/main.go
Labels: size/M, lgtm, kind/bug, area/tools

#6372 bug: add missing return statement at the end of build
  development/image-builder/main.go
Labels: size/XS, lgtm, kind/bug, area/tools

#6375 Make reconciler-cli-kyma-prev-to-last-release-upgrade-k3d optional
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#6267 Kyma dashboard PoC
  prow/jobs/kyma-dashboard/kyma-dashboard-dev.yaml
  templates/config.yaml
  templates/data/generic_component_kyma_dashboard_data.yaml
Labels: size/L, lgtm

#6348 Ignore error response during waiting for reconciling status
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm

#6384 Adding jmeter-performance image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6385 chore: prepare 2.9 update
  development/tools/jobs/releases/releases.go
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-dev.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-210.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/XL, lgtm

#6387 Exclude onsi/ginkgo/v2 from dependabot updates.
  .github/dependabot.yml
  templates/data/dependabot-config-data.yaml
Labels: size/XS, lgtm

#6393 remove pre-main-test-infra-validate-prow-jobs
  prow/jobs/test-infra/validation.yaml
  templates/data/validation-data.yaml
Labels: size/M, lgtm

#6182 Adding kyma-web-performance periodic job
  prow/jobs/busola/busola-web/periodic-performance-tests-web.yaml
Labels: size/S, lgtm

#6394 remove TestValidateProwJobsPresubmit test
  development/tools/jobs/testinfra/validate_test.go
Labels: size/S, lgtm

#6391 Fix releases Go file
  development/tools/jobs/releases/releases.go
  templates/templates/releases.go.tmpl
Labels: size/XS, lgtm

#6397 Migrate Prow to workload identity
  prow/cluster/components/crier_deployment.yaml
  prow/cluster/components/crier_rbac.yaml
  prow/cluster/components/deck_rbac.yaml
  prow/cluster/components/halogen.yaml
  prow/cluster/components/tide_rbac.yaml
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
  prow/cluster/resources/external-secrets/values_prow.yaml
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#6406 Remove `post-main-kyma-integration-k3d-central-app-connectivity-compass`
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/M, lgtm

#6408 Remove preset-gke-pod-security-policy for GKE
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-210.yaml
  prow/jobs/kyma/releases/kyma-release-29.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-release-data.yaml
Labels: size/XS, lgtm

#6409 Remove pPrecel, m00g3n and moelsayed from the CODEOWNERS file
  CODEOWNERS
Labels: size/XS, lgtm

#6411 Bump containerregistry dependency
  go.mod
  go.sum
Labels: size/XS, lgtm

#6415 Fix release candidate cluster job
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
Labels: size/S, lgtm

#6417 Bump images
  prow/cluster/components/monitoring/grafana_deployment.yaml
  prow/jobs/test-infra/kyma-bot.yaml
  templates/data/kyma-bot-data.yaml
Labels: size/XS, lgtm

#6403 fix: old img bump reconciler
  development/tools/jobs/incubator/reconciler/reconciler_test.go
  prow/autobump-config/control-plane-autobump-reconciler-config.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/scripts/reconciler-image-autobump.sh
  templates/data/incubator-buildpack-data.yaml
  templates/data/lifecycle-manager-data.yaml
Labels: size/L, lgtm

#6420 fix: add always_run to reconciler image build jobs
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#6418 Remove etcd jobs and tests
  development/tools/jobs/third-party-images/etcd_test.go
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: size/L, lgtm

#6421 Adjust quality dashboard time frame
  prow/cluster/components/monitoring/dashboards/quality/quality.json
Labels: size/XS, lgtm

#6422 bump nats-server to v2.9.7-alpine3.16
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6431 Bump outdated dependencies
  .github/dependabot.yml
  development/custom-image/install-deps-debian.sh
  development/gcp/cloud-run/gardener-sa-rotate/Dockerfile
  development/gcp/cloud-run/kms-rotate/Dockerfile
  prow/images/bootstrap/Dockerfile
  prow/images/gardener-rotate/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/needs-tws-external-plugin/Dockerfile
  templates/data/dependabot-config-data.yaml
Labels: area/security, size/M, lgtm

#6432 Fix bootstrap build job
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: size/XS, lgtm

#6434 Bump/images custom two
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-node/Dockerfile
  prow/images/cleaner/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
Labels: size/S, lgtm

#6425 Removed context flag from kaniko build
  prow/jobs/template-operator/template-operator.yaml
  templates/data/template-operator-data.yaml
Labels: size/XS, lgtm

#6435 Bump outdated dependencies
  prow/images/debug-commando/Dockerfile
Labels: size/XS, lgtm

#6399 Preview plan tests
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
  test-inventory-integration.md
Labels: size/M, lgtm

#6437 Make gcp-eventing and gcp-eventing-upgrade tests optional
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#6439 Remove unused Azure secret
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Labels: size/S, lgtm

#6441 remove Maja from codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#6440 Update documentation_guidelines.md
  docs/documentation_guidelines.md
Labels: area/documentation, lgtm

#6444 Increase test run interval for telemetry-integration-k3d
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#6373 Migrate third-party-images repo to image-builder
  development/tools/jobs/third-party-images/cloudsql_proxy_test.go
  development/tools/jobs/third-party-images/docker_registry_test.go
  development/tools/jobs/third-party-images/fluent_bit_test.go
  development/tools/jobs/third-party-images/grafana_test.go
  development/tools/jobs/third-party-images/jaeger_operator_test.go
  development/tools/jobs/third-party-images/kaniko_executer_test.go
  development/tools/jobs/third-party-images/kiali_test.go
  development/tools/jobs/third-party-images/kiwigrid_sidecar_test.go
  development/tools/jobs/third-party-images/loki_test.go
  development/tools/jobs/third-party-images/oauth2_proxy_test.go
  development/tools/jobs/third-party-images/prometheus_node_exporter_test.go
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/btp-manager/btp-manager-build.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-build.yaml
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/components/telemetry-operator/telemetry-operator-generic.yaml
  prow/jobs/kyma/components/webhook-cert-init/webhook-cert-init-generic.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/generic_external_module_data.yaml
  templates/data/module-manager-data.yaml
  templates/data/runtime-watcher-data.yaml
  templates/data/third-party-images-data.yaml
Labels: area/ci, size/XXL, lgtm, kind/deprecation

#6450 Make telemetry-operator lint, unit-test and build jobs required
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/S, lgtm

#6442 Add pipeline for otel-collector image
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: size/M, lgtm

#6430 Moving telemetry related tests to separate scripts
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
Labels: size/L, lgtm

#6455 Make reconciler-cli-kyma-prev-to-last-release-upgrade-k3d mandatory
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/XS, lgtm

#6456 Remove protection for luigiless-busola branch in busola
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#6386 Auto updated documentation index page.
  .github/dependabot.yml
  CODEOWNERS
  development/markdown-index/Dockerfile
  development/markdown-index/bumper/bumper.go
  development/markdown-index/main.go
  development/tools/cmd/jobguard/README.md
  development/tools/cmd/rendertemplates/README.md
  docs/index.md
  docs/prow/presets.md
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  prow/markdown-index/test-infra-markdown-index-autobump-config.yaml
  prow/scripts/resources/autobumper/bumper/bumper.go
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/dependabot-config-data.yaml
  templates/data/prow-periodics-data.yaml
Labels: size/XL, lgtm

#6457 Fix dependabot paths
  .github/dependabot.yml
  templates/data/dependabot-config-data.yaml
Labels: size/XS, lgtm

#6462 Tekton poc pipeline.
  prow/jobs/test-infra/poc-tekton.yaml
Labels: size/S, lgtm, area/prow, area/tools

#6463 Update Docker image for markdown-index
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
Labels: size/XS, lgtm

#6467 image-builder: enable image sign on dev
  configs/kaniko-build-config.yaml
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/btp-manager/btp-manager-build.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-build.yaml
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/components/telemetry-operator/telemetry-operator-generic.yaml
  prow/jobs/kyma/components/webhook-cert-init/webhook-cert-init-generic.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  prow/jobs/template-operator/template-operator.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/generic_external_module_data.yaml
  templates/data/module-manager-data.yaml
  templates/data/template-operator-data.yaml
Labels: size/XXL, lgtm

#6443 refactor: remove module-manager 'operator' folder
  prow/jobs/module-manager/module-manager.yaml
  templates/data/module-manager-data.yaml
Labels: size/M, lgtm

#6469 bug: signify -> secret
  configs/kaniko-build-config.yaml
Labels: size/XS, lgtm

#6468 Add Istio 1.16.0 to image syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6471 Enable preview again
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
  test-inventory-integration.md
Labels: size/M, lgtm

#6472 Fix failing post-test-infra-markdown-index-autobump
  development/markdown-index/bumper/bumper.go
Labels: size/XS, lgtm

#6474 starting setup
  prow/jobs/test-infra/poc-tekton.yaml
Labels: area/ci, size/XS, lgtm, area/tools

#6451 Remove ARM build for compass-console build job
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  templates/data/generic_component_compass_console_data.yaml
Labels: size/M, lgtm

#6466 Add signify secret
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Labels: size/S, lgtm

#6480 Fix sign image
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  templates/data/lifecycle-manager-data.yaml
  templates/data/module-manager-data.yaml
Labels: size/M, lgtm

#6481 Fix sign image for pull-lifecycle-mgr-build
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/module-manager/module-manager.yaml
  templates/data/lifecycle-manager-data.yaml
  templates/data/module-manager-data.yaml
Labels: size/M, lgtm

#6485 ignore VSC debug files
  .gitignore
Labels: size/XS, lgtm

#6479 Install kustomize in kyma-integration image
  prow/images/kyma-integration/Dockerfile
Labels: size/S, lgtm

#6488 enable protection
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/XS, lgtm
