Repository kyma-project/test-infra, pull requests merged in 2022-12, with the labels that each got.

#6497 fix prow links
  docs/prow/authorization.md
  docs/prow/production-cluster-configuration.md
Labels: size/XS, lgtm

#6496 Update VM image
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#6475 Fix failing post-test-infra-markdown-index-autobump
  development/markdown-index/bumper/bumper.go
Labels: size/S, lgtm

#6423 Change Kyma CLI version to 2.2.0 in Compass scripts
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/provision-vm-compass.sh
Labels: size/XS, lgtm

#6509 Fix triggering path for serverless runtimes
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/data/generic_component_data.yaml
Labels: area/serverless, size/S, lgtm

#6515 removed a-thaler from many code ownerships
  CODEOWNERS
Labels: size/M, lgtm

#6520 Reduce compass build jobs timeouts.
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/L, lgtm

#6521 Always print telemetry operator logs
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
Labels: size/S, lgtm

#6526 Index page
  README.md
Labels: area/documentation, area/ci, size/XS, lgtm

#6533 Add Mend scans for Warden
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/M, lgtm

#6537 Update postgresql image to "11.18-alpine3.17"
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6541 Rename java11 to java17
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/M, lgtm

#6543 update prometheus images to the latest
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6490 Add new post-submit job to build keda-module
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  templates/data/generic_external_module_data.yaml
Labels: size/M, lgtm

#6545 Update artifact registry URLs
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  templates/data/generic_external_module_data.yaml
Labels: size/XS, lgtm

#6542 Add build job for Serverless registry-gc
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  templates/data/generic_component_data.yaml
Labels: area/serverless, size/L, lgtm, kind/feature

#6557 bump golang image to 1.19.4-alpine1.17
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6476 Add pre-main-eventing job for Subscription v1alpha2 CRD
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#6535 label_sync docs
  docs/prow/label_sync.md
Labels: area/documentation, area/ci, size/XS, lgtm

#6562 Bump cypress version
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6564 Remove testing job pre-main-control-plane-gke-provisioner-integration
  development/tools/jobs/control-plane/control_plane_gke_provisioner_integration_test.go
  prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
Labels: size/L, lgtm

#6566 Revert "Bump cypress and Node version (#6563)"
  development/custom-image/install-deps-debian.sh
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
  prow/scripts/cluster-integration/busola-smoke-test-docker.sh
Labels: size/XS, lgtm

#6568 bump prometheus to latest image 2.40.6
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6569 Remove build job for Serverless registry-gc
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  templates/data/generic_component_data.yaml
Labels: area/serverless, size/L, lgtm, kind/bug

#6470 Migrate to External Secrets Operator
  prow/cluster/resources/external-secrets/README.md
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/cluster/resources/external-secrets/external_secrets_untrusted.yaml
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
  prow/cluster/resources/external-secrets/secrets_store.yaml
  prow/cluster/resources/external-secrets/values_prow.yaml
  prow/cluster/resources/external-secrets/values_trusted.yaml
  prow/cluster/resources/external-secrets/values_untrusted.yaml
Labels: size/XXL, lgtm

#6491 Keda manager pipeline
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/scripts/provision-vm-and-run-manager.sh
  templates/data/generic_external_module_data.yaml
Labels: size/L, lgtm

#6512 Image syncer: sync all architectures
  development/image-syncer/Makefile
  development/image-syncer/README.md
  development/image-syncer/external-images.yaml
  development/image-syncer/main.go
  development/image-syncer/pkg/common.go
  development/image-syncer/sign.go
  development/image-syncer/util.go
  development/image-url-helper/cmd/promote.go
  development/image-url-helper/pkg/promote/externalsyncer.go
  go.mod
  go.sum
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/test-infra/image-syncer.yaml
  templates/data/image-syncer-data.yaml
Labels: size/XXL, lgtm

#6571 Add btp-manager repo to tide config
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/config.yaml
Labels: size/L, lgtm

#6574 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#6572 Add merge method for btp-manager in tide config
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#6573 Fix java image name
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/XS, lgtm

#6576 Add istio-validation
  prow/jobs/istio/istio-validation.yaml
  templates/data/istio-validation.yaml
Labels: size/L, lgtm

#6579 Update golangci-lint run directory
  prow/jobs/istio/istio-validation.yaml
  templates/data/istio-validation.yaml
Labels: size/S, lgtm

#6582 Bump Debian VM image
  development/custom-image/create-custom-image.sh
  development/custom-image/install-deps-debian.sh
Labels: size/S, lgtm

#6590 Bump GO to 1.19.4
  development/gcp/cloud-run/gardener-sa-rotate/Dockerfile
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/gardener-rotate/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/whitesource-scanner/Dockerfile
Labels: size/S, lgtm

#6592 Bump Minikube
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#6589 Disable scanning for dead links in addons repository.
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup

#6594 change lighthouse job to optional
  prow/jobs/busola/lighthouse.yaml
  templates/data/busola-lighthouse.yaml
Labels: size/XS, lgtm

#6595 Update external-images.yaml
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6597 Switch Debian 11 back to cgroups v1
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#6603 Fix unit tests
  development/tools/jobs/governance/addons_governance_test.go
Labels: size/M, lgtm

#6606 Update kcp to master-8a4162fd
  prow/images/kyma-integration/Dockerfile
Labels: size/XS, lgtm

#6611 Bumping test-infra
  development/tools/jobs/kyma/kyma_integration_test.go
  development/tools/jobs/tester/tester.go
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
  prow/jobs/busola/busola-backend/backend-deployment-check.yaml
  prow/jobs/busola/busola-web/web-deployment-check.yaml
  prow/jobs/busola/integration-docker-test.yaml
  prow/jobs/busola/integration-k3s-test.yaml
  prow/jobs/busola/lighthouse.yaml
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-validation.yaml
  prow/jobs/kyma/releases/kyma-release-210.yaml
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/jobs/test-infra/kyma-bot.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  prow/jobs/test-infra/unstale-gardener-project.yaml
  prow/scripts/resources/debug-container.yaml
  templates/config.yaml
Labels: size/L, lgtm

#6613 Add nataliasitko to codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#6614 Remove control-plane-integration job
  development/tools/jobs/control-plane/control_plane_integration_test.go
  prow/jobs/control-plane/control-plane-integration.yaml
  prow/scripts/provision-vm-control-plane.sh
  templates/data/control-plane-integration-data.yaml
Labels: size/L, lgtm

#6500 Own Cluster Prow Tests Configuration
  prow/config.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/scripts/resources/skr-test/shoot-template.yaml
  prow/scripts/skr-integration-own-cluster.sh
  templates/data/skr-own-cluster-dev.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#6619 Add Pkg-config to debian vm
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#6623 add libgit 2
  development/custom-image/install-deps-debian.sh
Labels: size/XS, lgtm

#6616 Add build job for Serverless registry-gc
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#6624 Test eventing upgrade job with prod profile
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/S, lgtm

#6617 Enable java on serverless pipelines
  prow/scripts/cluster-integration/serverless-integration-k3s.sh
Labels: size/XS, lgtm

#6627 Enable java on gke external registry
  prow/scripts/resources/kyma-serverless-external-registry-integration-overrides.tpl.yaml
Labels: size/XS, lgtm

#6628 Revert make gcp-eventing and gcp-eventing-upgrade tests optional
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#6630 bump prometheus image to 2.40.7
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6626 Slack bot build job
  prow/jobs/slack-bot/slack-bot-build.yaml
  templates/data/slack-bot/slack-bot-build.yaml
Labels: size/M, lgtm

#6631 Made eventing lint jobs required
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/XS, lgtm

#6632 make pre-main-kyma-gardener-gcp-eventing-upgrade optional
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, lgtm

#6633 Revert "make pre-main-kyma-gardener-gcp-eventing-upgrade optional (#6632)"
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#6604 Test installation of k3d on changed vm image
  development/custom-image/create-custom-image.sh
  prow/jobs/test-infra/build-test-vm-image.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  prow/scripts/lib/utils.sh
  templates/data/build-test-vm-image.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/ci, size/L, lgtm, area/tests

#6634 refactor eventing related tests into separate files
  CODEOWNERS
  development/tools/jobs/kyma/kyma_gardener_integration_test.go
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-checks.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-checks.yaml
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: area/eventing, size/XXL, lgtm

#6641 Fix serverless-manager-test
  prow/scripts/provision-vm-and-test-serverless-manager.sh
Labels: size/XS, lgtm

#6638 Fix k3d upgrade tests
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
  prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma2-to-main.sh
  prow/scripts/cluster-integration/reconciler-integration-with-cli-k3d.sh
  prow/scripts/cluster-integration/reconciler-integration-with-cli-upgrade-k3d.sh
  prow/scripts/cluster-integration/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/utils.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm
