Repository kyma-project/test-infra, pull requests merged in 2023-12, with the labels that each got.

#9447 Remove 2 periodic whitesource prowjobs
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update, cla: yes

#9454 Move release job to GH Action
  prow/jobs/kyma-project/keda-manager/keda-manager-build.yaml
  templates/data/keda-manager.yaml
Labels: area/ci, size/M, lgtm, kind/cleanup, cla: yes

#9455 Support release branches
  prow/jobs/kyma-project/keda-manager/keda-manager-build.yaml
  prow/jobs/kyma-project/keda-manager/keda-manager-verify.yaml
  templates/data/keda-manager.yaml
Labels: area/ci, size/S, lgtm, kind/bug, cla: yes

#9461 Update image-builder run-if-changed and add post-build job
  prow/jobs/kyma-project/test-infra/images.yaml
Labels: size/M, lgtm, kind/feature, area/tools, cla: yes

#9437 Allow admins to bypass branch protection in community-modules
  prow/config.yaml
Labels: area/security, size/XS, lgtm, add-or-update, kind/chore, cla: yes

#9456 Tag telemetry-manager image with module version and remove release job
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-generic.yaml
  templates/data/telemetry-manager-data.yaml
Labels: size/M, lgtm, area/telemetry, kind/chore, cla: yes

#9471 Move job run to GH Action
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/ci, size/M, lgtm, kind/cleanup, cla: yes

#9484 Remove the eventing manager template.
  templates/data/eventing-manager-data.yaml
Labels: area/eventing, size/L, lgtm, kind/cleanup, cla: yes

#9487 fix run_if_changed for post backend busola
  prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, cla: yes

#9488 Ignore docker images based on regexp
  .gitleaks.toml
  cmd/cloud-run/scan-logs-for-secrets/kodata/gitleaks.toml
Labels: size/XS, lgtm, area/automation, kind/chore, cla: yes

#9498 allow post build job to run on release-* branches for eventing-manager
  prow/jobs/kyma-project/eventing-manager/eventing-manager-generic.yaml
Labels: area/eventing, size/M, lgtm, kind/feature, cla: yes

#9507 Fix serverless url
  prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
Labels: area/ci, size/XS, lgtm, kind/bug, cla: yes

#9499 removed jobs of directory-size-exporter
  prow/jobs/kyma-project/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: area/ci, size/M, lgtm, kind/cleanup, cla: yes

#9510 Ignore reconciler results as no non-migrated modules are left
  prow/scripts/reconciler/reconciler-e2e-gardener.sh
  prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
Labels: area/ci, size/XS, lgtm, kind/feature, cla: yes

#9505 Add required status check for KEB
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, cla: yes

#9516 add squash config for epp repository
  prow/config.yaml
Labels: area/eventing, size/XS, lgtm, kind/feature, cla: yes

#9518 Remove skr-aws-ugrade-integration test
  prow/jobs/kyma-project/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/scripts/cluster-integration/skr-aws-upgrade-integration-dev.sh
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, cla: yes

#9517 remove epp, eventing-tools, eventing-module jobs
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
  prow/jobs/kyma-project/eventing-manager/eventing-manager-generic.yaml
  prow/jobs/kyma-project/kyma/components/event-publisher-proxy/event-publisher-proxy-checks.yaml
  prow/jobs/kyma-project/kyma/components/eventing-controller/eventing-controller-checks.yaml
  prow/jobs/kyma-project/test-infra/prow-periodics.yaml
  templates/data/go-toolkit-validation.yaml
Labels: area/eventing, lgtm, kind/cleanup, cla: yes

#9519 Fix image building
  prow/jobs/kyma-project/test-infra/buildpack.yaml
  templates/data/test-infra/buildpack-data.yaml
Labels: area/ci, size/L, lgtm, kind/chore, cla: yes

#9462 Add ADO pipeline preview run feature and test
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  pkg/azuredevops/pipelines/pipelines.go
  pkg/azuredevops/pipelines/pipelines_test.go
  pkg/azuredevops/pipelines/templatesParams.go
Labels: size/L, lgtm, kind/missing-test, area/tools, cla: yes

#9524 Add Trial suspension E2E test prowjob
  prow/jobs/kyma-project/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
Labels: size/M, lgtm, kind/missing-test, area/tests, cla: yes

#9511 Adopt nats prow jobs for release flow.
  prow/jobs/kyma-project/nats-manager/nats-manager-generic.yaml
  templates/data/nats-manager-data.yaml
Labels: area/eventing, size/L, lgtm, kind/feature, cla: yes

#9529 add e2e-dind-nodejs-20 image with node 20.10
  images/e2e-dind-nodejs-20/Dockerfile
  images/e2e-dind-nodejs-20/init.sh
  images/e2e-dind-nodejs-20/test.sh
Labels: area/ci, size/L, lgtm, kind/feature, cla: yes

#9530 fix: Increase resources requests for cli release jobs
  prow/jobs/kyma-project/cli/cli-k3d.yaml
  prow/jobs/kyma-project/cli/cli.yaml
  templates/data/cli-data.yaml
Labels: area/cli, size/XS, lgtm, kind/flake, cla: yes

#9534 fix: Set resources limits for cli release jobs
  prow/jobs/kyma-project/cli/cli-k3d.yaml
  prow/jobs/kyma-project/cli/cli.yaml
  templates/data/cli-data.yaml
Labels: area/cli, size/XS, lgtm, kind/bug, cla: yes

#9532 Remove jobs for charts, website, istio-operator and director-size-exporter
  pkg/tools/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/image-detector/inrepo-config.yaml
  prow/jobs/kyma-project/test-infra/checkconfig.yaml
  prow/jobs/kyma-project/test-infra/pjconfigtests.yaml
  prow/jobs/kyma-project/test-infra/pjtester.yaml
  prow/jobs/kyma-project/test-infra/presubmit-scanner.yaml
  templates/config.yaml
Labels: area/ci, size/XL, lgtm, kind/cleanup, cla: yes

#9436 feat: Docs how to run ProwJobs locally
  docs/prow/pj-in-kind.md
Labels: area/ci, size/M, lgtm, kind/feature, cla: yes

#9533 enable wait for reconciler again
  prow/scripts/reconciler/reconciler-e2e-gardener.sh
  prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
Labels: area/ci, size/XS, lgtm, kind/bug, cla: yes

#9549 Remove not used KEB build jobs
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: area/ci, size/L, lgtm, kind/chore, cla: yes

#9551 change image for busola to e2e-dind-nodejs-20
  prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
  prow/jobs/kyma-project/busola/busola-integration.yaml
  prow/jobs/kyma-project/busola/lighthouse.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, cla: yes

#9540 Disable and remove label synchronisation
  docs/index.md
  docs/prow/label_sync.md
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
  prow/jobs/kyma-project/test-infra/prow-periodics.yaml
  prow/labels.yaml
Labels: area/ci, size/XL, lgtm, kind/cleanup, cla: yes

#9542 Add EPP image build job
  CODEOWNERS
  prow/jobs/kyma-project/eventing-publisher-proxy/eventing-publisher-proxy-generic.yaml
Labels: area/eventing, size/L, lgtm, kind/chore, cla: yes

#9560 Remove e2e-dind-nodejs-20, bump node version in e2e-dind-nodejs
  images/e2e-dind-nodejs-20/Dockerfile
  images/e2e-dind-nodejs-20/init.sh
  images/e2e-dind-nodejs-20/test.sh
  images/e2e-dind-nodejs/Dockerfile
  prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
Labels: area/ci, size/L, lgtm, kind/feature, cla: yes

#9563 change nodejs image for busola jobs
  prow/jobs/kyma-project/busola/busola-integration.yaml
  prow/jobs/kyma-project/busola/lighthouse.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, cla: yes

#9559 Remove ModuleTemplate building pipelines for Istio and API Gateway
  prow/jobs/kyma-project/api-gateway/api-gateway-manager-build.yaml
  prow/jobs/kyma-project/istio/istio-manager.yaml
  templates/data/api-gateway-manager-build.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, area/ci, size/L, lgtm, area/api-gateway, kind/cleanup, cla: yes

#9425 Dynamic Sources for serverless
  prow/jobs/kyma-project/kyma/tests/serverless/serverless-integration-k3d.yaml
  prow/jobs/kyma-project/serverless/serverless-verify.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
  templates/data/serverless.yaml
Labels: area/ci, size/M, lgtm, kind/feature, add-or-update, cla: yes

#9569 fix: post watcher build job
  prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml
Labels: lgtm, kind/bug, area/reconciler, cla: yes

#9571 Fix brackets in job
  prow/jobs/kyma-project/kyma/tests/serverless/serverless-integration-k3d.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, cla: yes

#9574 Update otters CODEOWNERS
  CODEOWNERS
Labels: area/ci, size/XS, lgtm, kind/cleanup, cla: yes

#9573 Fixed brackets for serverless jobs
  prow/jobs/kyma-project/serverless/serverless-verify.yaml
  templates/data/serverless.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, cla: yes

#9572 Move job to the correct directory
  prow/jobs/kyma-project/serverless/serverless-integration-k3d.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, cla: yes

#9570 Add background deletion test as a required check for lifecycle manager
  prow/config.yaml
Labels: size/XS, lgtm, area/tests, kind/chore, cla: yes

#9576 Remove not needed OPA Gatekeeper config
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
Labels: area/ci, size/XS, lgtm, kind/cleanup, cla: yes

#9577 Switch operators builds to use specific dockerfiles
  prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/ci, size/S, lgtm, kind/feature, cla: yes

#9538 Build image-builder in ado.
  prow/cluster/resources/gatekeeper-constraints/workloads/imageBuilderAdoSecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
  prow/jobs/kyma-project/test-infra/buildpack.yaml
  prow/jobs/kyma-project/test-infra/images.yaml
  templates/data/test-infra/buildpack-data.yaml
Labels: area/ci, size/M, lgtm, kind/feature, cla: yes

#9581 Build buildkit version of image-builder in ado
  cmd/image-builder/images/buildkit/Dockerfile
  prow/jobs/kyma-project/test-infra/images.yaml
Labels: area/ci, size/L, lgtm, kind/feature, cla: yes

#9592 Unblock terraform, disable automatic update for restricted actions
  .github/dependabot.yml
  .github/workflows/post-apply-prod-terraform.yaml
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/S, lgtm, kind/bug, area/automation, cla: yes

#9588 Rename post verify target for warden
  prow/jobs/kyma-project/warden/warden-verify.yaml
  templates/data/warden.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup, cla: yes

#9586 Add TF config for Security Dashboard auth Cloud Run
  configs/terraform/environments/prod/security-dashboard-token.tf
  configs/terraform/modules/security-dashboard-token/main.tf
  configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
Labels: size/M, lgtm, kind/feature, add-or-update, area/automation, cla: yes

#9595 Fix name of the security-dashboard-token Cloud Run
  configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update, cla: yes

#9589 Change trigger of EPP build job
  prow/jobs/kyma-project/eventing-publisher-proxy/eventing-publisher-proxy-generic.yaml
Labels: area/eventing, size/XS, lgtm, add-or-update, kind/chore, cla: yes

#9593 Add possibility to use kaniko build config from PR in ADO Builder
  cmd/image-builder/main.go
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: area/security, size/S, lgtm, kind/feature, cla: yes
