Repository kyma-project/test-infra, pull requests merged in 2023-11, with the labels that each got.

#9187 Adjust jobs to work with new serverless-manager's Dockerfile
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
  prow/jobs/kyma-project/serverless-manager/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/M, lgtm, kind/cleanup, destroy

#9236 Fix GitHub Actions link
  .github/workflows/lint-markdown-links-daily.yml
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update

#9240 Change repo name to serverless
  prow/jobs/kyma-project/serverless-manager/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup, add-or-update

#9248 Sync latest kedacore images
  cmd/image-syncer/external-images.yaml
Labels: area/serverless, size/XS, lgtm, add-or-update, kind/chore

#9250 Update nextRelease to 2.21
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/S, lgtm, add-or-update, kind/chore

#9249 Change serverless manager to serverless
  CODEOWNERS
  prow/cluster/components/monitoring/dashboards/quality/prstats.json
  prow/config.yaml
  prow/jobs/kyma-project/serverless/serverless.yaml
  prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/M, lgtm, kind/cleanup, add-or-update

#9246 Fix GitHub Action URL
  .github/workflows/lint-markdown-links-daily.yml
Labels: area/ci, size/XS, lgtm, add-or-update, kind/chore

#9255 Name of the final job for btp-manager e2e test changed
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update

#9257 Remove openssl dependency in VM image building
  .githooks/pre-commit.d/01-rendertemplates.sh
  experimental/custom-image/create-custom-image.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#9247 Tag Istio ModuleTemplate with release tag
  prow/jobs/kyma-project/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update

#9238 Update links
  README.md
  docs/documentation_guidelines.md
  docs/prow/manage-component-jobs-with-templates.md
  docs/prow/prow-jobs-quick-start.md
  docs/prow/quality-metrics.md
  experimental/custom-image/README.md
Labels: area/documentation, size/M, lgtm, kind/cleanup

#9259 Fix trusted secrets config
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, destroy

#9245 remove telemetry upgrade job
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-upgrade-test.yaml
Labels: area/ci, size/M, lgtm, add-or-update, kind/chore

#9239 Enable publishing watcher images with tags
  prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml
Labels: size/S, lgtm, kind/feature, add-or-update, area/reconciler

#9252 Add istio job
  prow/jobs/kyma-project/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, size/L, lgtm, kind/feature, add-or-update

#9265 Add KEB release job
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/M, lgtm, area/control-plane, kind/feature, add-or-update

#9267 Add version arg to the runtime-watcher prowjob
  prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, add-or-update

#9266 Adjust serverless jobs to the new Makefile paths
  prow/jobs/kyma-project/serverless/serverless.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/M, lgtm, kind/cleanup, add-or-update

#9270 Post Warden Integration with LM Jobs
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/warden.yaml
Labels: area/ci, size/M, lgtm, kind/feature, add-or-update

#9271 Bump k8s to 1.27.7
  experimental/custom-image/install-deps-debian.sh
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-garden/Dockerfile
  prow/config.yaml
  prow/scripts/reconciler/common.sh
  prow/scripts/reconciler/shoot-template.yaml
Labels: area/ci, size/S, lgtm, add-or-update, kind/chore

#9280 Fix KEB post release build
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/XS, lgtm, area/control-plane, kind/bug, add-or-update

#9288 Update Warden Verify job
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/warden.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update

#9286 Add keb release build to allowed jobs for signify secret
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
Labels: area/security, size/XS, lgtm, destroy, kind/chore

#9295 Rename post python39 build
  prow/jobs/kyma-project/serverless/serverless.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup, add-or-update

#9294 Add `latest` tag for post-main tpi otters images
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: area/serverless, size/XS, lgtm, kind/feature, add-or-update

#9307 Fix tagging KEB release builds
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/S, lgtm, area/control-plane, kind/bug, add-or-update

#9305 switch k8s to 1.27.5
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-garden/Dockerfile
Labels: area/ci, size/XS, lgtm, kind/bug

#9306 fix test pre-serverless-integration-k3s
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
Labels: area/serverless, area/ci, kind/failing-test, size/XS, lgtm

#9318 bump go image
  cmd/image-syncer/external-images.yaml
Labels: area/eventing, size/XS, lgtm, add-or-update, kind/chore

#9316 Add pipelines for template-operator releases
  prow/jobs/kyma-project/template-operator/template-operator.yaml
  templates/data/template-operator-data.yaml
Labels: size/L, lgtm, kind/feature, add-or-update, area/reconciler

#9319 switch k8s to 1.27.5
  prow/scripts/reconciler/common.sh
  prow/scripts/reconciler/shoot-template.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update

#9321 feat: Increase cli unit test memory
  prow/jobs/kyma-project/cli/cli.yaml
  templates/data/cli-data.yaml
Labels: area/cli, kind/failing-test, size/XS, lgtm, add-or-update

#9322 removed jobs for orphaned 3party images
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: area/ci, lgtm, kind/cleanup, add-or-update

#9320 Add golangci config
  prow/jobs/kyma-project/keda-manager/keda-manager.yaml
  prow/jobs/kyma-project/serverless/serverless.yaml
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/generic_module_data.yaml
  templates/data/warden.yaml
Labels: area/ci, size/M, lgtm, kind/cleanup, add-or-update

#9328 Spit generic component data
  templates/data/generic_module_data.yaml
  templates/data/keda-manager.yaml
  templates/data/serverless.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup, add-or-update

#9327 remove kyma-upgrade-gardener-kyma2-minor-versions
  prow/jobs/kyma-project/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/M, lgtm, area/prow, kind/deprecation, add-or-update

#9333 remove kyma-upgrade-gardener-kyma2-minor-versions
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update

#9335 fix: release-build args template-operator
  prow/jobs/kyma-project/template-operator/template-operator.yaml
Labels: area/ci, lgtm, kind/bug, add-or-update

#9339 Fix tofu build command
  .github/workflows/post-apply-prod-terraform.yaml
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/XS, lgtm, kind/bug, area/automation

#9342 Finalize migration to github actions and tofu for terraform
  configs/terraform/environments/prod/output.tf
  configs/terraform/environments/prod/terraform-executor-variables.tf
  configs/terraform/environments/prod/terraform-executor.tf
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
Labels: size/L, lgtm, kind/bug, area/automation, destroy

#9344 Fix tfcmt action used.
  .github/workflows/post-apply-prod-terraform.yaml
Labels: size/XS, lgtm, kind/bug, add-or-update, area/automation

#9346 Update testimage dependencies
  images/alpine/Dockerfile
  images/buildpack/Dockerfile
  images/buildpack/go/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
  images/unified-agent/Dockerfile
  images/unified-agent/go/Dockerfile
Labels: area/ci, size/M, lgtm, kind/chore

#9353 Remove custom-image build jobs
  prow/jobs/kyma-project/test-infra/build-test-vm-image.yaml
  templates/data/test-infra/build-test-vm-image.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update

#9356 Remove custom-image
  experimental/custom-image/create-custom-image.sh
  experimental/custom-image/install-deps-debian.sh
  experimental/custom-image/machine-id-clean-up.sh
  experimental/custom-image/resources/dbus-1_system-local.conf
Labels: area/ci, size/L, lgtm, kind/cleanup

#9357 Add Istio 1.12.0 distroless images to external-images.yaml for image-syncer
  cmd/image-syncer/external-images.yaml
Labels: area/service-mesh, lgtm, kind/feature, add-or-update

#9358 OPA constraints update for release-template-operator-assets prowjob.
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
Labels: area/ci, size/XS, lgtm, destroy, kind/chore

#9359 Remove pre-main-ory-reconciler-eval-integration-k3d
  prow/jobs/kyma-incubator/reconciler/reconciler.yaml
  prow/scripts/provision-vm-and-run-manager.sh
  prow/scripts/provision-vm-and-start-reconciler-istio-integration-k3d.sh
  templates/data/incubator-buildpack-data.yaml
  templates/data/istio-module-data.yaml
  templates/data/telemetry-manager-data.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update

#9345 Cleanup old definitions for terraform
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/images/terraform/Dockerfile
  prow/jobs/kyma-project/test-infra/hide-terraform-comments.yaml
Labels: size/L, lgtm, kind/cleanup, area/automation, destroy

#9360 exclude gitleaks
  cmd/cloud-run/scan-logs-for-secrets/kodata/gitleaks.toml
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  pkg/sign/notary_test.go
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
Labels: area/ci, size/XL, lgtm, kind/bug, add-or-update

#9369 add separate gitleaks config for repo scan
  .gitleaks.toml
Labels: area/security, size/XXL, lgtm, kind/chore

#9330 Initial smoke-test framework for docker testimages
  images/README.md
  images/build-images.sh
  images/buildpack/go/test.sh
  images/e2e-dind-k3d/test.sh
  images/e2e-dind-nodejs/test.sh
Labels: area/ci, size/M, lgtm, kind/feature

#9370 adjust run_if_changed for serverless, keda-manager and warden jobs
  prow/jobs/kyma-project/keda-manager/keda-manager-build.yaml
  prow/jobs/kyma-project/keda-manager/keda-manager-lint.yaml
  prow/jobs/kyma-project/keda-manager/keda-manager-verify.yaml
  prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
  prow/jobs/kyma-project/serverless/serverless-build.yaml
  prow/jobs/kyma-project/serverless/serverless-lint.yaml
  prow/jobs/kyma-project/serverless/serverless-verify.yaml
  prow/jobs/kyma-project/warden/integration-test.yaml
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/keda-manager.yaml
  templates/data/serverless.yaml
  templates/data/warden.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update

#9355 remove dump job
  prow/jobs/kyma-incubator/compass/compass-integration-with-dump.yaml
Labels: size/M, lgtm, area/prow, kind/feature, add-or-update

#9382 bug: Fix label-sync configuration
  prow/jobs/kyma-project/test-infra/prow-periodics.yaml
  prow/plugins.yaml
  templates/data/test-infra/prow-periodics-data.yaml
Labels: area/ci, size/L, lgtm, kind/bug, add-or-update

#9383 chore: bump slackmessagesender to alpine 3.18
  cmd/cloud-run/slack-message-sender/Dockerfile
  prow/jobs/kyma-project/compass-manager/static-checks.yaml
  prow/jobs/kyma-project/test-infra/presubmit-scanner.yaml
  templates/data/test-infra/presubmit_scanner_data.yaml
Labels: area/ci, size/M, lgtm, add-or-update, kind/chore

#9385 Remove prowjobparser and certbotauthenticator
  cmd/prowjobparser/Makefile
  cmd/prowjobparser/README.md
  cmd/prowjobparser/main.go
  docs/index.md
  prow/scripts/lib/utils.sh
Labels: area/ci, size/L, lgtm, kind/cleanup

#9381 Remove KMS rotation
  .koapps.yaml
  cmd/cloud-run/kms-rotate/README.md
  cmd/cloud-run/kms-rotate/kms-rotate.go
  cmd/cloud-run/kms-rotate/kms-rotate_test.go
  docs/index.md
  docs/prow/presets.md
  prow/config.yaml
  prow/jobs/kyma-incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci, size/XL, lgtm, add-or-update, kind/chore

#9391 bug: fix gatekeeper constraint for label-sync
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, destroy

#9393 move warden integration test to template
  prow/jobs/kyma-project/warden/integration-test.yaml
  templates/data/warden.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update

#9400 add libgit2 to image golangci-lint
  prow/images/golangci-lint/Dockerfile
Labels: area/ci, kind/failing-test, size/XS, lgtm

#9397 Add merge config for template-operator
  prow/config.yaml
Labels: lgtm, area/prow, add-or-update, kind/chore

#9407 Use Long Sha in build Jobs
  prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-build.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/M, lgtm, kind/feature, add-or-update

#9406 Bump PyGithub
  cmd/cloud-run/slack-message-sender/requirements.txt
Labels: size/XS, lgtm, area/automation, kind/chore

#9398 remove Grafana
  .koapps.yaml
  cmd/image-url-helper/excludes.yaml
  cmd/tools/githubissues/README.md
  cmd/tools/githubissues/main.go
  cmd/tools/githubissues/table_org_schema.json
  cmd/tools/githubissues/table_repo_schema.json
  docs/index.md
  docs/prow/prow-monitoring.md
  docs/prow/quality-metrics.md
  go.mod
  go.sum
  prow/cluster/components/monitoring/dashboards/Makefile
  prow/cluster/components/monitoring/dashboards/jsonnet/deck.jsonnet
  prow/cluster/components/monitoring/dashboards/jsonnet/ghproxy.jsonnet
  prow/cluster/components/monitoring/dashboards/jsonnet/hook.jsonnet
  prow/cluster/components/monitoring/dashboards/jsonnet/plank.jsonnet
  prow/cluster/components/monitoring/dashboards/jsonnet/prow.jsonnet
  prow/cluster/components/monitoring/dashboards/jsonnet/sinker.jsonnet
  prow/cluster/components/monitoring/dashboards/jsonnet/tide.jsonnet
  prow/cluster/components/monitoring/dashboards/jsonnetfile.json
  prow/cluster/components/monitoring/dashboards/jsonnetfile.lock.json
  prow/cluster/components/monitoring/dashboards/lib/config.libsonnet
  prow/cluster/components/monitoring/dashboards/lib/config_util.libsonnet
  prow/cluster/components/monitoring/dashboards/quality/prstats.json
  prow/cluster/components/monitoring/dashboards/quality/quality.json
  prow/cluster/components/monitoring/dashboards/quality/test_coverage.json
  prow/cluster/components/monitoring/dashboards/serverless/serverless-controller-dashboard.json
  prow/cluster/components/monitoring/grafana_configmaps.yaml
  prow/cluster/components/monitoring/grafana_deployment.yaml
  prow/cluster/components/monitoring/grafana_expose.yaml
  prow/cluster/components/monitoring/grafana_rbac.yaml
  prow/cluster/components/monitoring/grafana_secret.yaml
  prow/cluster/components/monitoring/monitoring-kyma-prow_managedcertificate.yaml
  prow/cluster/components/monitoring/prow_servicemonitors.yaml
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwToolsNamespaces.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSapTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/cluster/resources/monitoring/.gitignore
  prow/cluster/resources/monitoring/Chart.yaml
  prow/cluster/resources/monitoring/README.md
  prow/cluster/resources/monitoring/alertmanager-config.yaml
  prow/cluster/resources/monitoring/dashboards/grafana-prow.json
  prow/cluster/resources/monitoring/grafana-config.yaml
  prow/cluster/resources/monitoring/prometheus-config.yaml
  prow/cluster/resources/monitoring/requirements.lock
  prow/cluster/resources/monitoring/requirements.yaml
  prow/cluster/resources/monitoring/templates/grafana/configmap-dashboards.yaml
  prow/cluster/resources/monitoring/templates/prow_prometheusrules.yaml
  prow/cluster/resources/monitoring/values.yaml
  prow/jobs/kyma-project/kyma/kyma-validation.yaml
  prow/jobs/kyma-project/kyma/periodics.yaml
  templates/data/kyma-validation-data.yaml
Labels: size/XXL, lgtm, area/telemetry, destroy, kind/chore

#9415 Bump gitleaks
  cmd/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
  go.mod
  go.sum
Labels: area/ci, size/S, lgtm, kind/chore

#9420 bug: fix cla assistant autolabeling
  prow/plugins.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update

#9412 Remove image mitigation for Grafana
  docs/security/imagemitigation.json
Labels: area/security, size/S, lgtm, kind/chore, cla: yes

#9422 Remove success alerts for k8s-prow-periodics
  prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, kind/chore, cla: yes

#9424 Remove whitesource jobs migrated to the new solution
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci, size/XL, lgtm, kind/cleanup, add-or-update, cla: yes

#9396 CMP Group access
  CODEOWNERS
Labels: area/security, size/XS, lgtm, kind/cleanup, cla: yes

#9399 Remove api-gateway component leftovers
  prow/jobs/kyma-incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/cluster-integration/reconciler-istio-integration.sh
  prow/scripts/reconciler/reconciler-component-provision-gardener.sh
  prow/scripts/reconciler/reconciler-ory-production-gardener-integration.sh
  templates/data/incubator-buildpack-data.yaml
Labels: area/ci, size/L, lgtm, add-or-update, kind/chore, cla: yes

#9423 Build serverless images more frequently
  prow/jobs/kyma-project/kyma/tests/serverless/serverless-integration-k3d.yaml
  prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-build.yaml
  prow/jobs/kyma-project/serverless/serverless-verify.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/L, lgtm, kind/feature, add-or-update, cla: yes

#9428 remove jobs and references to fast-integration tests in kyma
  pkg/tools/pjtester/test_artifacts/test-prow-config.yaml
  prow/jobs/kyma-project/kyma/kyma-integration-gardener-eventing.yaml
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/cluster-integration/kyma-integration-skr-eventing.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
  prow/scripts/cluster-integration/skr-aws-upgrade-integration-dev.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/lib/utils.sh
  prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup, area/tests, add-or-update, cla: yes

#9426 Remove unused lines for serverless builds
  prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-build.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/S, lgtm, kind/cleanup, add-or-update, cla: yes

#9438 Add missing lifecycle manager required checks
  prow/config.yaml
Labels: size/XS, lgtm, area/tests, add-or-update, kind/chore, cla: yes
