Repository kyma-project/test-infra, pull requests merged in 2023-03, with the labels that each got.

#7021 PR(Keda) -> Main(Keda) Upgradability test
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/L, lgtm

#7089 add jobs for eventing-tools (build|test)
  prow/jobs/eventing-tools/eventing-tools-checks.yaml
  prow/jobs/eventing-tools/eventing-tools-generic.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/L, lgtm

#7031 Updated documentation to reflect migration to cloud run
  development/secrets-rotator/cloud-run/service-account-keys-cleaner/README.md
Labels: size/M, lgtm

#7028 add serverless manager integration tests
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/L, lgtm

#7098 change build trigger for eventing tools jobs
  prow/jobs/eventing-tools/eventing-tools-generic.yaml
Labels: size/XS, lgtm

#7090 Introduce build pipeline for Istio module
  prow/jobs/istio/istio-operator-build.yaml
  prow/jobs/istio/istio-validation.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/istio-module-data.yaml
  templates/data/istio-operator-build.yaml
  templates/data/istio-validation.yaml
Labels: size/XL, lgtm

#7100 Increase resources for telemetry manager jobs
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/S, lgtm

#7101 tag eventing-tools as latest
  prow/jobs/eventing-tools/eventing-tools-generic.yaml
  templates/data/eventing-tools-data.yaml
Labels: size/M, lgtm

#7030 Migrate rotate secrets service account cleaner to cloud run
  development/secrets-rotator/cloud-run/rotate-service-account/rotateserviceaccount.go
  development/secrets-rotator/cloud-run/service-account-keys-cleaner/Dockerfile
  development/secrets-rotator/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
  development/secrets-rotator/cloud-run/service-account-keys-cleaner/serviceaccountcleaner_test.go
Labels: size/XL, lgtm

#7107 Increase linter timeout.
  .golangci.yaml
Labels: size/XS, lgtm

#7113 Bump postgres 11.19 alpine3.17
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7124 Make Keda Pipe non-optional
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/XS, lgtm

#7118 Add telemetry-manager integration test
  CODEOWNERS
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-integration-test.yaml
Labels: size/M, lgtm

#7132 Fix post-keb-trial-cleanup-job-build trigger
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/control-plane-build.yaml
Labels: size/XS, lgtm

#7129 Align prowjobs running terraform executor with secrets rotator application tf config.
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: size/S, lgtm

#7125 Adding user provided labels and annotations to prowjob specification.
  development/tools/pkg/pjtester/pjtester.go
Labels: size/S, lgtm, kind/bug

#7120 Increase resources for linter. Hit timeoute again.
  prow/jobs/test-infra/go-validation.yaml
  templates/data/test-infra/golang-tests.yaml
Labels: kind/failing-test, lgtm

#7149 Remove module-manager scans
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/M, lgtm

#7126 Build terraform config for secrets rotator.
  development/secrets-rotator/terraform/environments/dev/.terraform.lock.hcl
  development/secrets-rotator/terraform/environments/dev/backend.tf
  development/secrets-rotator/terraform/environments/dev/main.tf
  development/secrets-rotator/terraform/environments/dev/provider.tf
  development/secrets-rotator/terraform/environments/dev/terraform.tfvars
  development/secrets-rotator/terraform/environments/dev/variables.tf
  development/secrets-rotator/terraform/environments/prod/.terraform.lock.hcl
  development/secrets-rotator/terraform/environments/prod/backend.tf
  development/secrets-rotator/terraform/environments/prod/main.tf
  development/secrets-rotator/terraform/environments/prod/provider.tf
  development/secrets-rotator/terraform/environments/prod/terraform.tfvars
  development/secrets-rotator/terraform/environments/prod/variables.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/main.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/output.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/provider.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/variables.tf
Labels: size/XL, lgtm, add-or-update, area/automation

#7131 add env variable EVENTING_UPGRADE_JOB to the eventing upgrade job
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, size/XS, lgtm

#7147 Fix pull-btp-manager-build to always run
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/XS, lgtm

#7134 Fixed usage of wrong type to load http request body to.
  development/gcp/cloud-run/gardener-sa-rotate/gardener-sa-rotate_test.go
  development/gcp/pkg/pubsub/types.go
  development/secrets-rotator/cloud-run/rotate-service-account/rotateserviceaccount.go
Labels: size/S, lgtm

#7152 Fix api-gateway release jobs
  prow/jobs/api-gateway/api-gateway-release.yaml
  templates/data/api-gateway-release.yaml
Labels: size/XS, lgtm

#7082 Minor fixes in secret leaks detector application 🔥 🥇
  configs/terraform/prow/main.tf
  configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
  development/gcp/cloud-run/move-gcs-bucket/move-gcs-bucket.go
  development/gcp/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
  development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
  development/gcp/workflows/secrets-leak-detector.yaml
Labels: size/M, lgtm, add-or-update

#7150 Add preset label to mount gh token.
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: lgtm, kind/bug

#7160 Update Keda Upgrade pipe
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/XS, lgtm

#7163 Prepare release 2.12
  development/tools/jobs/releases/releases.go
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-213.yaml
  prow/jobs/kyma/releases/kyma-release-28.yaml
  prow/jobs/kyma/releases/kyma-release-29.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/XXL, lgtm

#7164 Serverless nightly pipe
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/L, lgtm

#7194 Use latest prod images in secret leak detector.
  configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
Labels: size/S, lgtm, add-or-update

#7182 Generate tekton k8s cluster sa token valid for 365 days.
  configs/gencred-config.yaml
Labels: size/XS, lgtm

#7185 image-builder: Change 'PR' tag name to `default_tag`
  development/image-builder/main.go
  development/image-builder/main_test.go
Labels: size/M, lgtm

#7197 Change error in gencred config
  configs/gencred-config.yaml
Labels: priority/critical, area/ci, size/XS, kind/bug

#7183 Use the another make target for the verify job
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup

#7199 Bump image-builder image
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/btp-manager/btp-manager-build.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-build.yaml
  prow/jobs/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/eventing-tools/eventing-tools-generic.yaml
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma-project/warden/warden.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  prow/jobs/slack-bot/slack-bot-build.yaml
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  prow/jobs/template-operator/template-operator.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  prow/jobs/test-infra/terraform-executor.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/control-plane-build.yaml
  templates/data/generic_module_data.yaml
  templates/data/istio-module-data.yaml
  templates/data/runtime-watcher-data.yaml
Labels: size/L, lgtm

#7195 Removed pre-main-kyma-gardener-gcp-subscription-upgrade
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-subscription-upgrade.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: area/eventing, size/L, lgtm

#7200 Add external image for `golang:v1.20.2-alpine3.17`.
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7210 Update NATS 2.9.15
  development/image-syncer/external-images.yaml
Labels: area/eventing, size/XS, lgtm

#7212 Add istio 1.17.1 images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7181 eventing-tools autobumper job
  prow/autobump-config/eventing-tools-autobump-config.yaml
  prow/jobs/eventing-tools/eventing-tools-generic.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/eventing-tools-data.yaml
  templates/data/prow-periodics-data.yaml
Labels: size/M, lgtm

#7221 Remove dots
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
Labels: area/ci, size/XS, lgtm

#7189 Adding information about labels.
  docs/how-to/how-to-add-custom-secret.md
Labels: area/ci, size/XS, lgtm

#7162 Add serverless git auth integration local
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3s-local.sh
  prow/scripts/cluster-integration/kyma-serverless-integration-k3s.sh
  prow/scripts/lib/serverless-shared-k3s.sh
  prow/scripts/provision-vm-and-start-serverless-k3s-local.sh
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#7236 Add Tunas bot token
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#7215 move eventing-tools autobump config to eventing-tools repository
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: size/S, lgtm

#7237 Add guide on how to use K3d in a pod
  docs/prow/k3d-no-ssh.md
Labels: size/L, lgtm

#7208 Added terraform label
  prow/labels.yaml
Labels: size/XS, lgtm

#7249 Remove verification of telemetry production profile
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
Labels: size/S, lgtm, area/telemetry

#7157 Add tf module for sa keys cleaner
  development/secrets-rotator/terraform/environments/dev/main.tf
  development/secrets-rotator/terraform/environments/dev/terraform.tfvars
  development/secrets-rotator/terraform/environments/dev/variables.tf
  development/secrets-rotator/terraform/environments/prod/main.tf
  development/secrets-rotator/terraform/environments/prod/terraform.tfvars
  development/secrets-rotator/terraform/environments/prod/variables.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/main.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/variables.tf
  development/secrets-rotator/terraform/modules/service-account-keys-cleaner/main.tf
  development/secrets-rotator/terraform/modules/service-account-keys-cleaner/output.tf
  development/secrets-rotator/terraform/modules/service-account-keys-cleaner/provider.tf
  development/secrets-rotator/terraform/modules/service-account-keys-cleaner/variables.tf
  development/secrets-rotator/terraform/placeholder_for_tf_files
Labels: size/L, lgtm, add-or-update

#7211 Upgrade serverless-manager make targets
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/S, lgtm

#7233 Checkout tests from version we are upgrading to after upgrade
  prow/scripts/cluster-integration/reconciler-integration-with-cli-upgrade-k3d.sh
Labels: size/XS, lgtm

#7264 Clean orphaned disks, decrease resource requests.
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/pjtester-data.yaml
  templates/data/prow-periodics-data.yaml
  templates/data/test-infra/pjconfigtests.yaml
Labels: lgtm, kind/cleanup

#7228 Removed pre-main-kyma-gardener-gcp-eventing-v1alpha2
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#7227 Serverless integration cleanup
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
  prow/scripts/cluster-integration/kyma-serverless-integration-k3s-local.sh
  prow/scripts/lib/serverless-shared-k3s.sh
  prow/scripts/provision-vm-and-start-serverless-k3d.sh
  prow/scripts/provision-vm-and-start-serverless-k3s.sh
  templates/data/generic_component_data.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#7257 Move Keda Upgrade to Post
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/L, lgtm

#7267 Adjust disks cleaner regex.
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#7259 Remove ProwJobs from archived repositories
  prow/jobs/examples/examples-buildpack.yaml
  prow/jobs/incubator/documentation-component/documentation-component.yaml
  prow/jobs/incubator/github-slack-connectors/github-slack-connectors.yaml
  prow/jobs/incubator/hydra-login-consent/hydra-login-consent.yaml
  prow/jobs/incubator/knative-kafka/knative-kafka.yaml
  prow/jobs/incubator/kyma-showcase/kyma-showcase.yaml
  prow/jobs/incubator/varkes/varkes.yaml
  prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
  templates/data/examples-data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/kyma-showcase-data.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup

#7201 Comparing CRD table in MD files
  prow/jobs/governance.yaml
  prow/scripts/governance.sh
  templates/data/governance-data.yaml
Labels: size/S, lgtm

#7243 Make istio reconciler jobs fail on failed reconciliation
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/cluster-integration/reconciler-istio-integration.sh
  prow/scripts/provision-vm-and-start-reconciler-istio-integration-k3d.sh
  templates/data/incubator-buildpack-data.yaml
Labels: size/M, lgtm

#7281 Remove unused jobs for nodejs16 function runtime
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#7289 Fix test-infra governance jobs
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: size/S, lgtm

#7293 Remove jobs tests from Makefile
  Makefile
  development/tools/Makefile
Labels: size/XS, lgtm

#7291 Add istio 1.16.3 to image registry
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7256 Install latest CLI
  development/custom-image/create-custom-image.sh
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
  prow/scripts/cluster-integration/busola-lighthouse.sh
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
  prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma2-to-main.sh
  prow/scripts/lib/kyma.sh
Labels: size/M, lgtm

#7296 Fix autobumper config
  prow/autobump-config/test-infra-autobump-config.yaml
  templates/templates/test-infra-autobump-config.yaml
Labels: size/XS, lgtm

#7286 Cleanup of not used GCP service accounts
  development/prow-installer/config/prow-installer-config.yaml
  docs/prow/authorization.md
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
  templates/README.md
Labels: size/S, lgtm

#7297 Remove not used preset-gke-pod-security-policy
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  templates/templates/prow-config.yaml
Labels: size/S, lgtm

#7260 Removed unused cloud functions code.
  development/gcp/cloud-functions/getGithubIssue/.gcloudignore
  development/gcp/cloud-functions/getGithubIssue/getgithubissue.go
  development/gcp/cloud-functions/rotateserviceaccount/.gcloudignore
  development/gcp/cloud-functions/rotateserviceaccount/README.md
  development/gcp/cloud-functions/rotateserviceaccount/go.mod
  development/gcp/cloud-functions/rotateserviceaccount/go.sum
  development/gcp/cloud-functions/rotateserviceaccount/rotateserviceaccount.go
  development/gcp/cloud-functions/serviceaccountcleaner/README.md
  development/gcp/cloud-functions/serviceaccountcleaner/go.mod
  development/gcp/cloud-functions/serviceaccountcleaner/go.sum
  development/gcp/cloud-functions/serviceaccountcleaner/serviceaccountcleaner.go
  development/gcp/cloud-functions/serviceaccountcleaner/serviceaccountcleaner_test.go
  docs/index.md
Labels: size/XXL, lgtm, kind/cleanup

#7292 Update go version
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
Labels: size/XS, lgtm

#7300 Upgrade Kubernetes to 1.26
  development/custom-image/install-deps-debian.sh
  prow/config.yaml
  prow/images/bootstrap/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-211.yaml
  prow/jobs/kyma/releases/kyma-release-212.yaml
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
Labels: size/M, lgtm

#7282 Remove gke external registry job
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/scripts/cluster-integration/kyma-gke-external-registry.sh
  prow/scripts/resources/kyma-serverless-external-registry-integration-overrides.tpl.yaml
  templates/data/kyma-gke-external-registry-data.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#7310 Use K8s 1.26.1 for Gardener clusters
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#7290 Replace Keda Upgrade job
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/M, lgtm

#7283 Add ias adapter job definition
  prow/jobs/incubator/compass/components/ias-adapter/ias-adapter-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/L, lgtm

#7311 Upgrade gardenlinux to 934.6.0
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
  prow/scripts/resources/skr-test/shoot-template.yaml
Labels: size/S, lgtm

#7313 add dedicated lint and unit-test jobs for cli
  prow/jobs/cli/cli.yaml
  templates/data/cli-data.yaml
Labels: size/M, lgtm

#7314 Fix linting
  development/external-plugins/automerge-notification/main.go
  development/external-plugins/test-untrusted/cmd/main.go
  development/gcbuild/main.go
  development/image-builder/main.go
  development/markdown-index/bumper/bumper.go
  development/tools/cmd/dnscleaner/main.go
  development/tools/cmd/rendertemplates/main.go
  development/tools/pkg/gcscleaner/storage/bucket.go
  development/tools/pkg/release/mock.go
  development/tools/pkg/rendertemplates/rendertemplates.go
Labels: size/M, lgtm

#7319 Revert to Old Cli
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/kyma.sh
Labels: size/M, lgtm

#7315 Remove old job to build serverless tests
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
Labels: size/M, lgtm

#7318 change eventing-tools build trigger
  CODEOWNERS
  prow/jobs/eventing-tools/eventing-tools-generic.yaml
  templates/data/eventing-tools-data.yaml
Labels: size/S, lgtm

#7312 Upgrade kyma manager make targets
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/M, lgtm

#7330 Revert K8s 1.26 for Gardener clusters
  prow/config.yaml
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
  prow/scripts/resources/skr-test/shoot-template.yaml
  templates/templates/prow-config.yaml
Labels: size/S, lgtm

#7332 remove transfigure paragraph
  docs/prow/prow-k8s-testgrid.md
Labels: size/XS, lgtm

#7280 Unify serverless run script
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
  prow/scripts/cluster-integration/kyma-serverless-run-test.sh
  prow/scripts/lib/serverless-shared-k3s.sh
Labels: size/M, lgtm

#7333 Run API-Gateway kyma component tests on recources/istio changes
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm

#7339 Disabled Privileged Containers
  prow/scripts/resources/skr-test/shoot-template.yaml
Labels: size/XS, lgtm

#7347 Use updated pjtester.
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-validation.yaml
  prow/jobs/test-infra/kyma-bot.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/config.yaml
  templates/data/test-infra/pjtester-data.yaml
Labels: size/L, lgtm

#7353 Revert "Comparing CRD table in MD files (#7201)"
  prow/jobs/governance.yaml
  prow/scripts/governance.sh
  templates/data/governance-data.yaml
Labels: size/S, lgtm

#7356 compass manager
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/XS, lgtm

#7357 Add `compass-manager` repo
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  templates/config.yaml
Labels: size/L, lgtm

#7358 Change frogs to team
  CODEOWNERS
Labels: size/XS, lgtm

#7148 Move CRA tests to DinD, make app connector tests required
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-tests.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#7349 Update tekton default config.
  tekton/deployments/config_defaults.yaml
Labels: size/S, lgtm

#7378 Include .env in keda module job triggers
  CODEOWNERS
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/S, lgtm

#7354 Tekton demo prowjob update
  docs/examples/tekton-demo.yaml
Labels: size/L, lgtm

#7383 Rotate Kyma-dev kubeconfig
  development/gardener-rotate/gardener-kyma-dev-config.yaml
  prow/jobs/test-infra/gardener-kubeconfig-rotation.yaml
  templates/data/secret-rotation-data.yaml
Labels: size/M, lgtm

#7384 Change merging policy for compass-manager
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#7348 Updated dashboard and pipelines releases to newest versions.
  tekton/deployments/dashboard_release.yaml
  tekton/deployments/pipelines_release.yaml
Labels: size/L, lgtm

#7381 Adjust CODEOWNERS for Goats
  CODEOWNERS
Labels: area/ci, size/S, lgtm

#7379 add dedicate unit test job for reconciler
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/M, lgtm
