Repository kyma-project/test-infra, pull requests merged in 2023-06, with the labels that each got.

#7793 Fix image urls extractions from prowjobs without spec
  development/pkg/extractimageurls/prowjob.go
  development/pkg/extractimageurls/prowjob_test.go
Labels: area/security, size/S, lgtm, kind/bug

#7796 Fix linting
  prow/scripts/resources/autobumper/.golangci.yaml
Labels: kind/failing-test, size/XS, lgtm, area/tests, no-changes

#7780 Autobump list of images in sec-scanner-config.yml
  development/image-detector/bumper/bumper.go
  development/image-detector/main.go
  prow/image-detector/test-infra-sec-config-autobump-config.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/ci, size/XL, lgtm, kind/feature, no-changes

#7800 Remove profile for serverless tests
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
Labels: area/serverless, size/XS, lgtm, kind/chore

#7801 Bump yaml dependency
  development/tools/pkg/pjtester/pjtester.go
  go.mod
  go.sum
Labels: area/security, size/M, lgtm, kind/chore

#7768 Sort output template configs before render
  development/tools/cmd/rendertemplates/main.go
Labels: area/ci, size/XS, lgtm, kind/bug

#7732 Run api-gateway custom-domain tests on AWS
  prow/jobs/api-gateway/api-gateway-release.yaml
  templates/data/api-gateway-release.yaml
Labels: size/L, lgtm, area/api-gateway, kind/feature, no-changes

#7778 Add compass job metadata
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration-with-dump.yaml
  prow/jobs/incubator/compass/compass-smoke-test.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/ias-adapter/ias-adapter-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-director-gqlgen-validate.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/post-main-compass-vm-clean-no-dump.yaml
  prow/jobs/incubator/compass/post-main-compass-vm-clean-with-dump.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  templates/data/compass-gke-benchmark-data.yaml
  templates/data/compass-integration-no-dump-clean-data.yaml
  templates/data/compass-integration-no-dump-data.yaml
  templates/data/compass-integration-with-dump-clean-data.yaml
  templates/data/compass-integration-with-dump-data.yaml
  templates/data/compass-smoke-test-data.yaml
  templates/data/compass-validation-data.yaml
  templates/data/generic_component_compass_console_data.yaml
  templates/data/generic_component_compass_data.yaml
  templates/data/generic_component_ord_service_data.yaml
Labels: area/management-plane, size/L, lgtm, kind/chore, no-changes

#7779 Add security constraints
  opa/gatekeeper/constraint-templates/allowPrivilegeEscalation.yaml
  opa/gatekeeper/constraint-templates/apparmor.yaml
  opa/gatekeeper/constraint-templates/capabilities.yaml
  opa/gatekeeper/constraint-templates/hostFilesystem.yaml
  opa/gatekeeper/constraint-templates/hostNetworkPorts.yaml
  opa/gatekeeper/constraint-templates/privilegedContainers.yaml
  opa/gatekeeper/constraint-templates/pspHostNamespace.yaml
  opa/gatekeeper/constraint-templates/seccomp.yaml
  opa/gatekeeper/constraint-templates/selinux.yaml
  opa/gatekeeper/constraint-templates/users.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/apparmor.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/capabilities.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/hostFilesystem.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/hostNetworkPorts.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/pspHostNamespace.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/selinux.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/users.yaml
Labels: area/security, size/XXL, lgtm, kind/feature, add-or-update

#7809 Fix opa gatekeeper TF dependency
  opa/terraform/modules/gatekeeper/main.tf
Labels: area/security, size/XS, lgtm, kind/bug, add-or-update

#7807 Detect Image urls in InRepo config
  development/image-detector/main.go
  development/pkg/extractimageurls/prowjob.go
  prow/image-detector/inrepo-config.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
  templates/data/test-infra/image-detector.yaml
  templates/templates/image-detector-inrepo.tmpl
Labels: area/security, size/L, lgtm, kind/feature, no-changes

#7811 New jobs for Kyma 2.15 release
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-216.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/L, lgtm, kind/chore, no-changes

#7822 prow/jobs/incubator: Remove Redundant Unstable CLI Job
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: area/cli, size/M, lgtm, kind/cleanup, no-changes

#7810 Update documentation and bump image for image detector
  development/image-detector/README.md
  development/image-detector/main.go
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
Labels: area/documentation, size/S, lgtm, kind/chore, no-changes

#7824 Set max concurrency to 1 for terraform job
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  prow/jobs/test-infra/terraform.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: area/ci, size/S, lgtm, kind/chore, no-changes

#7808 update codeowners
  CODEOWNERS
Labels: area/ci, size/XS, lgtm, kind/feature

#7804 Update kyma-integration images
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/jobs/busola/busola-backend/backend-deployment-check.yaml
  prow/jobs/busola/busola-web/web-deployment-check.yaml
  prow/jobs/busola/integration-k3s-test.yaml
  prow/jobs/busola/lighthouse.yaml
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-test.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  prow/jobs/test-infra/build-test-vm-image.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/config.yaml
  templates/data/api-gateway-validation.yaml
  templates/data/build-test-vm-image.yaml
  templates/data/busola-backend-deployment-check-data.yaml
  templates/data/busola-integration-test-k3s-cluster-data.yaml
  templates/data/busola-integration-test-k3s-namespace-data.yaml
  templates/data/busola-lighthouse.yaml
  templates/data/busola-web-deployment-check-data.yaml
  templates/data/control-plane-integration-data.yaml
  templates/data/generic_module_data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/istio-module-data.yaml
  templates/data/kyma-dashboard-smoke-test-prod.yaml
  templates/data/kyma-dashboard-smoke-test-stage.yaml
  templates/data/kyma-dashboard-test.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/test-infra/pjtester-data.yaml
Labels: area/ci, size/L, lgtm, kind/chore, no-changes

#7833 Revert "Update kyma-integration images"
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/jobs/busola/busola-backend/backend-deployment-check.yaml
  prow/jobs/busola/busola-web/web-deployment-check.yaml
  prow/jobs/busola/integration-k3s-test.yaml
  prow/jobs/busola/lighthouse.yaml
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-test.yaml
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  prow/jobs/test-infra/build-test-vm-image.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/config.yaml
  templates/data/api-gateway-validation.yaml
  templates/data/build-test-vm-image.yaml
  templates/data/busola-backend-deployment-check-data.yaml
  templates/data/busola-integration-test-k3s-cluster-data.yaml
  templates/data/busola-integration-test-k3s-namespace-data.yaml
  templates/data/busola-lighthouse.yaml
  templates/data/busola-web-deployment-check-data.yaml
  templates/data/control-plane-integration-data.yaml
  templates/data/generic_module_data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/istio-module-data.yaml
  templates/data/kyma-dashboard-smoke-test-prod.yaml
  templates/data/kyma-dashboard-smoke-test-stage.yaml
  templates/data/kyma-dashboard-test.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/test-infra/pjtester-data.yaml
Labels: area/ci, size/L, lgtm, kind/chore, no-changes

#7795 Run Eventing Auth Manager Integration Tests in k3d clsuter
  prow/config.yaml
  prow/jobs/eventing-auth-manager/eam-integration-test.yaml
Labels: area/eventing, size/M, lgtm, kind/missing-test, no-changes

#7837 bump golang image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm, area/dependency, kind/chore, no-changes

#7813 Istio gcp integration test
  prow/jobs/istio/istio-integration.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, area/ci, size/M, lgtm, kind/feature, no-changes

#7838 Add gophers prow jobs metadata
  prow/jobs/btp-manager/btp-manager-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/e2e-provisioning-test-build.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/slack-bot/slack-bot-build.yaml
  templates/data/btp-manager-build.yaml
  templates/data/control-plane-build.yaml
  templates/data/slack-bot/slack-bot-build.yaml
Labels: size/L, lgtm, area/prow, kind/chore, no-changes

#7781 Add metadata to SRE owned jobs
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/kcp-cli.yaml
  templates/data/control-plane-build.yaml
  templates/data/control-plane-kcp-data.yaml
  templates/data/generic_component_control_plane_data.yaml
Labels: size/S, lgtm, area/prow, kind/chore, no-changes

#7825 Adding bot explicitly to not interfere with review automation.
  CODEOWNERS
Labels: size/M, lgtm, kind/bug, area/automation

#7782 Add prow jobs for kyma adapter
  prow/jobs/incubator/compass/components/kyma-adapter/kyma-adapter-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: area/management-plane, size/L, lgtm, kind/feature, no-changes

#7857 Fix command used by image-detector
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/security, size/XS, lgtm, kind/bug, no-changes

#7827 Using terraform-executor sa. This is the sa used in our IAC config.
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: size/S, lgtm, area/automation, kind/chore, no-changes

#7839 Add automatic provisioning of k3d in e2e-k3d image
  images/e2e-dind-k3d/init.sh
  prow/config.yaml
Labels: area/ci, size/S, lgtm, kind/feature, no-changes

#7830 Remove obsolete Kyma api-gateway tests
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm, area/api-gateway, kind/cleanup, no-changes

#7797 KEB endpoints test
  prow/jobs/kyma/keb-endpoints-test.yaml
  prow/scripts/keb-endpoints-test.sh
  templates/data/keb-endpoints-test.yaml
Labels: area/ci, size/L, lgtm, kind/feature, no-changes

#7864 Fix race condition in init script
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-k3d/init.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#7805 Moved terraform prod root module execution to k8s agent.
  prow/jobs/test-infra/hide-terraform-comments.yaml
  prow/jobs/test-infra/terraform-prod-module.yaml
  prow/jobs/test-infra/terraform.yaml
  templates/data/test-infra/hide-terraform-comments.yaml
  templates/data/test-infra/terraform-prod-module.yaml
Labels: size/L, lgtm, area/automation, kind/chore, no-changes

#7870 Update max_prowjob_age
  prow/config.yaml
Labels: area/ci, lgtm, kind/chore, no-changes

#7869 Add job for running istio installation with evalution profile
  prow/jobs/istio/istio-integration.yaml
Labels: area/service-mesh, area/ci, size/M, lgtm, kind/feature, no-changes

#7878 Fix Keda manager Whitesource excludes
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#7896 Add Istio 1.17.3 images for CVEs
  development/image-syncer/external-images.yaml
Labels: area/service-mesh, size/XS, lgtm, kind/feature, no-changes

#7897 Add initial e2e-dind-nodejs image
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-dind-nodejs/init.sh
Labels: area/ci, size/M, lgtm, kind/feature

#7905 Add alpine 1.17.4
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm, area/tools, kind/chore, no-changes

#7908 Don't skip api-gateway release jobs
  prow/jobs/api-gateway/api-gateway-release.yaml
  templates/data/api-gateway-release.yaml
Labels: size/S, lgtm, area/api-gateway, kind/bug, no-changes

#7909 Istio integration test go image
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/istio-module-data.yaml
  templates/templates/generic.tmpl
Labels: area/service-mesh, size/S, lgtm, kind/feature, destroy

#7921 Upgrade k8s to 1.26
  development/custom-image/install-deps-debian.sh
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
  prow/scripts/resources/skr-test/shoot-template.yaml
  templates/data/kyma-integration-data.yaml
Labels: area/ci, size/S, lgtm, kind/chore, no-changes

#7907 sync nats image 2.9.18
  development/image-syncer/external-images.yaml
Labels: area/eventing, size/XS, lgtm, kind/chore, no-changes

#7923 Fix image detector job
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/ci, size/S, lgtm, kind/chore, no-changes

#7916 Istio k3d integration jobs need e2e image with golang 1.20
  prow/jobs/istio/istio-integration.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, kind/failing-test, size/L, lgtm, no-changes

#7925 Fix github token path variable assignment in image detector
  development/image-detector/main.go
Labels: size/XS, lgtm, kind/bug, area/tools

#7882 Allow only trusted images and repositories.
  opa/gatekeeper/constraint-templates/k8sAllowedImages.yaml
  prow/cluster/resources/gatekeeper-constraints/prow-k8s-cluster/allowedImagesProwNamespace.yaml
  prow/cluster/resources/gatekeeper-constraints/prow-k8s-cluster/allowedImagesProwToolsNamespaces.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwProwjobsNamespace.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwToolsNamespaces.yaml
Labels: area/security, size/L, lgtm, kind/feature, add-or-update

#7927 Refactor k3d integration tests for Istio and cluster creation
  prow/jobs/istio/istio-integration.yaml
Labels: area/service-mesh, kind/failing-test, size/S, lgtm, no-changes

#7879 Run Istio performance tests nightly once a day
  prow/jobs/istio/istio-integration.yaml
  prow/jobs/istio/istio-validation.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/istio-module-data.yaml
  templates/data/istio-validation.yaml
Labels: area/service-mesh, area/ci, size/L, lgtm, kind/missing-test, kind/feature, no-changes

#7932 Downgrade kubectl for post-main-kyma-k3d-k8s-preview job
  development/custom-image/install-deps-debian.sh
Labels: area/ci, size/XS, lgtm, kind/chore

#7915 Include keda manifest file in keda module build triggers
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, lgtm, kind/bug, no-changes

#7935 Remove post-main-kyma-k3d-k8s-preview job
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: area/ci, size/L, lgtm, kind/chore, no-changes

#7922 Add pull-telemetry-manager-upgrade-test job
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-upgrade-test.yaml
Labels: size/M, lgtm, kind/missing-test, area/telemetry, no-changes

#7940 Remove nodejs 14 mentions
  prow/scripts/cluster-integration/kyma-serverless-benchmarks-nightly.sh
Labels: area/serverless, size/XS, lgtm, kind/chore

#7936 run unit-tests when changing Makefile
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/XS, lgtm, kind/missing-test, area/telemetry, no-changes

#7924 Secure usage of secrets and k8s service accounts.
  opa/gatekeeper/constraint-templates/secretTrustedUsage.yaml
  opa/gatekeeper/constraint-templates/serviceAccountTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/pjtesterSecretsTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
  prow/config.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/data/test-infra/pjtester-data.yaml
Labels: area/security, size/XXL, lgtm, kind/feature, destroy

#7943 Bump security scanner config periodically (daily)
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/ci, size/M, lgtm, kind/feature, add-or-update

#7944 Add extra-refs to image-detector periodic prow job
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#7931 Fix prowjobs privileged mode
  docs/prow/k3d-no-ssh.md
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-build.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
  prow/jobs/kyma/releases/kyma-release-213.yaml
  prow/jobs/kyma/releases/kyma-release-214.yaml
  prow/jobs/kyma/releases/kyma-release-215.yaml
  prow/jobs/kyma/releases/kyma-release-216.yaml
  prow/jobs/kyma/tests/contract/knative-channel-kafka/knative-channel-kafka-tests-generic.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  prow/jobs/test-infra/image-syncer.yaml
  prow/jobs/test-infra/validation.yaml
  prow/scripts/resources/debug-container.yaml
  templates/config.yaml
  templates/data/generic_module_data.yaml
  templates/data/image-syncer-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/kyma-release-data.yaml
  templates/data/kyma-release-image-guard-data.yaml
  templates/data/validation-data.yaml
  templates/templates/kyma-github-release.yaml
Labels: area/security, size/L, lgtm, kind/chore, no-changes

#7947 Fix privileged mode in reconciler jobs
  prow/jobs/control-plane/control-plane-reconciler-integration.yaml
  prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/control-plane-integration-data.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: area/security, size/M, lgtm, kind/chore, no-changes

#7945 Change image for post istio integration test
  prow/jobs/istio/istio-integration.yaml
Labels: area/service-mesh, size/XS, lgtm, kind/feature, no-changes

#7883 Secure access to secrets.
  configs/terraform/environments/prod/image-builder-variables.tf
  configs/terraform/environments/prod/image-builder.tf
  configs/terraform/environments/prod/opa-gatekeeper-variables.tf
  configs/terraform/environments/prod/output.tf
  configs/terraform/environments/prod/pjtester-variables.tf
  configs/terraform/environments/prod/pjtester.tf
  configs/terraform/environments/prod/terraform-executor-variables.tf
  configs/terraform/environments/prod/terraform-executor.tf
  configs/terraform/environments/prod/variables.tf
  development/terraform-executor/terraform/environments/dev/backend.tf
  development/terraform-executor/terraform/environments/dev/main.tf
  development/terraform-executor/terraform/environments/dev/output.tf
  development/terraform-executor/terraform/environments/dev/provider.tf
  development/terraform-executor/terraform/environments/dev/variables.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/main.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/output.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/provider.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/variables.tf
  development/terraform-executor/terraform/modules/k8s-terraform-executor/main.tf
  development/terraform-executor/terraform/modules/k8s-terraform-executor/output.tf
  development/terraform-executor/terraform/modules/k8s-terraform-executor/provider.tf
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  prow/jobs/test-infra/terraform-prod-module.yaml
  tekton/deployments/signify_secret_rbac.yaml
  templates/data/test-infra/pjtester-data.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secrets-rotator.yaml
  templates/data/test-infra/terraform-prod-module.yaml
Labels: area/security, size/XL, lgtm, kind/feature, destroy

#7948 Add extra refs to istio nightly
  prow/jobs/modules/internal/istio-manager.yaml
  templates/config.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, area/ci, size/S, lgtm, kind/bug, no-changes

#7950 Reconciler k3d integration jobs
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/scripts/provision-vm-and-start-reconciler-istio-integration-k3d.sh
  templates/data/incubator-buildpack-data.yaml
Labels: area/service-mesh, size/M, lgtm, kind/feature, no-changes

#7953 Prevent images using latest tag.
  opa/gatekeeper/constraint-templates/k8sAllowedImages.yaml
Labels: area/security, size/S, lgtm, kind/feature, destroy

#7941 Test if prowjob is using privileged container with allowed image.
  development/opagatekeeper/constraints.go
  development/prow/pjconfigtests/pjconfigtests_suite_test.go
  development/prow/pjconfigtests/pjconfigtests_test.go
  development/prow/pjconfigtests/validators.go
  development/prow/prowjobs.go
  prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
  prow/config.yaml
  prow/jobs/kyma/kyma-preview.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/terraform-prod-module.yaml
  templates/data/test-infra/pjconfigtests.yaml
  templates/data/test-infra/terraform-prod-module.yaml
Labels: area/security, size/L, lgtm, kind/feature, destroy

#7959 Fix pre-test-infra-test-untrusted-prow-plugin
  prow/config.yaml
  prow/jobs/test-infra/prow-plugins.yaml
  templates/data/prow-plugins-data.yaml
Labels: size/XS, lgtm, area/tests, add-or-update, kind/chore

#7946 Not fail on not found inrepo config
  development/image-detector/main.go
Labels: area/security, size/XS, lgtm, kind/bug

#7960 Fix post-test-infra-test-untrusted-prow-plugin
  prow/jobs/test-infra/prow-plugins.yaml
  templates/data/prow-plugins-data.yaml
Labels: size/XS, lgtm, area/tests, add-or-update, kind/chore

#7961 Bump image-detector
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, kind/chore

#7952 Add skip for sec-scanner-config for Istio jobs
  prow/jobs/istio/istio-validation.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/istio-module-data.yaml
  templates/data/istio-validation.yaml
Labels: area/service-mesh, area/ci, size/M, lgtm, kind/feature, add-or-update

#7964 Fixed rego function name.
  opa/gatekeeper/constraint-templates/k8sAllowedImages.yaml
Labels: area/security, size/XS, lgtm, kind/bug, destroy

#7963 Fix failing image-detector bumper
  development/image-detector/main.go
  development/pkg/extractimageurls/prowjob.go
Labels: area/security, size/S, lgtm, kind/bug

#7968 Bump Image Detector
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#7934 Run api-gateway integration tests on AWS
  prow/jobs/api-gateway/api-gateway-integration-tests.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/api-gateway/api-gateway-validation.yaml
  templates/data/api-gateway-integration-tests.yaml
  templates/data/api-gateway-release.yaml
  templates/data/api-gateway-validation.yaml
Labels: area/ci, size/XL, lgtm, area/api-gateway, kind/bug, no-changes

#7969 Add git to image-detector image
  development/image-detector/Dockerfile
Labels: size/XS, lgtm, kind/bug, area/tests

#7970 Fixed params order.
  opa/gatekeeper/constraint-templates/k8sAllowedImages.yaml
Labels: area/security, size/XS, lgtm, kind/bug, destroy

#7967 Adjust privileged mode image excludes
  prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
Labels: area/security, size/XS, lgtm, destroy, kind/chore

#7971 Bump Image Detetcor
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#7965 Fix Istio skip for sec-scanner-config
  prow/jobs/istio/istio-validation.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/istio-module-data.yaml
  templates/data/istio-validation.yaml
Labels: area/service-mesh, size/S, lgtm, kind/bug, no-changes

#7973 Add labels to security scanner autobump PR
  prow/image-detector/test-infra-sec-config-autobump-config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#7980 Corrected constraints allowed images to clean violations.
  prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwNamespace.yaml
  prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwToolsNamespaces.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwProwjobsNamespace.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwToolsNamespaces.yaml
Labels: area/security, size/XS, lgtm, kind/feature, destroy

#7966 Removed unused plugin.
  development/external-plugins/test-untrusted/cmd/main.go
  docs/index.md
  prow/images/test-untrusted-plugin/Dockerfile
  prow/images/test-untrusted-plugin/Makefile
  prow/images/test-untrusted-plugin/README.md
  prow/jobs/test-infra/prow-plugins.yaml
  templates/data/prow-plugins-data.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, kind/chore, no-changes

#7906 Unify auto bumpers for files
  development/github/pkg/bumper/bumper.go
  development/github/pkg/bumper/utils.go
  development/github/pkg/bumper/utils_test.go
  development/image-detector/main.go
  development/markdown-index/bumper/bumper.go
  development/markdown-index/main.go
Labels: area/ci, size/XL, lgtm, kind/cleanup

#7994 Make kyma-dashboard tests optional
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-test.yaml
  templates/data/kyma-dashboard-smoke-test-prod.yaml
  templates/data/kyma-dashboard-smoke-test-stage.yaml
  templates/data/kyma-dashboard-test.yaml
Labels: kind/failing-test, size/XS, lgtm, area/tests, no-changes

#8006 Fix gardener kubeconfig generation
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  prow/scripts/provision-vm-and-start-busola-lighthouse.sh
  prow/scripts/provision-vm-and-start-kyma-dashboard-smoke-test.sh
  prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
Labels: size/M, lgtm, kind/bug, area/tests

#8007 Rename sec-scanner-config.yml to sec-scanners-config.yaml
  development/image-detector/main.go
  prow/image-detector/test-infra-sec-config-autobump-config.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  sec-scanners-config.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/security, size/S, lgtm, kind/bug, no-changes

#8011 Bump markdown-index and image-detector
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/S, lgtm, kind/chore, no-changes

#8014 Add yaml tag to bumper Options struct
  development/github/pkg/bumper/bumper.go
Labels: area/ci, size/S, lgtm, kind/bug

#7962 Istio release build pipeline
  prow/jobs/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, area/ci, size/L, lgtm, kind/feature, no-changes

#8015 Fix Busola nightly job
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
Labels: area/security, size/M, lgtm, kind/bug

#8017 Fix gardener kubeconfig
  prow/scripts/cluster-integration/helpers/reconciler.sh
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  prow/scripts/provision-vm-and-start-busola-lighthouse.sh
  prow/scripts/provision-vm-and-start-kyma-dashboard-smoke-test.sh
  prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
Labels: area/security, size/S, lgtm, kind/bug

#8004 Remove tekton and it's traces from the test-infra
  docs/examples/tekton-demo.yaml
  docs/how-to/how-to_use_tekton-pipelines-in-prow.md
  docs/index.md
  opa/terraform/environments/dev/variables.tf
  prow/cluster/components/crier_deployment.yaml
  prow/cluster/components/deck_deployment.yaml
  prow/cluster/components/hook_deployment.yaml
  prow/cluster/components/pipeline_deployment.yaml
  prow/cluster/components/pipeline_rbac.yaml
  prow/cluster/components/prow_controller_manager_deployment.yaml
  prow/cluster/components/sinker_deployment.yaml
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
  sec-scanners-config.yaml
  task/clone-refs/0.1/README.md
  task/clone-refs/0.1/clone-refs.yaml
  task/clone-refs/0.1/samples/prowjob-cloning-repositories.yaml
  task/clone-refs/Dockerfile
  task/clone-refs/main.go
  task/go-unit-tests/0.1/README.md
  task/go-unit-tests/0.1/go-unit-tests.yaml
  task/go-unit-tests/0.1/samples/prowjob-testing-go-code.yaml
  task/golangci-lint/0.1/README.md
  task/golangci-lint/0.1/golangci-lint.yaml
  task/golangci-lint/0.1/samples/prowjob-linting-go-code.yaml
  task/hide-github-pr-comments/0.1/README.md
  task/hide-github-pr-comments/0.1/hide-github-pr-comments.yaml
  task/hide-github-pr-comments/samples/sample_prowjob_pipeline.yaml
  task/image-builder/0.1/README.md
  task/image-builder/0.1/image-builder.yaml
  task/image-builder/0.1/samples/prowjob-building-image.yaml
  task/terraform-executor/0.1/README.md
  task/terraform-executor/0.1/terraform-executor.yaml
  task/terraform-executor/samples/sample_prowjob_pipeline.yaml
  tekton/catalog/tasks/git-clone.yaml
  tekton/deployments/config_defaults.yaml
  tekton/deployments/dashboard_ingress.yaml
  tekton/deployments/dashboard_managedcertificate.yaml
  tekton/deployments/dashboard_release.yaml
  tekton/deployments/external-secrets/external_secrets.yaml
  tekton/deployments/external-secrets/secrets_store.yaml
  tekton/deployments/external-secrets/values.yaml
  tekton/deployments/gatekeeper-constraints/imageBuilderSATrustedUsage.yaml
  tekton/deployments/gatekeeper-constraints/signifyDevSecretTrustedUsage.yaml
  tekton/deployments/gatekeeper-constraints/signifyProdSecretTrustedUsage.yaml
  tekton/deployments/pipelines_release.yaml
  tekton/deployments/pipelines_serviceaccount.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup, destroy
