Repository kyma-project/test-infra, pull requests merged in 2023-07, with the labels that each got.

#7997 Fix constraints for prow cluster.
  prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwNamespace.yaml
  prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwToolsNamespaces.yaml
Labels: area/security, size/XS, lgtm, kind/bug, destroy

#8000 Add small initial build script that uses docker buildx
  images/Makefile
  images/build-images.sh
  prow/jobs/test-infra/images.yaml
  templates/data/prowjob-images-data.yaml
Labels: area/ci, size/XL, lgtm, kind/feature, no-changes

#8019 Correct project id for workload project.
  configs/terraform/environments/prod/output.tf
  configs/terraform/environments/prod/terraform-executor.tf
Labels: size/S, lgtm, kind/bug, area/automation, destroy

#8005 update label list
  prow/labels.yaml
Labels: size/L, lgtm, area/prow, kind/cleanup, add-or-update

#8023 Update Kyma nextRelease to 2.17
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-217.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/L, lgtm, add-or-update, kind/chore

#8016 Use provider from root module in sub-modules
  development/secrets-rotator/terraform/environments/dev/main.tf
  development/secrets-rotator/terraform/environments/dev/provider.tf
  development/secrets-rotator/terraform/environments/prod/main.tf
  development/secrets-rotator/terraform/environments/prod/provider.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/main.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/provider.tf
  development/secrets-rotator/terraform/modules/rotate-service-account/variables.tf
  development/secrets-rotator/terraform/modules/service-account-keys-cleaner/main.tf
  development/secrets-rotator/terraform/modules/service-account-keys-cleaner/variables.tf
Labels: area/ci, size/L, lgtm, kind/cleanup, no-changes

#8026 Run postsubmit for image detector on github package change
  prow/jobs/test-infra/image-detector.yaml
  templates/data/test-infra/image-detector.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8029 Remove istio lint
  prow/jobs/istio/istio-validation.yaml
  templates/data/istio-validation.yaml
Labels: area/service-mesh, area/ci, size/M, lgtm, kind/cleanup, no-changes

#8034 Bump image-detector tag
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#8030 Use squash in serverless manager
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/missing-test, no-changes

#8025 Update image dependencies
  images/buildpack-go/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-gcloud/Dockerfile
Labels: area/ci, size/S, lgtm, kind/chore

#8040 Remove tekton v2
  configs/terraform/environments/prod/opa-gatekeeper-variables.tf
  configs/terraform/environments/prod/opa-gatekeeper.tf
  configs/terraform/environments/prod/output.tf
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/variables.tf
  sec-scanners-config.yaml
Labels: area/ci, size/M, lgtm, kind/chore, no-changes

#7949 Remove jobs for building Loki image
  development/image-syncer/external-images.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: area/logging, size/L, lgtm, kind/cleanup, no-changes

#8041 Add conditional wait to docker daemon to be up.
  images/e2e-dind-k3d/init.sh
  images/e2e-dind-nodejs/init.sh
Labels: area/ci, size/S, lgtm, kind/feature

#8012 Secure kyma bot secrets
  configs/terraform/environments/prod/kyma-bots-secrets-variables.tf
  configs/terraform/environments/prod/kyma-bots-secrets.tf
  docs/index.md
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSapTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotTriageTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
Labels: area/security, size/L, lgtm, kind/feature, destroy

#8042 Fix istio nightly performance job
  prow/jobs/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, area/ci, lgtm, kind/bug, no-changes

#8046 Fix branch protection for kyma-environment-broker
  prow/config.yaml
Labels: area/security, size/XS, lgtm, kind/chore, no-changes

#8048 add jq to dind-node image
  images/e2e-dind-nodejs/Dockerfile
Labels: lgtm, kind/feature, area/tests

#8032 Add configuration for branches to be up-to-date
  prow/config.yaml
Labels: size/XS, lgtm, area/prow, kind/bug, no-changes

#8053 Add autobump for new testimages
  prow/autobump-config/test-infra-autobump-config.yaml
  templates/templates/test-infra-autobump-config.yaml
Labels: area/ci, size/S, lgtm, kind/feature, no-changes

#8056 Add compass-director-secret
  prow/cluster/resources/external-secrets/external_secrets_untrusted.yaml
Labels: area/ci, size/S, lgtm, kind/chore, no-changes

#8054 Remove tekton dependencies from Go code
  development/image-detector/main.go
  development/pkg/extractimageurls/kubernetes_test.go
  development/pkg/extractimageurls/prowjob_test.go
  development/pkg/extractimageurls/tekton.go
  development/pkg/extractimageurls/tekton_test.go
  development/tools/pkg/pjtester/pjtester.go
  go.mod
Labels: size/L, lgtm, area/tools, kind/chore

#8058 Add preset-compass-director-secret preset
  prow/config.yaml
Labels: area/ci, size/S, lgtm, kind/chore, no-changes

#8043 pre-main-kyma-integration-k3d-runtime-agent not watching installation directory
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-tests.yaml
Labels: area/application-connector, size/XS, lgtm, kind/flake, kind/chore, no-changes

#7992 Compass scripts relocation
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration-with-dump.yaml
  prow/jobs/incubator/compass/compass-smoke-test.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-director-gqlgen-validate.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
  prow/jobs/incubator/compass/post-main-compass-vm-clean-no-dump.yaml
  prow/jobs/incubator/compass/post-main-compass-vm-clean-with-dump.yaml
  prow/scripts/clean-vm-compass.sh
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/provision-vm-compass-smoke-test.sh
  prow/scripts/provision-vm-compass.sh
  prow/scripts/validate-compass-generic.sh
  templates/data/compass-gke-benchmark-data.yaml
  templates/data/compass-integration-no-dump-clean-data.yaml
  templates/data/compass-integration-no-dump-data.yaml
  templates/data/compass-integration-with-dump-clean-data.yaml
  templates/data/compass-integration-with-dump-data.yaml
  templates/data/compass-smoke-test-data.yaml
  templates/data/compass-validation-data.yaml
Labels: size/XL, lgtm, area/prow, kind/cleanup, no-changes

#8059 Add e2e images to allowed list for privileged mode
  prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
Labels: area/security, size/XS, lgtm, destroy, kind/chore

#8068 add nats-box image to internal registry
  development/image-syncer/external-images.yaml
Labels: area/eventing, size/XS, lgtm, kind/feature, no-changes

#8067 fluentd image added
  development/image-syncer/external-images.yaml
Labels: area/logging, size/XS, lgtm, kind/chore, no-changes

#8051 Add KEB repo
  prow/config.yaml
  prow/image-detector/inrepo-config.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  templates/config.yaml
Labels: area/ci, size/L, lgtm, kind/feature, no-changes

#8070 Cleanup k3d and docker after run
  images/e2e-dind-k3d/init.sh
  images/e2e-dind-nodejs/init.sh
Labels: area/ci, size/S, lgtm, kind/feature

#8039 Update README.md
  README.md
Labels: area/ci, size/XS, lgtm, kind/chore

#7863 refactor busola integration jobs
  prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
  prow/jobs/busola/busola-integration.yaml
  prow/jobs/busola/integration-k3s-test.yaml
  prow/scripts/cluster-integration/busola-integration-test-k3s.sh
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  templates/data/busola-integration-test-k3s-cluster-data.yaml
  templates/data/busola-integration-test-k3s-namespace-data.yaml
Labels: area/ci, size/XL, lgtm, kind/feature, destroy

#8083 Fix registry path for istio module
  prow/jobs/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, size/XS, lgtm, kind/bug, no-changes

#8088 Adjust cleanup and add TERM to trap
  images/e2e-dind-k3d/init.sh
  images/e2e-dind-nodejs/init.sh
Labels: area/ci, size/S, lgtm, kind/bug

#8084 Remove logging component from telemetry integration job
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
Labels: size/XS, lgtm, kind/cleanup, area/telemetry, no-changes

#8095 Update k3s config for istio integration tests
  prow/jobs/istio/istio-integration.yaml
Labels: area/service-mesh, area/ci, size/XS, lgtm, kind/feature, no-changes

#8089 Add label and change img of istio build module prow job
  prow/jobs/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, size/S, lgtm, kind/bug, no-changes

#8100 Change prowjob age
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#8103 fix run if change for smoke tests in kyma-dashboard
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8101 Prepare configure notifications
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
Labels: size/S, lgtm, area/control-plane, kind/feature, no-changes

#8107 Prepare gophers notifications part 2
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
  templates/data/skr-own-cluster-dev.yaml
Labels: size/XS, lgtm, area/control-plane, kind/feature, no-changes

#8108 Enable branch protection for kyma-environment-broker repo
  prow/config.yaml
Labels: area/security, size/XS, lgtm, kind/chore, no-changes

#8113 Testing gophers notifications
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-own-cluster-dev.yaml
Labels: size/XS, lgtm, area/control-plane, kind/feature

#8075 Update list of privileged images
  prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
  prow/jobs/kyma/kyma-preview.yaml
Labels: area/security, size/S, lgtm, destroy, kind/chore

#8120 Revert "Bumping test-infra and testimages (#8099)"
  prow/jobs/busola/busola-integration.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/istio/istio-integration.yaml
  prow/jobs/istio/istio-manager.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-upgrade-test.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-verify-module.yaml
  prow/jobs/test-infra/images.yaml
  sec-scanners-config.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/istio-module-data.yaml
Labels: area/ci, size/M, lgtm, kind/bug, no-changes

#8117 Remove cleanup logic
  images/e2e-dind-k3d/init.sh
  images/e2e-dind-nodejs/init.sh
Labels: area/ci, size/M, lgtm, kind/bug

#8123 Fix terraform constraints
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
Labels: area/security, size/S, lgtm, destroy, kind/chore

#8125 Fix terraform constraints
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
Labels: area/security, size/S, lgtm, destroy, kind/chore

#8127 Fix terraform constraints
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
Labels: area/security, size/S, lgtm, destroy, kind/chore

#8092 Fix secrets constraints
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSapTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotTriageTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
Labels: area/security, size/M, lgtm, destroy, kind/chore

#8119 initial prow cluster as terraform resource
  configs/terraform/environments/prod/dns.tf
  configs/terraform/environments/prod/prow.tf
Labels: area/ci, size/M, lgtm, kind/feature, add-or-update

#8132 Change GCP cluster region
  configs/gencred-config.yaml
  configs/terraform/environments/prod/variables.tf
Labels: area/ci, size/XS, lgtm, kind/deprecation

#8135 Add required labels to trusted cluster
  configs/terraform/environments/prod/prow.tf
Labels: priority/critical, area/ci, size/XS, lgtm, kind/chore, no-changes

#8074 Change keb-endpoints-test location
  prow/jobs/kyma/keb-endpoints-test.yaml
  prow/scripts/keb-endpoints-test.sh
  templates/config.yaml
  templates/data/keb-endpoints-test.yaml
Labels: area/ci, size/S, lgtm, kind/chore, no-changes

#8134 Change skr-aws-upgrade-integration-dev cron schedule
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#8104 Migrate keda k3d jobs
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/L, lgtm, kind/chore, no-changes

#8087 Migrate serverless k3d jobs
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/L, lgtm, kind/chore, no-changes

#8156 Remove old test-images build jobs
  .github/dependabot.yml
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
  templates/data/test-infra/dependabot-config-data.yaml
Labels: area/ci, size/XL, lgtm, kind/deprecation, no-changes

#8157 Do not use rootless user in Prow images
  images/buildpack-go/Dockerfile
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
Labels: area/ci, size/XS, lgtm, kind/bug

#8154 Run Istio Prow jobs on PRs to release branch
  prow/jobs/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: area/service-mesh, area/ci, size/S, lgtm, kind/bug, no-changes

#8136 Adapt compass jobs to use dind k3d
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration-with-dump.yaml
  prow/jobs/incubator/compass/compass-smoke-test.yaml
  prow/jobs/incubator/compass/post-main-compass-vm-clean-no-dump.yaml
  prow/jobs/incubator/compass/post-main-compass-vm-clean-with-dump.yaml
  templates/config.yaml
  templates/data/compass-integration-no-dump-clean-data.yaml
  templates/data/compass-integration-no-dump-data.yaml
  templates/data/compass-integration-with-dump-clean-data.yaml
  templates/data/compass-integration-with-dump-data.yaml
  templates/data/compass-smoke-test-data.yaml
Labels: size/L, lgtm, area/prow, kind/deprecation, no-changes

#8109 migrate serverless component jobs
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
  prow/scripts/provision-vm-and-start-serverless-k3d.sh
  templates/data/kyma-integration-data.yaml
Labels: area/ci, size/L, lgtm, kind/chore, no-changes

#8171 Configure own cluster skr test once per day
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-own-cluster-dev.yaml
Labels: size/XS, lgtm, area/control-plane, kind/feature, no-changes

#8175 Remove the usage of deleted sa-gcr-push-kyma-project secret/SA in com…
  prow/jobs/incubator/compass/compass-smoke-test.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-director-gqlgen-validate.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
  templates/data/compass-smoke-test-data.yaml
  templates/data/compass-validation-data.yaml
Labels: size/S, lgtm, area/prow, kind/bug, no-changes

#8165 Rewrite milv jobs
  .github/pull-request-template.md
  docs/how-to/how-to-create-standard-terraform-config.md
  docs/prow/production-cluster-configuration.md
  docs/prow/prow-monitoring.md
  milv.config.yaml
  prow/jobs/governance.yaml
  prow/scripts/governance.sh
  prow/scripts/metadata-governance.sh
  prow/scripts/resources/README.md
  templates/data/governance-data.yaml
  templates/templates/generic.tmpl
Labels: area/ci, size/XL, lgtm, kind/deprecation, no-changes

#8180 Remove sa-gcr-push
  docs/prow/presets.md
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/kcp-cli.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/milv/milv.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  prow/jobs/template-operator/template-operator.yaml
  prow/jobs/test-infra/image-syncer.yaml
  prow/scripts/build-kcp-cli.sh
  templates/config.yaml
  templates/data/control-plane-kcp-data.yaml
  templates/data/image-syncer-data.yaml
Labels: size/L, lgtm, kind/bug, area/tests, no-changes

#8181 Create trusted_workloadidentity_serviceaccount.yaml
  prow/workload-cluster/trusted-workload/gencred-refresher_serviceaccount.yaml
  prow/workload-cluster/trusted-workload/trusted_workloadidentity_serviceaccount.yaml
Labels: area/ci, size/M, lgtm, kind/cleanup, no-changes

#8182 Create untrusted_workloadidentity_serviceaccount.yaml
  prow/workload-cluster/untrusted_workloadidentity_serviceaccount.yaml
Labels: area/ci, size/M, lgtm, kind/cleanup, no-changes

#8183 Remove old and unused script from repo
  development/README.md
  development/create-service-accounts-for-fork.sh
  development/github-release.sh
  development/helper.sh
  development/install-prow.sh
  development/provision-cluster.sh
  development/remove-prow.sh
  development/test.files
  development/update-config.sh
  development/update-jobs.sh
  development/update-plugins.sh
  docs/index.md
  docs/prow/prow-architecture.md
  prow/create-secrets-for-workload-cluster.sh
  prow/set-up-workload-cluster.sh
Labels: area/ci, size/XL, lgtm, kind/cleanup

#8093 Add a job to execute the Eventing tests with the eventingWebhookAuth flag enabled
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  templates/data/kyma-integration-gardener-data.yaml
  test-inventory-integration.md
Labels: area/eventing, size/L, lgtm, kind/feature, no-changes

#8187 Make governance jobs optional
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: area/ci, kind/failing-test, size/S, lgtm, no-changes

#8137 Improve tfcmt GitHub comments.
  .tfcmt.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  prow/jobs/test-infra/terraform-prod-module.yaml
  templates/data/test-infra/hide-terraform-comments.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secrets-rotator.yaml
  templates/data/test-infra/terraform-prod-module.yaml
Labels: size/L, lgtm, kind/bug, area/automation, destroy

#8190 Add istio 1.18.1 to external images
  development/image-syncer/external-images.yaml
Labels: area/service-mesh, size/S, lgtm, kind/chore, no-changes

#8060 Add NATS-manager module build job
  prow/jobs/nats-manager/nats-manager-generic.yaml
  templates/data/nats-manager-data.yaml
Labels: area/eventing, size/L, lgtm, kind/missing-test, no-changes

#8153 Change skr test location
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/scripts/cluster-integration/skr-aws-upgrade-integration-dev.sh
  prow/scripts/keb-endpoints-test.sh
  prow/scripts/skr-integration-own-cluster.sh
  prow/scripts/skr-integration.sh
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
  templates/data/skr-integration-data.yaml
  templates/data/skr-own-cluster-dev.yaml
Labels: area/ci, size/M, lgtm, kind/chore, no-changes

#8197 Fixing wrong flags for postsubmit.
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  prow/jobs/test-infra/terraform-prod-module.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secrets-rotator.yaml
  templates/data/test-infra/terraform-prod-module.yaml
Labels: size/S, lgtm, kind/bug, area/automation, no-changes

#8193 busola-lighthouse
  prow/jobs/busola/lighthouse.yaml
  prow/scripts/cluster-integration/busola-lighthouse.sh
  prow/scripts/cluster-integration/busola-smoke-test-docker.sh
  prow/scripts/provision-vm-and-start-busola-lighthouse.sh
  templates/data/busola-lighthouse.yaml
Labels: area/ci, size/L, lgtm, kind/feature, no-changes

#8191 Remove duplicated area/automation label
  prow/labels.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8192 Use squash in keda manager
  prow/config.yaml
Labels: size/XS, lgtm, area/prow, kind/bug, no-changes

#8194 Update eventing-manager unit-test job
  CODEOWNERS
  prow/jobs/eventing-manager/eventing-manager-generic.yaml
  templates/data/eventing-manager-data.yaml
Labels: area/eventing, kind/failing-test, size/XS, lgtm, no-changes

#8196 fix run if change regex
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  templates/data/lifecycle-manager-data.yaml
Labels: size/XS, lgtm, area/templates, kind/bug, no-changes

#8206 Use correct credentials in Kyma artifacts 2.16
  prow/scripts/build-kyma-artifacts.sh
Labels: size/XS, lgtm, kind/bug, area/tests

#8207 Remove kyma-artifacts jobs and template
  prow/jobs/kyma/kyma-artifacts.yaml
  templates/data/kyma-artifacts-data.yaml
Labels: area/ci, size/L, lgtm, kind/deprecation, no-changes

#8210 Exclude sidecar from secrets constraints
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/pjtesterSecretsTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
Labels: area/security, size/S, lgtm, kind/bug, destroy

#8211 Fix typo in preset-compass-director-secret definition
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8214 Split telemetry-manager-e2e-test
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-logging.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-metrics.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-tracing.yaml
Labels: size/M, lgtm, area/telemetry, kind/chore, no-changes

#8217 Add one size node pool for small workloads
  configs/terraform/environments/prod/prow.tf
Labels: area/ci, size/S, lgtm, kind/feature, add-or-update

#8219 Enabled always run for NATS manager jobs
  prow/jobs/nats-manager/nats-manager-generic.yaml
  templates/data/nats-manager-data.yaml
Labels: area/eventing, size/S, lgtm, kind/flake, no-changes

#8220 Add node taint for minimal pool and enable autoscale between 1/2
  configs/terraform/environments/prod/prow.tf
Labels: area/ci, size/S, lgtm, kind/feature, destroy

#8209 Adjust scripts to work with new tracing test
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
  prow/scripts/cluster-integration/kyma-serverless-metrics-nightly.sh
  prow/scripts/cluster-integration/kyma-serverless-run-test.sh
  templates/data/kyma-integration-data.yaml
Labels: area/serverless, size/S, lgtm, kind/feature

#8221 Remove own-cluster SKR test
  prow/jobs/kyma/skr-integration.yaml
  prow/scripts/resources/skr-test/shoot-template.yaml
  prow/scripts/skr-integration-own-cluster.sh
  templates/data/skr-own-cluster-dev.yaml
  test-inventory-integration.md
Labels: area/ci, size/L, lgtm, kind/cleanup

#8226 Change skr-preview-dev cron schedule
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, kind/chore

#8228 Change node image for compass-console
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  templates/config.yaml
Labels: area/ci, size/XS, lgtm, kind/deprecation, add-or-update

#8232 Fix taints in node
  configs/terraform/environments/prod/prow.tf
Labels: area/ci, size/S, lgtm, kind/feature, add-or-update

#8045 Use new dind img for jellyfish owned gc vm pipelines
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/config.yaml
  prow/jobs/cli/cli-k3d.yaml
  prow/jobs/cli/cli.yaml
  prow/jobs/incubator/reconciler/reconciler-k3d.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/kyma-integration-k3d.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/compatibility-cli.sh
  prow/scripts/provision-vm-and-start-kyma-upgrade-k3d.sh
  prow/scripts/provision-vm-and-start-reconciler-k3d.sh
  prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh
  prow/scripts/provision-vm-cli.sh
  prow/scripts/reconciler-publish-unstable-cli.sh
  templates/config.yaml
  templates/data/cli-data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/XXL, lgtm, kind/cleanup, area/tests, destroy

#8231 Update image tag of image-detector
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
  templates/templates/test-infra-autobump-config.yaml
Labels: area/ci, size/S, lgtm, destroy, kind/chore

#8234 remove taint not yet supported by prow
  configs/terraform/environments/prod/prow.tf
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8236 Remove duplicated dependencies
  development/cloudevents/client/client.go
  development/external-plugins/automerge-notification/main.go
  development/gcp/cloud-run/create-github-issue/create-github-issue.go
  development/gcp/cloud-run/search-github-issue/search-github-issues.go
  development/gcp/pkg/pubsub/client.go
  development/github/pkg/client/client.go
  development/github/pkg/client/types.go
  development/github/pkg/types/types.go
  development/image-syncer/util.go
  development/image-url-helper/pkg/check/filecheck.go
  development/image-url-helper/pkg/common/outputlist.go
  development/image-url-helper/pkg/list/imagelister.go
  development/kyma-github-connector/githubWebhookGateway/pkg/gateway/webhookhandler.go
  development/kyma-github-connector/githubWebhookGateway/pkg/gateway/webhookhandler_test.go
  development/kyma-github-connector/githubWebhookGateway/pkg/github/receiver.go
  development/pkg/extractimageurls/prowjob.go
  development/prow-installer/pkg/config/config.go
  development/prow/pjconfigtests/pjconfigtests_test.go
  development/prow/prowjobs.go
  development/tools/cmd/githubissues/main.go
  development/tools/cmd/rendertemplates/main.go
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_test.go
  development/tools/pkg/prtagbuilder/mocks/fakeghclient.go
  development/tools/pkg/prtagbuilder/prtagbuilder.go
  development/tools/pkg/release/github.go
  development/tools/pkg/release/mock.go
  development/tools/pkg/rendertemplates/genericcomponent.go
  go.mod
  prow/scripts/resources/autobumper/go.sum
Labels: area/ci, size/M, lgtm, kind/cleanup

#8237 Update external secrets configuration to schedule on components pool
  configs/terraform/environments/prod/prow.tf
  opa/gatekeeper/deployments/gatekeeper.yaml
  prow/cluster/resources/external-secrets/values_trusted.yaml
Labels: area/ci, size/M, lgtm, kind/feature

#8240 Don't fail on inconsistent prod image bumps
  prow/autobump-config/test-infra-autobump-config.yaml
  templates/templates/test-infra-autobump-config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8239 Fix constraints warnings for pull-btp-manager-build
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/XS, lgtm, kind/cleanup, area/tests, destroy

#8238 Run api-gateway integration tests also on release branch
  prow/jobs/api-gateway/api-gateway-integration-tests.yaml
  prow/jobs/istio/istio-integration.yaml
  templates/data/api-gateway-integration-tests.yaml
Labels: area/ci, size/S, lgtm, area/api-gateway, kind/bug, destroy

#8244 Regenerate go.sum
  development/kyma-github-connector/githubWebhookGateway/go.mod
  development/kyma-github-connector/githubWebhookGateway/go.sum
  go.sum
  prow/scripts/resources/autobumper/go.sum
Labels: area/ci, size/M, lgtm, kind/chore

#8251 Give more CPU to Go linting
  prow/jobs/test-infra/go-validation.yaml
  templates/data/test-infra/golang-tests.yaml
Labels: size/XS, lgtm, area/tests, kind/chore, no-changes

#8254 bump resources
  prow/jobs/busola/busola-integration.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-integration.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
Labels: area/ci, size/S, lgtm, kind/feature, no-changes

#8227 Add DNS cleaner to Terraform
  configs/terraform/environments/prod/dns-collector.tf
  development/tools/cmd/dnscleaner/README.md
  development/tools/cmd/dnscleaner/main.go
  development/tools/pkg/dnscleaner/automock/dnsapi.go
  development/tools/pkg/dnscleaner/dns_wrapper.go
  development/tools/pkg/dnscleaner/remover.go
  development/tools/pkg/dnscleaner/remover_test.go
  docs/index.md
  test-inventory-integration.md
Labels: area/ci, size/XL, lgtm, kind/feature, add-or-update

#8249 bump prometheus images
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm, area/dependency, kind/feature, add-or-update

#8258 Replace bootstrap with new hadolint image
  images/build-images.sh
  images/governance-toolkit/Dockerfile
Labels: area/ci, size/S, lgtm, kind/feature

#8257 Require tag for images in terraform
  development/pkg/extractimageurls/terraform.go
  development/pkg/extractimageurls/terraform_test.go
Labels: area/security, size/S, lgtm, kind/bug

#8265 Replace bootstrap image with governance-toolkit in prow jobs
  prow/jobs/control-plane/control-plane-validation.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/kyma-release-pr-image-guard.yaml
  prow/jobs/kyma/kyma-validation.yaml
  prow/jobs/test-infra/validation.yaml
  templates/config.yaml
  templates/data/kyma-release-image-guard-data.yaml
  test-inventory-integration.md
Labels: area/ci, size/M, lgtm, kind/feature

#8267 Make eventing-with-auth-manager job required
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#8270 Switch to ko-based build for go applications
  .ko.yaml
  .koapps.yaml
  prow/jobs/test-infra/ko-build.yaml
Labels: area/ci, size/M, lgtm, kind/feature, no-changes

#8273 Remove not needed anymore ProwJobs
  .koapps.yaml
  development/gcp/cloud-run/create-github-issue/Dockerfile
  development/gcp/cloud-run/gardener-sa-rotate/Dockerfile
  development/gcp/cloud-run/kms-rotate/Dockerfile
  development/gcp/cloud-run/scan-logs-for-secrets/Dockerfile
  development/gcp/cloud-run/scan-logs-for-secrets/kodata/gitleaks.toml
  development/gcp/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
  development/gcp/cloud-run/search-github-issue/Dockerfile
  development/image-detector/Dockerfile
  development/markdown-index/Dockerfile
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/image-detector.yaml
  prow/jobs/test-infra/ko-build.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  templates/data/buildpack-data.yaml
  templates/data/test-infra/image-detector.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup, no-changes

#8296 Add tools to ko build
  .koapps.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#8086 Add json with mitigated images
  docs/security/imagemitigation.json
  docs/security/schema.json
Labels: area/security, size/XL, lgtm, kind/chore

#8248 Fix Busola secrets constraints
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
Labels: area/security, size/S, lgtm, destroy, kind/chore

#8262 GCP Workload Identity Federation for GitHub
  configs/terraform/core/main.tf
  configs/terraform/environments/prod/gcp-workload-identity-federation.tf
  configs/terraform/environments/prod/github-variables.tf
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/terraform-executor.tf
Labels: size/M, lgtm, kind/feature, add-or-update, area/automation

#8272 run eventing-controller test using makefile
  Makefile
  prow/jobs/kyma/components/eventing-controller/eventing-controller-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: area/eventing, size/XS, lgtm, kind/feature, add-or-update

#8325 Revert unprivileged mode from buildkit jobs
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, kind/failing-test, size/S, lgtm, add-or-update

#8329 fix shellcheck errors
  development/gcbuild/run.sh
  prow/scripts/kyma-testing.sh
  prow/scripts/lib/kyma.sh
  prow/scripts/lib/testing-helpers.sh
  prow/scripts/lib/utils.sh
  prow/scripts/vpathguard.sh
Labels: area/ci, kind/failing-test, size/S, lgtm

#8269 Fix nightly-main-reconciler-e2e job
  prow/scripts/cluster-integration/helpers/reconciler.sh
Labels: size/XS, lgtm, kind/bug, area/tests, no-changes

#8280 Remove prow-tools usage
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/kyma-validation.yaml
  prow/jobs/test-infra/gardener-kubeconfig-rotation.yaml
  prow/jobs/test-infra/image-syncer.yaml
  prow/jobs/test-infra/kyma-bot.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/config.yaml
  templates/data/image-syncer-data.yaml
  templates/data/kyma-bot-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-validation-data.yaml
  templates/data/prow-periodics-data.yaml
  templates/data/secret-rotation-data.yaml
  templates/data/test-infra/pjtester-data.yaml
Labels: area/ci, size/XL, lgtm, kind/deprecation, add-or-update

#8334 Remove autobumper
  prow/scripts/resources/autobumper/.golangci.yaml
  prow/scripts/resources/autobumper/bumper/bumper.go
  prow/scripts/resources/autobumper/bumper/bumper_test.go
  prow/scripts/resources/autobumper/go.mod
  prow/scripts/resources/autobumper/go.sum
  prow/scripts/resources/autobumper/helper.go
  prow/scripts/resources/autobumper/helper_test.go
  prow/scripts/resources/autobumper/main.go
  prow/scripts/resources/autobumper/main_test.go
Labels: size/XXL, lgtm, kind/cleanup, area/tests, add-or-update

#8328 Fix unit test job
  prow/jobs/eventing-auth-manager/eventing-auth-manager-generic.yaml
  templates/data/eventing-auth-manager-data.yaml
Labels: area/eventing, kind/failing-test, size/XS, lgtm, add-or-update

#8339 Revert "GCP Workload Identity Federation for GitHub"
  configs/terraform/core/main.tf
  configs/terraform/environments/prod/gcp-workload-identity-federation.tf
  configs/terraform/environments/prod/github-variables.tf
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/terraform-executor.tf
Labels: size/M, lgtm, kind/bug, area/automation, no-changes

#8343 Add new alpine-git image
  .hadolint.yaml
  images/alpine/Dockerfile
  images/alpine/git/Dockerfile
  images/build-images.sh
Labels: area/ci, size/M, lgtm, kind/feature

#8344 Use image bumpers with git image
  .ko.yaml
  prow/jobs/test-infra/ko-build.yaml
Labels: area/ci, size/S, lgtm, kind/feature, no-changes

#8213 Application Connector Docker-in-Docker pipelines
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/kyma-project/control-plane/components/kyma-environment-broker/keb-subscription-cleanup-job-build.yaml
  prow/jobs/kyma-project/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/kyma-project/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/kyma-project/control-plane/tests/provisioner-tests/provisioner-tests-build.yaml
  prow/jobs/kyma-project/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/kyma-project/kyma/components/central-application-connectivity-validator/build-image-validator.yaml
  prow/jobs/kyma-project/kyma/components/central-application-connectivity-validator/lint-validator.yaml
  prow/jobs/kyma-project/kyma/components/central-application-connectivity-validator/unit-tests-validator.yaml
  prow/jobs/kyma-project/kyma/components/central-application-gateway/build-image-gateway.yaml
  prow/jobs/kyma-project/kyma/components/central-application-gateway/lint-gateway.yaml
  prow/jobs/kyma-project/kyma/components/central-application-gateway/unit-tests-gateway.yaml
  prow/jobs/kyma-project/kyma/components/compass-runtime-agent/build-image-agent.yaml
  prow/jobs/kyma-project/kyma/components/compass-runtime-agent/lint-agent.yaml
  prow/jobs/kyma-project/kyma/components/compass-runtime-agent/unit-tests-agent.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-connectivity-validator/build-image-validator-tests.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-connectivity-validator/tests-validator.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-gateway/build-image-gateway-tests.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-gateway/tests-gateway.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/compass-runtime-agent/build-image-agent-tests.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/compass-runtime-agent/tests-agent.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/mock-app-build.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-tests.yaml
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  templates/data/control-plane-build.yaml
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: area/ci, size/XXL, lgtm, area/prow, kind/chore, no-changes

#8275 Fix Compass PR Jobs
  prow/jobs/incubator/compass/components/schema-migrator/compass-director-gqlgen-validate.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
  templates/data/compass-validation-data.yaml
Labels: area/management-plane, size/M, lgtm, kind/deprecation, no-changes

#8264 Terraform execution as GitHub workflow.
  .github/workflows/pull-plan-prod-terraform.yaml
  .gitignore
Labels: size/M, lgtm, kind/feature, area/automation, no-changes

#8348 Add Istio 1.18.2 to image syncer
  development/image-syncer/external-images.yaml
Labels: area/service-mesh, size/XS, lgtm, kind/chore, no-changes

#8335 Get Kyma components.yaml from repository instead of bucket
  .koapps.yaml
  development/tools/cmd/githubrelease/README.md
  development/tools/cmd/githubrelease/main.go
  development/tools/pkg/release/change-record.md
  development/tools/pkg/release/kyma-components.yaml
  development/tools/pkg/release/options.go
  development/tools/pkg/release/release.go
  development/tools/pkg/release/release_test.go
  prow/scripts/build-kyma-artifacts.sh
Labels: area/ci, size/L, lgtm, kind/bug, no-changes

#8354 Fix checkout ref
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/S, lgtm, kind/feature, area/automation, no-changes

#8356 Fetch more commits
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/XS, lgtm, kind/feature, area/automation, no-changes

#8357 Compare both merge commit parents.
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/XS, lgtm, kind/feature, area/automation, no-changes

#8359 Adding explicit permissions for ID token
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/XS, lgtm, kind/feature, area/automation, no-changes

#8360 Remove Kyma project reference from presubmit CLI job
  prow/jobs/cli/cli-k3d.yaml
Labels: size/XS, lgtm, kind/cleanup, area/tests, add-or-update

#8340 Consider release variants for Telemetry e2e-tests
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-logging-release.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-tracing-release.yaml
Labels: area/tracing, area/logging, size/M, lgtm, kind/missing-test

#8353 Loose provider versions requirements.
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/terraform-executor.tf
Labels: size/S, add-or-update, area/automation, kind/chore

#8349 changing pre-main-kcp-cli image
  prow/jobs/control-plane/kcp-cli.yaml
  templates/data/control-plane-kcp-data.yaml
Labels: area/ci, kind/failing-test, size/XS, lgtm

#8363 Fix the table
  development/tools/cmd/githubrelease/README.md
Labels: area/documentation, size/S, lgtm

#8361 fix kyma-dashboard-prod job
  prow/jobs/kyma-dashboard/kyma-dashboard-prod.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8355 Increase integration-with-dump and integration-no-dump jobs resources
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/incubator/compass/compass-integration-with-dump.yaml
  templates/data/compass-integration-no-dump-data.yaml
  templates/data/compass-integration-with-dump-data.yaml
Labels: area/management-plane, size/S, lgtm, kind/chore, no-changes

#8364 fix kyma-dashboard-stage job
  prow/jobs/kyma-dashboard/kyma-dashboard-stage.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, no-changes

#8362 Add gcr-cleaner to clean up ACR
  prow/jobs/test-infra/gcr-cleaner.yaml
  prow/workload-cluster/trusted-workload/trusted_workloadidentity_serviceaccount.yaml
Labels: area/ci, size/L, lgtm, kind/feature, no-changes

#8366 Lint terraform.
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/S, lgtm, kind/feature, area/automation, no-changes

#8245 Use google-beta and update cluster to optimize_utilization
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/prow.tf
Labels: area/ci, size/S, lgtm, kind/feature, destroy

#8368 Fix opa constraint warnings
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
Labels: area/ci, size/M, lgtm, destroy, kind/chore

#8367 Remove secrets leaks log scanner TF module jobs
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, destroy

#8374 Add K8s default limit ranges for pods
  prow/workload-cluster/test-pods_LimitRange.yaml
Labels: area/ci, size/S, lgtm, kind/feature, no-changes
