Repository kyma-project/test-infra, pull requests merged in 2023-05, with the labels that each got.

#7577 tidy-up labels.yaml
  prow/labels.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup

#7575 Add container limits to template
  templates/templates/generic.tmpl
Labels: size/S, lgtm, area/tooling, kind/bug

#7569 adjust kyma-dashboard to ar
  prow/jobs/kyma-dashboard/kyma-dashboard-dev.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-stage.yaml
  templates/data/generic_component_kyma_dashboard_data.yaml
Labels: area/ci, size/L, lgtm, kind/feature

#7534 Non failing check if prowjob has owner and description annotations.
  development/prow/pjconfigtests/pjconfigtests_suite_test.go
  development/prow/pjconfigtests/pjconfigtests_test.go
  development/prow/prowjobs.go
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/M, lgtm, kind/feature

#7581 fix image for tests
  prow/scripts/cluster-integration/kyma-dashboard-smoke-test.sh
  prow/scripts/cluster-integration/kyma-dashboard-test.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#7582 disable push to eu.gcr.io in image-builder
  configs/kaniko-build-config.yaml
Labels: area/ci, size/XS, lgtm, kind/cleanup

#7584 Bump prometheus images to latest
  development/image-syncer/external-images.yaml
Labels: area/security, area/monitoring, lgtm

#7479 Telemetry module verification and release prow jobs
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm, area/telemetry

#7598 Add kind label for dependabot pull requests
  .github/dependabot.yml
  templates/data/test-infra/dependabot-config-data.yaml
Labels: area/ci, size/XS, lgtm, kind/feature

#7603 Add kind label for dependabot
  .github/dependabot.yml
  templates/data/test-infra/dependabot-config-data.yaml
Labels: area/ci, size/XS, lgtm, kind/feature

#7576 Remove prow-config.yaml from templates
  prow/config.yaml
  templates/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup

#7606 add kind/chore and area/ labels to autobump config
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/ci, size/XS, lgtm, kind/feature

#7610 migrate to ManagedCertificate v1 version
  prow/cluster/components/gcsweb-kyma-prow_managedcertificate.yaml
  prow/cluster/components/monitoring/monitoring-kyma-prow_managedcertificate.yaml
  prow/cluster/components/status-kyma-prow_managedcertificate.yaml
  prow/cluster/resources/probot-stale/templates/managedcert.yaml
  prow/staging/cluster/kyma-prow_managedcertificate.yaml
  prow/staging/cluster/monitoring/monitoring-kyma-prow_managedcertificate.yaml
Labels: area/ci, size/S, lgtm, kind/deprecation

#7607 Block PR merge when PR has `needs-kind` and `needs-area` labels
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/feature

#7612 Delete test-log-collector
  development/test-log-collector/.dockerignore
  development/test-log-collector/.gitignore
  development/test-log-collector/Dockerfile
  development/test-log-collector/Makefile
  development/test-log-collector/README.md
  development/test-log-collector/chart/test-log-collector/.helmignore
  development/test-log-collector/chart/test-log-collector/Chart.yaml
  development/test-log-collector/chart/test-log-collector/files/config.yaml
  development/test-log-collector/chart/test-log-collector/templates/_helpers.tpl
  development/test-log-collector/chart/test-log-collector/templates/clusterrole.yaml
  development/test-log-collector/chart/test-log-collector/templates/clusterrolebinding.yaml
  development/test-log-collector/chart/test-log-collector/templates/cm.yaml
  development/test-log-collector/chart/test-log-collector/templates/job.yaml
  development/test-log-collector/chart/test-log-collector/templates/serviceaccount.yaml
  development/test-log-collector/chart/test-log-collector/values.yaml
  development/test-log-collector/cmd/app/mainerr.go
  development/test-log-collector/cmd/app/mainerr_test.go
  development/test-log-collector/cmd/main.go
  development/test-log-collector/go.mod
  development/test-log-collector/go.sum
  development/test-log-collector/pkg/config/config.go
  development/test-log-collector/pkg/config/config_test.go
  development/test-log-collector/pkg/resources/clustertestsuite/clustertestsuite.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/README.md
  development/test-log-collector/pkg/resources/clustertestsuite/types/labels.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/register.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/types.go
  development/test-log-collector/pkg/resources/clustertestsuite/types/zz_generated.deepcopy.go
  development/test-log-collector/pkg/resources/resource.go
  development/test-log-collector/pkg/slack/slack.go
  development/test-log-collector/pkg/slack/slack_test.go
  prow/jobs/test-infra/test-log-collector.yaml
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/cluster-integration/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
  prow/scripts/lib/utils.sh
  templates/data/test-log-collector-data.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup

#7617 fix image for tests
  prow/scripts/cluster-integration/busola-smoke-test-docker.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#7583 Add image build jobs
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: area/monitoring, size/L, lgtm, kind/feature

#7621 Bump prometheus image to latest 2.43.1
  development/image-syncer/external-images.yaml
Labels: area/security, area/monitoring, size/XS, lgtm, kind/chore

#7624 Remove stable cli release for JellyFish pipelines
  prow/jobs/cli/cli.yaml
  prow/scripts/cluster-integration/reconciler-integration-k3d.sh
  prow/scripts/lib/kyma.sh
  templates/data/cli-data.yaml
Labels: area/cli, size/M, lgtm, kind/deprecation

#7622 Update kind label help
  prow/plugins.yaml
Labels: area/ci, size/XS, lgtm, kind/chore

#7574 api-gateway integration custom domain job
  prow/config.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  templates/data/api-gateway-release.yaml
Labels: area/ci, size/M, lgtm, kind/feature

#7629 trying to fix post kyma dashboard
  prow/scripts/cluster-integration/kyma-dashboard-smoke-test.sh
  prow/scripts/cluster-integration/kyma-dashboard-test.sh
Labels: area/ci, size/S, lgtm, kind/bug

#7631 Golang 1.20.4 alpine3.17
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm, area/dependency, kind/chore

#7632 export pull number
  prow/scripts/provision-vm-and-start-kyma-dashboard-smoke-test.sh
  prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#7636 Changed nats-manager unit-tests target
  prow/jobs/nats-manager/nats-manager-generic.yaml
  templates/data/nats-manager-data.yaml
Labels: area/eventing, size/XS, lgtm, kind/bug

#7495 Initial rework of images
  images/README.md
  images/buildpack-go/Dockerfile
  images/buildpack-go/README.md
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-k3d/README.md
  images/e2e-dind-k3d/init.sh
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
  prow/images/README.md
Labels: size/L, lgtm

#7642 Add missing labels to dependabot
  .github/dependabot.yml
  templates/data/test-infra/dependabot-config-data.yaml
Labels: area/ci, size/S, lgtm, kind/bug

#7615 Update secret rotator TF config
  development/secrets-rotator/terraform/environments/prod/main.tf
  development/secrets-rotator/terraform/environments/prod/terraform.tfvars
  development/secrets-rotator/terraform/environments/prod/variables.tf
Labels: area/ci, size/S, lgtm, kind/feature, add-or-update

#7570 Terraform documentation
  docs/how-to/how-to-create-standard-terraform-config.md
Labels: area/documentation, size/L, lgtm, kind/feature

#7635 Improves the multi-platform part of the image-syncer documentation
  development/image-syncer/README.md
Labels: area/documentation, size/XS, lgtm, area/dependency, kind/chore

#7648 remove enableBasicAuthentication
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#7647 Prow group owns docs/index.md file.
  CODEOWNERS
Labels: area/ci, lgtm, kind/chore

#7628 Adapt to telemetry module scripts restructure
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  templates/data/directory-size-exporter-data.yaml
  templates/data/generic_component_data.yaml
  templates/data/telemetry-manager-data.yaml
Labels: size/L, lgtm, kind/cleanup, area/telemetry

#7649 Remove basic auth field for gardener
  prow/scripts/resources/reconciler/shoot-template.yaml
  prow/scripts/resources/skr-test/shoot-template.yaml
Labels: area/ci, size/M, lgtm, kind/chore

#7652 Prepare for Kyma 2.14
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-215.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: area/ci, size/L, lgtm, kind/chore

#7653 Fix Warden limits
  prow/jobs/kyma-project/warden/integration-test.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#7654 Istio integration tests job
  prow/jobs/istio/istio-integration.yaml
Labels: area/ci, size/M, lgtm, kind/feature

#7668 Trigger Eventing upgrade job when Eventing CRDs change
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, size/XS, lgtm, kind/bug

#7669 Remove unused jobs
  prow/jobs/busola/integration-docker-test.yaml
  prow/jobs/cli/cli-compatibility.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/governance.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/test-infra/validation.yaml
  templates/data/busola-integration-test-docker-data.yaml
  templates/data/cli-data.yaml
  templates/data/generic_component_control_plane_data.yaml
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/governance-data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/validation-data.yaml
Labels: area/ci, size/XXL, lgtm, kind/chore

#7559 Automatically update list of images in security scanners config
  development/image-detector/main.go
  development/pkg/extractimageurls/kubernetes.go
  development/pkg/extractimageurls/kubernetes_test.go
  development/pkg/extractimageurls/prowjob.go
  development/pkg/extractimageurls/prowjob_test.go
  development/pkg/extractimageurls/terraform.go
  development/pkg/extractimageurls/terraform_test.go
  development/pkg/extractimageurls/utils.go
  development/pkg/extractimageurls/utils_test.go
  development/pkg/securityconfig/securityconfig.go
  development/pkg/securityconfig/securityconfig_test.go
Labels: area/security, size/XL, lgtm, kind/feature

#7657 Fix the pre-main-control-plane-reconciler-e2e-latest-release
  prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
Labels: area/ci, kind/failing-test, size/S, lgtm

#7693 Goat projects prow run on code changes only
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/jobs/istio/istio-validation.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  templates/data/api-gateway-build.yaml
  templates/data/api-gateway-release.yaml
  templates/data/api-gateway-validation.yaml
  templates/data/istio-module-data.yaml
  templates/data/istio-validation.yaml
  templates/templates/generic.tmpl
Labels: area/service-mesh, area/ci, size/L, lgtm, area/api-gateway, kind/chore

#7685 Migrate test runner for serverless metrics
  prow/scripts/cluster-integration/kyma-serverless-metrics-nightly.sh
  prow/scripts/cluster-integration/kyma-serverless-run-test.sh
Labels: size/M, lgtm

#7701 prowjos for building new testimages
  images/buildpack-go/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
  prow/jobs/test-infra/images.yaml
  templates/data/prowjob-images-data.yaml
Labels: area/ci, size/XL, lgtm, kind/feature

#7694 Fix pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener prowjob
  prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
  prow/scripts/cluster-integration/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
Labels: area/ci, kind/failing-test, size/S, lgtm

#7709 Sync keda images into europe-docker.pkg.dev/kyma-project/prod
  development/image-syncer/external-images.yaml
Labels: lgtm, area/tools, kind/chore

#7704 Update pull-telemetry-manager-verify-module job
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  templates/data/telemetry-manager-data.yaml
Labels: size/XS, lgtm, kind/cleanup, area/telemetry

#7703 Goats prow jobs update: names, description and owner
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/istio/istio-validation.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/modules/internal/istio-manager.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/api-gateway-build.yaml
  templates/data/api-gateway-release.yaml
  templates/data/api-gateway-validation.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/istio-module-data.yaml
  templates/data/istio-validation.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/third-party-images-data.yaml
Labels: area/service-mesh, size/L, lgtm, area/api-gateway, kind/feature

#7663 Remove jobs failing for more than one week
  prow/jobs/busola/integration-docker-test.yaml
  prow/jobs/cli/cli-compatibility.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/kyma/releases/kyma-release-212.yaml
  templates/data/busola-integration-test-docker-data.yaml
  templates/data/cli-data.yaml
Labels: area/ci, size/L, lgtm, kind/chore

#7710 Fix the nightly-main-reconciler-publish-unstable-cli job
  prow/scripts/reconciler-publish-pr-cli.sh
  prow/scripts/reconciler-publish-unstable-cli.sh
Labels: area/cli, size/XS, lgtm, kind/bug

#7611 add configs for new app in keb
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/control-plane-build.yaml
Labels: size/L, lgtm, area/control-plane, kind/feature

#7714 Keda Release job
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/M, lgtm, kind/chore

#7708 Mark job controller-unit-test as required
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#7723 Update CODEOWNERS
  CODEOWNERS
Labels: size/M, lgtm, area/automation, kind/chore

#7724 Fix a typo in variable in keda release pipeline
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#7730 Increase resources for telemetry-manager e2e-tests
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test.yaml
Labels: size/XS, lgtm, kind/flake, area/telemetry

#7521 Gatekeeper workload clusters manifests
  .tfcmt.yaml
  configs/terraform/environments/prod/backend.tf
  configs/terraform/environments/prod/opa-gatekeeper.tf
  configs/terraform/environments/prod/output.tf
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/terraform-executor.tf
  configs/terraform/environments/prod/variables.tf
  configs/terraform/global.tfvars
  configs/terraform/prow/main.tf
  configs/terraform/prow/prow.tfvars
  configs/terraform/prow/trusted-workloads.tf
  development/terraform-executor/terraform/environments/dev/backend.tf
  development/terraform-executor/terraform/environments/dev/main.tf
  development/terraform-executor/terraform/environments/dev/output.tf
  development/terraform-executor/terraform/environments/dev/provider.tf
  development/terraform-executor/terraform/environments/dev/variables.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/main.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/output.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/provider.tf
  development/terraform-executor/terraform/modules/gcp-terraform-executor/variables.tf
  development/terraform-executor/terraform/modules/k8s-terraform-executor/main.tf
  development/terraform-executor/terraform/modules/k8s-terraform-executor/output.tf
  development/terraform-executor/terraform/modules/k8s-terraform-executor/provider.tf
  development/terraform-executor/terraform/modules/k8s-terraform-executor/variables.tf
  docs/examples/gatekeeper-poc.yaml
  opa/gatekeeper/constraint-templates/secretTrustedUsage.yaml
  opa/gatekeeper/constraint-templates/serviceAccountTrustedUsage.yaml
  opa/gatekeeper/constraint-templates/trustedSAUsage_test-data.yaml
  opa/gatekeeper/constraint-templates/trustedSecretUsage_test-data.yaml
  opa/gatekeeper/deployments/gatekeeper.yaml
  opa/terraform/environments/dev/backend.tf
  opa/terraform/environments/dev/main.tf
  opa/terraform/environments/dev/output.tf
  opa/terraform/environments/dev/provider.tf
  opa/terraform/environments/dev/terraform.tfvars
  opa/terraform/environments/dev/variables.tf
  opa/terraform/modules/gatekeeper/main.tf
  opa/terraform/modules/gatekeeper/output.tf
  opa/terraform/modules/gatekeeper/provider.tf
  opa/terraform/modules/gatekeeper/variables.tf
  tekton/deployments/config_defaults.yaml
  tekton/deployments/gatekeeper-constraints/imageBuilderSATrustedUsage.yaml
  tekton/deployments/gatekeeper-constraints/signifyDevSecretTrustedUsage.yaml
  tekton/deployments/gatekeeper-constraints/signifyProdSecretTrustedUsage.yaml
  tekton/deployments/signify_secret_rbac.yaml
Labels: size/XXL, lgtm, no-changes

#7740 have nginx in kyma docker registry
  development/image-syncer/external-images.yaml
Labels: kind/failing-test, size/XS, lgtm, area/tests, area/telemetry

#7742 Fix review assignments.
  CODEOWNERS
Labels: size/M, lgtm, kind/bug, area/automation

#7751 add file permission workaround to clone-refs.yaml
  task/clone-refs/0.1/clone-refs.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#7750 Set gatekeeper constraints warning enforce mode.
  opa/gatekeeper/constraint-templates/secretTrustedUsage.yaml
  opa/gatekeeper/constraint-templates/serviceAccountTrustedUsage.yaml
  opa/gatekeeper/constraint-templates/test-data/trustedSAUsage_test-data.jsonc
  opa/gatekeeper/constraint-templates/test-data/trustedSecretUsage_test-data.jsonc
  tekton/deployments/gatekeeper-constraints/imageBuilderSATrustedUsage.yaml
  tekton/deployments/gatekeeper-constraints/signifyDevSecretTrustedUsage.yaml
  tekton/deployments/gatekeeper-constraints/signifyProdSecretTrustedUsage.yaml
Labels: area/security, size/S, lgtm, kind/feature

#7753 Fix images.yaml
  prow/jobs/test-infra/images.yaml
  templates/data/prowjob-images-data.yaml
Labels: area/ci, size/M, lgtm, kind/bug

#7716 Add tekton as source entry for list of images in security config
  development/image-detector/main.go
  development/pkg/extractimageurls/tekton.go
  development/pkg/extractimageurls/tekton_test.go
  go.mod
  go.sum
Labels: area/security, size/L, lgtm, kind/feature

#7764 Add missing secret to signify
  prow/jobs/test-infra/images.yaml
  templates/data/prowjob-images-data.yaml
Labels: area/ci, size/S, lgtm, kind/bug

#7755 Fix terraform apply
  docs/index.md
  prow/jobs/test-infra/terraform.yaml
  task/hide-github-pr-comments/0.1/README.md
  task/hide-github-pr-comments/0.1/hide-github-pr-comments.yaml
  task/hide-github-pr-comments/samples/sample_prowjob_pipeline.yaml
  task/terraform-executor/0.1/README.md
  task/terraform-executor/0.1/terraform-executor.yaml
  task/terraform-executor/samples/sample_prowjob_pipeline.yaml
Labels: size/L, lgtm, kind/bug, area/automation

#7765 Remove btp-operator credentials references
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
  prow/config.yaml
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
  templates/data/skr-integration-data.yaml
  templates/data/skr-own-cluster-dev.yaml
Labels: size/L, lgtm, kind/cleanup, area/tests

#7752 Updated Expression to better match release version and added a secondary job to build the new image
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/M, lgtm, kind/bug, no-changes

#7702 Add Terraform config for opa gatekeeper constraints
  .gitignore
  configs/terraform/environments/prod/opa-gatekeeper.tf
  configs/terraform/environments/prod/variables.tf
  opa/terraform/environments/dev/main.tf
  opa/terraform/environments/dev/variables.tf
  opa/terraform/modules/gatekeeper/main.tf
  opa/terraform/modules/gatekeeper/variables.tf
Labels: area/ci, size/L, lgtm, kind/feature, add-or-update

#7766 added more ownership annotations
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/kyma-integration-data.yaml
Labels: area/ci, size/M, lgtm, kind/chore, no-changes

#7771 bump postgres image
  development/image-syncer/external-images.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, no-changes

#7773 Set annotations
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/releases/kyma-release-213.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  prow/jobs/test-infra/test-infra-trusted-jobs.yaml
  prow/jobs/test-infra/triage-jobs.yaml
  prow/staging/jobs/test-infra-jobs.yaml
  templates/data/checkconfig.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/presubmit_scanner_data.yaml
  templates/data/prow-periodics-data.yaml
  templates/data/test-infra/pjconfigtests.yaml
  templates/data/test-infra/pjtester-data.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: area/ci, size/XL, lgtm, kind/chore, no-changes

#7739 Add documentation for image-detector
  development/image-detector/README.md
  development/image-detector/main.go
Labels: area/security, size/M, lgtm, kind/feature

#7754 Fix trigger for nats-manager unit test job
  CODEOWNERS
  prow/jobs/nats-manager/nats-manager-generic.yaml
  templates/data/nats-manager-data.yaml
Labels: area/eventing, size/XS, lgtm, kind/bug, no-changes

#7763 update job owners eventing
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/eventing-auth-manager/eventing-auth-manager-generic.yaml
  prow/jobs/eventing-manager/eventing-manager-generic.yaml
  prow/jobs/eventing-tools/eventing-tools-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-checks.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-checks.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/control-plane-build.yaml
  templates/data/eventing-auth-manager-data.yaml
  templates/data/eventing-manager-data.yaml
  templates/data/eventing-tools-data.yaml
  templates/data/generic_component_control_plane_data.yaml
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/nats-manager-data.yaml
Labels: area/eventing, size/L, lgtm, kind/chore, no-changes

#7738 Add framefrog team prow jobs metadata
  prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/kyma-project/compass-manager/build.yaml
  prow/jobs/kyma-project/compass-manager/compass-manager-tests.yaml
  prow/jobs/kyma-project/compass-manager/golang-linter.yaml
  prow/jobs/kyma-project/compass-manager/static-checks.yaml
  prow/jobs/kyma/common/common.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-tests.yaml
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  templates/data/control-plane-build.yaml
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-tools-data.yaml
Labels: area/application-connector, size/L, lgtm, area/control-plane, kind/cleanup, no-changes
