Repository kyma-project/test-infra, pull requests merged in 2023-01, with the labels that each got.

#6646 Update NATS to 2.9.10
  development/image-syncer/external-images.yaml
Labels: area/eventing, size/XS, lgtm

#6639 Kyma dashboard
  prow/jobs/kyma-dashboard/kyma-dashboard-test.yaml
  prow/scripts/cluster-integration/kyma-dashboard-test.sh
  prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
  templates/data/kyma-dashboard-test.yaml
Labels: size/L, lgtm

#6647 Bump Prometheus
  prow/cluster/components/monitoring/prometheus_operator_deployment.yaml
  prow/cluster/components/monitoring/prometheus_operator_rbac.yaml
  prow/cluster/components/monitoring/prow_alertmanager.yaml
  prow/cluster/components/monitoring/prow_prometheus.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_alertmanagerconfigs.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_probes.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_prometheuses.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_thanosrulers.yaml
  prow/cluster/components/pushgateway_deployment.yaml
Labels: size/XXL, lgtm

#6649 Adopt K8S 1.22 in compass benchmark job
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/S, lgtm

#6650 Fix compass benchmark job after k8s 1.22 adoption
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/XS, lgtm

#6640 Fix API-gateway release pipeline
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  templates/data/api-gateway-release.yaml
Labels: size/M, lgtm

#6662 add kyma-dashboard to squash
  prow/config.yaml
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#6664 Fix pull-btp-manager-build
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/S, lgtm

#6652 adjust paths to new file organisation for tests
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
  prow/scripts/provision-vm-and-start-busola-lighthouse.sh
Labels: size/XS, lgtm

#6687 Generate jobs for Kyma 2.10 release
  development/tools/jobs/releases/releases.go
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-211.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/XL, lgtm

#6670 Pull Request statistics
  prow/cluster/components/monitoring/dashboards/quality/prstats.json
Labels: area/ci, lgtm

#6673 Update NATS to 2.9.11
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6655 add tekton-pipelines and dashboard configuration
  configs/tekton/deployments/config_defaults.yaml
  configs/tekton/deployments/dashboard_managedcertificate.yaml
  configs/tekton/deployments/dashboard_release.yaml
  configs/tekton/deployments/pipelines_release.yaml
  configs/tekton/deployments/pipelines_serviceaccount.yaml
Labels: size/XXL, lgtm

#6683 Scan logs for secrets dependencies
  development/gcp/pkg/http/http.go
  development/gcp/pkg/pubsub/types.go
  development/gcp/pkg/types/types.go
  development/github/pkg/client/client.go
  development/github/pkg/client/v2/client.go
  development/github/pkg/types/types.go
  development/types/types.go
  go.mod
  go.sum
Labels: area/security, size/L, lgtm, area/tools

#6691 Remove workaround in pipeline to serverless manager
  prow/scripts/provision-vm-and-test-serverless-manager.sh
Labels: size/XS, lgtm

#6672 Scan logs for secrets build images pjs
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  templates/data/secret-leaks-log-scanner.yaml
Labels: area/security, size/XL, lgtm, area/tools

#6693 Fix context and dockerfile location paramters for image builder.
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
  templates/data/generic_external_module_data.yaml
Labels: area/security, size/L, lgtm, area/tools

#6695 Client constructor function was getting log name instead project name.
  development/gcp/pkg/logging/client.go
  development/tools/cmd/usersmapchecker/main.go
Labels: size/S, lgtm, kind/bug, area/tools

#6700 Fixed context and dockerfile location. Image builder was not able to …
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  templates/data/secret-leaks-log-scanner.yaml
Labels: area/security, size/L, lgtm, area/tools

#6701 Add Grafana configmaps
  prow/cluster/components/monitoring/grafana_deployment.yaml
Labels: area/ci, size/XS, lgtm

#6486 Fix compass ord-service unit tests job
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  templates/data/generic_component_compass_data.yaml
  templates/data/generic_component_ord_service_data.yaml
Labels: size/M, lgtm

#6707 make jobs optional
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  templates/data/secret-leaks-log-scanner.yaml
Labels: size/S, lgtm, area/tools

#6705 Remove Kiali
  prow/jobs/third-party-images/third-party-images.yaml
  prow/scripts/resources/compass-gke-kyma-overrides.tpl.yaml
  templates/data/third-party-images-data.yaml
Labels: size/L, lgtm

#6702 Update Grafana documentation
  docs/prow/prow-monitoring.md
Labels: area/ci, size/S, lgtm

#6704 add warden build and static checks jobs
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/warden.yaml
Labels: size/L, lgtm

#6706 Add gencred jobs for workload clusters
  configs/gencred-config.yaml
  prow/jobs/test-infra/test-infra-trusted-jobs.yaml
  prow/workload-cluster/trusted-workload/gencred-refresher_serviceaccount.yaml
Labels: size/M, lgtm

#6722 Update run_if_changed for busola web, backend and local
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  templates/data/generic_component_busola_data.yaml
Labels: size/M, lgtm

#6724 Update run_if_changed for busola lighthouse, test-k3s-cluster and tes…
  prow/jobs/busola/integration-k3s-test.yaml
  prow/jobs/busola/lighthouse.yaml
  templates/data/busola-integration-test-k3s-cluster-data.yaml
  templates/data/busola-integration-test-k3s-namespace-data.yaml
  templates/data/busola-lighthouse.yaml
Labels: size/S, lgtm

#6676 Create GitHub issue cloud run service
  development/gcp/cloud-run/create-github-issue/Dockerfile
  development/gcp/cloud-run/create-github-issue/create-github-issue.go
  development/github/pkg/templates/secretsleak.go
Labels: area/security, size/L, lgtm, area/tools

#6725 Add Prow connection to workload clusters with gencred configs
  configs/gencred-config.yaml
  prow/cluster/components/crier_deployment.yaml
  prow/cluster/components/deck_deployment.yaml
  prow/cluster/components/hook_deployment.yaml
  prow/cluster/components/prow_controller_manager_deployment.yaml
  prow/cluster/components/sinker_deployment.yaml
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
Labels: size/L, lgtm

#6729 Btp manager release1
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/M, lgtm

#6675 Update kyma CLI version to 2.3.0
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
  prow/scripts/provision-vm-compass.sh
Labels: size/XS, lgtm

#6732 Bump Gardener Linux version
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#6741 Bump golagn image to v1.19.5 multiplatform
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6737 ARM build for schema migrator
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/XS, lgtm

#6698 Serach GitHub issue service
  development/gcp/cloud-run/search-github-issue/Dockerfile
  development/gcp/cloud-run/search-github-issue/search-github-issues.go
Labels: area/security, size/L, lgtm, area/tools

#6689 Move gcs bucket service
  development/gcp/cloud-run/move-gcs-bucket/Dockerfile
  development/gcp/cloud-run/move-gcs-bucket/move-gcs-bucket.go
  go.mod
  go.sum
Labels: area/security, size/L, lgtm, area/tools

#6685 Send slack message service
  development/gcp/cloud-run/slack-message-sender/Dockerfile
  development/gcp/cloud-run/slack-message-sender/requirements.txt
  development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
Labels: area/security, size/L, lgtm, area/tools

#6750 Fix btp module regexp
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/XS, lgtm

#6751 Btp manager registry settings
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/XS, lgtm

#6752 Update buildkit base image version
  development/image-builder/images/buildkit/Dockerfile
Labels: size/XS, lgtm

#6756 Revert ARM build for schema migrator
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  templates/data/generic_component_compass_data.yaml
Labels: size/XS, lgtm

#6758 Bump k8s to 1.25 for pipelines
  prow/config.yaml
  prow/jobs/kyma/releases/kyma-release-210.yaml
  prow/jobs/kyma/releases/kyma-release-29.yaml
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/M, lgtm

#6759 Upgrade kubectl to version for k8s 1.25
  development/custom-image/install-deps-debian.sh
  prow/images/bootstrap/Dockerfile
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
Labels: size/S, lgtm

#6760 Upgrade kyma preview job to k8s 1.26
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#6763 remove local-kyma from scripts
  prow/scripts/cluster-integration/busola-lighthouse.sh
  prow/scripts/provision-vm-and-start-busola-docker.sh
  prow/scripts/provision-vm-and-start-busola-k3s.sh
Labels: size/M, lgtm

#6766 Fix ProwJob authentication
  development/tools/cmd/pjtester/main.go
  development/tools/pkg/pjtester/pjtester.go
  development/tools/pkg/pjtester/pjtester_test.go
Labels: size/S, lgtm

#6773 BTP manager preset
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/S, lgtm

#6774 Disallow privileged containers in Busola
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
Labels: size/XS, lgtm

#6775 Disallow priviledged containers in Busola
  prow/scripts/resources/busola/cluster-busola.yaml
  prow/scripts/resources/busola/cluster-kyma.yaml
  prow/scripts/resources/reconciler/shoot-template.yaml
Labels: size/XS, lgtm

#6776 Return instead of exiting in utils::receive_from_vm
  prow/scripts/lib/utils.sh
Labels: size/S, lgtm

#6767 remove local-kyma from templates
  prow/jobs/kyma-dashboard/kyma-dashboard-test.yaml
  prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
  templates/data/kyma-dashboard-test.yaml
Labels: size/S, lgtm

#6765 remove local-kyma from templates
  prow/jobs/busola/busola-backend/backend-deployment-check.yaml
  prow/jobs/busola/busola-web/web-deployment-check.yaml
  prow/jobs/busola/integration-k3s-test.yaml
  templates/data/busola-backend-deployment-check-data.yaml
  templates/data/busola-integration-test-k3s-cluster-data.yaml
  templates/data/busola-integration-test-k3s-namespace-data.yaml
  templates/data/busola-web-deployment-check-data.yaml
Labels: size/M, lgtm

#6779 BTP-manager bot preset usage
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/S, lgtm

#6684 Scan logs for secrets service
  development/gcp/cloud-run/scan-logs-for-secrets/Dockerfile
  development/gcp/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
  go.mod
  go.sum
Labels: area/security, size/L, lgtm, area/tools

#6772 Add btp github bot
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
Labels: size/S, lgtm

#6686 Scan logs for secrets workflow.
  development/gcp/workflows/secrets-leak-detector.yaml
Labels: area/security, size/M, lgtm, area/tools

#6788 Add tracing component to kyma k3d telemetry job
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
Labels: size/XS, lgtm

#6789 Istio squash merge
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/XS, lgtm

#6784 Add api gateway secrets
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Labels: area/ci, size/M, lgtm

#6791 BTP manager releases jobs without run_if_changed
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/M, lgtm

#6736 Keda integration tests
  prow/jobs/kyma/kyma-gke-external-registry.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  prow/scripts/provision-vm-and-run-manager.sh
  prow/scripts/provision-vm-and-test-serverless-manager.sh
  templates/data/generic_module_data.yaml
Labels: size/XL, lgtm

#6802 Fixed path of files to copy from context.
  development/gcp/cloud-run/slack-message-sender/Dockerfile
Labels: size/XS, lgtm, kind/bug, area/tools

#6803 Branch setting for post-btp-manager-build
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/XS, lgtm

#6810 chore: update go.mod and codebase
  development/github/pkg/client/v2/client.go
  development/github/pkg/repoowners/client.go
  development/markdown-index/bumper/bumper.go
  go.mod
  go.sum
Labels: size/XXL, lgtm

#6762 Add validaiton jobs for SM and GQL in Director
  prow/jobs/incubator/compass/components/schema-migrator/compass-director-gqlgen-validate.yaml
  prow/jobs/incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
  prow/scripts/validate-compass-generic.sh
  templates/data/compass-validation-data.yaml
Labels: size/L, lgtm

#6795 Remove references to deprecated pod presets
  CODEOWNERS
  development/tools/jobs/incubator/podpreset-crd/podpreset_crd_test.go
  development/tools/jobs/testinfra/branchprotector_test.go
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjtester.yaml
  templates/config.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#6812 Mark unit test as mandatory in warden
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/warden.yaml
Labels: size/XS, lgtm

#6807 Removed usage of deprecated types.
  development/gcp/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
  development/types/types.go
Labels: size/S, lgtm, kind/bug, area/tools

#6819 fix: regexes for run_if_change
  prow/jobs/kyma-dashboard/kyma-dashboard-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
  prow/jobs/kyma-dashboard/kyma-dashboard-stage.yaml
  templates/data/generic_component_kyma_dashboard_data.yaml
  templates/data/kyma-dashboard-smoke-test-prod.yaml
  templates/data/kyma-dashboard-smoke-test-stage.yaml
Labels: size/S, lgtm

#6818 Mount secret for image build - SKR Runtime Watcher
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  templates/data/runtime-watcher-data.yaml
Labels: size/S, lgtm

#6824 Workaround: not failing the job regardless of kubectl logs result
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-alpha.sh
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
Labels: size/XS, lgtm

#6827 Add warden in-cluster integration test
  prow/jobs/kyma-project/warden/integration-test.yaml
Labels: size/M, lgtm
