Repository kyma-project/test-infra, pull requests merged in 2023-10, with the labels that each got.

#8988 Move OPA Gatekeeper terraform config to valid location.
  configs/terraform/environments/dev/opa-gatekeeper/backend.tf
  configs/terraform/environments/dev/opa-gatekeeper/main.tf
  configs/terraform/environments/dev/opa-gatekeeper/output.tf
  configs/terraform/environments/dev/opa-gatekeeper/provider.tf
  configs/terraform/environments/dev/opa-gatekeeper/terraform.tfvars
  configs/terraform/environments/dev/opa-gatekeeper/variables.tf
  configs/terraform/environments/prod/opa-gatekeeper.tf
  configs/terraform/modules/opa-gatekeeper/main.tf
  configs/terraform/modules/opa-gatekeeper/output.tf
  configs/terraform/modules/opa-gatekeeper/provider.tf
  configs/terraform/modules/opa-gatekeeper/variables.tf
  opa/terraform/environments/dev/main.tf
  opa/terraform/environments/dev/output.tf
Labels: size/M, lgtm, area/automation, kind/chore

#8982 Remove template for dependabot config
  templates/data/test-infra/dependabot-config-data.yaml
  templates/templates/dependabot.tmpl
Labels: area/ci, size/L, lgtm, kind/cleanup

#8989 Exclude prometheus secret from checker
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
Labels: size/S, lgtm, area/prow, kind/chore

#8990 Migrate Compass Manager linter job to GitHub Actions
  prow/jobs/kyma-project/compass-manager/golang-linter.yaml
Labels: area/ci, size/M, lgtm, kind/cleanup

#8992 bug fix api gateway manager job
  prow/jobs/api-gateway/api-gateway-manager-integration-tests.yaml
  templates/data/api-gateway-manager-integration-tests.yaml
Labels: size/XS, lgtm, area/api-gateway, kind/bug

#8961 Move serverless jobs to serverless manager file
  prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d-operator.sh
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/XXL, lgtm, kind/feature

#9001 Fix broken links
  development/tools/cmd/jobguard/README.md
  images/buildpack/go/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
  prow/images/README.md
Labels: area/ci, size/S, lgtm, kind/bug

#9007 Disable Signify dev
  configs/kaniko-build-config.yaml
Labels: area/ci, kind/failing-test, size/M, lgtm

#9009 Fix terraform job
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-detector.tf
  docs/how-to/how-to-create-standard-terraform-config.md
Labels: area/ci, kind/failing-test, size/XS, lgtm

#9010 remove signify dev
  configs/kaniko-build-config.yaml
Labels: area/ci, size/S, lgtm, kind/bug

#9012 Fix excludes file path
  .github/dependabot.yml
  .gitignore
  cmd/cloud-run/move-gcs-bucket/Dockerfile
  cmd/cloud-run/slack-message-sender/Dockerfile
  development/tools/pkg/pjtester/test_artifacts/test-job.yaml
  docs/examples/gatekeeper-poc.yaml
  pkg/logging/console.go
  prow/images/automerge-notification-external-plugin/Dockerfile
  prow/images/gardener-rotate/Dockerfile
  prow/images/prow-tools/Dockerfile
  prow/jobs/kyma/kyma-validation.yaml
  prow/jobs/test-infra/build-test-vm-image.yaml
  prow/jobs/test-infra/gardener-kubeconfig-rotation.yaml
  prow/jobs/test-infra/image-syncer.yaml
  prow/jobs/test-infra/ko-build.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/build-test-vm-image.yaml
  templates/data/image-syncer-data.yaml
  templates/data/kyma-validation-data.yaml
  templates/data/secret-rotation-data.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: area/ci, kind/failing-test, size/L, lgtm

#9013 Adding postsubmit job to build application-connector-manager
  prow/jobs/modules/internal/application-connector-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/application-connector, size/L, lgtm, kind/cleanup

#9021 remove not needed istio reconciler int test
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: lgtm, kind/cleanup, area/tests

#9008 Remove serverless kyma ci
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d-operator.sh
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
  prow/scripts/cluster-integration/kyma-serverless-metrics-nightly.sh
  prow/scripts/cluster-integration/kyma-serverless-run-test.sh
  prow/scripts/cluster-integration/serverless-metrics-collector.yaml
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
Labels: area/serverless, size/XXL, lgtm, kind/feature

#9022 Remove usage of generate_module_chart
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/S, lgtm, kind/feature

#9029 Remove deleted components
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  prow/scripts/cluster-integration/kyma-integration-k3d-api-gateway-components.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-app-connector-components-os.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-app-connector-components-skr.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-istio-components.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
  prow/scripts/cluster-integration/reconciler-istio-integration.sh
  prow/scripts/reconciler/reconciler-ory-production-gardener-integration.sh
Labels: area/ci, size/S, lgtm, kind/cleanup, area/tests

#9026 Remove application-connector verify jobs after migration to GH Action
  prow/jobs/modules/internal/application-connector-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/L, lgtm, kind/missing-test

#9033 Fix post-application-connector-module-build job to run as postsubmit
  prow/jobs/modules/internal/application-connector-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/M, lgtm, kind/bug

#9030 Add golang 1.21.2 alpine 3.18 to the registry
  cmd/image-syncer/external-images.yaml
Labels: area/security, size/XS, lgtm, kind/chore

#9031 Remove env binding in command
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
Labels: area/serverless, size/M, lgtm, kind/chore

#9019 Eventing Module build job
  prow/jobs/eventing-manager/eventing-manager-generic.yaml
  templates/data/eventing-manager-data.yaml
Labels: area/eventing, size/L, lgtm, kind/feature

#9032 Rename serverless test directory
  prow/scripts/cluster-integration/kyma-serverless-run-test.sh
Labels: area/serverless, size/XS, lgtm, kind/chore

#9035 Add missing argument to the warden dind job
  prow/jobs/kyma-project/warden/integration-test.yaml
Labels: area/ci, size/XS, lgtm, kind/chore

#9036 Unify naming in serverless jobs
  prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/L, lgtm, kind/chore

#9037 Restore pre-main-application-connector-manager-verify job
  prow/jobs/modules/internal/application-connector-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/M, lgtm, kind/missing-test

#9038 Fix run if changed path for serverless integration
  prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#9046 Fix `warden-unit-test` job
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/warden.yaml
Labels: kind/failing-test, size/S, lgtm, area/tests

#7017 Auto approve dependabot
  .ko.yaml
  .koapps.yaml
  cmd/external-plugins/automated-approver/main.go
  cmd/external-plugins/automated-approver/plugin.go
  cmd/external-plugins/automerge-notification/main.go
  cmd/external-plugins/cla-assistant/main.go
  configs/automated-approver-rules.yaml
  go.mod
  go.sum
  pkg/logging/console.go
  pkg/prow/externalplugin/externalplugin.go
  prow/cluster/components/automated-approver_external-plugin.yaml
  prow/plugins.yaml
Labels: size/XL, lgtm, kind/feature, area/automation

#9050 remove -operator suffix from names used by serverless jobs
  prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
Labels: area/serverless, size/XS, lgtm, kind/cleanup

#9062 Bump Mend agent
  images/unified-agent/Dockerfile
Labels: area/security, size/XS, lgtm, kind/chore

#9068 Bump terraform image
  prow/images/terraform/Dockerfile
Labels: area/security, size/S, lgtm, kind/chore

#9076 Bump Golang
  images/buildpack/go/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
  images/unified-agent/go/Dockerfile
Labels: area/ci, size/S, lgtm, kind/chore

#9078 Use supported version of tf kubectl plugin
  configs/terraform/environments/dev/opa-gatekeeper/provider.tf
  configs/terraform/environments/prod/provider.tf
  configs/terraform/modules/opa-gatekeeper/provider.tf
Labels: area/ci, size/S, lgtm, kind/chore

#9079 fix tf kubectl apply paths
  configs/terraform/environments/prod/prow-external-plugins.tf
Labels: area/ci, size/XS, lgtm, kind/bug

#9070 Automated approver tests
  cmd/external-plugins/automated-approver/automated_approver_suite_test.go
  cmd/external-plugins/automated-approver/main.go
  cmd/external-plugins/automated-approver/plugin.go
  cmd/external-plugins/automated-approver/plugin_test.go
  cmd/external-plugins/automated-approver/test_files/automated-approver-rules-no-file.yaml
  cmd/external-plugins/automated-approver/test_files/automated-approver-rules-no-label.yaml
  cmd/external-plugins/automated-approver/test_files/automated-approver-rules-no-user.yaml
  cmd/external-plugins/automated-approver/test_files/automated-approver-rules.yaml
  cmd/external-plugins/automated-approver/test_files/oldPullRequestSynchronizeEventPayload
  cmd/external-plugins/automated-approver/test_files/pullRequestReviewDismissedEventPayload
  cmd/external-plugins/automated-approver/test_files/pullRequestReviewRequestedEventPayload
  cmd/external-plugins/automated-approver/test_files/pullRequestSynchronizeEventPayload
  pkg/prow/externalplugin/externalplugin.go
Labels: size/XXL, lgtm, kind/missing-test, area/tests

#9091 Tag application connector manager images with git SHA
  prow/jobs/modules/internal/application-connector-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#9092 Unify job names
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/warden.yaml
Labels: area/serverless, size/M, lgtm, kind/cleanup

#9081 Fix coping module-chart in serverless-operator
  prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/S, lgtm, kind/chore

#9104 Allow tags without v prefix
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, lgtm, kind/cleanup

#9112 Turn off exit on error in serverless integration
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
Labels: area/serverless, size/XS, lgtm, kind/bug

#9105 Remove fast-integration from reconciler e2e pipelines
  prow/scripts/reconciler/reconciler-e2e-gardener.sh
  prow/scripts/reconciler/reconciler-e2e-nightly-gardener.sh
Labels: size/S, lgtm, kind/cleanup, area/tests

#9113 Ensure serverless installed before serverless dependant FIT tests
  prow/scripts/cluster-integration/helpers/eventing.sh
Labels: area/eventing, kind/failing-test, size/XS, lgtm

#9115 Fix semver tagging for k8s-prow
  prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#9106 Remove periodic azure gardener job
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/ci, lgtm, kind/cleanup

#9122 Add release branch to compass jobs
  prow/jobs/incubator/compass/compass-integration-no-dump.yaml
Labels: size/XS, lgtm, area/prow, kind/feature

#9123 Bump Istio images to 1.19.3
  cmd/image-syncer/external-images.yaml
Labels: area/installation, size/XS, lgtm, kind/chore

#9126 Adjust prow jobs for api gateway modularisation
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-integration-tests.yaml
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  prow/jobs/api-gateway/api-gateway-manager-integration-tests.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/api-gateway/api-gateway-validation.yaml
  templates/data/api-gateway-build.yaml
  templates/data/api-gateway-integration-tests.yaml
  templates/data/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-integration-tests.yaml
  templates/data/api-gateway-release.yaml
  templates/data/api-gateway-validation.yaml
Labels: size/XL, lgtm, area/api-gateway, kind/cleanup

#8912 Add default tenant mapping handler component jobs
  prow/jobs/incubator/compass/components/default-tenant-mapping-handler-generic/default-tenant-mapping-handler-generic.yaml
Labels: size/L, lgtm, area/prow, kind/feature

#9128 Pin used GH actions
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: area/security, size/S, lgtm, kind/chore

#9134 Update codeowners
  CODEOWNERS
Labels: area/security, size/XS, lgtm, kind/chore

#9135 Remove ci-kyma-k8s-integration-next-k3d job
  prow/jobs/kyma/kyma-preview.yaml
Labels: area/monitoring, size/M, lgtm, kind/cleanup

#9137 change trigger api-gateway release
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: area/ci, size/XS, lgtm, kind/cleanup

#9143 Api gateway job update
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  prow/jobs/api-gateway/api-gateway-manager-integration-tests.yaml
  templates/data/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-integration-tests.yaml
Labels: area/ci, size/S, lgtm, area/api-gateway, kind/feature

#9144 extend regex for builds on pull apigateway
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: area/ci, size/XS, lgtm, area/api-gateway, kind/feature

#9146 add custom domain test job on pr to rel branch
  prow/jobs/api-gateway/api-gateway-manager-integration-tests.yaml
  templates/data/api-gateway-manager-integration-tests.yaml
Labels: area/ci, size/L, lgtm, area/api-gateway, kind/feature

#9124 more cleanup of the repo
  development/tools/cmd/githubrelease/Dockerfile
  docs/index.md
  experimental/changelog-generator/README.md
  experimental/changelog-generator/app/config-cleanup.sh
  experimental/changelog-generator/app/config-git.sh
  experimental/changelog-generator/app/config-setup.sh
  experimental/changelog-generator/app/generate-full-changelog.sh
  experimental/changelog-generator/app/generate-release-changelog.sh
  experimental/changelog-generator/app/push-full-changelog.sh
  experimental/changelog-generator/app/variables.sh
  prow/images/automerge-notification-external-plugin/Dockerfile
  prow/images/automerge-notification-external-plugin/Makefile
  prow/images/bootstrap/Dockerfile
  prow/images/bootstrap/Makefile
  prow/images/bootstrap/README.md
  prow/images/buildpack-golang/Dockerfile
  prow/images/buildpack-golang/Makefile
  prow/images/buildpack-golang/README.md
  prow/images/buildpack-golang/license-puller.sh
  prow/images/buildpack-node/Dockerfile
  prow/images/buildpack-node/Makefile
  prow/images/buildpack-node/README.md
  prow/images/buildpack-node/license-puller.sh
  prow/images/cla-assistant-external-plugin/Dockerfile
  prow/images/cleaner/Dockerfile
  prow/images/cleaner/Makefile
  prow/images/cleaner/README.md
  prow/images/cleaner/cleaner.sh
  prow/images/debug-commando/Dockerfile
  prow/images/debug-commando/license-puller.sh
  prow/images/gardener-rotate/Dockerfile
  prow/images/gardener-rotate/Makefile
  prow/images/gardener-rotate/README.md
  prow/images/kyma-integration/Dockerfile
  prow/images/kyma-integration/Makefile
  prow/images/kyma-integration/README.md
  prow/images/needs-tws-external-plugin/Dockerfile
  prow/images/prow-tools/Dockerfile
  prow/images/prow-tools/Makefile
  prow/images/prow-tools/README.md
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup

#9125 Job Guard Documentation fix
  README.md
  cmd/jobguard/README.md
  prow/scripts/cluster-integration/README.md
Labels: area/documentation, size/M, lgtm, kind/cleanup

#9159 Delete letter prefix letter from job trigger pattern
  prow/jobs/eventing-manager/eventing-manager-generic.yaml
  templates/data/eventing-manager-data.yaml
Labels: area/eventing, size/XS, lgtm, kind/feature

#9160 Remove unneded script
  prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
  prow/scripts/lib/serverless-shared-k3s.sh
Labels: area/serverless, size/M, lgtm, kind/chore

#9148 Add jobs building warden modules
  prow/jobs/kyma-project/warden/warden.yaml
  templates/data/warden.yaml
Labels: area/ci, hacktoberfest-accepted, size/L, lgtm, kind/feature

#9172 add golang image 1.21.3-alpine3.18
  cmd/image-syncer/external-images.yaml
Labels: area/security, size/XS, lgtm, kind/chore

#9178 Add required status checks for CLI and lifecycle manager
  prow/config.yaml
Labels: size/S, lgtm, area/prow, kind/chore

#9101 Automated approver documentation.
  cmd/external-plugins/automated-approver/README.md
  cmd/external-plugins/automated-approver/assets/automated-approver.svg
  cmd/external-plugins/automated-approver/main.go
  cmd/external-plugins/automated-approver/plugin.go
  cmd/external-plugins/automated-approver/plugin_test.go
  docs/documentation_guidelines.md
Labels: area/documentation, size/L, lgtm, kind/feature

#9183 Increased lint job timeout
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#9184 Fix GH action commit
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#9182 remove branch protection for price calculator
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/feature

#9188 Update nextRelease in prow config to 2.20
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: area/security, size/M, lgtm, add-or-update, kind/chore

#9198 Delete not needed testgrid-default.yaml
  docs/prow/README.md
  docs/prow/prow-k8s-testgrid.md
  prow/testgrid-default.yaml
  templates/README.md
Labels: area/ci, size/M, lgtm, kind/cleanup, add-or-update

#9114 SKR test with region
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/jobs/kyma/skr-networking.yaml
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
  templates/data/skr-integration-data.yaml
  templates/data/skr-networking.yaml
Labels: area/ci, size/M, lgtm, add-or-update, kind/chore

#9202 Add module upgrade to the required state checks
  prow/config.yaml
Labels: size/XS, lgtm, area/prow, add-or-update, kind/chore

#9203 Fix post-test-infra-markdown-index-autobump secret constrain
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, destroy

#9206 Remove old CLI checks
  prow/config.yaml
Labels: size/XS, lgtm, area/prow, add-or-update, kind/chore

#9205 Add change-record.md to ignore list for index.md
  configs/autobump-config/test-infra-markdown-index-autobump-config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug, add-or-update

#9207 Add ARM64 architecture to compass schema migrator build job
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
Labels: size/XS, lgtm, area/prow, kind/feature, add-or-update

#9201 Add platformRegion to skr tests
  prow/jobs/kyma/keb-endpoints-test.yaml
  prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
  prow/jobs/kyma/skr-integration.yaml
  prow/jobs/kyma/skr-networking.yaml
  templates/data/keb-endpoints-test.yaml
  templates/data/skr-aws-upgrade-integration-dev-data.yaml
  templates/data/skr-integration-data.yaml
  templates/data/skr-networking.yaml
Labels: area/ci, size/M, lgtm, add-or-update, kind/chore

#9211 cleanup: moving jobs to repository-based structure
  prow/jobs/kyma-incubator/slack-bot/slack-bot-build.yaml
  prow/jobs/kyma-project/api-gateway/api-gateway-manager-build.yaml
  prow/jobs/kyma-project/api-gateway/api-gateway-manager-integration-tests.yaml
  prow/jobs/kyma-project/btp-manager/btp-manager-build.yaml
  prow/jobs/kyma-project/busola/busola-backend/backend-deployment-check.yaml
  prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
  prow/jobs/kyma-project/busola/busola-integration.yaml
  prow/jobs/kyma-project/busola/busola-web/busola-web.yaml
  prow/jobs/kyma-project/busola/busola-web/web-deployment-check.yaml
  prow/jobs/kyma-project/busola/busola.yaml
  prow/jobs/kyma-project/busola/lighthouse.yaml
  prow/jobs/kyma-project/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma-project/examples/examples-build.yaml
  prow/jobs/kyma-project/istio/istio-integration.yaml
  prow/jobs/kyma-project/istio/istio-manager.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-dev.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-integration.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-prod.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-stage.yaml
  prow/jobs/kyma-project/kyma-environment-broker/keb-endpoints-test.yaml
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-generic.yaml
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
  templates/data/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-integration-tests.yaml
  templates/data/btp-manager-build.yaml
  templates/data/directory-size-exporter-data.yaml
  templates/data/examples-build.yaml
  templates/data/istio-module-data.yaml
  templates/data/keb-endpoints-test.yaml
  templates/data/kyma-environment-broker-build.yaml
  templates/data/slack-bot/slack-bot-build.yaml
  templates/data/telemetry-manager-data.yaml
  templates/data/third-party-images-data.yaml
Labels: area/ci, size/S, lgtm, kind/cleanup, add-or-update

#9220 bug: fix gatekeeper constraints and remove not used job
  configs/autobump-config/dockerhub-autobump.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
Labels: area/ci, size/M, lgtm, kind/bug, destroy

#9227 Consolidation of notifications channels for neighbors team
  prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
  prow/jobs/test-infra/gardener-kubeconfig-rotation.yaml
  prow/jobs/test-infra/gcr-cleaner.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/prow-periodics-data.yaml
  templates/data/secret-rotation-data.yaml
Labels: area/ci, size/M, lgtm, add-or-update, kind/chore

#9212 cleanup: moving jobs to repository-based structure p2
  prow/jobs/kyma-incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/kyma-incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma-incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/kyma-incubator/compass/compass-integration-with-dump.yaml
  prow/jobs/kyma-incubator/compass/compass-smoke-test.yaml
  prow/jobs/kyma-incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/kyma-incubator/compass/components/default-tenant-mapping-handler-generic/default-tenant-mapping-handler-generic.yaml
  prow/jobs/kyma-incubator/compass/components/director/director-generic.yaml
  prow/jobs/kyma-incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/kyma-incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/kyma-incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/kyma-incubator/compass/components/ias-adapter/ias-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/instance-creator/instance-creator-generic.yaml
  prow/jobs/kyma-incubator/compass/components/kyma-adapter/kyma-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/kyma-incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-director-gqlgen-validate.yaml
  prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
  prow/jobs/kyma-incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/kyma-incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/kyma-incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/kyma-incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/kyma-incubator/reconciler/reconciler-k3d.yaml
  prow/jobs/kyma-incubator/reconciler/reconciler.yaml
  prow/jobs/kyma-project/api-gateway/eventing-webhook/eventing-webhook-certificates-build.yaml
  prow/jobs/kyma-project/api-gateway/eventing-webhook/eventing-webhook-certificates-release.yaml
  prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
  prow/jobs/kyma-project/cli/cli-k3d.yaml
  prow/jobs/kyma-project/cli/cli.yaml
  prow/jobs/kyma-project/eventing-auth-manager/eam-integration-test.yaml
  prow/jobs/kyma-project/eventing-auth-manager/eventing-auth-manager-generic.yaml
  prow/jobs/kyma-project/eventing-manager/eventing-manager-generic.yaml
  prow/jobs/kyma-project/hydroform/hydroform.yaml
  prow/jobs/kyma-project/infrastructure-manager/infrastructure-manager.yaml
  prow/jobs/kyma-project/keda-manager/keda-manager.yaml
  prow/jobs/kyma-project/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/kyma-project/nats-manager/nats-manager-generic.yaml
  prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml
  prow/jobs/kyma-project/serverless-manager/serverless-manager.yaml
  prow/jobs/kyma-project/template-operator/template-operator.yaml
  templates/data/cli-data.yaml
  templates/data/eventing-auth-manager-data.yaml
  templates/data/eventing-manager-data.yaml
  templates/data/eventing-webhook-certificates-build.yaml
  templates/data/eventing-webhook-certificates-release.yaml
  templates/data/generic_module_data.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/infrastructure-manager-data.yaml
  templates/data/lifecycle-manager-data.yaml
  templates/data/nats-manager-data.yaml
  templates/data/template-operator-data.yaml
Labels: area/ci, size/S, lgtm, kind/cleanup, add-or-update

#9229 Consolidation of notifications channels for neighbors team
  .github/workflows/lint-markdown-links-daily.yml
Labels: area/ci, size/S, lgtm, add-or-update, kind/chore

#9219 remove telemetry-manager integration jobs
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-logging-release.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-logging.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-metrics.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-tracing-release.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-tracing.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-integration-istio.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-verify-module.yaml
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update
