Repository kyma-project/test-infra, pull requests merged in 2023-04, with the labels that each got.

#7258 Clonerefs and image-builder tasks for tekton
  task/clone-refs/0.1/README.md
  task/clone-refs/0.1/clone-refs.yaml
  task/clone-refs/0.1/samples/prowjob-cloning-repositories.yaml
  task/clone-refs/Dockerfile
  task/clone-refs/main.go
  task/image-builder/0.1/README.md
  task/image-builder/0.1/image-builder.yaml
  task/image-builder/0.1/samples/prowjob-building-image.yaml
  tekton/deployments/external-secrets/external_secrets.yaml
  tekton/deployments/external-secrets/secrets_store.yaml
  tekton/deployments/external-secrets/values.yaml
Labels: size/XL, lgtm

#7374 Comparing CRD table in MD files using separate prow job
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: size/M, lgtm

#7398 Adds code coverage guard for Istio on PRs
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/jobs/istio/istio-validation.yaml
  templates/data/api-gateway-validation.yaml
  templates/data/istio-validation.yaml
Labels: size/M, lgtm

#7329 Updated tekton how to with details about clone-refs task.
  docs/how-to/how-to_use_tekton-pipelines-in-prow.md
Labels: area/documentation, area/ci, size/M, lgtm

#7400 Include .env in serverless module job triggers
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/XS, lgtm

#7394 Update external Alpine image to 3.17.3
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7401 Configure trivy for compass-manager
  prow/jobs/kyma-project/compass-manager/static-checks.yaml
Labels: size/M, lgtm

#7408 CRD comparison prow job trigger update
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: size/XS, lgtm

#7397 Removed unused tooling kyma functions and helm charts.
  development/kyma-ci-force-bot/ciforcebot/Dockerfile
  development/kyma-ci-force-bot/ciforcebot/Makefile
  development/kyma-ci-force-bot/ciforcebot/before-commit.sh
  development/kyma-ci-force-bot/ciforcebot/cmd/main.go
  development/kyma-ci-force-bot/ciforcebot/go.mod
  development/kyma-ci-force-bot/ciforcebot/go.sum
  development/kyma-ci-force-bot/kyma-ci-force-bot/.helmignore
  development/kyma-ci-force-bot/kyma-ci-force-bot/Chart.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/prod-values.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/stage-values.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/configMap.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/deployment.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/googleServiceAccountKeySecret.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/issueClosedSubscription.yaml
  development/kyma-ci-force-bot/kyma-ci-force-bot/templates/service.yaml
  development/kyma-slack-connector/notifyCommiterFunction/handler.py
  development/kyma-slack-connector/notifyCommiterFunction/requirements.txt
  development/kyma-slack-connector/oomFoundFunction/handler.py
  development/kyma-slack-connector/oomFoundFunction/requirements.txt
  development/kyma-slack-connector/pullrequestAutomergedFunction/handler.py
  development/kyma-slack-connector/pullrequestAutomergedFunction/requirements.txt
  development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/prod-values.yaml
  development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/pubsubConnectorEvent.json
  development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/pubsubConnectorEventAsyncSpec.json
  development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/stage-values.yaml
  development/kyma-slack-connector/slackConnectorChart/values/prowjob.failed/prod-values.yaml
  development/kyma-slack-connector/slackConnectorChart/values/prowjob.failed/stage-values.yaml
  development/kyma-slack-connector/slackConnectorChart/values/pullrequest.automerged/prod-values.yaml
  development/kyma-slack-connector/slackConnectorChart/values/pullrequest.automerged/stage-values.yaml
  prow/jobs/test-infra/buildpack.yaml
  templates/data/buildpack-data.yaml
Labels: size/XXL, lgtm, kind/cleanup

#7074 Eventing upgrade job to use release branch and disable atleastonce check for pre-upgrade tests
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, size/S, lgtm

#7410 Disable Privileged Containers
  prow/scripts/resources/skr-test/shoot-template.yaml
Labels: size/XS, lgtm

#7382 Move upgrade test logic to Keda repo
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/S, lgtm

#7411 Fixing typo in CRD comparison prow job
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: size/XS, lgtm

#7413 Removed unused function.
  development/gcp/pkg/pubsub/client.go
Labels: size/S, lgtm, kind/cleanup

#7407 Added neighbors-dev-bot as an owner of auto generated documentation files
  CODEOWNERS
Labels: size/XS, lgtm

#7430 Add lint reconciler
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: size/M, lgtm

#7431 Update cleaner regexp
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: area/ci, size/XS, lgtm

#7391 Fix issues labeled notification. Add slack users mentions.
  configs/tooling-kyma/external_secrets_tooling_kyma_prod.yaml
  development/gcp/cloud-run/slack-message-sender/requirements.txt
  development/kyma-slack-connector/issueLabeledFunction/handler.py
  development/kyma-slack-connector/issueLabeledFunction/handler_test.py
  development/kyma-slack-connector/slackConnectorChart/global-prod-values.yaml
  development/kyma-slack-connector/slackConnectorChart/templates/function.yaml
  development/kyma-slack-connector/slackConnectorChart/templates/functionServiceBindingUsage.yaml
  development/kyma-slack-connector/slackConnectorChart/templates/slackBotTokenSecret.yaml
Labels: size/L, lgtm

#7396 Fix sending notification for creation of release cluster
  development/kyma-slack-connector/releaseClusterCreatedFunction/handler.py
  development/kyma-slack-connector/slackConnectorChart/templates/gitRepository.yaml
  development/kyma-slack-connector/slackConnectorChart/templates/slackApplicationServiceBinding.yaml
  development/kyma-slack-connector/slackConnectorChart/templates/slackApplicationServiceInstance.yaml
Labels: size/M, lgtm, kind/bug, area/tools

#7435 Changed minimum number of machines for `pre-main-kyma-gardener-gcp-eventing-upgrade`
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  prow/scripts/lib/gardener/gcp.sh
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, size/S, lgtm

#7439 Shorten clustername
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#7438 Verbose & mandatory CLI lint
  prow/jobs/cli/cli.yaml
  templates/data/cli-data.yaml
Labels: size/S, lgtm

#7433 Bump the golang image to `golang:1.20.3-alpine3.17`
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7453 Do not delete persist cluster
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: area/ci, size/XS, lgtm

#7460 Fix cluster cleaner
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: size/XS, lgtm

#7461 Create release jobs for Kyma 2.13 release
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-214.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/L, lgtm

#7463 Use k8s 1.25 for GCP clusters
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#7469 update repository configuration for eventing-repositories
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#7471 remove event-subscriber-tools jobs
  CODEOWNERS
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#7470 add eventing- and nats- manager jobs
  prow/jobs/eventing-manager/eventing-manager-generic.yaml
  prow/jobs/eventing-tools/eventing-manager-checks.yaml
  prow/jobs/eventing-tools/nats-manager-checks.yaml
  prow/jobs/nats-manager/nats-manager-generic.yaml
  templates/data/eventing-manager-data.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/nats-manager-data.yaml
Labels: size/L, lgtm

#7393 Switch SAs to workload identity
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  docs/prow/presets.md
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/test-infra/kyma-bot.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  templates/data/kyma-bot-data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/prow-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: area/ci, size/L, lgtm

#7477 Add missing label for post-keb-deprovision-retrigger-job-build
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/control-plane-build.yaml
Labels: size/XS, lgtm

#7480 Updated Kcp Cli Version
  prow/images/kyma-integration/Dockerfile
Labels: size/XS, lgtm

#7482 Do not remove persist cluster
  prow/jobs/kyma/kyma-gardener-cleanup.yaml
  templates/data/kyma-gardener-cleanup-data.yaml
Labels: size/XS, lgtm

#7445 Pipeline for GolangCI linter in compass-manager repository
  prow/jobs/kyma-project/compass-manager/golang-linter.yaml
Labels: size/M, lgtm

#7454 Pipeline for component tests in compass-manager repository
  prow/jobs/kyma-project/compass-manager/compass-manager-tests.yaml
Labels: size/M, lgtm

#7493 Add missing job for building e2e-provisioning-test image
  prow/jobs/control-plane/tests/e2e/provisioning/e2e-provisioning-test-build.yaml
  templates/data/control-plane-build.yaml
Labels: size/L, lgtm

#7492 Update image-syncer target repository
  development/image-syncer/external-images.yaml
  prow/jobs/test-infra/image-syncer.yaml
  templates/data/image-syncer-data.yaml
Labels: size/S, lgtm

#7494 Remove docker from image-syncer jobs
  prow/jobs/test-infra/image-syncer.yaml
  templates/data/image-syncer-data.yaml
Labels: size/XS, lgtm

#7496 update nats image to 2.9.16
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7500 Remove control-plane-gke-integration prowjobs
  prow/jobs/control-plane/control-plane-gke-integration.yaml
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
  templates/data/control-plane-integration-data.yaml
Labels: size/XL, lgtm

#7501 Remove kcp-development-artifacts job
  prow/jobs/control-plane/kcp-development-artifacts.yaml
  prow/scripts/build-kcp-development-artifacts.sh
  templates/data/control-plane-kcp-data.yaml
Labels: size/L, lgtm

#7507 Reduce time to remove ProwJobs in Sinker
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#7510 Add BTP manager to Whitesource scans
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/M, lgtm

#7485 Enabled Stream/Consumer not recreated test Eventing upgrade job
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, size/XS, lgtm

#7508 Delete ias-adapter-migration job before installing Compass in compass-gke-benchmark job
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/XS, lgtm

#7468 Configure whitesource for `compass-manager`
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/M, lgtm

#7517 send notifications to the slack channel
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/kyma/releases/kyma-release-214.yaml
  templates/data/api-gateway-build.yaml
  templates/data/kyma-release-data.yaml
Labels: area/ci, size/S, lgtm

#7526 Clean-up module-manager test-infra
  prow/config.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  templates/config.yaml
  templates/data/module-manager-data.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#7516 Add missing job for building provisioner-test build job image
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-build.yaml
Labels: size/M, lgtm

#7528 Image bump prometheus-nats-exporter
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7530 Fix path to busola-e2e-cleaner.yaml
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
Labels: size/XS, lgtm

#7529 Fix invalid catalog path for Provisioner test
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-build.yaml
Labels: size/XS, lgtm

#7512 Update post-submit CRA job
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-tests.yaml
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#7532 Remove Jaeger TPI prow jobs
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: size/L, lgtm

#7543 Add Istio 1.17.2 to image registry
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7527 reduced footprint of azure jobs and disabled hibernation for gardener clusters
  prow/jobs/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gcp.sh
  templates/data/generic_component_data.yaml
  templates/data/kyma-integration-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
  templates/data/third-party-images-data.yaml
  test-inventory-integration.md
Labels: size/XL, lgtm

#7550 Configure token url for fast int tests
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm, kind/feature, area/tests

#7557 Add security scanner config file
  sec-scanner-config.yaml
Labels: area/security, size/XS, lgtm, kind/feature

#7560 Make pre-main-kyma-api-gateway-integration-k3d required
  prow/jobs/kyma/kyma-integration.yaml
  templates/data/kyma-integration-data.yaml
Labels: kind/failing-test, size/XS, lgtm, area/api-gateway

#7565 Bump postgres external image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm, area/prow, kind/feature

#7533 remove skr-azure-nightly job
  prow/jobs/kyma/skr-integration.yaml
  templates/data/skr-integration-data.yaml
  test-inventory-integration.md
Labels: area/eventing, size/M, lgtm, kind/cleanup

#7566 Bump postgres-exporter image
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm, needs-kind, needs-area

#7548 Remove unnecessary per-release compass benchmark job
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  templates/data/compass-gke-benchmark-data.yaml
Labels: area/management-plane, size/L, lgtm, kind/cleanup

#7571 Update prefix in autobump config to new registry
  prow/autobump-config/control-plane-autobump-reconciler-config.yaml
Labels: size/XS, lgtm, needs-kind, needs-area

#7544 Duplicate webhook certificate image build jobs
  prow/jobs/eventing-webhook/eventing-webhook-certificates-build.yaml
  prow/jobs/eventing-webhook/eventing-webhook-certificates-release.yaml
  templates/data/eventing-webhook-certificates-build.yaml
  templates/data/eventing-webhook-certificates-release.yaml
Labels: area/eventing, size/L, lgtm, area/api-gateway, kind/cleanup

#7572 Update codeowners of eventing build jobs
  CODEOWNERS
Labels: area/eventing, lgtm, kind/cleanup

#7573 Added missing pubsub labels.
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-integration-test.yaml
  prow/jobs/kyma-project/warden/integration-test.yaml
Labels: area/ci, kind/failing-test, size/XS, lgtm
