Repository kyma-project/test-infra, pull requests merged in 2023-09, with the labels that each got.

#8837 Sync latest kedacore images
  development/image-syncer/external-images.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#8839 add jellyfish as code owner to reconciler
  CODEOWNERS
Labels: area/community, size/XS, lgtm, kind/chore

#8838 make pre-main-reconciler-publish-pr-cli optional
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: kind/failing-test, size/XS, lgtm, area/reconciler

#8840 Make api-gateway webhook build jobs run on PR to main and release
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/eventing-webhook/eventing-webhook-certificates-build.yaml
  templates/data/api-gateway-build.yaml
  templates/data/eventing-webhook-certificates-build.yaml
Labels: size/S, lgtm, area/api-gateway, kind/chore

#8836 Define deny-default network policy
  configs/terraform/environments/prod/network-policy.tf
  configs/terraform/environments/prod/variables.tf
Labels: area/security, size/L, lgtm, kind/feature

#8842 Update external deps
  development/image-syncer/external-images.yaml
Labels: lgtm, area/dependency, kind/chore

#8732 Add jobs for instance-creator compass component
  prow/jobs/incubator/compass/components/instance-creator/instance-creator-generic.yaml
Labels: size/L, lgtm, area/prow, kind/feature

#8850 Fix gcscleaner tests
  development/tools/pkg/clusterscollector/collector.go
  development/tools/pkg/diskscollector/collector.go
  development/tools/pkg/dnscollector/collector.go
  development/tools/pkg/firewallcleaner/cleaner.go
  development/tools/pkg/gcscleaner/cleaner_test.go
  development/tools/pkg/gcscleaner/storage/automock/bucket_attrs.go
  development/tools/pkg/gcscleaner/storage/automock/bucket_handle.go
  development/tools/pkg/gcscleaner/storage/automock/bucket_iterator.go
  development/tools/pkg/gcscleaner/storage/automock/bucket_object.go
  development/tools/pkg/gcscleaner/storage/automock/client.go
  development/tools/pkg/gcscleaner/storage/automock/object_attrs.go
  development/tools/pkg/gcscleaner/storage/automock/object_handle.go
  development/tools/pkg/gcscleaner/storage/automock/object_iterator.go
  development/tools/pkg/gcscleaner/storage/automock/query.go
  development/tools/pkg/gcscleaner/storage/bucket.go
  development/tools/pkg/gcscleaner/storage/storage.go
  development/tools/pkg/orphanremover/remover.go
  development/tools/pkg/vmscollector/collector.go
Labels: area/ci, kind/failing-test, size/L, lgtm

#8848 Filter domains in CORS proxy
  development/gcp/cloud-run/cors-proxy/cors-proxy.go
Labels: area/security, size/M, lgtm, kind/feature

#8852 Bump CORS-proxy image
  configs/terraform/modules/cors-proxy/cors-proxy.tf
Labels: area/security, lgtm, kind/chore

#8819 Add job to build monitoring-custom-metrics example image
  prow/jobs/examples/examples-build.yaml
  templates/data/examples-build.yaml
Labels: size/L, lgtm, kind/feature, area/examples

#8861 Fix branch protection rules
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#8859 api-gateway module build prow jobs
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: area/ci, size/L, lgtm, kind/feature

#8865 Add istio 1.19.0 to external images
  development/image-syncer/external-images.yaml
Labels: area/service-mesh, size/XS, lgtm, kind/chore

#8866 Delete governance jobs for kyma, website and documentation-component
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: area/ci, size/L, lgtm, kind/deprecation

#8868 Invalid image name corrected
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: size/XS, lgtm, area/api-gateway, kind/bug

#8843 Building KEB from New Repository
  prow/jobs/kyma-environment-broker/new-kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/XL, lgtm, area/control-plane, kind/chore

#8867 Clean test infra from archived repositories
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/image-detector/inrepo-config.yaml
  prow/jobs/kyma/kyma-integration-gardener.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  prow/scripts/cluster-integration/README.md
  prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
  prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-integration.sh
  prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
  prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
  prow/scripts/kyma-testing.sh
  templates/config.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/ci, size/XXL, lgtm, kind/cleanup

#8878 Add debug info to gardener cleaner
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
Labels: area/cluster, size/XS, lgtm, kind/bug

#8863 Gardener Azure: Remove Slack notifications
  prow/jobs/kyma/kyma-integration-gardener.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XS, lgtm, area/tests, kind/chore

#8879 Cleanup of archived kyma-project repositories
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/image-detector/inrepo-config.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  prow/scripts/kyma-testing.sh
  templates/config.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup

#8880 Generic Build for the New KEB
  prow/jobs/control-plane/components/kyma-environment-broker/new-kyma-environment-broker-generic.yaml
Labels: area/ci, size/M, lgtm, area/prow, kind/feature

#8886 Fix gardener cleanup
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#8887 chore: Removes outdated governance jobs
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: area/ci, size/L, lgtm, kind/chore

#8888 Fix gardener cleanup
  prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
Labels: area/ci, size/S, lgtm, kind/bug

#8890 Remove governance jobs for community repository
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: area/community, size/L, lgtm, kind/cleanup

#8877 add cluster-inventory build and pull jobs
  prow/jobs/cluster-inventory/cluster-inventory.yaml
  templates/data/cluster-inventory-data.yaml
Labels: size/L, lgtm, area/control-plane, kind/feature

#8891 Removing Old Keb Jobs
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/new-kyma-environment-broker-generic.yaml
  prow/jobs/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/control-plane-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/XL, lgtm, area/control-plane, kind/cleanup

#8897 Update Kyma CLI version of k3d integration job
  prow/jobs/kyma/kyma-integration-k3d.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#8902 allow squash for busola
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#8903 Fix security issues
  development/gcp/cloud-run/create-github-issue/create-github-issue.go
  development/gcp/cloud-run/search-github-issue/search-github-issues.go
  development/tools/cmd/configuploader/main.go
  prow/jobs/incubator/compass/components/instance-creator/instance-creator-generic.yaml
Labels: area/security, size/S, lgtm, kind/chore

#8907 Bump Golang to 1.21.1
  images/buildpack/go/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
  images/unified-agent/go/Dockerfile
Labels: area/security, size/S, lgtm, kind/chore

#8894 renames build jobs from cluster inventory to infrastructure manager
  prow/jobs/infrastructure-manager/infrastructure-manager.yaml
  templates/data/infrastructure-manager-data.yaml
Labels: size/M, lgtm, area/control-plane, kind/cleanup

#8913 add module release jobs for nats manager
  prow/jobs/nats-manager/nats-manager-generic.yaml
  templates/data/nats-manager-data.yaml
Labels: area/eventing, size/L, lgtm, kind/feature

#8918 Bump cloud run images
  configs/terraform/modules/cors-proxy/cors-proxy.tf
  configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
  configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
Labels: area/security, size/S, lgtm, kind/chore

#8915 Run ko build on go.mod changes
  prow/jobs/test-infra/ko-build.yaml
Labels: area/security, size/S, lgtm, kind/bug

#8920 Fix jobs for Busola
  prow/jobs/busola/busola-integration.yaml
  prow/jobs/busola/lighthouse.yaml
Labels: size/XS, lgtm, kind/bug, area/busola

#8925 Remove pre-main-kyma-gardener-gcp-eventing w/o authmanager
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, size/M, lgtm, kind/cleanup

#8924 Add api gateway manager build post job
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: size/M, lgtm, area/api-gateway, kind/feature

#8927 api-gateway webhook removal
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/eventing-webhook/eventing-webhook-certificates-build.yaml
  prow/jobs/eventing-webhook/eventing-webhook-certificates-release.yaml
  templates/data/api-gateway-build.yaml
  templates/data/api-gateway-release.yaml
  templates/data/eventing-webhook-certificates-build.yaml
  templates/data/eventing-webhook-certificates-release.yaml
Labels: size/L, lgtm, area/api-gateway, kind/cleanup

#8928 Removed Unnecessary 'new' Prefix
  prow/jobs/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: area/ci, size/S, lgtm, kind/bug

#8935 Use unstable kyma in pipelines
  prow/jobs/kyma/kyma-integration-k3d.yaml
  prow/jobs/kyma/kyma-preview.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#8936 Run all serverless-manager jobs on release branches
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/M, lgtm, kind/feature

#8937 Change k8s-prow tag to v20230918-27dff7fe
  prow/cluster/components/crier_deployment.yaml
  prow/cluster/components/deck_deployment.yaml
  prow/cluster/components/gcsweb.yaml
  prow/cluster/components/ghproxy.yaml
  prow/cluster/components/hook_deployment.yaml
  prow/cluster/components/horologium_deployment.yaml
  prow/cluster/components/prow_controller_manager_deployment.yaml
  prow/cluster/components/sinker_deployment.yaml
  prow/cluster/components/statusreconciler_deployment.yaml
  prow/cluster/components/tide_deployment.yaml
  prow/config.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
  prow/jobs/test-infra/branchprotector.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/prow-periodics.yaml
  prow/jobs/test-infra/triage-jobs.yaml
  prow/scripts/branchprotector-job.yaml
  prow/workload-cluster/ghproxy.yaml
  sec-scanners-config.yaml
  templates/data/checkconfig.yaml
  templates/data/incubator-buildpack-data.yaml
  templates/data/prow-periodics-data.yaml
Labels: size/L, lgtm, area/prow, kind/bug

#8930 Module image creation jobs for api-gateway
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: size/L, lgtm, area/api-gateway, kind/feature

#8896 Remove make tests from KLM
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  templates/data/lifecycle-manager-data.yaml
Labels: size/M, lgtm, kind/cleanup, area/tests

#8941 Fix nginx constraint
  prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwNamespace.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#8944 Add sec conf for goreleaser
  prow/jobs/api-gateway/api-gateway-release.yaml
  templates/data/api-gateway-release.yaml
Labels: area/ci, size/XS, lgtm, kind/chore

#8949 increased resource limits for otel-collector build
  prow/jobs/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: area/ci, lgtm, kind/chore

#8950 Add missing parameter in Compass Manager build job
  prow/jobs/kyma-project/compass-manager/build.yaml
Labels: area/ci, size/XS, lgtm, kind/chore

#8943 Remove pre-main-kyma-integration-k3d-telemetry job
  prow/jobs/kyma/kyma-integration-k3d.yaml
Labels: size/M, lgtm, kind/cleanup, area/telemetry

#8951 Setting proper tag for api-gateway module while releasing
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: size/XS, lgtm, area/api-gateway, kind/feature

#8953 Add new governance job
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
  .mlc.config.json
Labels: area/ci, size/M, lgtm, kind/chore

#8954 Remove old governance jobs
  milv.config.yaml
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: area/ci, size/L, lgtm, kind/chore

#8956 Remove milv repo
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/chore

#8963 Move script to the expected folder
  prow/scripts/reconciler/reconciler-component-provision-gardener.sh
Labels: area/ci, size/XS, lgtm, kind/bug

#8964 Fix renamed script for Ory reconciler job
  prow/scripts/reconciler/reconciler-component-provision-gardener.sh
Labels: area/ci, lgtm, kind/bug, area/reconciler

#8966 Add new explicit Ory reconciler script
  prow/scripts/reconciler/reconciler-component-provision-gardener.sh
  prow/scripts/reconciler/reconciler-ory-production-gardener-integration.sh
Labels: area/ci, size/L, lgtm, kind/bug, area/reconciler

#8952 Add skr-networking-test
  prow/jobs/kyma/skr-networking.yaml
  templates/data/skr-networking.yaml
Labels: size/L, lgtm, area/control-plane, kind/feature

#8971 Protect Kyma branches
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#8969 Fix cra tests
  prow/jobs/kyma-project/kyma/components/compass-runtime-agent/unit-tests-agent.yaml
Labels: area/application-connector, kind/failing-test, size/XS, lgtm, area/tests

#8945 Adjust codeowners file
  CODEOWNERS
  prow/jobs/api-gateway/api-gateway-manager-build.yaml
  prow/jobs/eventing-auth-manager/eam-integration-test.yaml
  templates/data/api-gateway-manager-build.yaml
Labels: size/L, lgtm, area/tools, kind/chore

#8972 Update Keda Image to use PULL_BASE_REF
  prow/jobs/modules/external/keda-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/XS, lgtm, kind/feature

#8973 Fix external secrets checker
  development/tools/cmd/externalsecretschecker/main.go
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
Labels: area/ci, size/L, lgtm, kind/bug

#8975 Reconciler e2e just needs to run once a day
  prow/jobs/incubator/reconciler/reconciler.yaml
  templates/data/incubator-buildpack-data.yaml
Labels: area/ci, size/XS, lgtm, kind/chore

#8976 Add ko image for externalsecretschecker
  .koapps.yaml
Labels: area/ci, size/XS, lgtm, kind/bug

#8977 Bump externalsecretschecker image
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
Labels: area/ci, size/M, lgtm, kind/chore

#8979 Add .tf cloud run terraform files to autobump config
  docs/prow/prow-jobs-autobump.md
  prow/autobump-config/test-infra-autobump-config.yaml
  templates/config.yaml
  templates/templates/autobump-config.tmpl
  templates/templates/test-infra-autobump-config.yaml
Labels: area/ci, size/L, lgtm, kind/bug

#8981 cleanup prow secrets
  prow/cluster/resources/external-secrets/external_secrets_prow.yaml
Labels: size/M, lgtm, area/prow, kind/chore

#8980 Update release job to use PULL_BASE_REF
  prow/jobs/modules/internal/serverless-manager.yaml
  templates/data/generic_module_data.yaml
Labels: area/serverless, size/XS, lgtm, kind/feature

#8962 Add api gateway manager custom domain integration test jobs
  prow/jobs/api-gateway/api-gateway-manager-integration-tests.yaml
  templates/data/api-gateway-manager-integration-tests.yaml
Labels: size/L, lgtm, area/api-gateway, kind/feature
