Repository kyma-project/test-infra, pull requests merged in 2023-02, with the labels that each got.

#6831 Add missing run_if_changed directive
  prow/jobs/kyma-project/warden/integration-test.yaml
Labels: size/XS, lgtm

#6832 Bump istio images to 1.16.2 in image-syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6828 Fix upgrade pipeline
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
Labels: size/S, lgtm

#6830 update ginkgo and gomega modules
  go.mod
  go.sum
Labels: size/S, lgtm, area/dependency

#6823 Add libraries to dependabot ignore
  .github/dependabot.yml
  templates/data/dependabot-config-data.yaml
Labels: size/S, lgtm

#6801 Secret path from env
  development/gcp/cloud-run/create-github-issue/create-github-issue.go
  development/gcp/cloud-run/search-github-issue/search-github-issues.go
Labels: size/M, lgtm, area/tools

#6833 Enable dependabot additional updates.
  .github/dependabot.yml
  templates/data/dependabot-config-data.yaml
Labels: area/security, size/L, lgtm, area/dependency

#6854 Bump Golang and Alpine images
  development/gcp/cloud-run/create-github-issue/Dockerfile
  development/gcp/cloud-run/gardener-sa-rotate/Dockerfile
  development/gcp/cloud-run/kms-rotate/Dockerfile
  development/gcp/cloud-run/move-gcs-bucket/Dockerfile
  development/gcp/cloud-run/scan-logs-for-secrets/Dockerfile
  development/gcp/cloud-run/search-github-issue/Dockerfile
  development/image-builder/images/buildkit/Dockerfile
  development/image-syncer/external-images.yaml
  development/kyma-ci-force-bot/ciforcebot/Dockerfile
  development/kyma-github-connector/githubWebhookGateway/Dockerfile
  development/kyma-pubsub-connector/pubSubGateway/Dockerfile
  development/markdown-index/Dockerfile
  development/test-log-collector/Dockerfile
  prow/images/automerge-notification-external-plugin/Dockerfile
  prow/images/gardener-rotate/Dockerfile
  prow/images/test-untrusted-plugin/Dockerfile
Labels: size/M, lgtm

#6857 Add and update missing Tekton configuration
  configs/tekton/deployments/config_defaults.yaml
  configs/tekton/deployments/dashboard_ingress.yaml
  configs/tekton/deployments/pipelines_release.yaml
  prow/cluster/components/pipeline_deployment.yaml
  prow/cluster/components/pipeline_rbac.yaml
  prow/cluster/components/prowjob_customresourcedefinition.yaml
Labels: area/ci, size/XXL, lgtm

#6861 remove telemetry alpha job
  prow/config.yaml
  prow/jobs/kyma/kyma-integration.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-alpha.sh
  prow/scripts/provision-vm-and-start-kyma-k3d.sh
  templates/data/kyma-integration-data.yaml
  templates/templates/prow-config.yaml
  test-inventory-integration.md
Labels: size/L, lgtm

#6859 Using globalSets instead localSets with the same settings.
  templates/data/api-gateway-validation.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/istio-validation.yaml
Labels: size/L, lgtm, area/prow, area/tools

#6864 presubmit prowjob scanning commits
  prow/jobs/test-infra/presubmit-scanner.yaml
  templates/data/presubmit_scanner_data.yaml
Labels: size/XXL, lgtm

#6863 Update tekton to latest version
  configs/tekton/deployments/dashboard_ingress.yaml
  configs/tekton/deployments/dashboard_managedcertificate.yaml
  configs/tekton/deployments/dashboard_release.yaml
  configs/tekton/deployments/pipelines_release.yaml
Labels: size/XXL, lgtm

#6874 Prepare release 2.11
  development/tools/jobs/releases/releases.go
  prow/autobump-config/test-infra-autobump-config.yaml
  prow/jobs/busola/busola-backend/busola-backend.yaml
  prow/jobs/busola/busola-web/busola-web.yaml
  prow/jobs/busola/busola.yaml
  prow/jobs/cli/cli-integration.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
  prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
  prow/jobs/incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma/kyma-artifacts.yaml
  prow/jobs/kyma/releases/kyma-release-212.yaml
  prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/XL, lgtm

#6873 Enable security scans for the `keda-manager` repo
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/M, lgtm

#6862 Security Commit Scanner Documentation
  docs/prow/security_commit_scanner.md
Labels: size/M, lgtm

#6877 markdown format issue
  docs/prow/security_commit_scanner.md
Labels: size/S, lgtm

#6878 Bump golangci-lint image to 1.51.1
  prow/images/golangci-lint/Dockerfile
Labels: size/XS, lgtm

#6880 Mention security team on secret leak
  development/gcp/cloud-run/create-github-issue/create-github-issue.go
  development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
  development/github/pkg/templates/secretsleak.go
Labels: area/security, size/M, lgtm, area/tools

#6671 Scan logs for secrets terraform
  .github/dependabot.yml
  configs/terraform/core/apis.tf
  configs/terraform/secrets-leaks-log-scanner/.terraform.lock.hcl
  configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/secrets-leaks-log-scanner/main.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-detector.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
  templates/data/dependabot-config-data.yaml
Labels: area/security, area/monitoring, size/XL, lgtm, area/tooling

#6790 Build terraform image with populated provider plugins.
  prow/images/terraform/Dockerfile
  prow/jobs/test-infra/run-terraform-config.yaml
  prow/jobs/test-infra/terraform-executor.yaml
  templates/data/run-terraform-config.yaml
  templates/data/terraform-executor.yaml
  templates/templates/generic.tmpl
Labels: area/security, size/L, lgtm, area/tools

#6890 Require to build tf executor.
  prow/jobs/test-infra/terraform-executor.yaml
  templates/data/test-infra/terraform-executor.yaml
Labels: size/XS, lgtm

#6891 Fixed run if changed to run on changes any file in a path.
  prow/jobs/test-infra/terraform-executor.yaml
  templates/data/test-infra/terraform-executor.yaml
Labels: size/XS, lgtm

#6892 Change to trigger build.
  prow/images/terraform/Dockerfile
Labels: size/XS, lgtm

#6894 Add nodejs 18 runtime jobs
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/M, lgtm

#6856 Test pj specs pubsub config.
  .github/dependabot.yml
  development/external-plugins/needs-tws/plugin.go
  development/prow/pjconfigtests/pjconfigtests_suite_test.go
  development/prow/pjconfigtests/pjconfigtests_test.go
  development/prow/prowjobs.go
  prow/images/ginkgo/Dockerfile
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/run-terraform-config.yaml
  templates/data/buildpack-data.yaml
  templates/data/test-infra/dependabot-config-data.yaml
  templates/data/test-infra/pjconfigtests.yaml
  templates/templates/generic.tmpl
Labels: size/XXL, lgtm, area/prow, area/tests, area/tools

#6904 Added missing commit message prefix.
  .github/dependabot.yml
  templates/data/test-infra/dependabot-config-data.yaml
Labels: size/XS, lgtm, kind/bug

#6909 Remove `tekton_pipeline_run_spec` server-side validation from ProwJob CRD
  prow/cluster/components/prowjob_customresourcedefinition.yaml
Labels: size/XXL, lgtm, area/prow, kind/bug

#6903 Bumped NATS external image to 2.9.14 - test-infra
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6783 Adding API Gateway job provisioning Gardener cluster
  prow/config.yaml
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  templates/data/api-gateway-release.yaml
  templates/data/api-gateway-validation.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm

#6915 Add Signify prod secret
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
Labels: size/S, lgtm

#6884 Add Istio operator build job
  prow/jobs/istio/istio-operator-build.yaml
  prow/jobs/istio/istio-validation.yaml
  templates/data/istio-operator-build.yaml
  templates/data/istio-validation.yaml
Labels: size/L, lgtm

#6917 image-builder: pin notary signers to specific job types
  development/image-builder/main.go
  development/image-builder/main_test.go
  development/image-builder/sign/sign.go
Labels: size/M, lgtm, kind/feature, area/tools

#6834 Initial setup for deprovision retrigger
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/control-plane-build.yaml
Labels: size/L, lgtm

#6871 Reauthenticate client on passwd change
  development/gcp/cloud-run/create-github-issue/create-github-issue.go
  development/gcp/cloud-run/search-github-issue/search-github-issues.go
  development/gcp/pkg/cloudfunctions/logging.go
  development/github/pkg/client/client.go
Labels: area/security, size/L, lgtm, area/tools

#6922 change run if change for deployment check - busola
  prow/jobs/busola/busola-web/web-deployment-check.yaml
  templates/data/busola-web-deployment-check-data.yaml
Labels: size/XS, lgtm

#6888 Add Telemetry Manager module prow jobs
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/kyma/components/telemetry-operator/telemetry-manager-generic.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  templates/config.yaml
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/L, lgtm

#6938 Use Squash in warden
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#6920 Alert when error is logged for secrets leak detector services.
  configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/secrets-leaks-log-scanner/main.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
  development/gcp/pkg/cloudfunctions/logging.go
Labels: size/L, lgtm

#6895 documentation about how to add custom secrets
  docs/how-to/how-to-add-custom-secret.md
  docs/how-to/secret-manager-permissions.png
  docs/index.md
  docs/prow/prow-secrets-management.md
Labels: area/ci, size/M, lgtm

#6947 Removed not used cloud-functions.
  development/gcp/cloud-functions/checkoomevent/checkoomevent.go
  development/gcp/cloud-functions/checkoomevent/go.mod
  development/gcp/cloud-functions/checkoomevent/go.sum
  development/gcp/cloud-functions/getfailureinstancedetails/getfailureinstancedetails.go
  development/gcp/cloud-functions/getfailureinstancedetails/go.mod
  development/gcp/cloud-functions/getfailureinstancedetails/go.sum
  development/gcp/cloud-functions/getgithubcommiter/.gcloudignore
  development/gcp/cloud-functions/getgithubcommiter/getgithubcommiter.go
  development/gcp/cloud-functions/getslackuserforgithubuser/.gcloudignore
  development/gcp/cloud-functions/getslackuserforgithubuser/getslackuserforgithubuser.go
  development/gcp/cloud-functions/getslackuserforgithubuser/go.mod
  development/gcp/cloud-functions/getslackuserforgithubuser/go.sum
Labels: size/XXL, lgtm, kind/cleanup

#6869 Add how-to_use_tekton-pipelines-in-prow.md
  docs/prow/how-to_use_tekton-pipelines-in-prow.md
  tekton/catalog/tasks/git-clone.yaml
  tekton/deployments/config_defaults.yaml
  tekton/deployments/dashboard_ingress.yaml
  tekton/deployments/dashboard_managedcertificate.yaml
  tekton/deployments/dashboard_release.yaml
  tekton/deployments/pipelines_release.yaml
  tekton/deployments/pipelines_serviceaccount.yaml
Labels: size/XL, lgtm

#6954 Switch warden's ws scans to the main branch
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
Labels: size/XS, lgtm

#6943 Reverting changes as they were not used in final solution.
  development/github/pkg/client/v2/client.go
Labels: lgtm, kind/bug, kind/cleanup

#6893 Required pjs and prod images
  configs/terraform/global.tfvars
  configs/terraform/prow/main.tf
  configs/terraform/prow/prow.tfvars
  configs/terraform/prow/trusted-workloads.tf
  configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/secrets-leaks-log-scanner/main.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-detector.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
  prow/images/terraform/Dockerfile
  prow/jobs/test-infra/go-validation.yaml
  prow/jobs/test-infra/run-terraform-config.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  templates/data/secret-leaks-log-scanner.yaml
  templates/data/test-infra/run-terraform-config.yaml
  templates/templates/generic.tmpl
Labels: size/L, lgtm

#6946 Add pre-/postsubmit api-gateway integration tests (build job guarded)
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/scripts/cluster-integration/helpers/integration-tests.sh
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  templates/data/api-gateway-validation.yaml
Labels: size/L, lgtm

#6974 Always run istio test and prevent linting timeout
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/jobs/istio/istio-validation.yaml
  templates/data/api-gateway-validation.yaml
  templates/data/istio-validation.yaml
Labels: size/XS, lgtm

#6733 Pass Docker tags as build-args to dockerfile
  development/gcbuild/main.go
  development/image-builder/README.md
  development/image-builder/config.go
  development/image-builder/config_test.go
  development/image-builder/main.go
  development/image-builder/main_test.go
  development/pkg/sets/tags.go
  development/pkg/tags/tag.go
  development/pkg/tags/tag_test.go
  development/pkg/tags/tags.go
  development/pkg/tags/tags_test.go
Labels: size/L, lgtm

#6975 Presubmit job building module image
  prow/jobs/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/M, lgtm

#6910 Added troubleshooting logs to eventing prow jobs
  prow/scripts/cluster-integration/helpers/eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
  prow/scripts/cluster-integration/kyma-integration-gardener-subscription-upgrade.sh
Labels: size/L, lgtm

#6976 tekton dashboard: restrict access to default namespace
  tekton/deployments/dashboard_release.yaml
Labels: size/XS, lgtm, area/prow

#6961 add golang1.20.1-alpine3.17
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6982 Use prod images
  configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
  prow/jobs/test-infra/run-terraform-config.yaml
  templates/data/test-infra/run-terraform-config.yaml
Labels: size/M, lgtm

#6984 fixup sinify prod secret volume
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#6985 Adjust kyma-btp-manager-bot-github-token secret for untrusted
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Labels: size/M, lgtm

#6981 Run workflow on finished prowjob events.
  development/gcp/workflows/secrets-leak-detector.yaml
Labels: size/L, lgtm

#6989 Add azure token to trusted workload
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
Labels: size/S, lgtm

#6988 Set specific Gitleaks version
  prow/jobs/test-infra/presubmit-scanner.yaml
  templates/data/presubmit_scanner_data.yaml
Labels: size/L, lgtm

#6980 warden-integration-tests: add log fetching
  prow/jobs/kyma-project/warden/integration-test.yaml
Labels: size/XS, lgtm

#6990 Fixed tfcmt flags, again.
  prow/jobs/test-infra/run-terraform-config.yaml
  templates/data/test-infra/run-terraform-config.yaml
Labels: size/XS, lgtm

#6987 Run postsubmit builds on main branch only.
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/terraform-executor.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/terraform-executor.yaml
Labels: size/M, lgtm, kind/bug

#6992 Add Istio 1.17.0 to image syncer
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#6986 Remove Telemetry Operator prow jobs
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/kyma/components/telemetry-operator/telemetry-operator-generic.yaml
  prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
  prow/scripts/cluster-integration/kyma-integration-k3d.sh
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/L, lgtm

#6960 Prowjobs building rotateserviceaccount image and deploying to prod.
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: size/L, lgtm

#6998 Add Signify secret presets to the post telemetry build job
  prow/jobs/kyma/components/telemetry-operator/telemetry-manager-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/XS, lgtm

#6959 RotateServiceAccount documentation update.
  development/secrets-rotator/cloud-run/rotate-service-account/README.md
  development/secrets-rotator/terraform/placeholder_for_tf_files
Labels: size/S, lgtm

#7000 Use tide squash for telemetry-manager repository
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#7003 Update `runIfChanged` for eventing `pre-main-kyma-gardener-gcp-subscription-upgrade` job
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, lgtm

#7004 Trigger linter and unit test job when go.mod or go.sum changed
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  templates/data/go-toolkit-validation.yaml
Labels: size/XS, lgtm

#6977 Refactored rotateserviceaccount cloud function to run as cloud run
  .github/dependabot.yml
  development/secrets-rotator/cloud-run/rotate-service-account/Dockerfile
  development/secrets-rotator/cloud-run/rotate-service-account/rotateserviceaccount.go
  templates/data/test-infra/dependabot-config-data.yaml
Labels: size/L, lgtm

#7005 Fixup formatting errors in how-to guides
  docs/how-to/how-to-add-custom-secret.md
  docs/how-to/how-to_use_tekton-pipelines-in-prow.md
  docs/index.md
Labels: size/S, lgtm

#6921 Add custom detection rule to detect Bearer token leaks.
  development/gcp/cloud-run/scan-logs-for-secrets/Dockerfile
  development/gcp/cloud-run/scan-logs-for-secrets/gitleaks.toml
  development/gcp/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
Labels: size/XXL, lgtm

#7016 add label for telemetry module
  prow/labels.yaml
Labels: size/S, lgtm

#7001 Use gopher group in CODEOWNERS instead of enumerating its members
  CODEOWNERS
Labels: size/S, lgtm

#7018 Cleanup telemetry manager jobs
  CODEOWNERS
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/XS, lgtm

#7024 update alpine to 3.17.2
  development/image-syncer/external-images.yaml
Labels: size/XS, lgtm

#7025 remove `allow_cancellations` field from prow config.yaml
  development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/staging/config.yaml
  templates/templates/prow-config.yaml
Labels: size/XS, lgtm

#7022 Fix pull-telemetry-manager-build job
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/S, lgtm

#7015 Added prod signify secret for postsubmit builds.
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: size/S, lgtm

#7036 Increase cpu request for lint jobs
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/jobs/istio/istio-validation.yaml
  templates/data/api-gateway-validation.yaml
  templates/data/istio-validation.yaml
Labels: size/XS, lgtm

#7037 Revert nodejs18 build jobs
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/M, lgtm

#6955 Add Telemetry Manager governance job
  prow/jobs/governance.yaml
  templates/data/governance-data.yaml
Labels: size/M, lgtm

#7038 Added new labels for automation purposes.
  prow/labels.yaml
Labels: size/S, lgtm

#7019 Cleanup of code owners
  CODEOWNERS
Labels: size/XS, lgtm

#7013 Fix tf apply errors
  configs/terraform/core/apis.tf
  configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-detector.tf
  configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
  development/gcp/workflows/secrets-leak-detector.yaml
Labels: size/L, lgtm, add-or-update

#7023 Extending Build Args Through Configuration
  development/image-builder/README.md
  development/image-builder/main.go
  development/image-builder/main_test.go
Labels: size/M, lgtm

#7051 Bump Mend agent
  prow/images/whitesource-scanner/Dockerfile
Labels: size/S, lgtm

#7053 Bump Mend image
  prow/jobs/scans/whitesource-periodics.yaml
  templates/config.yaml
Labels: size/M, lgtm

#7054 Bump Mend base image
  prow/images/whitesource-scanner/Dockerfile
Labels: size/XS, lgtm

#7046 Add dummy secret for control-plane-gke-integration pipeline required for provisioner
  prow/scripts/cluster-integration/control-plane-gke-integration.sh
Labels: size/XS, lgtm

#7056 Bump imagebuilder image
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/btp-manager/btp-manager-build.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-build.yaml
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/istio/istio-operator-build.yaml
  prow/jobs/kyma-project/warden/warden.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  prow/jobs/slack-bot/slack-bot-build.yaml
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  prow/jobs/test-infra/terraform-executor.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/generic_module_data.yaml
  templates/data/runtime-watcher-data.yaml
Labels: size/L, lgtm

#7058 Made eventing v1alpha2 pre-main jobs required
  prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: area/eventing, size/XS, lgtm

#7045 Build jobs for nodejs runtimes from common folder
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  templates/data/generic_component_data.yaml
Labels: size/L, lgtm

#6929 Use generic Dockerfile for KEB jobs
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/control-plane-build.yaml
Labels: size/M, lgtm

#7014 Grouped secrets leak detector prowjobs.
  prow/jobs/test-infra/hide-terraform-comments.yaml
  prow/jobs/test-infra/run-terraform-config.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/hide-terraform-comments.yaml
  templates/data/test-infra/run-terraform-config.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
Labels: size/L, lgtm

#7067 Missing Env File Panic
  development/image-builder/main.go
Labels: size/XS, lgtm, add-or-update

#7066 Github.com and Azure DevOps pipeline integration
  docs/how-to/ado/README.md
  docs/how-to/ado/how-to_integrate-githubcom-azurepipeline.md
  docs/how-to/ado/images/check-branch.png
  docs/how-to/ado/images/clone-repo.png
  docs/how-to/ado/images/create-repo.png
  docs/how-to/ado/images/git-clone-repo.png
  docs/how-to/ado/images/git-clone.png
  docs/how-to/ado/images/incomindwebhook-data.png
  docs/how-to/ado/images/incomingwebhook.png
  docs/how-to/ado/images/new-file.png
  docs/how-to/ado/images/new-pipeline.png
  docs/how-to/ado/images/new-service-connection.png
  docs/how-to/ado/images/open-in-ide.png
  docs/how-to/ado/images/pat-recommended-scopes.png
  docs/how-to/ado/images/pipeline-gitrepository.png
  docs/how-to/ado/images/pipeline-review.png
  docs/how-to/ado/images/pipeline-save.png
  docs/how-to/ado/images/pipeline-saved.png
  docs/how-to/ado/images/pipeline-source.png
  docs/how-to/ado/images/pipeline.png
  docs/how-to/ado/images/project-settings.png
  docs/how-to/ado/images/push-changes.png
  docs/how-to/ado/images/repo-hook-add.png
  docs/how-to/ado/images/repo-hook-new01.png
  docs/how-to/ado/images/repo-hook-new02.png
  docs/how-to/ado/images/repo-hook-new03.png
  docs/how-to/ado/images/repo-hook-ping.png
  docs/how-to/ado/images/repo-hook.png
  docs/how-to/ado/images/repo-location.png
  docs/how-to/ado/images/repo-settings.png
  docs/how-to/ado/images/secret-parameters.png
  docs/how-to/ado/images/service-connections.png
  docs/how-to/ado/images/start-create-repo.png
  docs/how-to/ado/images/test-ado-closed.png
  docs/how-to/ado/images/test-ado-opened.png
  docs/how-to/ado/images/test-pullrequest-ado.png
  docs/how-to/ado/images/test-pullrequest.png
  docs/how-to/ado/images/test-pullrequestresult.png
  docs/index.md
Labels: size/L, lgtm

#7071 Add azure-devops-token mapping in prow config
  prow/config.yaml
  templates/templates/prow-config.yaml
Labels: size/S, lgtm

#7041 Api-gateway integration tests from own repo
  prow/jobs/api-gateway/api-gateway-validation.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  templates/data/api-gateway-validation.yaml
Labels: size/M, lgtm, add-or-update

#7077 Bump image builder
  prow/jobs/api-gateway/api-gateway-build.yaml
  prow/jobs/api-gateway/api-gateway-release.yaml
  prow/jobs/btp-manager/btp-manager-build.yaml
  prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
  prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
  prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
  prow/jobs/control-plane/components/schema-migrator/schema-migrator-build.yaml
  prow/jobs/incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/incubator/compass/components/director/director-generic.yaml
  prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/incubator/reconciler/reconciler.yaml
  prow/jobs/istio/istio-operator-build.yaml
  prow/jobs/kyma-project/warden/warden.yaml
  prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
  prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
  prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
  prow/jobs/kyma/components/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
  prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
  prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
  prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
  prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
  prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
  prow/jobs/kyma/tests/serverless-bench/serverless-bench-generic.yaml
  prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
  prow/jobs/kyma/tools/gitserver/gitserver-generic.yaml
  prow/jobs/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/module-manager/module-manager.yaml
  prow/jobs/modules/external/keda-manager.yaml
  prow/jobs/runtime-watcher/runtime-watcher.yaml
  prow/jobs/slack-bot/slack-bot-build.yaml
  prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
  prow/jobs/test-infra/buildpack.yaml
  prow/jobs/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/test-infra/secrets-rotator.yaml
  prow/jobs/test-infra/terraform-executor.yaml
  prow/jobs/third-party-images/third-party-images.yaml
  templates/config.yaml
  templates/data/buildpack-data.yaml
  templates/data/control-plane-build.yaml
  templates/data/generic_module_data.yaml
  templates/data/runtime-watcher-data.yaml
Labels: size/L, lgtm

#7032 Defined builds of images for service account keys cleaner
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: size/L, lgtm, add-or-update

#7020 Add prow jobs for new repository directory-size-exporter
  CODEOWNERS
  development/tools/jobs/kyma/kyma_integration_test.go
  prow/config.yaml
  prow/jobs/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/governance.yaml
  prow/jobs/kyma/components/kyma-components-static-checks.yaml
  prow/jobs/scans/whitesource-periodics.yaml
  prow/jobs/test-infra/checkconfig.yaml
  prow/jobs/test-infra/pjconfigtests.yaml
  prow/jobs/test-infra/pjtester.yaml
  prow/jobs/test-infra/presubmit-scanner.yaml
  templates/config.yaml
  templates/data/generic_component_data.yaml
  templates/data/go-toolkit-validation.yaml
  templates/data/governance-data.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/prow-config.yaml
Labels: size/L, lgtm, add-or-update

#7084 replace local signify-secret config to global kaniko_buildpack
  prow/jobs/template-operator/template-operator.yaml
  templates/data/template-operator-data.yaml
Labels: size/M, lgtm

#7087 Updated run if changed to not build images on documentation changes.
  prow/jobs/test-infra/secrets-rotator.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: size/S, lgtm, kind/bug

#7083 Fix compass benchmark job
  prow/scripts/cluster-integration/compass-gke-benchmark.sh
Labels: size/XS, lgtm
