Repository kyma-project/test-infra, pull requests merged in 2024-03, with the labels that each got.

#9981 Update Dockerfile for gingo image
  prow/images/ginkgo/Dockerfile
Labels: size/XS, lgtm, cla: yes

#9971 remove kubeconfig-service job
  prow/jobs/kyma-project/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
  prow/jobs/kyma-project/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
  templates/data/control-plane-build.yaml
  templates/data/generic_component_control_plane_data.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#9973 Documentation update
  README.md
  cmd/cloud-run/gardener-sa-rotate/README.md
  cmd/cloud-run/rotate-service-account/README.md
  cmd/cloud-run/service-account-keys-cleaner/README.md
  cmd/external-plugins/automated-approver/README.md
  cmd/external-plugins/automated-approver/assets/automated-approver.drawio
  cmd/external-plugins/automated-approver/assets/automated-approver.svg
  cmd/gardener-rotate/README.md
  cmd/image-detector/README.md
  cmd/image-syncer/README.md
  docs/documentation_guidelines.md
Labels: area/documentation, size/L, lgtm, kind/chore, cla: yes

#9972 Add serverless Pyton 3.12 build jobs
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/L, lgtm, kind/feature, add-or-update, cla: yes

#9965 Setup github variables, add terraform planner servcie account
  .github/workflows/post-apply-prod-terraform.yaml
  configs/terraform/environments/prod/gcp-workfload-identity-federation-variables.tf
  configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
  configs/terraform/environments/prod/github-com.tf
  configs/terraform/environments/prod/terraform-service-accounts-variables.tf
  configs/terraform/environments/prod/terraform-service-accounts.tf
Labels: size/L, lgtm, kind/feature, area/automation, destroy, cla: yes

#10003 Fix terraform planner workload role
  .github/workflows/pull-plan-prod-terraform.yaml
  configs/terraform/environments/prod/terraform-service-accounts.tf
Labels: size/XS, lgtm, kind/bug, area/automation, cla: yes

#9974 Remove application-connector module build jobs
  prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/L, add-or-update, cla: yes

#10005 Changes postsubmits to run on main
  prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-release.yaml
Labels: size/XS, cla: yes

#9975 Serverless pyhton312 release build
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/L, lgtm, kind/feature, add-or-update, cla: yes

#9989 serverless: remove python39-classic jobs
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/L, lgtm, kind/cleanup, add-or-update, cla: yes

#10006 Disable branch protection for tech user branches in KEB and BTP manager
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/chore, cla: yes

#10008 Removal od Deprecated Schema Migrator Job
  prow/jobs/kyma-incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
Labels: size/XS, lgtm, cla: yes

#9970 Image builder GitHub workflow integration design proposal.
  cmd/image-builder/documentation_assets/image-builder-activity-diagram.png
  cmd/image-builder/documentation_assets/image-builder-block-diagram.png
  cmd/image-builder/github-workflow-integration.md
Labels: size/L, lgtm, cla: yes

#10018 Increase memory request, CM build job is OOMK
  prow/jobs/kyma-project/compass-manager/build.yaml
Labels: area/ci, size/XS, lgtm, cla: yes

#10017 add KMC build jobs for new repository and removed non-relevant prow jobs
  CODEOWNERS
  prow/config.yaml
  prow/jobs/kyma-project/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  prow/jobs/kyma-project/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
  templates/data/control-plane-build.yaml
  templates/data/generic_component_control_plane_data.yaml
Labels: size/L, lgtm, cla: yes

#10026 autobump image-builder images in test-infra
  configs/autobump-config/test-infra-autobump-config.yaml
Labels: size/S, lgtm, cla: yes

#9967 Add watcher-metrics as required check for runtime watcher
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10011 serverless: Simplify build context
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/S, lgtm, kind/chore, cla: yes

#10010 serverless: Add nodejs 20 images build jobs
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/L, lgtm, kind/feature, cla: yes

#10051 feat: add feature branch for busola builds
  prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
  prow/jobs/kyma-project/busola/busola-web/busola-web.yaml
  prow/jobs/kyma-project/busola/busola.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, cla: yes

#10037 Switch to build in ADO
  prow/jobs/kyma-project/test-infra/ado-validation.yaml
  prow/jobs/kyma-project/test-infra/images.yaml
  prow/jobs/kyma-project/test-infra/kyma-bot.yaml
  prow/jobs/kyma-project/test-infra/secret-leaks-log-scanner.yaml
  prow/jobs/kyma-project/test-infra/secrets-rotator.yaml
  templates/data/test-infra/kyma-bot-data.yaml
  templates/data/test-infra/secret-leaks-log-scanner.yaml
  templates/data/test-infra/secrets-rotator.yaml
Labels: size/L, lgtm, cla: yes

#10062 Update image versions in all .tf files
  configs/autobump-config/test-infra-autobump-config.yaml
Labels: size/M, lgtm, cla: yes

#10064 Clarify process flow
  cmd/image-builder/github-workflow-integration.md
Labels: size/XS, lgtm, cla: yes

#10007 Update terraform planner role to roles/viewer
  .github/workflows/pull-plan-prod-terraform.yaml
  configs/terraform/environments/prod/terraform-service-accounts.tf
Labels: size/M, lgtm, kind/bug, area/automation, cla: yes

#10063 Add HSTS related response header.
  cmd/dashboard-token-proxy/main.go
Labels: size/XS, lgtm, cla: yes

#10029 chore: remove pull-eventing-auth-manager-integration-test
  prow/jobs/kyma-project/eventing-auth-manager/eam-integration-test.yaml
Labels: size/M, lgtm, kind/cleanup, add-or-update, cla: yes

#10077 Increase memory for CM post-build-job
  prow/jobs/kyma-project/compass-manager/build.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, cla: yes

#10020 Switch jobs for observability team to use ADO
  prow/jobs/kyma-project/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-generic.yaml
  templates/data/directory-size-exporter-data.yaml
  templates/data/telemetry-manager-data.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10093 Unordered lists are appropriate for items that have no sequential order
  docs/documentation_guidelines.md
Labels: size/S, lgtm, cla: yes

#10097 Change compass ord-service maven image
  prow/jobs/kyma-incubator/ord-service/components/ord-service/ord-service-generic.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10016 Remove application-connector-manager verify job
  prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
  templates/data/generic_module_data.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#10098 Make job pre-main-provisioner-e2e-tests optional
  prow/jobs/kyma-project/control-plane/components/provisioner/provisioner-integration-test.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10096 Use planner token
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: size/XS, lgtm, kind/bug, add-or-update, area/automation, cla: yes

#10102 Use gitleaks action
  .github/dependabot.yml
  .github/workflows/gitleaks.yml
Labels: size/S, lgtm, kind/feature, add-or-update, area/automation, cla: yes

#10113 Add markdown-link-check as required check for lifecycle manager
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10116 feat: Make `Diff manifests` job a required check for lifecycle manager
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10034 Removes run_if_changed for presubmits
  prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-build.yaml
Labels: size/XS, lgtm, cla: yes

#10114 Add configuration to access gitleaks secrets from test-infra
  configs/terraform/environments/prod/gitleaks-variables.tf
  configs/terraform/environments/prod/gitleaks.tf
  configs/terraform/modules/gcp-workload-identity-federation/outputs.tf
Labels: area/security, size/M, lgtm, kind/feature, add-or-update, cla: yes

#10130 Add repository id to gitleaks principal member
  configs/terraform/environments/prod/gitleaks-variables.tf
  configs/terraform/environments/prod/gitleaks.tf
Labels: size/S, lgtm, kind/bug, add-or-update, area/automation, cla: yes

#10131 Use proper principal binding for gitleaks
  configs/terraform/environments/prod/gitleaks.tf
Labels: size/XS, lgtm, kind/bug, add-or-update, area/automation, cla: yes

#10115 Use created variables in workflow
  .github/workflows/gitleaks.yml
Labels: area/security, size/S, lgtm, kind/feature, add-or-update, cla: yes

#10132 Fix permissions for gitleaks
  .github/workflows/gitleaks.yml
Labels: area/security, size/XS, lgtm, kind/bug, add-or-update, cla: yes

#10138 Update external-images.yaml
  cmd/image-syncer/external-images.yaml
Labels: size/S, lgtm, add-or-update, cla: yes

#10136 Bump Keda to 2.13.1
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10155 chore: added release build job for KMC
  prow/jobs/kyma-project/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#10056 Remove Nodejs16 image
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/L, lgtm, add-or-update, kind/chore, cla: yes

#10175 Add new prow job for self-monitor image build
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
  templates/data/third-party-images-data.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10194 chore: Add New Jobs as Required
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10198 Skip unknown contexts
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10193 Add subaccount-sync jobs
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/L, lgtm, area/control-plane, add-or-update, cla: yes

#10203 RUn gitleaks as pull_request_target
  .ci-config.json
  .github/workflows/pull-gitleaks.yml
Labels: size/S, lgtm, kind/bug, add-or-update, area/automation, cla: yes

#10205 Add required status check for BTP Manager
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10204 Fixes presubmits trigger
  prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-build.yaml
  prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-release.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10124 Add GCP secret-manager documentation
  docs/how-to/how-to-add-custom-secret.md
  docs/how-to/how-to-name-secret.md
Labels: size/S, lgtm, cla: yes

#10227 Fix context for release job
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/serverless, size/XS, lgtm, kind/bug, add-or-update, cla: yes

#10225 Switch gitleaks workflow to binary instead of action
  .ci-config.json
  .github/workflows/pull-gitleaks.yml
  configs/terraform/environments/prod/gitleaks-variables.tf
Labels: size/M, lgtm, kind/bug, add-or-update, area/automation, cla: yes
