Repository kyma-project/test-infra, pull requests merged in 2024-08, with the labels that each got.

#11538 Add needed properties for Python unified agent config
  images/unified-agent/python/python-wss-unified-agent.config
Labels: size/S, lgtm, cla: yes

#11542 feat: add kyma-dashboard workflows to tide
  prow/config.yaml
Labels: area/ci, size/S, lgtm, kind/feature, add-or-update, cla: yes

#11545 chore: add new python image in external images
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11546 Add service accounts to retrieve secrets in pipelines
  configs/terraform/environments/prod/service_accounts.tf
Labels: size/S, lgtm, add-or-update, cla: yes

#11562 Upgrade UNIFIED_AGENT_VERSION to the newest v24.7.1 version
  images/unified-agent/Dockerfile
  images/unified-agent/go/go-mod-wss-unified-agent.config
  images/unified-agent/nodejs/javascript-wss-unified-agent.config
  images/unified-agent/python/python-wss-unified-agent.config
  images/unified-agent/start-wssagent.sh
Labels: size/S, lgtm, cla: yes

#11586 Revert "feat: add kyma-dashboard workflows to tide"
  prow/config.yaml
Labels: area/ci, size/S, lgtm, kind/feature, add-or-update, cla: yes

#11595 feat: add kyma-dashboard workflows to tide
  prow/config.yaml
Labels: area/ci, size/S, lgtm, kind/feature, add-or-update, cla: yes

#11597 Fix required status checks for Busola
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11596 Remove KEB pull-build jobs
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/XL, lgtm, add-or-update, cla: yes

#11609 fix: kyma-dashboard tide
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, add-or-update, cla: yes

#11606 Remove remaining ACM stuff
  prow/config.yaml
  prow/jobs/kyma-project/application-connector-manager/components/build-image-agent.yaml
  prow/jobs/kyma-project/application-connector-manager/components/build-image-gateway.yaml
  prow/jobs/kyma-project/application-connector-manager/components/build-image-validator.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-connectivity-validator/build-image-validator-tests.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-gateway/build-image-gateway-tests.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/compass-runtime-agent/build-image-agent-tests.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/mock-app-build.yaml
  prow/jobs/kyma-project/test-infra/pjconfigtests.yaml
  prow/jobs/kyma-project/test-infra/pjtester.yaml
  templates/config.yaml
Labels: size/XL, lgtm, add-or-update, cla: yes

#11610 Update KEB branch protection rules
  prow/config.yaml
Labels: size/S, lgtm, add-or-update, cla: yes

#11611 Add golang 1.22.6 image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11612 Add golang 1.22.6-alpine image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11613 Remove KEB post-build jobs
  prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
  templates/data/kyma-environment-broker-build.yaml
Labels: size/XL, lgtm, add-or-update, cla: yes

#11631 chore: Remove migrated prow jobs for telemery-manager and directory-size-exporter
  prow/jobs/kyma-project/directory-size-exporter/directory-size-exporter-generic.yaml
  prow/jobs/kyma-project/telemetry-manager/telemetry-manager-generic.yaml
Labels: area/ci, size/L, lgtm, kind/cleanup, add-or-update, cla: yes

#11630 chore: Set telemetry repositories to unmanaged
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11653 Add nginx 1.27-alpine image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11655 Change nginx 1.27-alpine to nginx-unprivileged
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11654 Add golang 1.23.0-alpine3.20 image to image syncer
  cmd/image-syncer/external-images.yaml
Labels: lgtm, add-or-update, cla: yes

#11656 Test what version of reusable workflow a run will pick up.
  .github/workflows/pull-image-builder-test.yml
Labels: size/S, lgtm, add-or-update, cla: yes

#11658 Remove not needed anymore Prow jobs
  prow/jobs/kyma-project/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
  prow/jobs/kyma-project/kyma/common/common.yaml
  templates/data/kyma-tools-data.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#11659 Update version of buildkit and python for image syncer
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11638 chore: cloud-manager-tests unmanaged
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11662 chore: Run template-op-main-build only on main
  prow/jobs/kyma-project/template-operator/template-operator.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11670 update external image fluentbit to 3.1.6
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, area/telemetry, kind/chore, cla: yes

#11687 Add node 22.3.0 image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11697 Remove BTP Manager jobs
  prow/jobs/kyma-project/btp-manager/btp-manager-build.yaml
  templates/data/btp-manager-build.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#11696 Add golangci/golangci-lint to external-images.yaml
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11698 BTP Manager required status check
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11704 Delete ci-prow-branchprotector Prow job
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/jobs/kyma-project/test-infra/branchprotector.yaml
Labels: size/M, lgtm, destroy, cla: yes

#11707 cloud-manager-tests squash merge method
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11709 Remove unused workflow
  .github/workflows/call-reusable-autobumper.yml
Labels: size/S, lgtm, add-or-update, cla: yes

#11713 Add github.tools.sap to the trusted oidc issuers
  cmd/cloud-run/rotate-service-account/rotateserviceaccount.go
  cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
  cmd/tools/usersmapchecker/main.go
  pkg/gcp/http/http.go
  pkg/oidc/oidc.go
  pkg/tools/gcscleaner/cleaner.go
Labels: size/M, lgtm, cla: yes

#11719 Update golangci-lint to v1.60.3 in the image syncer config
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11720 Show only new issues from golangci-lint
  .golangci.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11725 feat: change nginx image
  cmd/image-syncer/external-images.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, add-or-update, cla: yes

#11726 feat: change nginx image
  cmd/image-syncer/external-images.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, add-or-update, cla: yes

#11714 Fix review comments from PR 11713
  cmd/cloud-run/rotate-service-account/rotateserviceaccount.go
  cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
  cmd/tools/usersmapchecker/main.go
  pkg/gcp/http/http.go
  pkg/oidc/oidc.go
  pkg/tools/gcscleaner/cleaner.go
Labels: size/M, lgtm, cla: yes

#11739 Revert "Show only new issues (#11720)"
  .golangci.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11757 feat: remove busola and kyma-dashboard prow builds
  prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
  prow/jobs/kyma-project/busola/busola-web/busola-web.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-dev.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-prod.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-stage.yaml
Labels: area/ci, size/XL, lgtm, kind/feature, add-or-update, cla: yes
