Repository kyma-project/test-infra, pull requests merged in 2024-10, with the labels that each got.

#12025 Set jobtype for schedule event
  cmd/image-builder/main.go
  pkg/azuredevops/pipelines/templatesParams.go
Labels: size/S, lgtm, cla: yes

#12023 Simplify and consolidate image building - Adapt buildx to GH workflow
  .github/workflows/pull-ex-buildx-images.yml
Labels: size/L, lgtm, add-or-update, cla: yes

#12029 Update pull-ex-buildx-images.yml
  .github/workflows/pull-ex-buildx-images.yml
Labels: size/S, lgtm, add-or-update, cla: yes

#12019 Migrate linters from prow to github actions
  .github/dependabot.yml
  .github/workflows/pull-go-lint.yaml
  .github/workflows/pull-unit-test-go.yaml
  .github/workflows/pull-validate-dockerfiles.yaml
  .github/workflows/pull-validate-scripts.yaml
  cmd/jobguard/run.sh
  images/alpine/hadolint/Dockerfile
  images/alpine/shellcheck/Dockerfile
  images/e2e-dind-k3d/init.sh
  images/e2e-dind-nodejs/init.sh
  images/unified-agent/start-wssagent.sh
  prow/images/golangci-lint/Dockerfile
  prow/images/golangci-lint/Makefile
  prow/images/golangci-lint/README.md
  prow/images/golangci-lint/golangci-lint.sh
  prow/jobs/kyma-project/test-infra/buildpack.yaml
  prow/jobs/kyma-project/test-infra/go-validation.yaml
  prow/jobs/kyma-project/test-infra/validation.yaml
  templates/config.yaml
  templates/data/test-infra/golang-tests.yaml
  templates/data/test-infra/validation-data.yaml
Labels: size/XL, lgtm, add-or-update, cla: yes

#12033 Fix digest format for Signify
  pkg/sign/notary.go
  pkg/sign/notary_mocks.go
  pkg/sign/notary_test.go
Labels: size/M, lgtm, cla: yes

#12037 clean telemetry-manager repos
  prow/config.yaml
  prow/jobs/kyma-project/test-infra/pjconfigtests.yaml
  prow/jobs/kyma-project/test-infra/pjtester.yaml
  templates/config.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#12024 chore: Remove tide and status check config from jellyfish components
  prow/config.yaml
Labels: area/quality, size/M, lgtm, add-or-update, cla: yes

#12040 Revert image digest to manifest digest, Switch to use digest.Hex inst…
  pkg/sign/notary.go
  pkg/sign/notary_test.go
Labels: size/M, lgtm, cla: yes

#12028 Update image-builder README.md for schedule event and signing with Signify
  cmd/image-builder/README.md
Labels: size/XS, lgtm, cla: yes

#11915 Adjust terraform to store cleanup policies
  configs/terraform/environments/prod/dns-collector.tf
  configs/terraform/environments/prod/image-builder-variables.tf
  configs/terraform/environments/prod/image-builder.tf
  configs/terraform/modules/service-account-keys-cleaner/main.tf
Labels: size/M, lgtm, add-or-update, cla: yes

#12045 Corrected version of Buildx images, cleanup
  .github/workflows/pull-ex-buildx-images.yml
  images/Makefile
  images/alpine/git/Dockerfile
  images/alpine/git/gke-aws-auth/Dockerfile
  images/build-images.sh
  images/buildpack/go/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-k3d/README.md
  images/e2e-dind-k3d/init.sh
  images/e2e-dind-k3d/test.sh
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-dind-nodejs/init.sh
  images/e2e-dind-nodejs/test.sh
  images/unified-agent/Dockerfile
  images/unified-agent/go/Dockerfile
  images/unified-agent/nodejs/Dockerfile
  images/unified-agent/python/Dockerfile
  prow/jobs/kyma-project/test-infra/images.yaml
Labels: size/XL, lgtm, add-or-update, cla: yes

#12058 chore: exclude cloud-manager from tide
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12059 Update and rename pull-ex-buildx-images.yml to buildx-images.yml
  .github/workflows/buildx-images.yml
Labels: size/M, lgtm, add-or-update, cla: yes

#12055 cleanup of ko
  .ko.yaml
  .koapps.yaml
  cmd/image-builder/images/buildkit/Dockerfile
  cmd/image-builder/images/kaniko/Dockerfile
  configs/autobump-config/test-infra-autobump-config.yaml
  configs/terraform/modules/cors-proxy/cors-proxy.tf
  configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
  configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
  images/buildpack/go/test.sh
  opa/gatekeeper/constraint-templates/test-data/trustedSAUsage_test-data.jsonc
  pkg/securityconfig/securityconfig_test.go
  prow/cluster/components/automated-approver_external-plugin.yaml
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSapTokenTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/pjtesterSecretsTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
  prow/jobs/kyma-project/test-infra/image-syncer.yaml
  prow/jobs/kyma-project/test-infra/ko-build.yaml
  prow/jobs/kyma-project/test-infra/kyma-bot.yaml
  prow/jobs/kyma-project/test-infra/periodics.yaml
  prow/jobs/kyma-project/test-infra/pjtester.yaml
  prow/jobs/kyma-project/test-infra/prow-periodics.yaml
  prow/jobs/kyma-project/test-infra/validation.yaml
  sec-scanners-config.yaml
  templates/config.yaml
  templates/data/test-infra/image-syncer-data.yaml
  templates/data/test-infra/pjtester-data.yaml
Labels: size/L, lgtm, destroy, cla: yes

#12063 Update test-infra-autobump-config.yaml
  configs/autobump-config/test-infra-autobump-config.yaml
Labels: size/S, lgtm, add-or-update, cla: yes

#12066 Fix build-pack to use correct tag
  prow/jobs/kyma-project/test-infra/validation.yaml
  templates/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12070 Remove not used pjobs and tools.
  cmd/tools/pjtester/Dockerfile
  cmd/tools/pjtester/README.md
  cmd/tools/pjtester/main.go
  cmd/tools/rendertemplates/README.md
  cmd/tools/rendertemplates/main.go
  go.mod
  go.sum
  pkg/prow/pjconfigtests/pjconfigtests_suite_test.go
  pkg/prow/pjconfigtests/pjconfigtests_test.go
  pkg/prow/pjconfigtests/validators.go
  prow/jobs/kyma-project/test-infra/buildpack.yaml
  prow/jobs/kyma-project/test-infra/pjconfigtests.yaml
  prow/jobs/kyma-project/test-infra/pjtester.yaml
  prow/jobs/kyma-project/test-infra/validation.yaml
  templates/README.md
  templates/config.yaml
  templates/data/test-infra/image-syncer-data.yaml
  templates/data/test-infra/pjconfigtests.yaml
  templates/data/test-infra/pjtester-data.yaml
  templates/data/test-infra/validation-data.yaml
  templates/templates/generic.tmpl
Labels: size/XXL, lgtm, kind/cleanup, add-or-update, cla: yes

#12071 Use static version of markdown-links-check github actions
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12065 Migrate cleaners
  configs/terraform/environments/prod/artifact-registry-variables.tf
  configs/terraform/environments/prod/artifact-registry.tf
  configs/terraform/environments/prod/image-builder-variables.tf
  prow/jobs/kyma-project/test-infra/periodics.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#12078 Remove building pjtester. Tool is not used.
  .github/workflows/build-pjtester.yml
Labels: size/M, lgtm, no-changes, cla: yes

#11981 Use pr default tag together with user provided tags
  cmd/image-builder/config.go
  cmd/image-builder/config_test.go
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  configs/kaniko-build-config.yaml
  pkg/tags/options.go
  pkg/tags/options_test.go
  pkg/tags/tag.go
  pkg/tags/tag_test.go
  pkg/tags/tags.go
Labels: size/XL, lgtm, no-changes, cla: yes

#12087 add tide excludes for telemetry-manager repos
  prow/config.yaml
Labels: size/XS, lgtm, no-changes, cla: yes

#12086 Removed parameter to test kaniko from pr.
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: size/M, lgtm, cla: yes, image-builder

#12089 Fix dead links in the documentation
  docs/index.md
  docs/prow/README.md
  docs/prow/prow-jobs-quick-start.md
  images/README.md
Labels: size/M, lgtm, cla: yes

#12069 Support custom tags on pr images in image-builder reusable workflow
  .github/actions/image-builder/action.yml
  .github/workflows/image-builder.yml
  .github/workflows/pull-validate-kaniko-build-config.yml
  configs/image-builder-client-config.yaml
  configs/kaniko-build-config.yaml
Labels: size/M, lgtm, no-changes, cla: yes, image-builder

#12074 Remove gcr-cleaner prow jobs
  prow/jobs/kyma-project/test-infra/gcr-cleaner.yaml
Labels: size/L, lgtm, no-changes, cla: yes

#12095 Fix dead links in the documentation
  docs/prow/manage-component-jobs-with-templates.md
  images/README.md
  images/buildpack/go/test.sh
Labels: size/L, lgtm, cla: yes

#12103 Hello world
  .github/workflows/hello-world.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12111 Add GitHub action md index
  .github/workflows/autobump-docs-index-md.yml
Labels: size/M, cla: yes

#12110 Add schedule to supported signing events in image builder README file
  cmd/image-builder/README.md
Labels: size/XS, lgtm, cla: yes

#12127 Add image autobumper to the github workflows
  .github/workflows/autobump-images.yml
  .github/workflows/reusable-image-autobumper.yml
Labels: size/M, lgtm, no-changes, cla: yes

#12128 Rename autobump token secret for github workflows
  configs/terraform/environments/prod/kyma-bots-secrets-variables.tf
  configs/terraform/environments/prod/kyma-bots-secrets.tf
Labels: size/S, lgtm, add-or-update, cla: yes

#12130 Rename image-autobumper reusable workflow, fix secret reference
  .github/workflows/autobump-images.yml
  .github/workflows/image-autobumper.yml
Labels: size/S, lgtm, add-or-update, cla: yes

#12131 Fix image-autobumper reusable workflow
  .github/workflows/image-autobumper.yml
  prow/jobs/kyma-project/test-infra/prow-periodics.yaml
Labels: size/M, lgtm, no-changes, cla: yes

#12132 Fix the reference to autobump config in steps
  .github/workflows/image-autobumper.yml
Labels: size/XS, lgtm, no-changes, cla: yes

#12138 Adding IaC for submission pipeline.
  configs/terraform/environments/prod/artifact-registry-variables.tf
  configs/terraform/environments/prod/artifact-registry.tf
  configs/terraform/environments/prod/image-builder-variables.tf
  configs/terraform/environments/prod/image-builder.tf
  configs/terraform/environments/prod/modules-submission-variables.tf
  configs/terraform/environments/prod/modules-submission.tf
  configs/terraform/environments/prod/service_accounts.tf
Labels: size/L, lgtm, add-or-update, cla: yes

#12146 Add Istio, APIGateway and networking-dev-tools to tide exclusion
  prow/config.yaml
Labels: size/XS, lgtm, no-changes, cla: yes

#12088 Debug logging for generating tags
  cmd/image-builder/config.go
  cmd/image-builder/images/kaniko/Dockerfile
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  pkg/tags/options.go
  pkg/tags/tags.go
  pkg/tags/tags_test.go
Labels: size/L, lgtm, no-changes, cla: yes, image-builder

#12152 Update GO_VERSION=1.23.2 for unified-agent Dockerfile
  images/unified-agent/go/Dockerfile
Labels: size/XS, lgtm, cla: yes

#12134 Unify autobumpers in test-infra repository
  cmd/image-autobumper/bumper/bumper.go
  cmd/image-autobumper/main.go
  pkg/github/bumper/bumper.go
  pkg/github/bumper/bumper_test.go
Labels: size/XL, lgtm, cla: yes

#12123 Read access token to use it in authentication.
  cmd/image-syncer/image_syncer_suite_test.go
  cmd/image-syncer/main.go
  cmd/image-syncer/main_test.go
  cmd/image-syncer/test-fixtures/keyfile.json
  cmd/image-syncer/util_test.go
  go.mod
  go.sum
Labels: size/L, lgtm, cla: yes

#12142 Removed unused prowjob scenario docs.
  cmd/image-builder/README.md
  cmd/image-builder/README_deprecated.md
  docs/index.md
Labels: size/L, lgtm, cla: yes, image-builder

#12156 Use newest production image syncer.
  .github/workflows/image-syncer.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12159 Bump image autobumper
  .github/workflows/image-autobumper.yml
Labels: size/XS, lgtm, no-changes, cla: yes

#12164 Disable updates for golangci linter actions
  .github/dependabot.yml
Labels: size/XS, lgtm, no-changes, cla: yes

#12162 Use go-git/v5 in bumper instead of calling git binary
  cmd/image-autobumper/Dockerfile
  go.mod
  go.sum
  pkg/github/bumper/bumper.go
  pkg/github/bumper/bumper_test.go
  pkg/github/bumper/utils.go
  pkg/github/bumper/utils_test.go
Labels: size/XL, lgtm, cla: yes

#12168 Bump image autobumper image to the newest version
  .github/workflows/image-autobumper.yml
Labels: size/XS, lgtm, no-changes, cla: yes

#12171 Update image-autobumper to correctly utilize go-git
  pkg/github/bumper/bumper.go
Labels: size/M, lgtm, cla: yes

#12183 Restore k8s based bumper
  cmd/image-autobumper/Dockerfile
  cmd/image-autobumper/main.go
  cmd/image-detector/main.go
  cmd/markdown-index/main.go
  pkg/github/bumper/bumper.go
Labels: size/XL, lgtm, cla: yes

#12188 Remove unused project mentions
  configs/terraform/environments/prod/output.tf
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/secrets-rotator.tf
  configs/terraform/environments/prod/service_accounts.tf
  configs/terraform/environments/prod/terraform-executor.tf
  configs/terraform/environments/prod/variables.tf
  pkg/tools/pjtester/test_artifacts/test-prow-config.yaml
  prow/config.yaml
  prow/jobs/kyma-project/test-infra/periodics.yaml
Labels: size/M, lgtm, cla: yes

#12187 Cleanup image syncer config
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12193 Fix bumpers don't have permisisons to access global git config in container
  .github/workflows/autobump-docs-index-md.yml
  .github/workflows/autobump-security-config.yaml
Labels: size/XS, lgtm, no-changes, cla: yes

#12151 Cleanup of prow images
  .github/dependabot.yml
  .github/workflows/image-builder.yml
  .github/workflows/pull-image-builder-test.yml
  .github/workflows/pull-validate-kaniko-build-config.yml
  cmd/image-builder/README.md
  docs/index.md
  images/ginkgo/Dockerfile
  images/ginkgo/envs
  prow/images/README.md
  prow/images/whitesource-scanner/Dockerfile
  prow/images/whitesource-scanner/Makefile
  prow/images/whitesource-scanner/README.md
  prow/images/whitesource-scanner/go-mod-wss-unified-agent.config
  prow/images/whitesource-scanner/go-wss-unified-agent.config
  prow/images/whitesource-scanner/javascript-wss-unified-agent.config
Labels: size/XL, lgtm, no-changes, cla: yes

#12201 Allow auto approver to approve changes in .yml files changed by kyma-bot
  configs/automated-approver-rules.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12214 Delete docs/prow/k3d-no-ssh.md
  docs/prow/k3d-no-ssh.md
Labels: size/L, lgtm, cla: yes

#12218 Verify oidc token against extended expiration time
  cmd/oidc-token-verifier/main.go
  pkg/oidc/oidc.go
  pkg/oidc/oidc_test.go
Labels: size/L, lgtm, cla: yes

#12205 Add image autobumper documentation
  cmd/image-autobumper/README.md
Labels: size/M, lgtm, cla: yes

#12245 Run expiration check with extended time for all tokens
  cmd/oidc-token-verifier/main.go
  pkg/oidc/oidc.go
  pkg/oidc/oidc_test.go
  pkg/oidc/oidc_unit_test.go
Labels: size/L, lgtm, cla: yes

#12255 Remove not needed anymore sap-kyma-workloads GCP cleaners code
  .github/workflows/build-gcscleaner.yml
  cmd/tools/firewallcleaner/main.go
  cmd/tools/gcscleaner/Dockerfile
  cmd/tools/gcscleaner/main.go
  cmd/tools/gcscleaner/main_test.go
  cmd/tools/prtagbuilder/main.go
  docs/index.md
  pkg/tools/firewallcleaner/automock/compute_api.go
  pkg/tools/firewallcleaner/cleaner.go
  pkg/tools/firewallcleaner/cleaner_test.go
  pkg/tools/firewallcleaner/options.go
  pkg/tools/firewallcleaner/wrappers.go
  pkg/tools/gcscleaner/cleaner.go
  pkg/tools/gcscleaner/cleaner_test.go
  pkg/tools/gcscleaner/export_test.go
  pkg/tools/gcscleaner/storage/automock/bucket_attrs.go
  pkg/tools/gcscleaner/storage/automock/bucket_handle.go
  pkg/tools/gcscleaner/storage/automock/bucket_iterator.go
  pkg/tools/gcscleaner/storage/automock/bucket_object.go
  pkg/tools/gcscleaner/storage/automock/client.go
  pkg/tools/gcscleaner/storage/automock/object_attrs.go
  pkg/tools/gcscleaner/storage/automock/object_handle.go
  pkg/tools/gcscleaner/storage/automock/object_iterator.go
  pkg/tools/gcscleaner/storage/automock/query.go
  pkg/tools/gcscleaner/storage/bucket.go
  pkg/tools/gcscleaner/storage/storage.go
  pkg/tools/prtagbuilder/README.md
  pkg/tools/prtagbuilder/mocks/fakeghclient.go
  pkg/tools/prtagbuilder/prtagbuilder.go
  prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
  prow/scripts/build-generic.sh
  prow/scripts/lib/docker.sh
Labels: size/XXL, lgtm, destroy, cla: yes

#12083 Switch signify secret rotator to alpine base image
  cmd/cloud-run/signifysecretrotator/Dockerfile
Labels: size/XS, lgtm, cla: yes

#12294 Remove image syncer Prow Jobs
  cmd/image-syncer/external-images.yaml
  prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
  prow/jobs/kyma-project/test-infra/image-syncer.yaml
Labels: size/L, lgtm, destroy, cla: yes

#12295 Setup access to audit logs for kyma-project admins
  configs/terraform/environments/prod/iam-variables.tf
  configs/terraform/environments/prod/iam.tf
  configs/terraform/environments/prod/service_accounts.tf
Labels: size/M, lgtm, destroy, cla: yes

#12300 Add required role to see data access logs
  configs/terraform/environments/prod/iam.tf
Labels: size/XS, lgtm, add-or-update, cla: yes

#12075 Enable cleanup policies for kyma-project GCP project
  configs/terraform/environments/prod/artifact-registry-variables.tf
Labels: size/XS, lgtm, add-or-update, cla: yes
