Repository kyma-project/test-infra, pull requests merged in 2024-05, with the labels that each got.

#10577 Add full sha tag for release serverless operator build job
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10598 Update istio-manager experimental image after trigger changed
  prow/jobs/kyma-project/istio/istio-manager.yaml
  templates/data/istio-module-data.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10611 Add `registry-init` image building jobs
  prow/jobs/kyma-project/docker-registry/docker-registry-build-operator.yaml
  prow/jobs/kyma-project/docker-registry/docker-registry-release.yaml
  templates/data/docker-registry.yaml
Labels: area/ci, size/L, lgtm, add-or-update, kind/chore, cla: yes

#10515 Use ADO for Jellyfish Prow Jobs
  prow/jobs/kyma-project/lifecycle-manager/lifecycle-manager.yaml
  prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml
  prow/jobs/kyma-project/template-operator/template-operator.yaml
  templates/data/lifecycle-manager-data.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10612 Deprecate kyma provision k3d command
  prow/scripts/lib/kyma.sh
Labels: size/S, lgtm, area/tooling, kind/cleanup, cla: yes

#10623 Pin SHA of registry image to existing version
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10622 Add Istio 1.21.2 to the registry
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10607 OIDC verifier package
  .gitleaksignore
  gitleaks.toml
  go.mod
  go.sum
  pkg/oidc/mocks/mock_ClaimsInterface.go
  pkg/oidc/mocks/mock_ClaimsReader.go
  pkg/oidc/mocks/mock_ProviderInterface.go
  pkg/oidc/mocks/mock_TokenInterface.go
  pkg/oidc/mocks/mock_TokenProcessorOption.go
  pkg/oidc/mocks/mock_TokenVerifierInterface.go
  pkg/oidc/mocks/mock_Verifier.go
  pkg/oidc/mocks/mock_VerifierConfigOption.go
  pkg/oidc/mocks/mock_VerifierConfigOptions.go
  pkg/oidc/mocks/mock_VerifierProvider.go
  pkg/oidc/mocks/mock_loggerInterface.go
  pkg/oidc/oidc.go
  pkg/oidc/oidc_suite_test.go
  pkg/oidc/oidc_test.go
  pkg/oidc/test-fixtures/oidc-token.jwt
  pkg/oidc/test-fixtures/raw-oidc-token
Labels: size/XXL, lgtm, cla: yes

#10608 Token verifier
  cmd/oidc-token-verifier/main.go
Labels: size/L, lgtm, cla: yes

#10609 Build OIDC verifier
  cmd/oidc-token-verifier/Dockerfile
  prow/jobs/kyma-project/test-infra/oidc-token-verifier.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10442 Change Tide configurations for compass and ord-service
  prow/config.yaml
  prow/plugins.yaml
Labels: size/S, lgtm, area/prow, add-or-update, cla: yes

#10435 Remove test jobs
  prow/jobs/kyma-incubator/compass/compass-gke-benchmark.yaml
  prow/jobs/kyma-incubator/compass/compass-integration-no-dump.yaml
  prow/jobs/kyma-incubator/compass/compass-smoke-test.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10660 Add modulectl repo to prow config
  prow/config.yaml
Labels: size/S, lgtm, add-or-update, cla: yes

#10657 [Compass Manager] Run `post-job` only on main branch
  prow/jobs/kyma-project/compass-manager/build.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, cla: yes

#10466 Allow to use env file in image-builder when buildInADO is true
  cmd/image-builder/README.md
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  pkg/azuredevops/pipelines/templatesParams.go
Labels: size/M, lgtm, cla: yes

#10684 Fix handling prow job pull requests in post submit jobs
  cmd/image-builder/config.go
  cmd/image-builder/config_test.go
Labels: size/M, lgtm, cla: yes

#10690 Use native gitleaks allow mechanism
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
  gitleaks.toml
  pkg/sign/notary_test.go
  prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
Labels: size/S, lgtm, add-or-update, cla: yes

#10692 Add sec-scanners-config to allow list
  gitleaks.toml
Labels: size/XS, lgtm, cla: yes

#10689 Remove not needed Whitesource Prow jobs
  prow/jobs/scans/whitesource-periodics.yaml
  templates/data/whitesource-periodics-data.yaml
  templates/templates/whitesource-periodics.tmpl
Labels: size/L, lgtm, add-or-update, cla: yes

#10693 Remove inrepo config
  cmd/image-detector/README.md
  cmd/image-detector/main.go
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
  prow/image-detector/inrepo-config.yaml
  prow/jobs/kyma-project/test-infra/prow-periodics.yaml
  templates/data/test-infra/image-detector.yaml
  templates/templates/image-detector-inrepo.tmpl
Labels: size/L, lgtm, destroy, cla: yes

#10707 Bump prow to fix autobumper
  pkg/tools/pjtester/test_artifacts/test-prow-config.yaml
  prow/cluster/components/halogen.yaml
  prow/jobs/kyma-project/test-infra/test-infra-trusted-jobs.yaml
  sec-scanners-config.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10654 Add github action to call oci-image-builder
  .github/actions/image-builder/action.yml
  .github/workflows/get-oidc-token-test.yml
  .github/workflows/image-builder.yml
  .github/workflows/pull-image-builder-test.yml
  .github/workflows/reusable-workflow.yml
Labels: size/L, lgtm, add-or-update, cla: yes

#10712 Fix gcsweb version
  prow/cluster/components/gcsweb.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10713 Fix prow components verison
  prow/cluster/components/halogen.yaml
  prow/jobs/kyma-project/test-infra/test-infra-trusted-jobs.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, add-or-update, cla: yes

#10714 Fix prow
  configs/autobump-config/prow-cluster-autobump-config.yaml
Labels: size/S, lgtm, add-or-update, cla: yes

#10724 Remove docker-credential-gcr
  images/e2e-gcloud/Dockerfile
Labels: size/XS, lgtm, cla: yes

#10735 Bump golang, k3d, kind, helm, k8s versions in Dockerfiles
  cmd/oidc-token-verifier/Dockerfile
  images/e2e-dind-k3d/Dockerfile
  images/e2e-dind-nodejs/Dockerfile
  images/e2e-garden/Dockerfile
  images/e2e-gcloud/Dockerfile
Labels: size/M, lgtm, cla: yes

#10738 Cleanup unused or broken gardener related jobs and scripts
  prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
  prow/jobs/kyma-project/kyma/kyma-integration-gardener.yaml
  prow/scripts/cluster-integration/kyma-integration-gardener.sh
  prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
  prow/scripts/lib/gardener/aws.sh
  prow/scripts/lib/gardener/azure.sh
  prow/scripts/lib/gardener/gardener.sh
  prow/scripts/lib/gardener/gcp.sh
  prow/scripts/reconciler/reconciler-component-provision-gardener.sh
  prow/scripts/unstale-gardener-project.sh
  templates/data/incubator-buildpack-data.yaml
  templates/data/kyma-integration-gardener-data.yaml
Labels: size/XXL, lgtm, area/tooling, kind/cleanup, destroy, cla: yes

#10741 Add the `binutils-gold` to the buildpack base
  images/buildpack/Dockerfile
Labels: area/ci, size/XS, lgtm, kind/bug, cla: yes

#10749 Don't manage cli branch protection
  prow/config.yaml
Labels: area/cli, size/M, lgtm, kind/feature, add-or-update, cla: yes

#10752 feat: bump busola resources
  prow/jobs/kyma-project/busola/busola-integration.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-integration.yaml
Labels: area/ci, size/S, lgtm, kind/feature, add-or-update, cla: yes

#10754 Revert "Fix serverless build jobs dockefile path (#10751)"
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#10753 Remove all cli jobs
  prow/jobs/kyma-project/cli/cli-k3d.yaml
  prow/jobs/kyma-project/cli/cli.yaml
  templates/data/cli-data.yaml
Labels: area/cli, size/L, lgtm, kind/cleanup, add-or-update, cla: yes

#10750 Bump gcr-cleaner-cli to 0.12.0
  prow/jobs/kyma-project/test-infra/gcr-cleaner.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10755 feat: bump busola resources
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-integration.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, add-or-update, cla: yes

#10766 feat: bump busola resources
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-integration.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, add-or-update, cla: yes

#10756 Remove prometheus-operator
  prow/cluster/components/monitoring/prometheus_expose.yaml
  prow/cluster/components/monitoring/prometheus_operator_deployment.yaml
  prow/cluster/components/monitoring/prometheus_operator_rbac.yaml
  prow/cluster/components/monitoring/prometheus_rbac.yaml
  prow/cluster/components/monitoring/prow_alertmanager.yaml
  prow/cluster/components/monitoring/prow_monitoring_namespace.yaml
  prow/cluster/components/monitoring/prow_prometheus.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_alertmanagerconfigs.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_probes.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_prometheuses.yaml
  prow/cluster/components/monitoring/prow_prometheus_crd_thanosrulers.yaml
  prow/cluster/components/monitoring/prow_servicemonitors.yaml
  sec-scanners-config.yaml
Labels: size/XXL, lgtm, add-or-update, cla: yes

#10785 Bump alpine & alpine-based golang image
  cmd/image-syncer/external-images.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, kind/chore, cla: yes

#10784 Bump python image version for Slack message sender
  cmd/cloud-run/slack-message-sender/Dockerfile
Labels: size/XS, lgtm, cla: yes

#10788 Fix gitserver build
  prow/jobs/kyma-project/serverless/serverless-gitserver.yaml
  templates/data/serverless.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#10787 Revert "revert the switch of 3party-images to ado (#10540)"
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10789 Bump keda
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, kind/chore, cla: yes

#10791 Bump dependencies of image-builder images
  cmd/image-builder/images/buildkit/Dockerfile
  cmd/image-builder/images/kaniko/Dockerfile
Labels: size/XS, lgtm, cla: yes

#10800 Add buildkit-image-builder to test-infra-autobump-config.yaml
  configs/autobump-config/test-infra-autobump-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10805 Update CODEOWNERS - add Prow team to all Prow Jobs
  CODEOWNERS
Labels: size/L, lgtm, cla: yes

#10807 Change consistentImages to true for buildkit-image-builder
  configs/autobump-config/test-infra-autobump-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10769 Semantic versioning in Compass Manager release images
  prow/jobs/kyma-project/compass-manager/build.yaml
Labels: area/ci, size/M, lgtm, add-or-update, cla: yes

#10794 Semantic versioning in Infrastructure Manager release images
  prow/jobs/kyma-project/infrastructure-manager/infrastructure-manager.yaml
  templates/data/infrastructure-manager-data.yaml
Labels: area/ci, size/M, lgtm, add-or-update, cla: yes

#10808 Revert "Add buildkit-image-builder to test-infra-autobump-config.yaml…
  configs/autobump-config/test-infra-autobump-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10813 Add support for AzureDevOps CI System
  cmd/image-builder/config.go
Labels: size/S, lgtm, cla: yes

#10825 Set api-gateway and istio to unmanaged in prow config
  prow/config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10803 Rollback image for schema migrator validation
  prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, cla: yes

#10831 Add `build-in-ado` to ACM release job
  prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, cla: yes

#10833 Revert image
  prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10835 [ACM] Rollback to changes without `ado`
  prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
Labels: area/ci, size/XS, lgtm, add-or-update, cla: yes

#10821 Remove migrated pipelines
  prow/jobs/kyma-project/application-connector-manager/components/build-image-agent.yaml
  prow/jobs/kyma-project/application-connector-manager/components/build-image-gateway.yaml
  prow/jobs/kyma-project/application-connector-manager/components/build-image-validator.yaml
  prow/jobs/kyma-project/kyma/components/central-application-connectivity-validator/unit-tests-validator.yaml
  prow/jobs/kyma-project/kyma/components/central-application-gateway/unit-tests-gateway.yaml
  prow/jobs/kyma-project/kyma/components/compass-runtime-agent/unit-tests-agent.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-connectivity-validator/tests-validator.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/central-application-gateway/tests-gateway.yaml
  prow/jobs/kyma-project/kyma/tests/components/application-connector/compass-runtime-agent/tests-agent.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#10696 Verify token claims values
  .mockery.yaml
  cmd/oidc-token-verifier/main.go
  pkg/oidc/mocks/mock_ClaimsInterface.go
  pkg/oidc/mocks/mock_TokenInterface.go
  pkg/oidc/oidc.go
  pkg/oidc/oidc_test.go
Labels: size/L, lgtm, add-or-update, cla: yes

#10861 Fix reusable workflow for oci-image-builder
  .github/workflows/image-builder.yml
Labels: size/S, lgtm, add-or-update, cla: yes

#10860 Read ado pat from gcp secret manager in image-builder reusable workflow.
  .github/workflows/image-builder.yml
  .gitignore
  configs/terraform/environments/prod/.terraform.lock.hcl
  configs/terraform/environments/prod/gcp-workfload-identity-federation-variables.tf
  configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
  configs/terraform/environments/prod/github-com.tf
  configs/terraform/environments/prod/gitleaks.tf
  configs/terraform/environments/prod/image-builder-variables.tf
  configs/terraform/environments/prod/image-builder.tf
  configs/terraform/environments/prod/provider.tf
Labels: size/L, lgtm, add-or-update, cla: yes

#10875 Fix reusable workflow name. The name is not a file name.
  configs/terraform/environments/prod/image-builder-variables.tf
Labels: size/XS, lgtm, add-or-update, cla: yes

#10876 Use reusable workflow ref and sha in google wif
  configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
  configs/terraform/environments/prod/image-builder-variables.tf
  configs/terraform/environments/prod/image-builder.tf
Labels: size/S, lgtm, destroy, cla: yes

#10879 Don't use a service account impersontation on GCP.
  .github/workflows/image-builder.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#10882 Use required image-builder audience in oidc token.
  .github/workflows/image-builder.yml
Labels: size/S, lgtm, add-or-update, cla: yes
