Repository kyma-project/test-infra, pull requests merged in 2024-11, with the labels that each got.

#12304 Disable dry run on cache repository
  configs/terraform/environments/prod/image-builder-variables.tf
Labels: size/XS, lgtm, add-or-update, cla: yes

#12310 Delete .github/workflows/hello-world.yml
  .github/workflows/hello-world.yml
Labels: size/M, lgtm, add-or-update, cla: yes

#12313 Revert "actions(deps): bump golangci/golangci-lint-action from 6.1.0 to 6.1.1"
  .github/workflows/pull-go-lint.yaml
  pkg/github/bumper/bumper.go
Labels: size/XS, lgtm, no-changes, cla: yes

#12335 Add option to use go internal modules in github actions
  .github/actions/image-builder/action.yml
  .github/workflows/image-builder.yml
Labels: size/S, lgtm, no-changes, cla: yes

#12339 Rename use-go-internal-modules to use-go-internal-sap-modules
  .github/actions/image-builder/action.yml
  cmd/image-builder/main.go
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: size/M, lgtm, no-changes, cla: yes

#12340 Fix builder is failing due to unknown flag
  .github/actions/image-builder/action.yml
Labels: size/XS, lgtm, no-changes, cla: yes

#12343 Fix typo in use-go-internal-sap-modules flag
  cmd/image-builder/main.go
Labels: size/XS, lgtm, cla: yes

#12342 Revert "Fix builder is failing due to unknown flag"
  .github/actions/image-builder/action.yml
Labels: size/XS, lgtm, no-changes, cla: yes

#12345 Add rc-tag in the sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, no-changes, cla: yes

#12347 Add rc-tag in the sec-scanners-config.yaml
  pkg/securityconfig/securityconfig.go
  sec-scanners-config.yaml
Labels: size/XS, lgtm, no-changes, cla: yes

#12336 Add description of Go internal modules
  cmd/image-builder/image-builder.md
Labels: size/XS, lgtm, cla: yes

#12361 Add support for merge group in image-builder
  cmd/image-builder/config.go
  cmd/image-builder/main.go
  pkg/azuredevops/pipelines/templatesParams.go
Labels: size/S, lgtm, cla: yes

#12161 Name and dockerfile as required inputs.
  .github/workflows/image-builder.yml
Labels: size/XS, lgtm, no-changes, cla: yes, image-builder

#12372 Add CheckmarxOne to security-config structure
  pkg/securityconfig/securityconfig.go
Labels: size/S, lgtm, cla: yes

#12378 Update securityconfig.go
  pkg/securityconfig/securityconfig.go
Labels: size/XS, lgtm, cla: yes

#12369 Add CheckmarxOne to sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#12385 Add merge group event to image-builder-test
  .github/workflows/pull-image-builder-test.yml
Labels: size/XS, lgtm, no-changes, cla: yes

#12386 Test
  cmd/dnsclient/main.go
Labels: size/XS, cla: yes

#12390 Update pull-image-builder-test.yml
  .github/workflows/pull-image-builder-test.yml
Labels: size/XS, lgtm, cla: yes

#12375 Update image-builder documentation with merge_group
  cmd/image-builder/README.md
Labels: size/XS, lgtm, cla: yes

#12398 Fix merge group ib
  cmd/image-builder/config.go
  cmd/image-builder/config_test.go
  cmd/image-builder/test_fixture/merge-group_event.json
Labels: size/L, lgtm, no-changes, cla: yes

#12400 Fix handling merge group event
  cmd/image-builder/config.go
  cmd/image-builder/config_test.go
  cmd/image-builder/test_fixture/merge-group_event.json
Labels: size/L, lgtm, no-changes, cla: yes

#12406 Require werkzeug minimum 3.0.6 version
  cmd/cloud-run/slack-message-sender/requirements.txt
Labels: size/XS, lgtm, cla: yes
