Repository kyma-project/test-infra, pull requests merged in 2024-07, with the labels that each got.

#11183 Update Istio images to 1.22.2
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11186 Bump go-containerregistry to 0.19.2
  cmd/tools/gcrcleaner/main.go
  go.mod
  go.sum
Labels: size/S, lgtm, cla: yes

#11191 Add gitleaks allow to terrform vars
  configs/terraform/environments/dev/secrets-rotator/terraform.tfvars
  configs/terraform/environments/prod/terraform.tfvars
Labels: size/XS, lgtm, add-or-update, cla: yes

#11193 Fix gitleaks workflow
  .github/workflows/pull-gitleaks.yml
  .gitleaks.toml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11196 Remove not used gcrcleaner tool
  .koapps.yaml
  cmd/tools/gcrcleaner/README.md
  cmd/tools/gcrcleaner/main.go
  pkg/tools/gcrcleaner/automock/image_api.go
  pkg/tools/gcrcleaner/automock/repo_api.go
  pkg/tools/gcrcleaner/cleaner.go
  pkg/tools/gcrcleaner/cleaner_test.go
  pkg/tools/gcrcleaner/wrappers.go
Labels: size/XL, lgtm, add-or-update, cla: yes

#11200 Remove cmp jobs
  prow/config.yaml
  prow/jobs/kyma-incubator/compass-console/compass/compass-ui.yaml
  prow/jobs/kyma-incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/connector/connector-generic.yaml
  prow/jobs/kyma-incubator/compass/components/default-tenant-mapping-handler-generic/default-tenant-mapping-handler-generic.yaml
  prow/jobs/kyma-incubator/compass/components/director/director-generic.yaml
  prow/jobs/kyma-incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
  prow/jobs/kyma-incubator/compass/components/gateway/gateway-generic.yaml
  prow/jobs/kyma-incubator/compass/components/hydrator/hydrator-generic.yaml
  prow/jobs/kyma-incubator/compass/components/ias-adapter/ias-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/instance-creator/instance-creator-generic.yaml
  prow/jobs/kyma-incubator/compass/components/kyma-adapter/kyma-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/operations-controller/operations-controller-generic.yaml
  prow/jobs/kyma-incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
  prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-director-gqlgen-validate.yaml
  prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
  prow/jobs/kyma-incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
  prow/jobs/kyma-incubator/compass/components/system-broker/system-broker-generic.yaml
  prow/jobs/kyma-incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
  prow/jobs/kyma-incubator/ord-service/components/ord-service/ord-service-generic.yaml
  prow/jobs/kyma-project/test-infra/pjconfigtests.yaml
  prow/jobs/kyma-project/test-infra/pjtester.yaml
  prow/plugins.yaml
  templates/config.yaml
Labels: size/XXL, lgtm, area/prow, kind/cleanup, add-or-update, cla: yes

#11216 Fix getting list of built images on presubmits job
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
Labels: size/L, lgtm, cla: yes

#11190 Add support for workflow_dispatch event
  cmd/image-builder/config.go
  cmd/image-builder/config_test.go
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  cmd/image-builder/test_fixture/workflow_dispatch.json
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: size/L, lgtm, cla: yes

#11243 Rename JobType from on-demand to workflow_dispatch
  cmd/image-builder/config.go
  cmd/image-builder/config_test.go
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: size/M, lgtm, cla: yes

#11258 Upgrade image-builder image in the github action
  .github/actions/image-builder/action.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11261 chore: update go version to 1.22.5 in buildpack
  images/buildpack/go/Dockerfile
Labels: size/XS, lgtm, cla: yes

#11266 Add correct permissions for pull-validate-kaniko-build-config workflow
  .github/workflows/pull-validate-kaniko-build-config.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11268 feat: remove busola and kyma-dashboard tests
  prow/jobs/kyma-project/busola/busola-integration.yaml
  prow/jobs/kyma-project/busola/lighthouse.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-integration.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
  prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
Labels: area/ci, size/L, lgtm, kind/feature, add-or-update, cla: yes

#11239 Link example workflow from our repos directly in the documentation
  cmd/image-builder/README.md
Labels: size/XS, lgtm, cla: yes

#11286 chore: update go version to 1.22.5 in external images
  cmd/image-syncer/external-images.yaml
Labels: lgtm, add-or-update, cla: yes

#11303 chore: Remove manifest diff job from required
  prow/config.yaml
Labels: area/ci, lgtm, add-or-update, cla: yes

#11314 chore: remove fluentbit and selfmonitor jobs
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#11329 Remove serverless build jobs
  prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
  prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
  prow/jobs/kyma-project/serverless/serverless-build.yaml
  prow/jobs/kyma-project/serverless/serverless-gitserver.yaml
  prow/jobs/kyma-project/serverless/serverless-release.yaml
  templates/data/serverless.yaml
Labels: area/serverless, lgtm, kind/feature, add-or-update, cla: yes

#11334 Use non-deprecated variable setup method
  .github/workflows/pull-image-builder-test.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11331 Remove Keda build jobs
  prow/jobs/kyma-project/keda-manager/keda-manager-build.yaml
  templates/data/keda-manager.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#11335 Fix non-deprecated variable setup method
  .github/workflows/pull-image-builder-test.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11339 Use head ref for image builder Github action test
  .github/workflows/pull-image-builder-test.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11223 chore: remove otel-collector jobs
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#11354 Add Source part to the imagesyncer
  cmd/cloud-run/gardener-sa-rotate/gardener-sa-rotate.go
  cmd/cloud-run/rotate-service-account/rotateserviceaccount.go
  cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
  cmd/image-syncer/util.go
  cmd/image-syncer/util_test.go
Labels: size/L, lgtm, cla: yes

#11355 Add external images go version for image builder
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11360 Add "library" as a default, if image is not namespaced
  cmd/image-syncer/util.go
  cmd/image-syncer/util_test.go
Labels: size/XS, lgtm, cla: yes

#11365 Import golang:1.22.5-bookworm
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, area/dependency, add-or-update, kind/chore, cla: yes

#11366 Add golang 1.22.5-alpine to external-images.yaml
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11376 feat: add alpine 3.20.1 image
  cmd/image-syncer/external-images.yaml
Labels: area/ci, size/L, lgtm, kind/feature, add-or-update, cla: yes

#11332 Remove more migrated jobs
  prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
  prow/jobs/kyma-project/control-plane/components/provisioner/provisioner-integration-test.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#11377 Sync kaniko
  cmd/image-syncer/external-images.yaml
Labels: area/serverless, size/XS, lgtm, add-or-update, kind/chore, cla: yes

#11378 Remove otters tpi builds
  prow/jobs/kyma-project/third-party-images/third-party-images.yaml
Labels: area/serverless, size/L, lgtm, add-or-update, kind/chore, cla: yes

#11380 Sync python images
  cmd/image-syncer/external-images.yaml
Labels: area/serverless, size/XS, lgtm, add-or-update, kind/chore, cla: yes

#11382 chore: add fluentbit and node to external-images
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11381 Update usage for sa-gcs-plank service account
  docs/prow/authorization.md
Labels: size/S, lgtm, cla: yes

#11385 add golang:1.21 and gcr.io/distroless/static:nonroot
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, destroy, cla: yes

#11386 add golang 1.22.3
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11387 Add image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11393 Add service accounts to the Terraform config
  configs/terraform/environments/prod/secrets-rotator.tf
  configs/terraform/environments/prod/service_accounts.tf
Labels: size/L, lgtm, destroy, cla: yes

#11397 chore: add new python image in external images
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11400 Delete pointless provisioner job
  prow/jobs/kyma-project/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#11402 Use main as ref for image builder Github action test
  .github/workflows/pull-image-builder-test.yml
Labels: size/XS, lgtm, destroy, cla: yes

#11411 Remove docker-registry build jobs
  prow/jobs/kyma-project/docker-registry/docker-registry-build-operator.yaml
  prow/jobs/kyma-project/docker-registry/docker-registry-release.yaml
  templates/data/docker-registry.yaml
Labels: size/XL, lgtm, add-or-update, cla: yes

#11383 Remove tooling-kyma configs
  configs/tooling-kyma/SecretStores_tooling_kyma_prod.yaml
  configs/tooling-kyma/external_secrets_tooling_kyma_prod.yaml
  configs/tooling-kyma/stage/SecretStores_tooling_kyma_dev.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#11401 Remove already existing accounts(duplicated) in the tf configs
  configs/terraform/environments/prod/service_accounts.tf
Labels: size/L, lgtm, add-or-update, cla: yes

#11307 Rewrite AutoBumper to test-infra with switchable host
  .ko.yaml
  .koapps.yaml
  cmd/image-autobumper/bumper/bumper.go
  cmd/image-autobumper/bumper/bumper_test.go
  cmd/image-autobumper/imagebumper/imagebumper.go
  cmd/image-autobumper/imagebumper/imagebumper_test.go
  cmd/image-autobumper/main.go
  cmd/image-autobumper/updater/updater.go
  cmd/image-autobumper/updater/updater_test.go
  go.mod
  go.sum
Labels: size/XXL, lgtm, add-or-update, cla: yes

#11439 Add kyma-submission-pipeline SA to the TF config
  configs/terraform/environments/prod/service_accounts.tf
Labels: size/XS, lgtm, add-or-update, cla: yes

#11340 Use head ref for image builder Github action test
  .github/workflows/pull-image-builder-test.yml
Labels: size/S, lgtm, add-or-update, cla: yes

#11460 Add Alpine 3.20.2
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11463 add golang:1.22 image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11468 chore: add 3.12.2-slim-bullseye image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11504 Add Signify support for workflow_dispatch job type
  configs/kaniko-build-config.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11506 concomitant disease
  .github/workflows/pull-validate-kaniko-build-config.yml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11523 Bump external registry image
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11502 Improve Service Accounts keys cleaner
  cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
  cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner_test.go
Labels: size/M, lgtm, cla: yes

#11524 Fix post-main-test-infra-image-syncer-run
  cmd/image-syncer/external-images.yaml
Labels: size/XS, lgtm, add-or-update, cla: yes

#11528 feat: add busola workflows to tide
  prow/config.yaml
Labels: area/ci, size/XS, lgtm, kind/feature, add-or-update, cla: yes

#11527 Add Python unified agent Docker image
  images/unified-agent/python/Dockerfile
  images/unified-agent/python/python-wss-unified-agent.config
  images/unified-agent/start-wssagent.sh
Labels: size/L, lgtm, cla: yes
