Repository kyma-project/test-infra, pull requests merged in 2025-03, with the labels that each got.

#12742 Fix auto approver build
  .github/workflows/build-automated-approver.yml
Labels: size/XS, no-changes

#12748 Fix building images by adding write permission for the default token
  .github/workflows/build-cors-proxy.yml
  .github/workflows/build-create-github-issue.yml
  .github/workflows/build-dashboard-token-proxy.yml
  .github/workflows/build-externalsecretschecker.yml
  .github/workflows/build-github-webhook-gateway.yml
  .github/workflows/build-image-url-helper.yml
  .github/workflows/build-markdown-index.yml
  .github/workflows/build-move-gcs-bucket.yml
  .github/workflows/build-scan-logs-for-secrets.yml
  .github/workflows/build-search-github-issue.yml
  .github/workflows/build-usersmapchecker.yml
  .github/workflows/buildx-images.yml
  .github/workflows/pull-build-image-autobumper.yaml
  .github/workflows/pull-build-image-builder.yml
  .github/workflows/pull-build-image-detector.yml
  .github/workflows/pull-build-image-syncer.yml
  .github/workflows/pull-build-oidc-token-verifier.yml
  .github/workflows/pull-build-rotate-service-account-keys.yml
  .github/workflows/pull-build-service-account-keys-cleaner.yml
  .github/workflows/pull-build-signify-secret-rotator.yml
  .github/workflows/pull-build-slack-message-sender.yml
  .github/workflows/push-build-image-autobumper.yaml
  .github/workflows/push-build-image-builder.yml
  .github/workflows/push-build-image-detector.yml
  .github/workflows/push-build-image-syncer.yml
  .github/workflows/push-build-oidc-token-verifier.yml
  .github/workflows/push-build-rotate-service-account-keys.yml
  .github/workflows/push-build-service-account-keys-cleaner.yml
  .github/workflows/push-build-signify-secret-rotator.yml
  .github/workflows/push-build-slack-message-sender.yml
Labels: size/L, lgtm, no-changes

#12761 Remove custom UnmarshalYAML function for security config
  pkg/securityconfig/securityconfig.go
  pkg/securityconfig/securityconfig_test.go
Labels: size/M

#12766 Remove temporary code
  pkg/imagebuilder/report.go
  pkg/imagebuilder/report_test.go
Labels: size/M, lgtm

#12739 Indicate the purpose of the Image Builder docs
  cmd/image-builder/README.md
  cmd/image-builder/image-builder.md
Labels: area/documentation, size/L, lgtm, kind/chore

#12771 Update dependabot to work with pip requirements files
  .github/dependabot.yml
Labels: no-changes

#12741 Switch to new prow module location.
  cmd/external-plugins/automated-approver/main.go
  cmd/external-plugins/automated-approver/plugin.go
  cmd/external-plugins/automated-approver/plugin_test.go
  cmd/image-autobumper/updater/updater.go
  cmd/image-autobumper/updater/updater_test.go
  cmd/image-detector/main.go
  cmd/jobguard/main.go
  go.mod
  go.sum
  pkg/extractimageurls/prowjob.go
  pkg/extractimageurls/prowjob_test.go
  pkg/gcp/pubsub/types.go
  pkg/github/agent.go
  pkg/github/bumper/bumper.go
  pkg/github/client/client.go
  pkg/github/client/v2/client.go
  pkg/github/git/client.go
  pkg/github/repoowners/client.go
  pkg/github/repoowners/owners.go
  pkg/jobguard/v2/jobguard.go
  pkg/jobguard/v2/status.go
  pkg/prow/externalplugin/externalplugin.go
  pkg/prow/prowjobs.go
Labels: size/XL, technical-debt

#12774 Update cla-assistant image to v20250307-875cc1f
  prow/cluster/components/cla-assistant.yaml
Labels: no-changes

#12775 Update dependabot to work with pip requirements files (explicit paths)
  .github/dependabot.yml
Labels: no-changes

#12787 Update version python in signify secret rotator and add step to depen…
  .github/dependabot.yml
  cmd/cloud-run/signifysecretrotator/Dockerfile
Labels: add-or-update

#12798 Updated diagrams
  cmd/image-builder/documentation_assets/image-builder-activity-diagram.svg
  cmd/image-builder/documentation_assets/image-builder-block-diagram.svg
Labels: area/documentation

#12826 Update test-infra-autobump-config.yaml
  configs/autobump-config/test-infra-autobump-config.yaml
Labels: add-or-update

#12817 Image builder documentation update
  cmd/image-builder/README.md
  cmd/image-builder/image-builder.md
Labels: area/documentation
