Repository kyma-project/test-infra, pull requests merged in 2025-04, with the labels that each got.

#12828 Automatically create fork if not found for autobumper
  .mockery.yaml
  cmd/image-autobumper/README.md
  cmd/image-autobumper/main.go
  cmd/image-autobumper/updater/updater_test.go
  configs/autobump-config/test-infra-autobump-config.yaml
  pkg/github/bumper/bumper.go
  pkg/github/bumper/bumper_suite_test.go
  pkg/github/bumper/bumper_test.go
  pkg/github/bumper/mocks/mock_GitHubClientAdapterInterface.go
Labels: add-or-update

#12872 Add information about empty commit to the image syncer
  .github/workflows/image-syncer.yml
Labels: add-or-update

#12894 Remove ignored actions
  .github/dependabot.yml
Labels: add-or-update

#12891 Fix Autobumper triggers for image build
  .github/workflows/pull-build-image-autobumper.yaml
  .github/workflows/push-build-image-autobumper.yaml
Labels: no-changes

#12877 introduce resource of error alerting for cloud runs
  configs/terraform/modules/rotate-service-account/main.tf
  configs/terraform/modules/signify-secret-rotator/main.tf
Labels: add-or-update

#12915 Improve artifact-registry module naming and default values.
  configs/terraform/environments/prod/artifact-registry-variables.tf
  configs/terraform/environments/prod/artifact-registry.tf
  configs/terraform/environments/prod/terraform.tfvars
  configs/terraform/modules/artifact-registry/main.tf
  configs/terraform/modules/artifact-registry/variables.tf
Labels: destroy

#12921 Add Guidelines for Managing Follow-Up Issues
  docs/how-to/how-to-manage-follow-up-issues.md
Labels: area/documentation

#12922 Add Terraform Configuration for dev-kyma-modules and kyma-modules Repositories
  configs/terraform/environments/prod/artifact-registry-variables.tf
  configs/terraform/environments/prod/artifact-registry.tf
  configs/terraform/environments/prod/modules-submission-variables.tf
  configs/terraform/environments/prod/modules-submission.tf
  configs/terraform/modules/artifact-registry/main.tf
  configs/terraform/modules/artifact-registry/variables.tf
Labels: add-or-update

#12913 Rewrite validate message to return bool and not raise error
  .gitignore
  cmd/cloud-run/signifysecretrotator/messagevalidator.py
  cmd/cloud-run/signifysecretrotator/requirements.txt
  cmd/cloud-run/signifysecretrotator/signifysecretrotator.py
  cmd/cloud-run/signifysecretrotator/test_messagevalidator.py
  cmd/cloud-run/signifysecretrotator/test_signifysecretrotator.py
Labels: add-or-update

#12939 Allow building images using docker buildx
  cmd/image-builder/main.go
  cmd/image-builder/main_suite_test.go
  cmd/image-builder/main_test.go
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: add-or-update

#12955 Remove unused workflows
  .github/workflows/build-create-github-issue.yml
  .github/workflows/build-externalsecretschecker.yml
  .github/workflows/build-move-gcs-bucket.yml
  .github/workflows/build-scan-logs-for-secrets.yml
  .github/workflows/build-search-github-issue.yml
Labels: area/ci, kind/cleanup, no-changes

#12951 Fix cors-proxy CVE-2024-45336 vulnerability
  cmd/cloud-run/cors-proxy/Dockerfile
  go.mod
Labels: area/dependency

#12954 Refactor Dockerfile to fix vulnerabilities
  cmd/cloud-run/github-webhook-gateway/Dockerfile
  cmd/dashboard-token-proxy/Dockerfile
Labels: area/security

#12962 Add support for platforms and build engines to github actions
  .github/actions/image-builder/action.yml
  .github/workflows/image-builder.yml
Labels: no-changes

#12953 Removed unused code.
  cmd/cloud-run/create-github-issue/Dockerfile
  cmd/cloud-run/create-github-issue/create-github-issue.go
  cmd/cloud-run/move-gcs-bucket/Dockerfile
  cmd/cloud-run/move-gcs-bucket/move-gcs-bucket.go
  cmd/cloud-run/scan-logs-for-secrets/Dockerfile
  cmd/cloud-run/scan-logs-for-secrets/kodata/gitleaks.toml
  cmd/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
  cmd/cloud-run/search-github-issue/Dockerfile
  cmd/cloud-run/search-github-issue/search-github-issues.go
  configs/terraform/environments/prod/pjtester-variables.tf
  configs/terraform/environments/prod/pjtester.tf
  configs/terraform/environments/prod/secrets-leaks-log-scanner.tf
  configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/modules/secrets-leaks-log-scanner/main.tf
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-detector.tf
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  pkg/gcp/workflows/secrets-leak-detector.yaml
Labels: kind/cleanup, destroy

#12979 Switch to setup-tofu as it is stable now
  .github/workflows/post-apply-prod-terraform.yaml
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: no-changes

#12980 Add Auto Author Assign
  .github/workflows/auto-author-assign.yml
Labels: no-changes, team-goal

#12978 Add terraform file linter
  .github/workflows/tf-lint.yaml
  .tflint.hcl
  configs/terraform/core/apis.tf
  configs/terraform/environments/dev/artifact-registry/provider.tf
  configs/terraform/environments/dev/opa-gatekeeper/backend.tf
  configs/terraform/environments/dev/secrets-rotator/backend.tf
  configs/terraform/environments/dev/secrets-rotator/provider.tf
  configs/terraform/environments/prod/cors-proxy.tf
  configs/terraform/environments/prod/network-policy.tf
  configs/terraform/environments/prod/provider.tf
  configs/terraform/environments/prod/security-dashboard-token.tf
  configs/terraform/environments/prod/variables.tf
  configs/terraform/modules/artifact-registry/provider.tf
  configs/terraform/modules/artifact-registry/variables.tf
  configs/terraform/modules/cors-proxy/main.tf
  configs/terraform/modules/gcp-workload-identity-federation/provider.tf
  configs/terraform/modules/github-webhook-gateway/main.tf
  configs/terraform/modules/opa-gatekeeper/provider.tf
  configs/terraform/modules/rotate-service-account/provider.tf
  configs/terraform/modules/rotate-service-account/variables.tf
  configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf
  configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf
  configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
  configs/terraform/modules/security-dashboard-token/main.tf
  configs/terraform/modules/service-account-keys-cleaner/provider.tf
  configs/terraform/modules/signify-secret-rotator/provider.tf
  configs/terraform/modules/signify-secret-rotator/variables.tf
  configs/terraform/modules/slack-message-sender/main.tf
Labels: add-or-update

#12975 Parse report with architecture
  cmd/image-builder/main.go
  pkg/imagebuilder/report.go
  pkg/imagebuilder/report_test.go
Labels: area/tools, image-builder

#12987 Improve summary by placing images in table and adding architectures
  .github/workflows/image-builder.yml
Labels: no-changes

#12994 Remove print-image steps from multiple build YAML files.
  .github/workflows/build-automated-approver.yml
  .github/workflows/build-cors-proxy.yml
  .github/workflows/build-dashboard-token-proxy.yml
  .github/workflows/build-github-webhook-gateway.yml
  .github/workflows/build-image-url-helper.yml
  .github/workflows/build-markdown-index.yml
  .github/workflows/build-usersmapchecker.yml
  .github/workflows/pull-build-image-autobumper.yaml
  .github/workflows/pull-build-image-detector.yml
  .github/workflows/pull-build-image-syncer.yml
  .github/workflows/push-build-image-autobumper.yaml
  .github/workflows/push-build-image-detector.yml
  .github/workflows/push-build-image-syncer.yml
Labels: area/ci, kind/cleanup, no-changes

#12989 Add architecture output in image buidler action, which is used in step summary
  .github/actions/image-builder/action.yml
Labels: no-changes
