Repository kyma-project/test-infra, pull requests merged in 2025-05, with the labels that each got.

#13014 Unify build workflows names, switch to amd64 only
  .github/workflows/build-automated-approver.yml
  .github/workflows/build-cors-proxy.yml
  .github/workflows/build-dashboard-token-proxy.yml
  .github/workflows/build-github-webhook-gateway.yml
  .github/workflows/build-image-autobumper.yaml
  .github/workflows/build-image-builder.yml
  .github/workflows/build-image-detector.yml
  .github/workflows/build-image-syncer.yml
  .github/workflows/build-image-url-helper.yml
  .github/workflows/build-markdown-index.yml
  .github/workflows/build-oidc-token-verifier.yml
  .github/workflows/build-rotate-service-account-keys.yml
  .github/workflows/build-service-account-keys-cleaner.yml
  .github/workflows/build-signify-secret-rotator.yml
  .github/workflows/build-slack-message-sender.yml
  .github/workflows/build-usersmapchecker.yml
  .github/workflows/buildx-images.yml
  .github/workflows/pull-build-image-autobumper.yaml
  .github/workflows/pull-build-image-detector.yml
  .github/workflows/pull-build-image-syncer.yml
  .github/workflows/pull-build-rotate-service-account-keys.yml
  .github/workflows/pull-build-service-account-keys-cleaner.yml
  .github/workflows/push-build-image-builder.yml
  .github/workflows/push-build-oidc-token-verifier.yml
  .github/workflows/push-build-signify-secret-rotator.yml
  .github/workflows/push-build-slack-message-sender.yml
Labels: add-or-update

#13018 Enhance Infrastructure as Code guidelines
  configs/terraform/environments/dev/secrets-rotator/terraform.tfvars
  docs/guidelines_iac.md
Labels: area/documentation, add-or-update, terraform

#12984 Add Terraform configuration for restricted markets service account an…
  configs/terraform/environments/prod/restricted-markets-delivery.tf
Labels: add-or-update

#13024 Remove OPA Gatekeeper
  configs/terraform/environments/prod/opa-gatekeeper-variables.tf
  configs/terraform/environments/prod/opa-gatekeeper.tf
  configs/terraform/environments/prod/output.tf
  configs/terraform/environments/prod/variables.tf
  opa/gatekeeper/constraint-templates/allowPrivilegeEscalation.yaml
  opa/gatekeeper/constraint-templates/apparmor.yaml
  opa/gatekeeper/constraint-templates/capabilities.yaml
  opa/gatekeeper/constraint-templates/hostFilesystem.yaml
  opa/gatekeeper/constraint-templates/hostNetworkPorts.yaml
  opa/gatekeeper/constraint-templates/k8sAllowedImages.yaml
  opa/gatekeeper/constraint-templates/privilegedContainers.yaml
  opa/gatekeeper/constraint-templates/pspHostNamespace.yaml
  opa/gatekeeper/constraint-templates/seccomp.yaml
  opa/gatekeeper/constraint-templates/secretTrustedUsage.yaml
  opa/gatekeeper/constraint-templates/selinux.yaml
  opa/gatekeeper/constraint-templates/serviceAccountTrustedUsage.yaml
  opa/gatekeeper/constraint-templates/test-data/trustedSAUsage_test-data.jsonc
  opa/gatekeeper/constraint-templates/test-data/trustedSecretUsage_test-data.jsonc
  opa/gatekeeper/constraint-templates/users.yaml
  opa/gatekeeper/deployments/gatekeeper.yaml
Labels: destroy

#13025 fix: specify project for IAM members in restricted markets delivery
  configs/terraform/environments/prod/restricted-markets-delivery.tf
Labels: kind/bug, terraform

#13026 Update image-syncer README.md
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
  .mlc.config.json
  cmd/image-syncer/README.md
Labels: no-changes

#13029 fix: Grant permissions for correct repository
  configs/terraform/environments/prod/restricted-markets-delivery.tf
Labels: kind/bug, destroy, terraform

#13037 Non native arch builds recommendations
  cmd/image-builder/README.md
Labels: area/documentation

#12929 Add Authentication configuration for dockerhub in dockerhub-mirror repo
  configs/terraform/environments/prod/artifact-registry-variables.tf
  configs/terraform/environments/prod/artifact-registry.tf
  configs/terraform/environments/prod/image-builder-variables.tf
  configs/terraform/environments/prod/image-builder.tf
  configs/terraform/environments/prod/modules-submission-variables.tf
  configs/terraform/environments/prod/modules-submission.tf
  configs/terraform/modules/artifact-registry/main.tf
  configs/terraform/modules/artifact-registry/output.tf
  configs/terraform/modules/artifact-registry/variables.tf
Labels: destroy

#13050 Use correct attribute reference to get secret path
  configs/terraform/environments/prod/image-builder.tf
Labels: add-or-update

#13061 Use minimal base image and multistage build of python image
  cmd/cloud-run/signifysecretrotator/Dockerfile
  cmd/cloud-run/slack-message-sender/Dockerfile
Labels: area/security

#13062 Switch SA for image builder which uses ArtifactRegistry
  configs/terraform/environments/prod/image-builder.tf
Labels: destroy

#13064 Dynamic Docker Config to fix Remote Repository
  configs/terraform/environments/prod/image-builder-variables.tf
  configs/terraform/environments/prod/image-builder.tf
  configs/terraform/modules/artifact-registry/main.tf
Labels: add-or-update

#13065 Update image-autobumper.yml
  .github/workflows/image-autobumper.yml
Labels: no-changes

#13069 Update image-autobumper.yml
  .github/workflows/image-autobumper.yml
Labels: no-changes

#13040 Update documentation for artifact-registry terraform module
  configs/terraform/modules/artifact-registry/README.md
Labels: area/documentation, image-builder

#13076 fix: set ENTRYPOINT to use Python from virtual environment in Dockerfile
  cmd/cloud-run/signifysecretrotator/Dockerfile
  cmd/cloud-run/slack-message-sender/Dockerfile
Labels: kind/bug

#13049 Add code checks for python code
  .github/workflows/build-slack-message-sender.yml
  .github/workflows/code-checks-python.yml
  .pylintrc
  cmd/cloud-run/signifysecretrotator/pylogger/test_logger.py
  cmd/cloud-run/signifysecretrotator/secretmanager/client.py
  cmd/cloud-run/signifysecretrotator/secretmanager/test_client.py
  cmd/cloud-run/signifysecretrotator/signify/test_client.py
  cmd/cloud-run/signifysecretrotator/signifysecretrotator.py
  cmd/cloud-run/signifysecretrotator/test_signifysecretrotator.py
  cmd/cloud-run/slackmessagesender/Dockerfile
  cmd/cloud-run/slackmessagesender/requirements.txt
  cmd/cloud-run/slackmessagesender/slackmessagesender.py
  cmd/cloud-run/slackmessagesender/test_slackmessagesender.py
Labels: add-or-update

#13104 Add workflow controllers
  .github/workflows/build-automated-approver.yml
  .github/workflows/build-cors-proxy.yml
  .github/workflows/build-dashboard-token-proxy.yml
  .github/workflows/build-github-webhook-gateway.yml
  .github/workflows/build-image-autobumper.yaml
  .github/workflows/build-image-builder.yml
  .github/workflows/build-image-detector.yml
  .github/workflows/build-image-syncer.yml
  .github/workflows/build-image-url-helper.yml
  .github/workflows/build-markdown-index.yml
  .github/workflows/build-oidc-token-verifier.yml
  .github/workflows/build-rotate-service-account-keys.yml
  .github/workflows/build-service-account-keys-cleaner.yml
  .github/workflows/build-signify-secret-rotator.yml
  .github/workflows/build-slack-message-sender.yml
  .github/workflows/build-usersmapchecker.yml
  .github/workflows/buildx-images.yml
  .github/workflows/code-checks-python.yml
  .github/workflows/pull-gitleaks.yml
  .github/workflows/pull-go-lint.yaml
  .github/workflows/pull-image-builder-test.yml
  .github/workflows/pull-plan-prod-terraform.yaml
  .github/workflows/pull-unit-test-go.yaml
  .github/workflows/pull-validate-dockerfiles.yaml
  .github/workflows/pull-validate-kaniko-build-config.yml
  .github/workflows/pull-validate-scripts.yaml
  .github/workflows/pull-validate-service-accounts.yaml
  .github/workflows/tf-lint.yaml
  .github/workflows/workflow-controller-build-1.yml
  .github/workflows/workflow-controller-build-2.yml
  .github/workflows/workflow-controller-pull-requests.yml
  controller-filters.yaml
Labels: area/tools, add-or-update, area/automation
