Repository kyma-project/test-infra, pull requests merged in 2025-02, with the labels that each got.

#12626 Rename fields in security config, support both names by custom unmarshal
  pkg/securityconfig/securityconfig.go
  pkg/securityconfig/securityconfig_test.go
  sec-scanners-config.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#12629 Support new field naming sec cfg, fix misisng assgin
  pkg/securityconfig/securityconfig.go
Labels: size/XS, lgtm, cla: yes

#12646 Use custom env to retrieve base commit sha
  cmd/image-builder/config.go
  cmd/image-builder/config_test.go
Labels: size/M, lgtm, cla: yes

#12661 chore: Remove tide from busola
  prow/config.yaml
Labels: size/M, lgtm, add-or-update, cla: yes

#12676 Disable tide for all teams
  docs/index.md
  docs/prow/authorization.md
  docs/prow/prow-architecture.md
  docs/prow/prow-cluster-update.md
  docs/prow/tide-introduction-notes.md
  prow/cluster/components/deck_deployment.yaml
  prow/cluster/components/tide_deployment.yaml
  prow/cluster/components/tide_rbac.yaml
  prow/cluster/components/tide_service.yaml
  prow/cluster/deploy.sh
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L, lgtm, add-or-update, cla: yes

#12677 Update version github.com/vbatts/tar-split from v0.11.6 to v0.12.1git…
  go.mod
  go.sum
Labels: size/S, lgtm, cla: yes

#12680 Remove tide from Automated Approver
  cmd/external-plugins/automated-approver/README.md
  cmd/external-plugins/automated-approver/plugin.go
  cmd/external-plugins/automated-approver/plugin_test.go
  pkg/image-url-helper/missing/missing_test.go
Labels: size/M, lgtm, cla: yes

#12692 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, no-changes, cla: yes

#12719 Remove unique-jobs-name and jobguard
  cmd/tools/jobguard/README.md
  cmd/tools/jobguard/nobuild.lock
  cmd/tools/jobguard/run.sh
  cmd/unique-jobs-name/main.go
Labels: size/L, lgtm, cla: yes

#12724 Switch to new build report format
  cmd/image-builder/main.go
  pkg/imagebuilder/report.go
  pkg/imagebuilder/report_test.go
Labels: size/L, lgtm, cla: yes

#12732 Use new build report format
  pkg/imagebuilder/report.go
  pkg/imagebuilder/report_test.go
Labels: size/M, lgtm, cla: yes

#12737 Print workflow ref
  .github/workflows/image-builder.yml
Labels: size/XS, no-changes, cla: yes
