Repository kyma-project/test-infra, pull requests merged in 2025-10, with the labels that each got.

#13554 Feat: add target dockerfile support
  .github/actions/image-builder/action.yml
  .github/workflows/image-builder.yml
  cmd/image-builder/github-workflow-integration.md
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: add-or-update

#13559 Hotfix: remove target argument to make image builder build
  .github/actions/image-builder/action.yml
Labels: area/ci, add-or-update

#13564 chore: update image-builder version in action.yml
  .github/actions/image-builder/action.yml
Labels: add-or-update, area/automation

#13550 Chore: Remove comment tag in auto approve action
  .github/workflows/renovate-auto-approve.yml
Labels: area/ci, add-or-update

#13556 Remove unused service accounts and secure critical ones
  configs/terraform/environments/prod/service_accounts.tf
Labels: destroy
