Repository kyma-project/test-infra, pull requests merged in 2025-09, with the labels that each got.

#13420 Cleanup terraform after removing old submission pipeline
  configs/terraform/environments/prod/modules-submission.tf
Labels: destroy

#13437 Add reusable workflow for managing stale issues
  .github/workflows/reusable-stale.yml
  .github/workflows/stale.yml
Labels: add-or-update

#13443 Remove temporary -cover flag for go test
  .github/controller-filters.yaml
  .github/workflows/pull-unit-test-go.yaml
Labels: add-or-update

#13445 Bump Go to 1.25.1 version
  .github/workflows/pull-go-lint.yaml
  .github/workflows/pull-unit-test-go.yaml
  cmd/cloud-run/cors-proxy/Dockerfile
  cmd/cloud-run/github-webhook-gateway/Dockerfile
  cmd/cloud-run/rotate-service-account/Dockerfile
  cmd/cloud-run/service-account-keys-cleaner/Dockerfile
  cmd/dashboard-token-proxy/Dockerfile
  cmd/image-autobumper/Dockerfile
  cmd/image-builder/Dockerfile
  cmd/image-detector/Dockerfile
  cmd/image-syncer/Dockerfile
  cmd/image-url-helper/Dockerfile
  cmd/markdown-index/Dockerfile
  cmd/oidc-token-verifier/Dockerfile
  configs/terraform/core/apis.tf
  go.mod
  images/ginkgo/Dockerfile
  images/ginkgo/envs
Labels: add-or-update

#13449 Update regex for dependency name matching
  .github/renovate-sharable-config.json
Labels: area/dependency, add-or-update, area/automation

#13453 Chore: Change github actions versioning from commit sha to using sem ver
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/post-apply-prod-terraform.yaml
  .github/workflows/pull-plan-prod-terraform.yaml
Labels: add-or-update

#13478 Refactor Renovate configuration for package rules
  .github/renovate-sharable-config.json
Labels: area/dependency

#13498 Remove images/ginkgo
  .github/dependabot.yml
  images/ginkgo/Dockerfile
  images/ginkgo/envs
Labels: add-or-update

#13499 Add rangeStrategy to Go dependencies group
  .github/renovate-sharable-config.json
Labels: area/dependency

#13515 (chore): Add GitHub Action digest pinning to Renovate config and remove ignoring actions
  .github/renovate-sharable-config.json
Labels: area/dependency, area/automation

#13527 chore: remove auto bumper workflows from controller filters and build…
  .github/controller-filters.yaml
  .github/workflows/autobump-images.yml
  .github/workflows/build-image-autobumper.yaml
  .github/workflows/image-autobumper.yml
  .github/workflows/workflow-controller-build-1.yml
  cmd/image-autobumper/README.md
  configs/autobump-config/test-infra-autobump-config.yaml
  docs/index.md
Labels: add-or-update, area/automation

#13544 feat: Add auto approve workflow with if statement and deleted debuggi…
  .github/workflows/renovate-auto-approve.yml
Labels: area/ci, add-or-update
