Repository kyma-project/test-infra, pull requests merged in 2025-07, with the labels that each got.

#13221 feat: add input sanitization to prevent injection attacks
  cmd/dashboard-token-proxy/main.go
Labels: area/security

#13260 Remove build engine backend code
  .github/actions/image-builder/action.yml
  .github/workflows/image-builder.yml
  cmd/image-builder/main.go
  cmd/image-builder/main_test.go
  pkg/azuredevops/pipelines/templatesParams.go
  pkg/azuredevops/pipelines/templatesParams_test.go
Labels: no-changes

#13275 Bug fix: Update workflow-controller-build-1.yml to ignore deeper bran…
  .github/workflows/workflow-controller-build-1.yml
  .github/workflows/workflow-controller-build-2.yml
Labels: kind/bug, no-changes

#13307 Remove unused external-secret
  prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
  prow/config.yaml
Labels: no-changes

#13295 Add new image-builder client image
  .github/workflows/build-image-builder.yml
  cmd/image-builder/Dockerfile
Labels: no-changes

#13315 Remove Buildpack workflows
  .github/controller-filters.yaml
  .github/dependabot.yml
  .github/workflows/build-buildpack.yml
  .github/workflows/workflow-controller-build-2.yml
Labels: no-changes

#13314 Remove buildpack images
  images/buildpack/Dockerfile
  images/buildpack/go/Dockerfile
Labels: no-changes
